/**
 * @file cad-lab-document-generators.ts — Shared document generation functions.
 *
 * @description Generates RFQ, SOW, and NDA document templates from project
 * data in Markdown format. Extracted from cad-lab-contracting.tsx so both
 * the legacy contracting component and the new shortlist component can share
 * the same generators.
 */

import type { CadLabModule } from "@/lib/cad-lab-types"
import type { DiagnosticAnswers } from "@/components/cad/cad-lab-diagnostics"

/**
 * Generates an RFQ document from project data in Markdown format.
 *
 * @param projectName - Project title
 * @param modules - Array of modules to include in the RFQ
 * @param diagnosticAnswers - Diagnostic answers per module
 * @param buyerName - Buyer/company name
 * @param deadline - Quote submission deadline
 * @param specialTerms - Any special terms or requirements
 * @param rfqId - Marketplace RFQ ID (if already created)
 * @param rfqStatus - Current RFQ status
 * @returns Markdown-formatted RFQ document
 */
export function generateRfq(
  projectName: string,
  modules: CadLabModule[],
  diagnosticAnswers?: DiagnosticAnswers,
  buyerName?: string,
  deadline?: string,
  specialTerms?: string,
  rfqId?: string,
  rfqStatus?: string,
): string {
  const date = new Date().toLocaleDateString("en-GB", {
    day: "numeric",
    month: "long",
    year: "numeric",
  })
  const lines: string[] = []

  lines.push("# Request for Quotation (RFQ)")
  lines.push("")
  lines.push(`**Project:** ${projectName}  `)
  lines.push(`**Date:** ${date}  `)
  if (buyerName) lines.push(`**Buyer:** ${buyerName}  `)
  if (deadline) lines.push(`**Submission Deadline:** ${deadline}  `)
  if (rfqId) lines.push(`**Marketplace RFQ ID:** ${rfqId}  `)
  if (rfqStatus) lines.push(`**Marketplace Status:** ${rfqStatus}  `)
  lines.push(`**Modules:** ${modules.length}`)
  lines.push("")

  lines.push("## Scope of Supply")
  lines.push("")

  // Build dynamic table columns based on available data
  const headers = ["Module", "Purpose", "Key Parts", "Lead Time"]
  const hasProcess = modules.some((m) => diagnosticAnswers?.[m.id]?.mfg_process)
  const hasMaterial = modules.some((m) => diagnosticAnswers?.[m.id]?.material)
  const hasDimensions = modules.some((m) => m.result?.bbox)
  const hasQuantity = modules.some((m) => diagnosticAnswers?.[m.id]?.batch_size)
  if (hasProcess) headers.push("Process")
  if (hasMaterial) headers.push("Material")
  if (hasDimensions) headers.push("Dimensions")
  if (hasQuantity) headers.push("Quantity")

  lines.push(`| ${headers.join(" | ")} |`)
  lines.push(`| ${headers.map(() => "---").join(" | ")} |`)

  for (const mod of modules) {
    const diag = diagnosticAnswers?.[mod.id] || {}
    const cells = [
      mod.name,
      mod.purpose,
      mod.keyParts.join(", "),
      `${mod.leadWeeks} wk`,
    ]
    if (hasProcess) cells.push(diag.mfg_process || "—")
    if (hasMaterial) cells.push(diag.material || "—")
    if (hasDimensions) cells.push(mod.result?.bbox ? `${mod.result.bbox.xLen.toFixed(0)}×${mod.result.bbox.yLen.toFixed(0)}×${mod.result.bbox.zLen.toFixed(0)}mm` : "—")
    if (hasQuantity) cells.push(diag.batch_size || "—")
    lines.push(`| ${cells.join(" | ")} |`)
  }

  // Per-module detail for fields not in the table
  const detailModules = modules.filter((m) => {
    const d = diagnosticAnswers?.[m.id] || {}
    return d.tolerance || d.finish || d.environment || m.result?.massGrams
  })
  if (detailModules.length > 0) {
    lines.push("")
    lines.push("### Additional Specifications")
    lines.push("")
    for (const mod of detailModules) {
      const diag = diagnosticAnswers?.[mod.id] || {}
      const details: string[] = []
      if (diag.tolerance) details.push(`Tolerance: ${diag.tolerance}`)
      if (diag.finish) details.push(`Finish: ${diag.finish}`)
      if (diag.environment) details.push(`Environment: ${diag.environment}`)
      if (mod.result?.massGrams) details.push(`Mass: ${mod.result.massGrams.toFixed(1)}g`)
      if (details.length > 0) {
        lines.push(`- **${mod.name}:** ${details.join(" · ")}`)
      }
    }
  }

  lines.push("")
  lines.push("## Quote Requirements")
  lines.push("")
  lines.push("Please provide:")
  lines.push("1. Unit price per module")
  lines.push("2. Tooling costs (if applicable)")
  lines.push("3. Lead time from order confirmation")
  lines.push("4. Minimum order quantity")
  lines.push("5. Material certifications available")
  lines.push("6. Quality inspection method")
  lines.push("")

  if (specialTerms) {
    lines.push("## Special Terms")
    lines.push("")
    lines.push(specialTerms)
    lines.push("")
  }

  lines.push("---")
  lines.push(`*Generated by The Forge — ForgeOS — ${date}*`)

  return lines.join("\n")
}

/**
 * Generates a Statement of Work from project data in Markdown format.
 *
 * @param projectName - Project title
 * @param modules - Array of modules to include
 * @param diagnosticAnswers - Diagnostic answers per module
 * @param buyerName - Client/buyer name
 * @param rfqId - Reference RFQ ID
 * @returns Markdown-formatted SOW document
 */
export function generateSow(
  projectName: string,
  modules: CadLabModule[],
  diagnosticAnswers?: DiagnosticAnswers,
  buyerName?: string,
  rfqId?: string,
): string {
  const date = new Date().toLocaleDateString("en-GB", {
    day: "numeric",
    month: "long",
    year: "numeric",
  })
  const maxLead = Math.max(...modules.map((m) => m.leadWeeks), 0)
  const lines: string[] = []

  lines.push("# Statement of Work (SOW)")
  lines.push("")
  lines.push(`**Project:** ${projectName}  `)
  lines.push(`**Date:** ${date}  `)
  if (buyerName) lines.push(`**Client:** ${buyerName}  `)
  if (rfqId) lines.push(`**Marketplace RFQ Reference:** ${rfqId}  `)
  lines.push("")

  lines.push("## 1. Scope")
  lines.push("")
  lines.push(`Manufacturing and delivery of ${modules.length} modules as specified below.`)
  lines.push("")

  lines.push("## 2. Deliverables")
  lines.push("")
  lines.push("| # | Module | Purpose | Key Parts | Lead Time |")
  lines.push("| --- | --- | --- | --- | --- |")
  for (let i = 0; i < modules.length; i++) {
    const mod = modules[i]
    lines.push(`| ${i + 1} | ${mod.name} | ${mod.purpose} | ${mod.keyParts.join(", ")} | ${mod.leadWeeks} wk |`)
  }
  lines.push("")

  lines.push("## 3. Timeline")
  lines.push("")
  lines.push(`**Estimated total duration:** ${maxLead} weeks (critical path)`)
  lines.push("")
  lines.push("| Milestone | Week |")
  lines.push("| --- | --- |")
  lines.push("| Kick-off and material procurement | 0 |")
  lines.push(`| First article inspection | ${Math.ceil(maxLead * 0.3)} |`)
  lines.push(`| Pre-delivery review | ${Math.ceil(maxLead * 0.7)} |`)
  lines.push(`| Final delivery and acceptance | ${maxLead} |`)
  lines.push("")

  lines.push("## 4. Acceptance Criteria")
  lines.push("")
  lines.push("- Dimensional compliance per specified tolerances")
  lines.push("- Material certification provided")
  lines.push("- Visual inspection: no defects, correct finish")
  lines.push("- Functional test (if applicable)")
  lines.push("")

  lines.push("## 5. Payment Terms")
  lines.push("")
  lines.push("| Milestone | % |")
  lines.push("| --- | --- |")
  lines.push("| Order confirmation | 30% |")
  lines.push("| First article approval | 40% |")
  lines.push("| Final delivery and acceptance | 30% |")
  lines.push("")

  lines.push("---")
  lines.push(`*Generated by The Forge — ForgeOS — ${date}*`)

  return lines.join("\n")
}

/**
 * Generates a mutual NDA template in Markdown format.
 *
 * @param projectName - Project title
 * @param buyerName - Buyer/discloser name
 * @param rfqId - Reference RFQ ID
 * @returns Markdown-formatted NDA document
 */
export function generateNda(projectName: string, buyerName?: string, rfqId?: string): string {
  const date = new Date().toLocaleDateString("en-GB", {
    day: "numeric",
    month: "long",
    year: "numeric",
  })
  const lines: string[] = []

  lines.push("# Mutual Non-Disclosure Agreement")
  lines.push("")
  lines.push(`**Date:** ${date}  `)
  lines.push(`**Project:** ${projectName}  `)
  if (rfqId) lines.push(`**RFQ Reference:** ${rfqId}  `)
  lines.push("")
  lines.push("**Between:**")
  lines.push(`- **Party A (Discloser):** ${buyerName || "[BUYER NAME]"}`)
  lines.push("- **Party B (Recipient):** [SUPPLIER NAME]")
  lines.push("")

  lines.push("## 1. Purpose")
  lines.push("")
  lines.push(`The parties wish to exchange confidential technical information relating to the project "${projectName}" for the purpose of evaluating a potential manufacturing engagement.`)
  lines.push("")

  lines.push("## 2. Confidential Information Includes")
  lines.push("")
  lines.push("- CAD models, drawings, and specifications")
  lines.push("- Manufacturing processes and parameters")
  lines.push("- Material compositions and formulations")
  lines.push("- Cost data, pricing, and business terms")
  lines.push("- Research reports and analysis results")
  lines.push("")

  lines.push("## 3. Obligations")
  lines.push("")
  lines.push("- Treat all disclosed information as confidential")
  lines.push("- Use information solely for the stated purpose")
  lines.push("- Not disclose to third parties without written consent")
  lines.push("- Return or destroy all materials upon request")
  lines.push("")

  lines.push("## 4. Term")
  lines.push("")
  lines.push("This agreement shall remain in effect for **3 years** from the date above.")
  lines.push("")

  lines.push("## 5. Signatures")
  lines.push("")
  lines.push("| | Name | Signature | Date |")
  lines.push("| --- | --- | --- | --- |")
  lines.push(`| Party A | ${buyerName || "________________"} | ________________ | ________ |`)
  lines.push("| Party B | ________________ | ________________ | ________ |")
  lines.push("")

  lines.push("---")
  lines.push(`*Template generated by The Forge — ForgeOS — ${date}*`)

  return lines.join("\n")
}
