/**
 * @file investor-export.ts
 *
 * @description Export functions for investor data — CSV download and PPTX deck generation.
 * CSV is available for starter+, PPTX for professional+.
 */

import type { InvestorFirm } from '@/actions/investors'

// ---------------------------------------------------------------------------
// CSV Export
// ---------------------------------------------------------------------------

/**
 * Generates a CSV string and triggers a browser download.
 */
export function exportInvestorsCSV(
  firms: InvestorFirm[],
  matchScores?: Record<string, number>
): void {
  const headers = [
    'Name', 'Type', 'Fund Size (GBP)', 'Cheque Min', 'Cheque Max',
    'Stage Focus', 'Sectors', 'HQ City', 'Active Deploying', 'Quality Score',
    'Match Score', 'Priority', 'BVCA Member',
  ]

  const rows = firms.map(f => {
    const a = f.attributes
    return [
      escapeCsv(f.title),
      escapeCsv(a.firm_type ?? ''),
      escapeCsv(a.fund_size_gbp?.toString() ?? ''),
      escapeCsv(a.cheque_range_gbp?.min?.toString() ?? ''),
      escapeCsv(a.cheque_range_gbp?.max?.toString() ?? ''),
      escapeCsv((a.stage_focus ?? []).join('; ')),
      escapeCsv((a.sectors ?? []).join('; ')),
      escapeCsv(a.hq_city ?? ''),
      a.is_active_deploying ? 'Yes' : 'No',
      escapeCsv(a.data_quality_score?.toFixed(1) ?? ''),
      escapeCsv(matchScores?.[f.id]?.toString() ?? ''),
      escapeCsv(a.outreach_priority ?? ''),
      a.bvca_member ? 'Yes' : 'No',
    ].join(',')
  })

  // GOTCHA: UTF-8 BOM (\uFEFF) needed for Windows Excel to correctly detect encoding
  const csv = '\uFEFF' + [headers.join(','), ...rows].join('\n')
  downloadBlob(csv, 'investor-directory.csv', 'text/csv;charset=utf-8')
}

function escapeCsv(value: string): string {
  // SECURITY: Neutralize formula injection (=, +, -, @, \t, \r can trigger formulas in Excel/Sheets)
  if (/^[=+\-@\t\r]/.test(value)) {
    value = "'" + value
  }
  if (value.includes(',') || value.includes('"') || value.includes('\n') || value.includes("'")) {
    return `"${value.replace(/"/g, '""')}"`
  }
  return value
}

function downloadBlob(content: string, filename: string, mimeType: string): void {
  const blob = new Blob([content], { type: mimeType })
  const url = URL.createObjectURL(blob)
  const a = document.createElement('a')
  a.href = url
  a.download = filename
  document.body.appendChild(a)
  a.click()
  document.body.removeChild(a)
  URL.revokeObjectURL(url)
}

// ---------------------------------------------------------------------------
// PPTX Export
// ---------------------------------------------------------------------------

// DECISION: Brand constants matching ForgeOS design system
const BRAND = {
  ORANGE: 'FF4500',
  DARK: '1A1A2E',
  WHITE: 'FFFFFF',
  GRAY: '6B7280',
  LIGHT_GRAY: 'F9FAFB',
}

/**
 * Generates a "Target Investor List" PPTX deck and triggers download.
 * Requires PptxGenJS (dynamically imported to keep bundle size down).
 */
export async function exportInvestorsPPTX(
  firms: InvestorFirm[],
  companyName: string,
  matchScores?: Record<string, number>
): Promise<void> {
  const PptxGenJS = (await import('pptxgenjs')).default
  const pptx = new PptxGenJS()

  pptx.layout = 'LAYOUT_WIDE' // 16:9
  pptx.author = 'ForgeOS'
  pptx.title = `Target Investor List — ${companyName}`

  // Cover slide
  const cover = pptx.addSlide()
  cover.background = { color: BRAND.DARK }
  cover.addText('Target Investor List', {
    x: 1, y: 2, w: 11, h: 1.5,
    fontSize: 36, bold: true, color: BRAND.WHITE,
    fontFace: 'Arial',
  })
  cover.addText(companyName, {
    x: 1, y: 3.5, w: 11, h: 0.6,
    fontSize: 18, color: BRAND.ORANGE,
    fontFace: 'Arial',
  })
  cover.addText(
    `${firms.length} firms · ${new Date().toLocaleDateString('en-GB', { day: 'numeric', month: 'long', year: 'numeric' })}`,
    { x: 1, y: 4.2, w: 11, h: 0.4, fontSize: 12, color: BRAND.GRAY, fontFace: 'Arial' }
  )
  cover.addText('Generated by ForgeOS', {
    x: 1, y: 6.5, w: 11, h: 0.3,
    fontSize: 9, color: BRAND.GRAY, fontFace: 'Arial',
  })

  // Summary slide
  const summary = pptx.addSlide()
  summary.addText('Summary', {
    x: 0.5, y: 0.3, w: 12, h: 0.6,
    fontSize: 24, bold: true, color: BRAND.DARK, fontFace: 'Arial',
  })

  // Type breakdown
  const typeCounts: Record<string, number> = {}
  for (const f of firms) {
    const t = f.attributes.firm_type ?? 'Other'
    typeCounts[t] = (typeCounts[t] ?? 0) + 1
  }
  const typeText = Object.entries(typeCounts)
    .sort((a, b) => b[1] - a[1])
    .map(([type, count]) => `${type}: ${count}`)
    .join('\n')

  summary.addText(`Total firms: ${firms.length}`, {
    x: 0.5, y: 1.2, w: 5, h: 0.4,
    fontSize: 14, bold: true, color: BRAND.DARK, fontFace: 'Arial',
  })
  summary.addText(typeText, {
    x: 0.5, y: 1.8, w: 5, h: 3,
    fontSize: 11, color: BRAND.GRAY, fontFace: 'Arial', lineSpacingMultiple: 1.5,
  })

  // Active deploying count
  const activeCount = firms.filter(f => f.attributes.is_active_deploying).length
  summary.addText(`Actively deploying: ${activeCount}/${firms.length}`, {
    x: 6.5, y: 1.2, w: 5, h: 0.4,
    fontSize: 14, bold: true, color: BRAND.DARK, fontFace: 'Arial',
  })

  // Table slides (10 firms per slide)
  const ROWS_PER_SLIDE = 10
  for (let i = 0; i < firms.length; i += ROWS_PER_SLIDE) {
    const chunk = firms.slice(i, i + ROWS_PER_SLIDE)
    const tableSlide = pptx.addSlide()

    tableSlide.addText(`Investor List (${i + 1}–${i + chunk.length} of ${firms.length})`, {
      x: 0.5, y: 0.3, w: 12, h: 0.5,
      fontSize: 16, bold: true, color: BRAND.DARK, fontFace: 'Arial',
    })

    const tableRows: Array<Array<{ text: string; options?: Record<string, unknown> }>> = [
      // Header
      ['Name', 'Type', 'Fund Size', 'Stage', 'Match'].map(h => ({
        text: h,
        options: { bold: true, fontSize: 9, color: BRAND.WHITE, fill: { color: BRAND.DARK } },
      })),
      // Data rows
      ...chunk.map(f => {
        const a = f.attributes
        return [
          { text: f.title, options: { fontSize: 8 } },
          { text: a.firm_type ?? '', options: { fontSize: 8 } },
          { text: a.fund_size_gbp ? `£${(a.fund_size_gbp / 1e6).toFixed(0)}M` : '', options: { fontSize: 8 } },
          { text: (a.stage_focus ?? []).slice(0, 2).join(', '), options: { fontSize: 8 } },
          { text: matchScores?.[f.id]?.toString() ?? '', options: { fontSize: 8 } },
        ]
      }),
    ]

    tableSlide.addTable(tableRows, {
      x: 0.5, y: 1, w: 12, h: 0.3,
      fontSize: 8,
      border: { type: 'solid', pt: 0.5, color: 'CCCCCC' },
      colW: [4, 1.5, 1.5, 3, 1.5],
      autoPage: false,
    })
  }

  const safeName = companyName.toLowerCase().replace(/[^a-z0-9]+/g, '-').replace(/^-|-$/g, '').slice(0, 50)
  await pptx.writeFile({ fileName: `investor-list-${safeName || 'export'}.pptx` })
}
