"use client"

/**
 * @file huddle-report.tsx
 *
 * @description Shareable meeting report dialog. After Cal's wrap-up generates a
 * structured report, this dialog lets the user preview it, copy it as markdown,
 * or email it to team members. Uses the existing Resend email infrastructure
 * via a server action.
 *
 * @related
 * - team-meeting-dialog.tsx — Parent triggers this dialog
 * - meeting-outputs.tsx — "Share Report" button opens this
 * - src/actions/agent-artifacts.ts — sendArtifactAsEmail pattern
 */

import { useState, useCallback, useMemo } from "react"
import {
    Dialog,
    DialogContent,
    DialogHeader,
    DialogTitle,
    DialogFooter,
} from "@/components/ui/dialog"
import { Button } from "@/components/ui/button"
import { Input } from "@/components/ui/input"
import { Badge } from "@/components/ui/badge"
import { ScrollArea } from "@/components/ui/scroll-area"
import {
    Send,
    Copy,
    CheckCircle2,
    Plus,
    X,
    Loader2,
    Mail,
} from "lucide-react"
import { cn } from "@/lib/utils"
import { toast } from "sonner"
import { Markdown } from "@/components/ui/markdown"
import { sendHuddleReportEmail } from "@/actions/huddle-report-email"

interface ReportData {
    subject: string
    summary: string
    decisions: string[]
    newActions: string[]
    removedItems: string[]
}

interface HuddleReportProps {
    open: boolean
    onOpenChange: (open: boolean) => void
    report: ReportData
    topic: string
    attendees: string[]
}

export function HuddleReport({
    open,
    onOpenChange,
    report,
    topic,
    attendees,
}: HuddleReportProps) {
    const [recipients, setRecipients] = useState<string[]>([])
    const [emailInput, setEmailInput] = useState("")
    const [isSending, setIsSending] = useState(false)
    const [isSent, setIsSent] = useState(false)
    const [isCopied, setIsCopied] = useState(false)

    const markdownReport = useMemo(() => {
        const lines: string[] = [
            `# ${report.subject}`,
            "",
            `**Meeting:** ${topic}`,
            `**Attendees:** ${attendees.join(", ")}`,
            `**Date:** ${new Date().toLocaleDateString("en-US", { weekday: "long", year: "numeric", month: "long", day: "numeric" })}`,
            "",
            "## Summary",
            "",
            report.summary,
            "",
        ]

        if (report.decisions.length > 0) {
            lines.push("## Key Decisions", "")
            for (const d of report.decisions) {
                lines.push(`- ${d}`)
            }
            lines.push("")
        }

        if (report.newActions.length > 0) {
            lines.push("## New Actions", "")
            for (const a of report.newActions) {
                lines.push(`- ${a}`)
            }
            lines.push("")
        }

        if (report.removedItems.length > 0) {
            lines.push("## Items Retired", "")
            for (const r of report.removedItems) {
                lines.push(`- ${r}`)
            }
            lines.push("")
        }

        lines.push("---", "", "*Report generated by Cal, Chief of Staff — ForgeOS*")

        return lines.join("\n")
    }, [report, topic, attendees])

    const handleAddRecipient = useCallback(() => {
        const email = emailInput.trim().toLowerCase()
        if (!email) return

        const emailRegex = /^[^\s@]+@[^\s@]+\.[^\s@]+$/
        if (!emailRegex.test(email)) {
            toast.error("Invalid email address")
            return
        }

        if (recipients.includes(email)) {
            toast.error("Already added")
            return
        }

        setRecipients((prev) => [...prev, email])
        setEmailInput("")
    }, [emailInput, recipients])

    const handleRemoveRecipient = useCallback((email: string) => {
        setRecipients((prev) => prev.filter((e) => e !== email))
    }, [])

    const handleCopy = useCallback(async () => {
        try {
            await navigator.clipboard.writeText(markdownReport)
            setIsCopied(true)
            toast.success("Report copied to clipboard")
            setTimeout(() => setIsCopied(false), 3000)
        } catch {
            toast.error("Failed to copy — try selecting and copying manually")
        }
    }, [markdownReport])

    const handleSend = useCallback(async () => {
        if (recipients.length === 0) {
            toast.error("Add at least one recipient")
            return
        }

        setIsSending(true)

        try {
            const result = await sendHuddleReportEmail(
                recipients,
                report.subject,
                markdownReport
            )

            if (result.error) {
                toast.error("Failed to send", { description: result.error })
            } else {
                setIsSent(true)
                toast.success("Report sent", {
                    description: `Emailed to ${recipients.length} recipient${recipients.length !== 1 ? "s" : ""}`,
                })
            }
        } catch (err) {
            const message = err instanceof Error ? err.message : "Unknown error"
            toast.error("Failed to send", { description: message })
        } finally {
            setIsSending(false)
        }
    }, [recipients, report.subject, markdownReport])

    const handleKeyDown = useCallback(
        (e: React.KeyboardEvent<HTMLInputElement>) => {
            if (e.key === "Enter") {
                e.preventDefault()
                handleAddRecipient()
            }
        },
        [handleAddRecipient]
    )

    return (
        <Dialog open={open} onOpenChange={onOpenChange}>
            <DialogContent size="lg" className="max-h-[90vh] flex flex-col">
                <DialogHeader>
                    <DialogTitle className="flex items-center gap-2">
                        <Mail className="h-5 w-5 text-international-orange" />
                        Share Meeting Report
                    </DialogTitle>
                </DialogHeader>

                <ScrollArea className="flex-1 max-h-[50vh]">
                    <div className="rounded-lg border border-muted bg-muted/20 p-5">
                        <Markdown content={markdownReport} className="text-sm" />
                    </div>
                </ScrollArea>

                {/* Email Recipients */}
                <div className="space-y-3 pt-2">
                    <div className="flex items-center gap-2">
                        <Input
                            placeholder="Add email address..."
                            value={emailInput}
                            onChange={(e) => setEmailInput(e.target.value)}
                            onKeyDown={handleKeyDown}
                            className="flex-1"
                            type="email"
                        />
                        <Button
                            variant="secondary"
                            size="sm"
                            onClick={handleAddRecipient}
                            disabled={!emailInput.trim()}
                        >
                            <Plus className="h-4 w-4" />
                        </Button>
                    </div>

                    {recipients.length > 0 && (
                        <div className="flex flex-wrap gap-1.5">
                            {recipients.map((email) => (
                                <Badge
                                    key={email}
                                    variant="secondary"
                                    className="flex items-center gap-1 pr-1"
                                >
                                    {email}
                                    <button
                                        onClick={() => handleRemoveRecipient(email)}
                                        className="ml-0.5 p-0.5 rounded hover:bg-muted"
                                        aria-label={`Remove ${email}`}
                                    >
                                        <X className="h-3 w-3" />
                                    </button>
                                </Badge>
                            ))}
                        </div>
                    )}
                </div>

                <DialogFooter>
                    <div className="flex w-full items-center justify-between gap-2">
                        <Button variant="secondary" onClick={handleCopy}>
                            {isCopied ? (
                                <CheckCircle2 className="h-4 w-4 mr-2 text-status-success" />
                            ) : (
                                <Copy className="h-4 w-4 mr-2" />
                            )}
                            {isCopied ? "Copied" : "Copy as Markdown"}
                        </Button>

                        <Button
                            onClick={handleSend}
                            disabled={recipients.length === 0 || isSending || isSent}
                            className={cn(
                                !isSent && "bg-international-orange hover:bg-international-orange-hover text-white"
                            )}
                        >
                            {isSending ? (
                                <Loader2 className="h-4 w-4 animate-spin mr-2" />
                            ) : isSent ? (
                                <CheckCircle2 className="h-4 w-4 mr-2 text-status-success" />
                            ) : (
                                <Send className="h-4 w-4 mr-2" />
                            )}
                            {isSent
                                ? "Sent"
                                : recipients.length > 0
                                  ? `Send to ${recipients.length} recipient${recipients.length !== 1 ? "s" : ""}`
                                  : "Send"}
                        </Button>
                    </div>
                </DialogFooter>
            </DialogContent>
        </Dialog>
    )
}
