/**
 * @file download-pack.ts
 * @description Client-side downloadable technical pack (ZIP) for RFQ attachments.
 * Fetches all attachments, generates a spec sheet, and bundles into a ZIP download.
 */

import type { RFQWithDetails } from '@/types/rfq'

/**
 * Build a plain-text spec sheet from RFQ data
 */
function buildSpecSheet(rfq: RFQWithDetails): string {
  const lines: string[] = []

  lines.push(`RFQ Technical Pack`)
  lines.push(`==================`)
  lines.push(``)
  lines.push(`Title: ${rfq.title}`)
  lines.push(`Type: ${rfq.rfq_type}`)
  lines.push(`Category: ${rfq.category || 'Not specified'}`)
  lines.push(`Status: ${rfq.status}`)
  lines.push(`Created: ${new Date(rfq.created_at).toLocaleDateString()}`)
  lines.push(``)

  if (rfq.budget_min != null || rfq.budget_max != null) {
    const min = rfq.budget_min != null ? `£${rfq.budget_min.toLocaleString()}` : 'N/A'
    const max = rfq.budget_max != null ? `£${rfq.budget_max.toLocaleString()}` : 'N/A'
    lines.push(`Budget: ${min} – ${max}`)
  }

  if (rfq.deadline) {
    lines.push(`Deadline: ${new Date(rfq.deadline).toLocaleDateString()}`)
  }

  lines.push(``)
  lines.push(`Specifications`)
  lines.push(`--------------`)

  const specs = rfq.specifications
  if (specs?.description) {
    lines.push(specs.description as string)
  }

  if (specs?.quantity) {
    lines.push(`Quantity: ${specs.quantity} ${specs.unit || 'units'}`)
  }

  if (specs?.materials && Array.isArray(specs.materials)) {
    lines.push(`Materials: ${specs.materials.join(', ')}`)
  }

  if (specs?.dimensions) {
    const d = specs.dimensions
    lines.push(`Dimensions: ${d.length || '?'} x ${d.width || '?'} x ${d.height || '?'} ${d.unit || 'mm'}`)
  }

  // Structured modules from custom_fields
  const customFields = specs?.custom_fields as Record<string, unknown> | undefined
  if (customFields?.modules && Array.isArray(customFields.modules)) {
    lines.push(``)
    lines.push(`Modules`)
    lines.push(`-------`)
    for (const mod of customFields.modules) {
      const m = mod as Record<string, unknown>
      lines.push(``)
      lines.push(`  Name: ${m.name || 'Unnamed'}`)
      if (m.process) lines.push(`  Process: ${m.process}`)
      if (m.material) lines.push(`  Material: ${m.material}`)
      if (m.finish) lines.push(`  Finish: ${m.finish}`)
      if (m.tolerance) lines.push(`  Tolerance: ${m.tolerance}`)
      if (m.quantity) lines.push(`  Quantity: ${m.quantity}`)
    }
  }

  lines.push(``)
  lines.push(`---`)
  lines.push(`Generated by ForgeOS`)

  return lines.join('\n')
}

/**
 * Download a technical pack ZIP for an RFQ.
 * Client-side only — fetches attachments and bundles with spec sheet.
 */
export async function downloadTechPack(rfq: RFQWithDetails): Promise<void> {
  const JSZip = (await import('jszip')).default
  const zip = new JSZip()

  // Add spec sheet
  const specSheet = buildSpecSheet(rfq)
  zip.file('spec-sheet.txt', specSheet)

  // Fetch and add attachments (cap at 50 to prevent browser overload)
  const attachments = rfq.specifications?.attachments
  if (Array.isArray(attachments)) {
    const maxAttachments = 50
    for (let i = 0; i < Math.min(attachments.length, maxAttachments); i++) {
      const url = attachments[i]
      if (typeof url !== 'string' || !url) continue

      // SECURITY: Only allow HTTPS URLs to prevent protocol abuse
      try {
        const parsed = new URL(url)
        if (parsed.protocol !== 'https:') continue
      } catch { continue }

      try {
        const response = await fetch(url)
        if (!response.ok) continue

        const blob = await response.blob()

        // Extract filename from URL
        const urlPath = new URL(url).pathname
        const segments = urlPath.split('/')
        const rawName = segments[segments.length - 1] || `attachment-${i + 1}`
        // SECURITY: Sanitize filename — strip path traversal, control chars, reserved chars
        const fileName = decodeURIComponent(rawName)
          .replace(/\.\./g, '_')
          .replace(/[/\\:*?"<>|\x00-\x1f]/g, '_')
        if (!fileName || fileName === '.' || fileName === '..') continue

        zip.file(`attachments/${fileName}`, blob)
      } catch {
        // Skip failed downloads — don't block the pack
        console.warn(`Failed to download attachment: ${url}`)
      }
    }
  }

  // Generate and trigger download
  const content = await zip.generateAsync({ type: 'blob' })
  const downloadUrl = URL.createObjectURL(content)
  const a = document.createElement('a')
  a.href = downloadUrl
  const safeName = rfq.title.replace(/[^a-zA-Z0-9-_ ]/g, '').trim() || 'rfq'
  a.download = `${safeName}-tech-pack.zip`
  document.body.appendChild(a)
  a.click()
  document.body.removeChild(a)
  // Delay revocation so the browser can finish reading the blob
  setTimeout(() => URL.revokeObjectURL(downloadUrl), 10000)
}
