'use client'

import type { CoverSectionData } from '@/lib/reports/report-document-types'

type CoverSectionProps = CoverSectionData

export function CoverSection({
  companyName,
  reportTitle,
  subtitle,
  generatedAt,
}: CoverSectionProps) {
  const formattedDate = new Intl.DateTimeFormat('en-US', {
    weekday: 'long',
    year: 'numeric',
    month: 'long',
    day: 'numeric',
    hour: 'numeric',
    minute: '2-digit',
  }).format(new Date(generatedAt))

  return (
    <section className="flex flex-col items-center justify-center py-16 text-center">
      <h1 className="text-3xl font-display font-bold text-foreground">
        {companyName}
      </h1>

      <div className="mt-6 flex justify-center">
        <div className="h-1 w-16 rounded-full bg-international-orange" />
      </div>

      <h2 className="mt-6 text-xl text-muted-foreground">{reportTitle}</h2>

      <p className="mt-3 text-base text-muted-foreground">{subtitle}</p>

      <p className="mt-12 text-xs text-muted-foreground">
        Generated {formattedDate}
      </p>
      <p className="mt-1 text-xs text-muted-foreground">
        Generated by ForgeOS
      </p>
    </section>
  )
}
