'use client'

/* eslint-disable @next/next/no-img-element */

import type { CoverSectionData, ReportBranding } from '@/lib/reports/report-document-types'

interface CoverSectionProps extends CoverSectionData {
  branding?: ReportBranding
}

export function CoverSection({
  companyName,
  reportTitle,
  subtitle,
  generatedAt,
  branding,
}: CoverSectionProps) {
  const formattedDate = new Intl.DateTimeFormat('en-US', {
    weekday: 'long',
    year: 'numeric',
    month: 'long',
    day: 'numeric',
    hour: 'numeric',
    minute: '2-digit',
  }).format(new Date(generatedAt))

  return (
    <section className="flex flex-col items-center justify-center py-16 text-center">
      {branding?.logoUrl && (
        <img
          src={branding.logoUrl}
          alt={`${companyName} logo`}
          className="mb-6 h-16 w-auto object-contain"
        />
      )}

      <h1 className="text-3xl font-display font-bold text-foreground">
        {companyName}
      </h1>

      <div className="mt-6 flex justify-center">
        <div
          className="h-1 w-16 rounded-full bg-international-orange"
          style={branding?.primaryColor ? { backgroundColor: branding.primaryColor } : undefined}
        />
      </div>

      <h2 className="mt-6 text-xl text-muted-foreground">{reportTitle}</h2>

      <p className="mt-3 text-base text-muted-foreground">{subtitle}</p>

      <p className="mt-12 text-xs text-muted-foreground">
        Generated {formattedDate}
      </p>
      <p className="mt-1 text-xs text-muted-foreground">
        Generated by ForgeOS
      </p>
    </section>
  )
}
