'use client'

/**
 * @file ReportDocument.tsx
 *
 * @description Main report renderer that composes report sections into a
 * scrollable document. Serves double duty as the in-app preview and as the
 * HTML source for PDF generation (via the `forPrint` prop).
 *
 * @related
 * - src/lib/reports/report-document-types.ts — Type definitions
 * - src/components/reports/sections/ — Individual section renderers
 * - src/app/(platform)/reports/page.tsx — Reports page UI
 */

import { format } from 'date-fns'

import { cn } from '@/lib/utils'
import {
  CoverSection,
  ExecutiveSummarySection,
  KeyMetricsSection,
  ObjectivesProgressSection,
  TeamActivitySection,
  BlockersRisksSection,
  CompletionTrendSection,
  WeekAheadSection,
} from '@/components/reports/sections'

import type {
  ReportDocument as ReportDocumentType,
  SectionData,
  ReportBranding,
  ReportTemplateId,
} from '@/lib/reports/report-document-types'

/* eslint-disable @typescript-eslint/no-explicit-any */
const SECTION_RENDERERS: Record<string, React.ComponentType<any>> = {
  'cover': CoverSection,
  'executive-summary': ExecutiveSummarySection,
  'key-metrics': KeyMetricsSection,
  'objectives-progress': ObjectivesProgressSection,
  'team-activity': TeamActivitySection,
  'blockers-risks': BlockersRisksSection,
  'completion-trend': CompletionTrendSection,
  'week-ahead': WeekAheadSection,
}
/* eslint-enable @typescript-eslint/no-explicit-any */

interface ReportDocumentProps {
  document: ReportDocumentType
  forPrint?: boolean
}

function renderSection(
  section: SectionData,
  _forPrint: boolean,
  branding: ReportBranding | undefined,
  templateId: ReportTemplateId,
  sectionNumber: number,
): React.ReactNode {
  const Renderer = SECTION_RENDERERS[section.type]
  if (!Renderer) return null

  const sharedProps = { templateId, sectionNumber }
  const extraProps = section.type === 'cover' ? { branding } : {}
  return <Renderer {...section.data} {...extraProps} {...sharedProps} />
}

export function ReportDocument({ document, forPrint = false }: ReportDocumentProps): React.JSX.Element {
  const formattedTimestamp = format(new Date(document.generatedAt), 'd MMM yyyy, h:mm a')
  const templateId = (document.templateId || 'weekly-update') as ReportTemplateId

  let sectionCounter = 0

  return (
    <div
      className={cn(
        'max-w-4xl mx-auto bg-background',
        forPrint && 'print-document'
      )}
    >
      <div className="space-y-12">
        {document.sections.map((section, index) => {
          const isCover = section.type === 'cover'
          const isMajorSection = !isCover && index > 0

          if (!isCover) sectionCounter++
          const sectionNumber = isCover ? 0 : sectionCounter

          return (
            <div
              key={`${section.type}-${index}`}
              className={cn(
                !isCover && 'border-t border-muted pt-12',
                forPrint && isMajorSection && 'print-page-break'
              )}
            >
              {renderSection(section, forPrint, document.branding, templateId, sectionNumber)}
            </div>
          )
        })}
      </div>

      <footer className="mt-16 border-t border-muted py-8 text-center">
        <p className="text-xs text-muted-foreground">
          Generated by ForgeOS · {formattedTimestamp}
        </p>
      </footer>

      {forPrint && (
        <style>{`
          .print-document {
            -webkit-print-color-adjust: exact;
            print-color-adjust: exact;
          }
          .print-document .print-page-break {
            page-break-before: always;
          }
          @media print {
            .print-document * {
              transition: none !important;
              animation: none !important;
            }
          }
        `}</style>
      )}
    </div>
  )
}
