/**
 * @file modal-compute.ts — Client for Modal Python computation endpoint.
 *
 * @description Sends Python code to Modal's serverless infrastructure for
 * execution with engineering libraries (numpy, scipy, sympy, pint).
 * Used by engineering tool handlers for stress analysis, tolerance
 * stack-ups, thermal calculations, and other computations that require
 * real numerical methods — not LLM approximation.
 *
 * INTENT: LLMs cannot reliably do engineering math. This module provides
 * a bridge to real Python computation so specialist tool calls return
 * verifiable numbers backed by classical mechanics formulas.
 *
 * @security
 * - Code is template-generated by handlers, not user-provided
 * - Modal containers are sandboxed (no ForgeOS infra access)
 * - 30-second timeout prevents runaway computation
 * - Dangerous imports blocked by validation
 *
 * @related
 * - CAD execution: src/app/(platform)/the-forge/services/cad-generator.ts
 * - Tool handlers: src/lib/agents/tools/handlers/engineering-compute.ts
 * - Tool registry: src/lib/agents/tools/registry.ts
 */

// ─── Constants ───────────────────────────────────────────────────────

const COMPUTE_TIMEOUT_MS = 30_000
const MAX_CODE_LENGTH = 50_000

/** Dangerous imports that should never appear in compute code. */
const DANGEROUS_CODE_RE =
    /(?:^|\s)(?:import|from)\s+(?:os|sys|subprocess|shutil|importlib|pickle|marshal|ctypes)\b|__import__\s*\(|__builtins__|(?:exec|eval|compile|open)\s*\(|getattr\s*\([^)]*__|globals\s*\(|locals\s*\(|__subclasses__/m

// ─── Types ───────────────────────────────────────────────────────────

export interface ComputeResult {
    /** Parsed JSON result if the script printed valid JSON, otherwise raw stdout */
    result: unknown
    /** Raw stdout from the Python script */
    stdout: string
    /** Error message if execution failed */
    error: string | null
    /** Execution time in milliseconds */
    duration_ms: number
}

// ─── Validation ──────────────────────────────────────────────────────

/**
 * Validates Python code before sending to Modal.
 *
 * @param code - Python source code to validate
 * @returns null if valid, or human-readable error string
 */
function validateComputeCode(code: string): string | null {
    if (!code || code.length < 10) {
        return "Code too short to be a valid computation script."
    }
    if (code.length > MAX_CODE_LENGTH) {
        return `Code too long (${code.length} chars, max ${MAX_CODE_LENGTH}).`
    }
    const dangerousMatch = DANGEROUS_CODE_RE.exec(code)
    if (dangerousMatch) {
        return `Blocked dangerous code: '${dangerousMatch[0].trim()}'`
    }
    return null
}

// ─── Modal Client ────────────────────────────────────────────────────

/**
 * Executes Python code on Modal's serverless compute infrastructure.
 *
 * @description Sends code to the Modal `/compute` endpoint which has
 * numpy, scipy, sympy, and pint pre-installed. The script should print
 * its result as JSON to stdout (via `json.dumps()`).
 *
 * @param code - Python code to execute. Should print result as JSON to stdout.
 * @param description - Human-readable description for logging.
 * @returns Parsed result, raw stdout, error status, and duration.
 *
 * @throws Error if MODAL_CAD_ENDPOINT_URL is not configured or if
 *   the code contains dangerous imports.
 */
export async function executeModalCompute(
    code: string,
    description?: string,
): Promise<ComputeResult> {
    const startMs = Date.now()

    // Validate code safety
    const validationError = validateComputeCode(code)
    if (validationError) {
        return {
            result: null,
            stdout: "",
            error: validationError,
            duration_ms: Date.now() - startMs,
        }
    }

    // Get Modal endpoint
    const baseUrl = process.env.MODAL_CAD_ENDPOINT_URL?.replace(/\/$/, "")
    if (!baseUrl) {
        return {
            result: null,
            stdout: "",
            error: "MODAL_CAD_ENDPOINT_URL not configured. Engineering computation unavailable.",
            duration_ms: Date.now() - startMs,
        }
    }

    console.info("[ModalCompute] Sending computation:", {
        description: description ?? "unnamed",
        codeLength: code.length,
    })

    const controller = new AbortController()
    const timeoutId = setTimeout(() => controller.abort(), COMPUTE_TIMEOUT_MS)

    try {
        const response = await fetch(`${baseUrl}/compute`, {
            method: "POST",
            headers: { "Content-Type": "application/json" },
            body: JSON.stringify({
                code,
                timeout_s: Math.floor(COMPUTE_TIMEOUT_MS / 1000),
            }),
            signal: controller.signal,
        })

        const durationMs = Date.now() - startMs

        if (!response.ok) {
            const errText = await response.text()
            return {
                result: null,
                stdout: "",
                error: `Modal API error (${response.status}): ${errText.slice(0, 500)}`,
                duration_ms: durationMs,
            }
        }

        const body = (await response.json()) as {
            result?: unknown
            stdout?: string
            error?: string
        }

        if (body.error) {
            return {
                result: null,
                stdout: body.stdout ?? "",
                error: body.error,
                duration_ms: durationMs,
            }
        }

        // Try to parse stdout as JSON if no structured result
        let result = body.result ?? null
        const stdout = body.stdout ?? ""

        if (result === null && stdout.trim()) {
            try {
                result = JSON.parse(stdout.trim())
            } catch {
                // stdout is not JSON — return as raw string
                result = stdout.trim()
            }
        }

        return {
            result,
            stdout,
            error: null,
            duration_ms: durationMs,
        }
    } catch (error) {
        const durationMs = Date.now() - startMs
        if (error instanceof DOMException && error.name === "AbortError") {
            return {
                result: null,
                stdout: "",
                error: `Computation timed out after ${COMPUTE_TIMEOUT_MS / 1000}s.`,
                duration_ms: durationMs,
            }
        }
        return {
            result: null,
            stdout: "",
            error: error instanceof Error ? error.message : String(error),
            duration_ms: durationMs,
        }
    } finally {
        clearTimeout(timeoutId)
    }
}
