"use server"

/**
 * @file design-standards.ts — Server actions for the Design Standards Library.
 *
 * INTENT: Provides query and search capabilities for design standards stored
 * in Supabase. Standards are global (not per-foundry) and readable by all
 * authenticated users.
 */

import { createClient } from "@/lib/supabase/server"
import type { DesignStandard } from "@/types/design-standards"
import type { IndustryDomain } from "@/lib/cad-lab/industry-domains"

/**
 * Get all standards for a specific industry domain.
 */
export async function getStandardsByDomain(
  domain: IndustryDomain,
): Promise<{ data: DesignStandard[] | null; error: string | null }> {
  const supabase = await createClient()
  const { data, error } = await supabase
    .from("design_standards")
    .select("*")
    .eq("industry_domain", domain)
    .is("superseded_by", null)
    .order("standard_code")

  if (error) return { data: null, error: error.message }
  return { data: data as unknown as DesignStandard[], error: null }
}

/**
 * Get a single standard by its code.
 */
export async function getStandardByCode(
  code: string,
): Promise<{ data: DesignStandard | null; error: string | null }> {
  const supabase = await createClient()
  const { data, error } = await supabase
    .from("design_standards")
    .select("*")
    .eq("standard_code", code)
    .single()

  if (error) return { data: null, error: error.message }
  return { data: data as unknown as DesignStandard, error: null }
}

/**
 * Search standards by text query across code, name, and summary.
 */
export async function searchStandards(
  query: string,
  limit: number = 20,
): Promise<{ data: DesignStandard[] | null; error: string | null }> {
  const supabase = await createClient()
  if (!query || query.trim().length === 0) {
    return { data: [], error: null }
  }

  // SECURITY: Escape LIKE wildcards to prevent injection via % and _
  const escaped = query.trim().replace(/[%_\\]/g, (c) => `\\${c}`)
  const { data, error } = await supabase
    .from("design_standards")
    .select("*")
    .or(`standard_code.ilike.%${escaped}%,standard_name.ilike.%${escaped}%,summary.ilike.%${escaped}%`)
    .is("superseded_by", null)
    .limit(limit)

  if (error) return { data: null, error: error.message }
  return { data: data as unknown as DesignStandard[], error: null }
}

/**
 * Get total standards count and breakdown by domain.
 */
export async function getStandardsStats(): Promise<{
  total: number
  byDomain: Record<string, number>
  verified: number
  autoGenerated: number
}> {
  const supabase = await createClient()
  const { data, error } = await supabase
    .from("design_standards")
    .select("industry_domain, source, verified")

  if (error || !data) return { total: 0, byDomain: {}, verified: 0, autoGenerated: 0 }

  const byDomain: Record<string, number> = {}
  let verified = 0
  let autoGenerated = 0

  for (const row of data) {
    byDomain[row.industry_domain] = (byDomain[row.industry_domain] || 0) + 1
    if (row.verified === true) verified++
    if (row.source === "ai_auto_generated" || row.source === "ai_generated") autoGenerated++
  }

  return { total: data.length, byDomain, verified, autoGenerated }
}

/**
 * Fetches full engineering intelligence data for inclusion in reports.
 * Returns standards details, material properties, and process capabilities.
 */
export async function getEngineeringIntelligenceForReport(
  standardCodes: string[],
  industryDomain: string | null,
  description: string,
): Promise<{
  standards: { code: string; name: string; issuingBody: string; summary: string }[]
  materials: { code: string; name: string; density: number | null; yieldStrength: number | null; thermalConductivity: number | null; costPerKg: number | null }[]
  processes: { name: string; displayName: string; toleranceTypical: number | null; minWall: number | null }[]
  hardwareCount: number
}> {
  const supabase = await createClient()

  // Fetch full standard details for the referenced codes
  let standards: { code: string; name: string; issuingBody: string; summary: string }[] = []
  if (standardCodes.length > 0) {
    const { data: stdData } = await supabase
      .from("design_standards")
      .select("standard_code, standard_name, issuing_body, summary")
      .in("standard_code", standardCodes)
    if (stdData) {
      standards = stdData.map(s => ({
        code: s.standard_code,
        name: s.standard_name,
        issuingBody: s.issuing_body,
        summary: (s.summary as string).slice(0, 300),
      }))
    }
  }

  // Fetch material properties for detected families
  const { data: matData } = await supabase
    .from("material_properties")
    .select("material_code, material_name, density_kg_m3, yield_strength_mpa, thermal_conductivity_w_mk, cost_per_kg_usd")
    .limit(20)
  const materials = (matData ?? []).map(m => ({
    code: m.material_code as string,
    name: m.material_name as string,
    density: m.density_kg_m3 as number | null,
    yieldStrength: m.yield_strength_mpa as number | null,
    thermalConductivity: m.thermal_conductivity_w_mk as number | null,
    costPerKg: m.cost_per_kg_usd as number | null,
  }))

  // Fetch process capabilities
  const { data: procData } = await supabase
    .from("process_capabilities")
    .select("process_name, display_name, tolerance_typical_mm, min_wall_thickness_mm")
    .limit(20)
  const processes = (procData ?? []).map(p => ({
    name: p.process_name as string,
    displayName: p.display_name as string,
    toleranceTypical: p.tolerance_typical_mm as number | null,
    minWall: p.min_wall_thickness_mm as number | null,
  }))

  // Count hardware items
  const { count: hardwareCount } = await supabase
    .from("standard_hardware")
    .select("id", { count: "exact", head: true })

  return { standards, materials, processes, hardwareCount: hardwareCount ?? 0 }
}
