"use server"

/**
 * @file design-standards.ts — Server actions for the Design Standards Library.
 *
 * INTENT: Provides query and search capabilities for design standards stored
 * in Supabase. Standards are global (not per-foundry) and readable by all
 * authenticated users.
 */

import { createClient } from "@/lib/supabase/server"
import type { DesignStandard } from "@/types/design-standards"
import type { IndustryDomain } from "@/lib/cad-lab/industry-domains"

/**
 * Get all standards for a specific industry domain.
 */
export async function getStandardsByDomain(
  domain: IndustryDomain,
): Promise<{ data: DesignStandard[] | null; error: string | null }> {
  const supabase = await createClient()
  const { data, error } = await supabase
    .from("design_standards")
    .select("*")
    .eq("industry_domain", domain)
    .is("superseded_by", null)
    .order("standard_code")

  if (error) return { data: null, error: error.message }
  return { data: data as unknown as DesignStandard[], error: null }
}

/**
 * Get a single standard by its code.
 */
export async function getStandardByCode(
  code: string,
): Promise<{ data: DesignStandard | null; error: string | null }> {
  const supabase = await createClient()
  const { data, error } = await supabase
    .from("design_standards")
    .select("*")
    .eq("standard_code", code)
    .single()

  if (error) return { data: null, error: error.message }
  return { data: data as unknown as DesignStandard, error: null }
}

/**
 * Search standards by text query across code, name, and summary.
 */
export async function searchStandards(
  query: string,
  limit: number = 20,
): Promise<{ data: DesignStandard[] | null; error: string | null }> {
  const supabase = await createClient()
  // SECURITY: Escape LIKE wildcards to prevent injection via % and _
  const escaped = query.replace(/[%_\\]/g, (c) => `\\${c}`)
  const { data, error } = await supabase
    .from("design_standards")
    .select("*")
    .or(`standard_code.ilike.%${escaped}%,standard_name.ilike.%${escaped}%,summary.ilike.%${escaped}%`)
    .is("superseded_by", null)
    .limit(limit)

  if (error) return { data: null, error: error.message }
  return { data: data as unknown as DesignStandard[], error: null }
}

/**
 * Get total standards count and breakdown by domain.
 */
export async function getStandardsStats(): Promise<{
  total: number
  byDomain: Record<string, number>
  verified: number
  autoGenerated: number
}> {
  const supabase = await createClient()
  const { data, error } = await supabase
    .from("design_standards")
    .select("industry_domain, source, verified")

  if (error || !data) return { total: 0, byDomain: {}, verified: 0, autoGenerated: 0 }

  const byDomain: Record<string, number> = {}
  let verified = 0
  let autoGenerated = 0

  for (const row of data) {
    byDomain[row.industry_domain] = (byDomain[row.industry_domain] || 0) + 1
    if (row.verified) verified++
    if (row.source === "ai_auto_generated") autoGenerated++
  }

  return { total: data.length, byDomain, verified, autoGenerated }
}
