"use server"

/**
 * @file design-standards.ts — Server actions for the Design Standards Library.
 *
 * INTENT: Provides query and search capabilities for design standards stored
 * in Supabase. Standards are global (not per-foundry) and readable by all
 * authenticated users.
 */

import { createClient } from "@/lib/supabase/server"
import type { DesignStandard } from "@/types/design-standards"
import type { IndustryDomain } from "@/lib/cad-lab/industry-domains"

/**
 * Get all standards for a specific industry domain.
 */
export async function getStandardsByDomain(
  domain: IndustryDomain,
): Promise<{ data: DesignStandard[] | null; error: string | null }> {
  const supabase = await createClient()
  const { data, error } = await supabase
    .from("design_standards")
    .select("*")
    .eq("industry_domain", domain)
    .is("superseded_by", null)
    .order("standard_code")

  if (error) return { data: null, error: error.message }
  return { data: data as unknown as DesignStandard[], error: null }
}

/**
 * Get a single standard by its code.
 */
export async function getStandardByCode(
  code: string,
): Promise<{ data: DesignStandard | null; error: string | null }> {
  const supabase = await createClient()
  const { data, error } = await supabase
    .from("design_standards")
    .select("*")
    .eq("standard_code", code)
    .single()

  if (error) return { data: null, error: error.message }
  return { data: data as unknown as DesignStandard, error: null }
}

/**
 * Search standards by text query across code, name, and summary.
 */
export async function searchStandards(
  query: string,
  limit: number = 20,
): Promise<{ data: DesignStandard[] | null; error: string | null }> {
  const supabase = await createClient()
  if (!query || query.trim().length === 0) {
    return { data: [], error: null }
  }

  // SECURITY: Escape LIKE wildcards to prevent injection via % and _
  const escaped = query.trim().replace(/[%_\\]/g, (c) => `\\${c}`)
  const { data, error } = await supabase
    .from("design_standards")
    .select("*")
    .or(`standard_code.ilike.%${escaped}%,standard_name.ilike.%${escaped}%,summary.ilike.%${escaped}%`)
    .is("superseded_by", null)
    .limit(limit)

  if (error) return { data: null, error: error.message }
  return { data: data as unknown as DesignStandard[], error: null }
}

/**
 * Get total standards count and breakdown by domain.
 */
export async function getStandardsStats(): Promise<{
  total: number
  byDomain: Record<string, number>
  verified: number
  autoGenerated: number
}> {
  const supabase = await createClient()
  const { data, error } = await supabase
    .from("design_standards")
    .select("industry_domain, source, verified")

  if (error || !data) return { total: 0, byDomain: {}, verified: 0, autoGenerated: 0 }

  const byDomain: Record<string, number> = {}
  let verified = 0
  let autoGenerated = 0

  for (const row of data) {
    byDomain[row.industry_domain] = (byDomain[row.industry_domain] || 0) + 1
    if (row.verified === true) verified++
    if (row.source === "ai_auto_generated" || row.source === "ai_generated") autoGenerated++
  }

  return { total: data.length, byDomain, verified, autoGenerated }
}

/**
 * Fetches full engineering intelligence data for inclusion in reports.
 * Returns standards details, material properties, and process capabilities.
 */
export async function getEngineeringIntelligenceForReport(
  standardCodes: string[],
  industryDomain: string | null,
  description: string,
): Promise<{
  standards: { code: string; name: string; issuingBody: string; summary: string }[]
  materials: { code: string; name: string; density: number | null; yieldStrength: number | null; thermalConductivity: number | null; costPerKg: number | null }[]
  processes: { name: string; displayName: string; toleranceTypical: number | null; minWall: number | null }[]
  hardwareCount: number
  supplierInsights: { technique: string; supplierCount: number; tolerances: string; materials: string }[]
}> {
  const supabase = await createClient()

  // Fetch full standard details for the referenced codes
  let standards: { code: string; name: string; issuingBody: string; summary: string }[] = []
  if (standardCodes.length > 0) {
    const { data: stdData, error: stdErr } = await supabase
      .from("design_standards")
      .select("standard_code, standard_name, issuing_body, summary")
      .in("standard_code", standardCodes)
    if (stdErr) console.warn("[design-standards] Standards fetch failed:", stdErr.message)
    if (stdData) {
      standards = stdData.map(s => ({
        code: s.standard_code as string,
        name: s.standard_name as string,
        issuingBody: s.issuing_body as string,
        summary: ((s.summary as string | null) ?? "").slice(0, 300),
      }))
    }
  }

  // Fetch material properties — filter by families detected in the description
  const lower = description.toLowerCase()
  const familyFilters: string[] = []
  if (/\baluminu?m\b/i.test(lower)) familyFilters.push("aluminum")
  if (/\bsteel\b/i.test(lower)) familyFilters.push("steel")
  if (/\bstainless\b/i.test(lower)) familyFilters.push("stainless_steel")
  if (/\btitanium\b/i.test(lower)) familyFilters.push("titanium")
  if (/\bcopper|brass|bronze\b/i.test(lower)) familyFilters.push("copper")
  if (/\bplastic|polymer|abs|pla|petg|nylon|peek\b/i.test(lower)) familyFilters.push("polymer")
  if (/\brubber|silicone|tpu|elastomer\b/i.test(lower)) familyFilters.push("elastomer")
  if (/\bcarbon fiber|composite|fiberglass\b/i.test(lower)) familyFilters.push("composite")
  if (/\bwood|plywood|timber\b/i.test(lower)) familyFilters.push("wood")

  let matQuery = supabase
    .from("material_properties")
    .select("material_code, material_name, density_kg_m3, yield_strength_mpa, thermal_conductivity_w_mk, cost_per_kg_usd")
  if (familyFilters.length > 0) {
    matQuery = matQuery.in("material_family", familyFilters)
  }
  const { data: matData } = await matQuery.limit(20)
  const materials = (matData ?? []).map(m => ({
    code: m.material_code as string,
    name: m.material_name as string,
    density: m.density_kg_m3 as number | null,
    yieldStrength: m.yield_strength_mpa as number | null,
    thermalConductivity: m.thermal_conductivity_w_mk as number | null,
    costPerKg: m.cost_per_kg_usd as number | null,
  }))

  // Fetch process capabilities
  const { data: procData } = await supabase
    .from("process_capabilities")
    .select("process_name, display_name, tolerance_typical_mm, min_wall_thickness_mm")
    .limit(20)
  const processes = (procData ?? []).map(p => ({
    name: p.process_name as string,
    displayName: p.display_name as string,
    toleranceTypical: p.tolerance_typical_mm as number | null,
    minWall: p.min_wall_thickness_mm as number | null,
  }))

  // Count hardware items
  const { count: hardwareCount } = await supabase
    .from("standard_hardware")
    .select("id", { count: "exact", head: true })

  // Fetch Nightshift technique enrichments (real supplier data)
  let supplierInsights: { technique: string; supplierCount: number; tolerances: string; materials: string }[] = []
  try {
    const { data: techData } = await supabase
      .from("manufacturing_technique_enrichments")
      .select("technique_slug, supplier_count, real_world_tolerances, real_world_materials")
      .order("supplier_count", { ascending: false })
      .limit(10)
    if (techData) {
      supplierInsights = techData.map(t => {
        const tols = t.real_world_tolerances as Record<string, unknown> | null
        const mats = t.real_world_materials as Array<{ material?: string }> | null
        return {
          technique: (t.technique_slug as string).replace(/-/g, " ").replace(/\b\w/g, c => c.toUpperCase()),
          supplierCount: (t.supplier_count as number) ?? 0,
          tolerances: tols ? `${tols.min_mm ?? "?"}–${tols.max_mm ?? "?"}mm` : "—",
          materials: Array.isArray(mats) ? mats.slice(0, 3).map(m => m.material ?? "").filter(Boolean).join(", ") : "—",
        }
      })
    }
  } catch {
    // Non-fatal — technique enrichments may not exist
  }

  return { standards, materials, processes, hardwareCount: hardwareCount ?? 0, supplierInsights }
}

/**
 * Verify a single standard (admin action — uses service role to bypass RLS).
 */
export async function verifyStandard(id: string): Promise<{ success: boolean; error?: string }> {
  const { createAdminClient } = await import("@/lib/supabase/admin")
  const supabase = createAdminClient()
  const { error } = await supabase
    .from("design_standards")
    .update({ verified: true, updated_at: new Date().toISOString() })
    .eq("id", id)
  if (error) return { success: false, error: error.message }
  return { success: true }
}

/**
 * Bulk verify multiple standards.
 */
export async function bulkVerifyStandards(ids: string[]): Promise<{ success: boolean; count: number; error?: string }> {
  if (ids.length === 0) return { success: true, count: 0 }
  const { createAdminClient } = await import("@/lib/supabase/admin")
  const supabase = createAdminClient()
  const { error, count } = await supabase
    .from("design_standards")
    .update({ verified: true, updated_at: new Date().toISOString() })
    .in("id", ids)
  if (error) return { success: false, count: 0, error: error.message }
  return { success: true, count: count ?? ids.length }
}

/**
 * Get full standard detail including requirements markdown.
 */
export async function getStandardDetail(id: string): Promise<{
  data: { standard_code: string; standard_name: string; issuing_body: string; summary: string; requirements_markdown: string; design_rules: unknown; verified: boolean; source: string; industry_domain: string } | null
  error: string | null
}> {
  const supabase = await createClient()
  const { data, error } = await supabase
    .from("design_standards")
    .select("standard_code, standard_name, issuing_body, summary, requirements_markdown, design_rules, verified, source, industry_domain")
    .eq("id", id)
    .single()
  if (error) return { data: null, error: error.message }
  return { data: data as typeof data, error: null }
}
