'use server'

/**
 * @file intelligence.ts
 *
 * @description Server actions for fetching and managing intelligence reports.
 * These reports are generated by specialist sweeps that analyze the company's
 * external landscape (market trends, risks, compliance, etc.).
 *
 * @security All actions verify user authentication and foundry membership.
 * @audit Report reads and sweep triggers are logged via Supabase RLS.
 *
 * @related
 * - Sweep orchestrator: src/lib/agents/intelligence-sweep-orchestrator.ts
 * - Intelligence sources: src/lib/agents/external-intelligence.ts
 * - Dashboard UI: src/components/specialists/intelligence-feed.tsx
 */

import { createClient } from '@/lib/supabase/server'

// ─── Types ──────────────────────────────────────────────────────────

export interface IntelligenceReportView {
    id: string
    sourceId: string
    specialistId: string
    title: string
    summary: string
    implications: string[]
    recommendedActions: string[]
    urgency: 'immediate' | 'this_week' | 'monitor'
    isRead: boolean
    createdAt: string
}

// ─── Server Actions ─────────────────────────────────────────────────

/**
 * Fetches intelligence reports for the user's foundry.
 *
 * @description Queries the intelligence_reports table with optional urgency
 * filtering. Returns reports ordered by creation date (newest first).
 *
 * @param limit - Maximum number of reports to return (default: 20)
 * @param urgencyFilter - Optional urgency level filter
 * @returns Array of intelligence reports mapped to the view type
 *
 * @security Requires authenticated user with foundry membership
 */
export async function getIntelligenceReports(
    limit: number = 20,
    urgencyFilter?: 'immediate' | 'this_week' | 'monitor',
): Promise<IntelligenceReportView[]> {
    const supabase = await createClient()

    // AUTH: Verify user is authenticated
    const { data: { user } } = await supabase.auth.getUser()
    if (!user) return []

    // AUTH: Get user's foundry membership
    const { data: membership } = await supabase
        .from('foundry_memberships')
        .select('foundry_id')
        .eq('user_id', user.id)
        .limit(1)
        .single()

    if (!membership) return []

    let query = supabase
        .from('intelligence_reports')
        .select('*')
        .eq('foundry_id', membership.foundry_id)
        .order('created_at', { ascending: false })
        .limit(limit)

    if (urgencyFilter) {
        query = query.eq('urgency', urgencyFilter)
    }

    const { data, error } = await query

    if (error) {
        console.error('[IntelligenceActions] Failed to fetch reports:', {
            error: error.message,
            code: error.code,
            foundryId: membership.foundry_id,
        })
        return []
    }

    return (data ?? []).map(row => ({
        id: row.id,
        sourceId: row.source_id,
        specialistId: row.specialist_id,
        title: row.title,
        summary: row.summary,
        implications: (row.implications ?? []) as string[],
        recommendedActions: (row.recommended_actions ?? []) as string[],
        urgency: row.urgency as 'immediate' | 'this_week' | 'monitor',
        isRead: row.is_read ?? false,
        createdAt: row.created_at,
    }))
}

/**
 * Marks an intelligence report as read.
 *
 * @description Updates the is_read flag on a single report.
 *
 * @param reportId - The report ID to mark as read
 *
 * @security Requires authenticated user. RLS enforces foundry isolation.
 */
export async function markReportRead(reportId: string): Promise<void> {
    const supabase = await createClient()

    // AUTH: Verify user is authenticated
    const { data: { user } } = await supabase.auth.getUser()
    if (!user) return

    const { error } = await supabase
        .from('intelligence_reports')
        .update({ is_read: true })
        .eq('id', reportId)

    if (error) {
        console.error('[IntelligenceActions] Failed to mark report read:', {
            reportId,
            error: error.message,
        })
    }
}

/**
 * Triggers a manual intelligence sweep for the user's foundry.
 *
 * @description Invokes the sweep orchestrator to analyze external intelligence
 * sources and generate new reports. Can optionally target specific sources.
 *
 * @param sourceIds - Optional specific sources to sweep
 * @returns Success status and number of reports generated
 *
 * @security Requires authenticated user with foundry membership
 */
export async function triggerIntelligenceSweep(
    sourceIds?: string[],
): Promise<{ success: boolean; reportsGenerated: number }> {
    const supabase = await createClient()

    // AUTH: Verify user is authenticated
    const { data: { user } } = await supabase.auth.getUser()
    if (!user) return { success: false, reportsGenerated: 0 }

    // AUTH: Get user's foundry membership
    const { data: membership } = await supabase
        .from('foundry_memberships')
        .select('foundry_id')
        .eq('user_id', user.id)
        .limit(1)
        .single()

    if (!membership) return { success: false, reportsGenerated: 0 }

    try {
        const { runIntelligenceSweep } = await import(
            '@/lib/agents/intelligence-sweep-orchestrator'
        )
        const result = await runIntelligenceSweep({
            foundryId: membership.foundry_id,
            sourceIds,
            force: true,
        })

        return {
            success: true,
            reportsGenerated: result.reports.length,
        }
    } catch (err) {
        console.error('[IntelligenceActions] Sweep failed:', {
            error: err instanceof Error ? err.message : 'Unknown error',
            foundryId: membership.foundry_id,
        })
        return { success: false, reportsGenerated: 0 }
    }
}
