"""
ForgeOS — EV Component Physical Properties
============================================
Engineering data for all 23 EV/e-bike/e-scooter components.
"""

EV_PHYSICAL_PROPERTIES = {

    "hub_motor": {
        "mass": {"material": "aluminium_shell_copper_windings_neodymium_magnets", "density_kg_m3": None,
                 "typical_mass_g": {"250W_20inch": 2800, "500W_26inch": 3500, "1000W_26inch": 5500, "3000W_scooter": 8000}},
        "electrical": {
            "voltage_nom_v": {"36V": 36, "48V": 48, "72V": 72},
            "power_continuous_w": [250, 500, 750, 1000, 1500, 3000],
            "power_peak_w": {"250W": 500, "500W": 1000, "1000W": 2000, "3000W": 5000},
            "current_max_a": {"250W_36V": 15, "500W_48V": 20, "1000W_48V": 35, "3000W_72V": 60},
            "kv_rpm_per_v": {"250W": 7.5, "500W": 6.5, "1000W": 5.5},
            "efficiency_pct": [82, 88],
            "poles": [46, 50, 54],
            "hall_sensors": True,
        },
        "thermal": {"operating_temp_c": [-20, 60], "max_winding_temp_c": 155, "derating_above_c": 40},
        "mechanical": {
            "max_rpm": 600,
            "max_torque_nm": {"250W": 18, "500W": 35, "1000W": 60, "3000W": 120},
            "spoke_count": [32, 36],
            "axle_d_mm": [12, 14],
            "dropout_width_mm": {"front": 100, "rear_ebike": 135, "rear_fat": 170},
            "ip_rating": "IP54",
        },
        "interface": {"connector": "9_pin_waterproof_or_Anderson", "controller": "sinewave_FOC", "hall": "JST_5pin"},
        "procurement": {"typical_unit_cost_gbp": 60.00, "lead_time_days": 14, "common_suppliers": ["Bafang", "MXUS", "QS Motor", "AliExpress"]},
    },

    "mid_drive_motor": {
        "mass": {"material": "aluminium_die_cast_steel_gears_copper", "density_kg_m3": None,
                 "typical_mass_g": {"250W_Bafang_BBS01": 3200, "500W_BBS02": 3800, "750W_BBSHD": 4200, "1000W_M620": 4500}},
        "electrical": {
            "voltage_nom_v": {"36V": 36, "48V": 48, "52V": 52},
            "power_continuous_w": [250, 500, 750, 1000],
            "current_max_a": {"250W": 15, "500W": 25, "750W": 30, "1000W": 35},
            "efficiency_pct": [80, 85],
            "controller": "integrated_FOC",
            "cadence_sensor": True,
            "torque_sensor": {"BBS01": False, "M620": True},
        },
        "thermal": {"operating_temp_c": [-20, 45], "thermal_cutoff_c": 115},
        "mechanical": {
            "reduction_ratio": {"BBS01": 21.9, "BBSHD": 21.9, "M620": 24.3},
            "max_cadence_rpm": 120,
            "max_torque_nm": {"250W": 40, "500W": 80, "750W": 120, "1000W": 160},
            "bb_type": ["BSA_68mm", "BSA_73mm", "press_fit"],
            "chainring_teeth": [42, 44, 46, 48, 52],
        },
        "interface": {"display": "UART_protocol", "connector": "Higo_waterproof", "programming": "USB_UART"},
        "procurement": {"typical_unit_cost_gbp": 200.00, "lead_time_days": 7, "common_suppliers": ["Bafang", "Tongsheng", "Shimano", "Bosch"]},
    },

    "traction_motor": {
        "mass": {"material": "aluminium_housing_silicon_steel_laminations_NdFeB_copper", "density_kg_m3": None,
                 "typical_mass_g": None, "typical_mass_kg": {"20kW": 12, "50kW": 25, "100kW": 35, "200kW": 55}},
        "electrical": {
            "voltage_nom_v": {"LV": 48, "HV_car": 400, "HV_800V": 800},
            "power_continuous_kw": [20, 50, 100, 150, 200],
            "power_peak_kw": {"50kW": 80, "100kW": 160, "150kW": 240, "200kW": 350},
            "current_max_a_rms": {"50kW_400V": 200, "100kW_400V": 400, "200kW_800V": 350},
            "efficiency_peak_pct": 97,
            "efficiency_map_pct": [88, 97],
            "poles": [6, 8, 10],
            "type": "IPM_PMSM",
        },
        "thermal": {"operating_temp_c": [-40, 80], "max_winding_temp_c": 200, "coolant": "water_glycol",
                    "coolant_flow_lpm": [6, 12], "max_coolant_temp_c": 65},
        "mechanical": {
            "max_rpm": {"50kW": 10000, "100kW": 12000, "200kW": 16000},
            "max_torque_nm": {"50kW": 120, "100kW": 250, "200kW": 400},
            "shaft_type": "splined",
            "ip_rating": "IP67",
        },
        "interface": {"phase_connector": "HV_bus_bar_or_ring_terminal", "resolver": "sin_cos_analog", "coolant": "SAE_quick_disconnect"},
        "procurement": {"typical_unit_cost_gbp": 800.00, "lead_time_days": 30, "common_suppliers": ["QS Motor", "HPEVS", "NetGain", "Dana TM4"]},
    },

    "motor_controller_ev": {
        "mass": {"material": "aluminium_heatsink_IGBT_modules_PCB", "density_kg_m3": None,
                 "typical_mass_kg": {"small_48V_100A": 1.5, "car_400V_400A": 6, "car_800V_350A": 5}},
        "electrical": {
            "voltage_range_v": {"LV": [36, 72], "HV400": [250, 450], "HV800": [500, 850]},
            "phase_current_continuous_a_rms": [100, 200, 300, 400, 600],
            "phase_current_peak_a_rms": {"200A": 400, "400A": 800},
            "switching_freq_khz": [8, 10, 16, 20],
            "control_method": "FOC_sensorless_or_resolver",
            "efficiency_pct": [96, 99],
            "regen_braking": True,
            "12v_aux_output_a": 10,
        },
        "thermal": {"operating_temp_c": [-40, 70], "coolant": "water_glycol_or_air", "tdp_w": {"100A": 100, "400A": 400}},
        "mechanical": {"ip_rating": "IP67"},
        "interface": {"comms": ["CAN_2.0B", "CAN_FD"], "throttle_input": "0_5V_or_hall", "encoder": "resolver_sin_cos_or_ABZ"},
        "procurement": {"typical_unit_cost_gbp": 300.00, "lead_time_days": 14, "common_suppliers": ["Kelly Controller", "Sevcon/BorgWarner", "Cascadia Motion", "Rinehart"]},
    },

    "reduction_gearbox": {
        "mass": {"material": "aluminium_housing_hardened_steel_gears", "density_kg_m3": None,
                 "typical_mass_kg": {"single_speed_EV": 8, "2_speed_EV": 15}},
        "electrical": None,
        "thermal": {"operating_temp_c": [-30, 120], "oil_type": "ATF_or_synthetic_75W90", "oil_volume_l": {"small": 0.5, "car": 1.5}},
        "mechanical": {
            "ratio": {"single_speed_EV": [7, 12], "e_bike_internal": [1.5, 3]},
            "input_torque_max_nm": [250, 400],
            "input_rpm_max": 16000,
            "efficiency_pct": [97, 98.5],
            "gear_type": "helical",
            "noise_db_at_1m": 65,
            "lubrication": "splash_or_pump",
        },
        "interface": {"input_flange": "SAE_or_custom", "output": "splined_half_shaft"},
        "procurement": {"typical_unit_cost_gbp": 500.00, "lead_time_days": 30, "common_suppliers": ["Bosch", "BorgWarner", "GKN", "Custom"]},
    },

    "cv_joint": {
        "mass": {"material": "hardened_steel_chromoly_rubber_boot", "density_kg_m3": None,
                 "typical_mass_g": {"light_EV_go_kart": 800, "car": 2500}},
        "electrical": None,
        "thermal": {"operating_temp_c": [-40, 120], "grease": "moly_disulphide_CV_grease"},
        "mechanical": {
            "max_torque_nm": {"light": 200, "car": 3500},
            "max_angle_deg": {"plunge_inner": 25, "fixed_outer": 47},
            "max_rpm": 2500,
            "type": ["Rzeppa_fixed", "tripod_plunge"],
            "fatigue_life_km": 200000,
        },
        "interface": {"shaft_connection": "splined", "retention": "circlip"},
        "procurement": {"typical_unit_cost_gbp": 25.00, "lead_time_days": 7, "common_suppliers": ["GKN", "NTN", "SKF", "GSP"]},
    },

    "chain_sprocket": {
        "mass": {"material": "steel_C45_hardened_teeth_or_7075_aluminium", "density_kg_m3": None,
                 "typical_mass_g": {"14T_front_steel": 20, "44T_rear_steel": 180, "44T_rear_alu": 80}},
        "electrical": None,
        "thermal": {"operating_temp_c": [-30, 80]},
        "mechanical": {
            "chain_pitch_mm": {"bicycle_1_2": 12.7, "go_kart_428": 12.7, "motorcycle_520": 15.875, "motorcycle_530": 15.875},
            "max_rpm": 8000,
            "hardness_hrc": {"steel": 55, "aluminium": "N/A"},
            "life_km": {"steel": 30000, "aluminium": 10000},
        },
        "interface": {"mounting": "bolt_on_BCD_or_splined", "chain_type": "roller"},
        "procurement": {"typical_unit_cost_gbp": 8.00, "lead_time_days": 5, "common_suppliers": ["JT Sprockets", "Supersprox", "RK"]},
    },

    "battery_module_ev": {
        "mass": {"material": "prismatic_LFP_or_NMC_aluminium_busbars_steel_housing", "density_kg_m3": None,
                 "typical_mass_kg": {"8S_LFP_25Ah": 6.5, "8S_NMC_50Ah": 12, "16S_LFP_100Ah": 55}},
        "electrical": {
            "cell_chemistry": {"LFP": {"nom_v_per_cell": 3.2, "range_v": [2.5, 3.65]},
                              "NMC": {"nom_v_per_cell": 3.7, "range_v": [2.8, 4.2]}},
            "capacity_ah": [20, 50, 100, 200, 280],
            "energy_density_wh_kg": {"LFP": 160, "NMC": 250},
            "max_discharge_c": {"LFP": 3, "NMC": 2},
            "max_charge_c": {"LFP": 1, "NMC": 0.7},
            "internal_resistance_mohm_per_cell": {"LFP_100Ah": 0.3, "NMC_50Ah": 0.8},
            "cycle_life_80pct": {"LFP": 4000, "NMC": 1500},
        },
        "thermal": {"operating_temp_c": [-20, 55], "optimal_temp_c": [15, 35],
                    "cooling": "liquid_plate_or_air", "thermal_runaway_temp_c": {"LFP": 270, "NMC": 200}},
        "mechanical": {
            "cell_format": "prismatic_CATL_BYD_or_pouch",
            "compression_force_kn": [5, 15],
            "vibration_spec": "UN38.3_T3_SAE_J2380",
        },
        "interface": {"busbar": "nickel_plated_copper_M6_stud", "sense_wiring": "JST_or_Molex", "coolant": "quick_disconnect"},
        "procurement": {"typical_unit_cost_gbp": 250.00, "lead_time_days": 21, "common_suppliers": ["EVE", "CATL", "BYD", "Samsung SDI"]},
    },

    "bms_board": {
        "mass": {"material": "FR4_pcb_mosfet_balancers", "density_kg_m3": None,
                 "typical_mass_g": {"4S_20A": 15, "16S_100A": 80, "96S_250A": 300}},
        "electrical": {
            "cells_series": [4, 8, 12, 16, 24, 32, 48, 96],
            "continuous_current_a": [20, 60, 100, 150, 250],
            "balance_current_ma": {"passive": [50, 100], "active": [1000, 3000]},
            "balance_type": "passive_resistive_or_active_inductor",
            "cell_voltage_accuracy_mv": 5,
            "temperature_sensors": [2, 4, 8],
            "protection": ["OVP", "UVP", "OCP", "OTP", "SCP"],
            "soc_estimation": "coulomb_counting_EKF",
            "quiescent_current_ua": 50,
        },
        "thermal": {"operating_temp_c": [-30, 75]},
        "mechanical": {},
        "interface": {"comms": ["CAN", "UART", "Bluetooth", "RS485"], "software": "configurable_via_UART_or_CAN"},
        "procurement": {"typical_unit_cost_gbp": 30.00, "lead_time_days": 7, "common_suppliers": ["Daly", "JBD", "Orion BMS", "REC BMS", "Batrium"]},
    },

    "charging_port": {
        "mass": {"material": "PA66_GF30_copper_alloy_contacts", "density_kg_m3": None,
                 "typical_mass_g": {"Type_2_inlet": 400, "CCS2_inlet": 600, "J1772": 350}},
        "electrical": {
            "ac_voltage_max_v": {"Type_2": 480, "J1772": 240},
            "ac_current_max_a": {"Type_2": 63, "J1772": 80},
            "dc_voltage_max_v": {"CCS2": 1000, "CHAdeMO": 500},
            "dc_current_max_a": {"CCS2": 500, "CHAdeMO": 400},
            "power_max_kw": {"Type_2_AC": 43, "CCS2_DC": 350, "J1772_AC": 19.2},
            "pilot_signal": "IEC_61851_control_pilot_1kHz_PWM",
            "proximity_detection": True,
            "mating_cycles": 10000,
        },
        "thermal": {"operating_temp_c": [-30, 50]},
        "mechanical": {"ip_rating": "IP55_mated", "locking": "electromagnetic_or_mechanical"},
        "interface": {"standard": ["IEC_62196_Type_2", "SAE_J1772", "CCS_Combo2"], "comms": "PLC_ISO15118_for_V2G"},
        "procurement": {"typical_unit_cost_gbp": 40.00, "lead_time_days": 14, "common_suppliers": ["Phoenix Contact", "TE Connectivity", "ITT", "Amphenol"]},
    },

    "hv_contactor": {
        "mass": {"material": "epoxy_sealed_copper_contacts_steel_armature", "density_kg_m3": None,
                 "typical_mass_g": {"200A": 350, "500A": 600, "800A": 1000}},
        "electrical": {
            "contact_voltage_max_v": [450, 900, 1000],
            "continuous_current_a": [200, 350, 500, 800],
            "breaking_capacity_a": {"200A": 2000, "500A": 5000},
            "coil_voltage_v": [12, 24],
            "coil_power_w": [3, 8],
            "contact_resistance_mohm": 0.2,
            "arc_suppression": "magnetic_blowout_or_hydrogen_sealed",
            "lifecycle_operations": {"full_load": 100000, "no_load": 500000},
        },
        "thermal": {"operating_temp_c": [-40, 85]},
        "mechanical": {"vibration_resistance_g": 30, "shock_resistance_g": 50},
        "interface": {"control": "12V_coil_via_pre_charge_relay", "mounting": "M5_stud_or_bracket"},
        "procurement": {"typical_unit_cost_gbp": 30.00, "lead_time_days": 7, "common_suppliers": ["Gigavac", "TE Kilovac", "Panasonic", "Hongfa"]},
    },

    "wheel_hub": {
        "mass": {"material": "ductile_iron_GGG40_or_forged_steel", "density_kg_m3": 7200,
                 "typical_mass_g": {"go_kart_4x100": 1200, "car_4x100": 2500, "car_5x114.3": 3500}},
        "electrical": None,
        "thermal": {"operating_temp_c": [-40, 200]},
        "mechanical": {
            "pcd_mm": [100, 108, 110, 112, 114.3, 120, 130, 139.7],
            "studs": [4, 5, 6],
            "stud_size": ["M12x1.5", "M12x1.25", "M14x1.5"],
            "wheel_bearing": "double_row_angular_contact_or_tapered_roller",
            "bearing_load_kn": {"go_kart": 15, "car": 45},
            "runout_max_mm": 0.05,
            "abs_ring": "magnetic_encoder_integrated",
        },
        "interface": {"brake": "disc_or_drum", "drive": "splined_CV_or_stub_axle"},
        "procurement": {"typical_unit_cost_gbp": 25.00, "lead_time_days": 7, "common_suppliers": ["SKF", "NTN", "Timken", "FAG"]},
    },

    "brake_disc": {
        "mass": {"material": "grey_cast_iron_GG25_or_carbon_ceramic", "density_kg_m3": 7200,
                 "typical_mass_g": {"240mm_solid_go_kart": 1500, "280mm_vented_car": 5500, "330mm_vented_performance": 8000}},
        "electrical": None,
        "thermal": {"operating_temp_c": [-40, 700], "max_continuous_temp_c": 500,
                    "thermal_capacity_kj_kg_k": 0.46, "conductivity_w_mk": 48},
        "mechanical": {
            "friction_coefficient": [0.35, 0.45],
            "min_thickness_mm": {"280mm_vented": 22, "280mm_worn_limit": 20},
            "runout_max_mm": 0.05,
            "hardness_hb": [180, 230],
            "dv_standard": "ECE_R90",
        },
        "interface": {"hub_connection": "bolt_on_or_floating", "bolt_count": [4, 5, 6]},
        "procurement": {"typical_unit_cost_gbp": 20.00, "lead_time_days": 5, "common_suppliers": ["Brembo", "EBC", "TRW", "Apec"]},
    },

    "brake_caliper": {
        "mass": {"material": "aluminium_6061_T6_anodised", "density_kg_m3": 2700,
                 "typical_mass_g": {"single_piston_bicycle": 120, "2_piston_go_kart": 800, "4_piston_car": 3500}},
        "electrical": None,
        "thermal": {"operating_temp_c": [-40, 300], "max_fluid_temp_c": {"DOT4": 230, "DOT5.1": 260}},
        "mechanical": {
            "piston_d_mm": {"bicycle": [22, 25], "go_kart": [30, 34], "car": [36, 40, 44, 48]},
            "clamping_force_kn": {"2_piston_30mm": 8, "4_piston_40mm": 24},
            "pad_area_cm2": {"go_kart": 12, "car": 40},
            "seal_type": "EPDM_square_section",
            "bleed_type": "DOT4_fluid_or_mineral_oil",
        },
        "interface": {"mount": "radial_or_axial_bolt_on", "brake_line": "M10x1_banjo_or_AN3"},
        "procurement": {"typical_unit_cost_gbp": 30.00, "lead_time_days": 5, "common_suppliers": ["Brembo", "Wilwood", "AP Racing", "Shimano"]},
    },

    "coilover_shock": {
        "mass": {"material": "aluminium_body_steel_shaft_spring", "density_kg_m3": None,
                 "typical_mass_g": {"go_kart": 800, "car_sport": 2500, "car_race": 2000}},
        "electrical": None,
        "thermal": {"operating_temp_c": [-30, 80], "damper_fluid": "shock_oil_5_15wt"},
        "mechanical": {
            "stroke_mm": {"go_kart": [50, 80], "car": [80, 120]},
            "spring_rate_n_mm": {"go_kart": [15, 40], "car_front": [30, 80], "car_rear": [40, 100]},
            "damping_force_n_at_0.3ms": {"compression": [300, 2000], "rebound": [600, 4000]},
            "adjustment": ["ride_height", "compression_damping", "rebound_damping", "preload"],
            "reservoir": ["monotube", "twin_tube", "piggyback"],
        },
        "interface": {"mount_top": "eye_or_spherical_bearing", "mount_bottom": "eye_or_clevis",
                     "spring_id_mm": [60, 62, 65]},
        "procurement": {"typical_unit_cost_gbp": 80.00, "lead_time_days": 7, "common_suppliers": ["Bilstein", "Ohlins", "KW", "BC Racing", "MeisterR"]},
    },

    "wishbone": {
        "mass": {"material": "CDS_steel_tube_or_forged_aluminium_6082", "density_kg_m3": None,
                 "typical_mass_g": {"go_kart_steel": 1200, "car_steel": 4000, "car_alu_forged": 2500}},
        "electrical": None,
        "thermal": {"operating_temp_c": [-40, 120]},
        "mechanical": {
            "yield_strength_mpa": {"CDS_tube": 350, "6082_T6_forged": 310},
            "max_vertical_load_kn": {"go_kart": 5, "car": 15},
            "max_lateral_load_kn": {"go_kart": 3, "car": 10},
            "bushing_type": ["rubber", "polyurethane", "spherical_bearing_uniball"],
            "ball_joint_type": "press_in_or_bolt_on",
        },
        "interface": {"chassis_mount": "M10_or_M12_bolt_through_bushing", "upright_mount": "ball_joint_taper"},
        "procurement": {"typical_unit_cost_gbp": 40.00, "lead_time_days": 14, "common_suppliers": ["Custom fabrication", "Flaming River", "CBS Engineering"]},
    },

    "tie_rod_end": {
        "mass": {"material": "forged_steel_chrome_plated", "density_kg_m3": 7850,
                 "typical_mass_g": {"M10_go_kart": 150, "M14_car": 400}},
        "electrical": None,
        "thermal": {"operating_temp_c": [-40, 120]},
        "mechanical": {
            "axial_load_kn": {"M10": 8, "M12": 12, "M14": 18},
            "articulation_angle_deg": [15, 25],
            "taper_ratio": "1:10_SAE",
            "thread": ["M10x1.5", "M12x1.25", "M14x1.5"],
            "boot": "polyurethane_dust_boot",
        },
        "interface": {"thread": "metric_right_hand_left_hand_pair", "taper": "1_in_10"},
        "procurement": {"typical_unit_cost_gbp": 8.00, "lead_time_days": 5, "common_suppliers": ["Lemforder", "Meyle", "TRW", "Moog"]},
    },

    "steering_rack": {
        "mass": {"material": "aluminium_housing_hardened_steel_rack_pinion", "density_kg_m3": None,
                 "typical_mass_kg": {"manual_go_kart": 2, "power_assist_car": 8, "EPAS_car": 10}},
        "electrical": {
            "epas_motor_voltage_v": [12, 48],
            "epas_power_max_w": [500, 1000],
            "epas_current_max_a": 80,
        },
        "thermal": {"operating_temp_c": [-40, 120]},
        "mechanical": {
            "rack_travel_mm": {"go_kart": [150, 200], "car": [140, 160]},
            "ratio_turns_lock_to_lock": {"manual": [2.5, 3.5], "power": [2.5, 4.0]},
            "max_input_torque_nm": 6,
            "rack_force_max_kn": {"manual": 5, "power_assist": 12},
            "tie_rod_thread": "M12_or_M14",
        },
        "interface": {"input": "splined_steering_column_with_UJ", "output": "M12_tie_rod_thread"},
        "procurement": {"typical_unit_cost_gbp": 80.00, "lead_time_days": 14, "common_suppliers": ["ZF", "JTEKT", "NSK", "Custom"]},
    },

    "wheel_rim": {
        "mass": {"material": "aluminium_A356_T6_gravity_or_low_pressure_cast", "density_kg_m3": 2680,
                 "typical_mass_g": None, "typical_mass_kg": {"13x5.5_go_kart": 3.5, "14x6_car": 6.5, "17x7.5_car": 9.0, "18x8_performance": 9.5}},
        "electrical": None,
        "thermal": {"operating_temp_c": [-40, 120]},
        "mechanical": {
            "load_rating_kg": {"13_inch": 500, "17_inch": 750, "18_inch": 800},
            "offset_et_mm": [30, 35, 40, 45],
            "centre_bore_mm": [54.1, 56.1, 57.1, 60.1, 63.4, 66.6, 72.6],
            "jj_flange_profile": True,
            "impact_test": "SAE_J175",
            "fatigue_test_cycles": 500000,
        },
        "interface": {"tyre_bead": "tubeless_drop_centre", "valve": "TR413_rubber_or_TPMS"},
        "procurement": {"typical_unit_cost_gbp": 50.00, "lead_time_days": 7, "common_suppliers": ["Team Dynamics", "OZ Racing", "Rota", "Braid"]},
    },

    "throttle_sensor": {
        "mass": {"material": "PA66_body_neodymium_magnet_hall_IC", "density_kg_m3": None,
                 "typical_mass_g": {"twist_grip": 80, "thumb_lever": 30, "pedal_car": 200}},
        "electrical": {
            "voltage_v": 5.0,
            "voltage_range_v": [3.3, 12],
            "output_signal": "0_5V_analog_or_0_4.2V",
            "current_ma": 15,
            "redundancy": {"car": "dual_track_opposing", "bike": "single"},
            "linearity_pct": 1,
        },
        "thermal": {"operating_temp_c": [-30, 80]},
        "mechanical": {
            "rotation_deg": {"twist": 90, "thumb": 30, "pedal": 25},
            "return_spring": True,
            "ip_rating": "IP65",
            "lifecycle_operations": 1000000,
        },
        "interface": {"connector": "3_pin_JST_or_waterproof", "protocol": "analog_voltage"},
        "procurement": {"typical_unit_cost_gbp": 8.00, "lead_time_days": 5, "common_suppliers": ["Magura", "Wuxing", "CTS", "Bosch"]},
    },

    "speed_sensor_wheel": {
        "mass": {"material": "PA66_body_hall_effect_IC", "density_kg_m3": None, "typical_mass_g": 25},
        "electrical": {
            "voltage_v": 5.0,
            "voltage_range_v": [4.5, 24],
            "output": "digital_pulse_or_analog_sin_cos",
            "current_ma": 10,
            "frequency_max_hz": 10000,
            "air_gap_mm": [0.5, 1.5],
        },
        "thermal": {"operating_temp_c": [-40, 150]},
        "mechanical": {
            "sensing_element": "hall_effect_or_magnetoresistive",
            "target": "toothed_ring_or_magnetic_encoder",
            "teeth_count": [48, 96],
            "ip_rating": "IP69K",
        },
        "interface": {"connector": "2_pin_or_3_pin_weatherproof", "mounting": "M5_bolt_or_press_in"},
        "procurement": {"typical_unit_cost_gbp": 5.00, "lead_time_days": 5, "common_suppliers": ["Bosch", "Continental", "Allegro", "TDK"]},
    },

    "wiring_connector_deutsch": {
        "mass": {"material": "glass_filled_nylon_nickel_plated_copper_contacts", "density_kg_m3": None,
                 "typical_mass_g": {"DT_2pin": 8, "DT_4pin": 12, "DT_6pin": 15, "DT_12pin": 25}},
        "electrical": {
            "voltage_max_v": 250,
            "current_max_a": {"size_16_contact": 13, "size_12_contact": 25},
            "contact_resistance_mohm": 1.5,
            "wire_range_awg": {"size_16": [16, 20], "size_12": [12, 16]},
            "mating_cycles": 100,
            "ip_rating_mated": "IP69K",
        },
        "thermal": {"operating_temp_c": [-55, 125]},
        "mechanical": {
            "vibration_resistance": "MIL_STD_202",
            "sealing": "silicone_interfacial_seal",
            "locking": "positive_lock_with_secondary",
        },
        "interface": {"series": ["DT", "DTM", "DTP"], "crimp_tool": "Deutsch_HDT_48_00"},
        "procurement": {"typical_unit_cost_gbp": 2.00, "lead_time_days": 5, "common_suppliers": ["Deutsch/TE", "RS", "Hella"]},
    },

    "fuse_box": {
        "mass": {"material": "PA66_V0_copper_bus_bars", "density_kg_m3": None,
                 "typical_mass_g": {"8_way_blade": 120, "12_way_blade": 180, "EV_HV_fuse_box": 500}},
        "electrical": {
            "fuse_type": ["ATO_blade", "MIDI", "MEGA", "bolt_down"],
            "voltage_max_v": {"LV_blade": 32, "MIDI": 58, "MEGA": 58, "HV_bolt": 500},
            "current_ratings_a": {"blade": [5, 7.5, 10, 15, 20, 25, 30], "MIDI": [40, 50, 60, 70, 80, 100], "MEGA": [100, 125, 150, 175, 200, 225, 250]},
            "bus_bar_current_max_a": 200,
        },
        "thermal": {"operating_temp_c": [-40, 85]},
        "mechanical": {"ip_rating": "IP54_with_lid"},
        "interface": {"input": "M6_or_M8_stud", "output": "blade_or_bolt_down"},
        "procurement": {"typical_unit_cost_gbp": 8.00, "lead_time_days": 5, "common_suppliers": ["Bussman/Eaton", "Littelfuse", "MTA", "BlueSea"]},
    },
}
