"""
ForgeOS — Factory Logistics Physical Properties
=================================================
"""

LOGISTICS_PHYSICAL_PROPERTIES = {

    "belt_conveyor": {
        "mass": {"material": "mild_steel_frame_PVC_or_PU_belt",
                 "typical_mass_kg_per_m": {"400mm": 25, "600mm": 35, "800mm": 45, "1200mm": 65}},
        "electrical": {"voltage_v": [240, 415], "motor_kw": [0.37, 0.55, 0.75, 1.1, 1.5, 2.2],
                       "gearbox": "shaft_mounted_or_drum_motor", "vfd": "recommended"},
        "thermal": {"belt_max_temp_c": {"PVC": 80, "PU": 90, "silicone": 200}, "food_grade": "PU_FDA_EU_10_2011"},
        "mechanical": {"speed_m_min": [5, 10, 20, 30, 60], "load_kg_m": {"light": 25, "medium": 50, "heavy": 100},
                       "belt_type": ["PVC_2ply", "PU_2ply", "modular_plastic"], "incline_max_deg": {"flat": 0, "cleated": 30}},
        "interface": {"drive": "head_drum_or_centre", "supports": "floor_or_ceiling_hung"},
        "procurement": {"typical_unit_cost_gbp_per_m": {"light": 400, "medium": 600, "heavy": 900}, "lead_time_days": 21,
                        "common_suppliers": ["Interroll", "Hytrol", "L.A.C. Conveyors", "Conveyor Units", "Transnorm"]},
    },

    "roller_conveyor": {
        "mass": {"material": "mild_steel_frame_galvanised_rollers",
                 "typical_mass_kg_per_m": {"gravity_500mm": 15, "powered_500mm": 25, "powered_600mm": 35}},
        "electrical": {"voltage_v": 24, "motor_per_zone_w": [10, 20, 40],
                       "control": "24V_MDR_zero_pressure_accumulation"},
        "thermal": {"operating_temp_c": [-10, 50]},
        "mechanical": {"roller_d_mm": [50, 60, 80], "pitch_mm": [75, 100, 125], "load_per_roller_kg": {"50mm": 30, "80mm": 100},
                       "speed_m_min": [5, 15, 30, 45], "accumulation": "zero_pressure_MDR"},
        "interface": {"drive": "MDR_24V_or_lineshaft", "merge_divert": "blade_or_pop_up"},
        "procurement": {"typical_unit_cost_gbp_per_m": {"gravity": 150, "MDR": 400}, "lead_time_days": 14,
                        "common_suppliers": ["Interroll", "Itoh Denki", "L.A.C.", "Dematic"]},
    },

    "spiral_conveyor": {
        "mass": {"material": "steel_frame_plastic_slat_belt", "typical_mass_kg": {"1500mm_OD_3m": 500}},
        "electrical": {"voltage_v": 415, "motor_kw": [1.5, 2.2, 3.0], "vfd": True},
        "thermal": {"operating_temp_c": [-25, 60], "food_grade_option": True},
        "mechanical": {"elevation_m": [1.5, 3, 5, 8, 12], "throughput_uph": [1000, 2000, 3000],
                       "belt": "modular_plastic_slat", "max_product_kg": [30, 50]},
        "interface": {"infeed_outfeed": "tangential"},
        "procurement": {"typical_unit_cost_gbp": 15000, "lead_time_days": 42,
                        "common_suppliers": ["Ambaflex", "Ryson", "Apollo VTS", "Transnorm"]},
    },

    "ball_transfer_table": {
        "mass": {"material": "steel_frame_steel_ball_units", "typical_mass_kg": {"600x600": 25, "900x900": 45}},
        "electrical": None,
        "thermal": {"operating_temp_c": [0, 50]},
        "mechanical": {"ball_d_mm": [25, 30, 38], "load_per_unit_kg": [15, 30, 70], "table_load_kg": [200, 500, 1000]},
        "interface": {"mounting": "adjustable_legs", "inline_or_90deg": True},
        "procurement": {"typical_unit_cost_gbp": 300, "lead_time_days": 7,
                        "common_suppliers": ["Alwayse", "ISB", "Conveyor Units"]},
    },

    "amr_platform": {
        "mass": {"material": "steel_chassis_HDPE_covers",
                 "typical_mass_kg": {"300kg": 80, "600kg": 130, "1500kg": 250}},
        "electrical": {"battery": {"type": "LFP", "voltage_v": 48, "capacity_kwh": [1.5, 3, 5],
                                   "charge_time_h": [1, 2], "auto_charge": True},
                       "drive_motor_w": [200, 400]},
        "thermal": {"operating_temp_c": [0, 40]},
        "mechanical": {"payload_kg": [100, 300, 600, 1000, 1500], "speed_m_s": [1.0, 1.5, 2.0],
                       "navigation": ["SLAM_LiDAR", "QR_code", "natural_feature"],
                       "safety": ["LiDAR_360", "3D_camera", "bumper", "e_stop"], "runtime_h": [8, 12, 16]},
        "interface": {"fleet": "VDA_5050_or_proprietary", "WMS": "REST_API_MQTT", "charging": "auto_dock"},
        "procurement": {"typical_unit_cost_gbp": {"300kg": 25000, "600kg": 40000, "1500kg": 65000}, "lead_time_days": 56,
                        "common_suppliers": ["Locus Robotics", "6 River Systems", "MiR", "OTTO Motors", "Geek+"]},
    },

    "pallet_agv": {
        "mass": {"material": "steel_chassis", "typical_mass_kg": {"1t": 500, "2t": 800}},
        "electrical": {"battery": {"type": "LFP", "voltage_v": 48, "capacity_kwh": [8, 15, 25]}, "drive_kw": [3, 5, 8]},
        "thermal": {"operating_temp_c": [-10, 45]},
        "mechanical": {"payload_kg": [1000, 1500, 2000, 3000], "lift_height_mm": [200, 1500, 3000, 6000],
                       "speed_m_s": [1.0, 1.5], "navigation": ["SLAM_LiDAR", "reflector"]},
        "interface": {"fleet": "VDA_5050", "WMS": "REST_API"},
        "procurement": {"typical_unit_cost_gbp": 60000, "lead_time_days": 84,
                        "common_suppliers": ["Jungheinrich", "KUKA", "Dematic", "Toyota AGV", "Vecna"]},
    },

    "sorting_robot": {
        "mass": {"material": "aluminium_frame_tilt_tray", "typical_mass_kg_per_cell": 15},
        "electrical": {"voltage_v": 24, "power_per_cell_w": 50, "induction": "linear_motor"},
        "thermal": {"operating_temp_c": [5, 40]},
        "mechanical": {"tray_capacity_kg": [5, 15, 30], "sort_rate_items_hr": [5000, 10000, 15000],
                       "speed_m_s": [1.5, 2.5], "chute_count": [50, 100, 200, 500]},
        "interface": {"scanner": "overhead_6_side", "WCS": "sort_plan_PLC"},
        "procurement": {"typical_system_cost_gbp": 500000, "lead_time_days": 180,
                        "common_suppliers": ["Beumer", "Vanderlande", "Dematic", "Interroll"]},
    },

    "miniload_crane": {
        "mass": {"material": "steel_mast_aluminium_carriage", "typical_mass_kg": 800},
        "electrical": {"voltage_v": 415, "drive_kw": {"hoist": 5, "travel": 8}, "busbar": "conductor_rail"},
        "thermal": {"operating_temp_c": [0, 40]},
        "mechanical": {"payload_kg": [50, 100, 150], "height_m": [6, 8, 10, 12, 15],
                       "travel_speed_m_s": [4, 6], "lift_speed_m_s": [2, 3],
                       "throughput_totes_hr": [120, 200, 300]},
        "interface": {"WMS": "task_queue", "conveyor": "P_and_D_station"},
        "procurement": {"typical_unit_cost_gbp": 120000, "lead_time_days": 180,
                        "common_suppliers": ["Dematic", "SSI Schaefer", "Swisslog", "TGW", "Knapp"]},
    },

    "vlm_unit": {
        "mass": {"material": "steel_frame_steel_trays", "typical_mass_kg": {"6m": 3000, "10m": 5000}},
        "electrical": {"voltage_v": 240, "motor_kw": [2.2, 4], "connection": "13A_or_32A"},
        "thermal": {"operating_temp_c": [5, 40], "cold_store_option": "-25C"},
        "mechanical": {"tray_payload_kg": [250, 500, 1000], "height_m": [3, 6, 8, 10, 12, 16],
                       "tray_width_mm": [1250, 2500, 4100], "throughput_trays_hr": [50, 80, 120]},
        "interface": {"WMS": "Ethernet_TCP_IP", "pick_to_light": "integrated"},
        "procurement": {"typical_unit_cost_gbp": {"6m": 25000, "10m": 40000}, "lead_time_days": 56,
                        "common_suppliers": ["Kardex", "Hanel", "Modula", "SSI Schaefer Logimat"]},
    },

    "shuttle_car": {
        "mass": {"material": "steel_chassis_lithium_battery", "typical_mass_kg": 120},
        "electrical": {"battery": {"type": "LFP_or_supercapacitor", "voltage_v": 48, "charge": "in_aisle_contact"}, "drive_w": 400},
        "thermal": {"operating_temp_c": [-25, 40], "cold_store": True},
        "mechanical": {"payload_kg": [1000, 1500], "speed_m_s": [1.5, 4.0],
                       "depth_positions": [2, 4, 6, 10, 20], "cycle_time_s_per_pos": 4},
        "interface": {"crane": "transferred_by_SRM_or_lift", "comms": "WiFi_or_IR"},
        "procurement": {"typical_unit_cost_gbp": 15000, "lead_time_days": 90,
                        "common_suppliers": ["Dematic", "SSI Schaefer", "Swisslog", "Mecalux"]},
    },

    "cube_storage_robot": {
        "mass": {"material": "aluminium_frame_LFP_battery", "typical_mass_kg": 35},
        "electrical": {"battery": {"type": "LFP", "voltage_v": 48, "runtime_h": 16, "charge_min": 6}, "drive_w": 200},
        "thermal": {"operating_temp_c": [2, 35]},
        "mechanical": {"bin_payload_kg": 30, "speed_m_s": 3.1, "grid_cell_mm": 650, "bin_depth_max": 24},
        "interface": {"grid": "aluminium_rail_bolted", "port": "workstation_conveyor", "fleet": "proprietary_controller"},
        "procurement": {"typical_unit_cost_gbp": 10000, "lead_time_days": 120,
                        "common_suppliers": ["AutoStore", "Ocado Technology"]},
    },

    "scissor_lift_table": {
        "mass": {"material": "mild_steel_hydraulic", "typical_mass_kg": {"1t": 350, "2t": 600}},
        "electrical": {"voltage_v": [240, 415], "motor_kw": [1.1, 2.2, 3.0], "hydraulic": "integral_power_pack"},
        "thermal": {"operating_temp_c": [0, 40]},
        "mechanical": {"capacity_kg": [500, 1000, 2000, 4000], "travel_mm": [500, 750, 1000, 1500, 2000],
                       "collapsed_h_mm": [200, 250, 300], "lift_time_s": [15, 25, 40]},
        "interface": {"control": "push_button_or_foot_pedal", "safety": "toe_guard_belly_bar_overload",
                      "install": "pit_or_floor_level"},
        "procurement": {"typical_unit_cost_gbp": {"1t": 2000, "2t": 3500}, "lead_time_days": 21,
                        "common_suppliers": ["Edmolift", "Southworth", "Bolzoni", "Sax Lift"]},
    },

    "goods_lift": {
        "mass": {"material": "steel_structure_hydraulic_or_chain", "typical_mass_kg": 800},
        "electrical": {"voltage_v": 415, "motor_kw": [3, 5.5, 7.5], "control": "PLC_with_interlocks"},
        "thermal": {"operating_temp_c": [0, 40]},
        "mechanical": {"capacity_kg": [500, 1000, 2000, 5000], "travel_m": [2, 3, 5, 8, 12],
                       "speed_m_s": [0.15, 0.3], "drive": ["hydraulic", "chain", "screw"],
                       "regulation": "LOLER_PUWER_Machinery_Directive"},
        "interface": {"gates": "powered_roller_shutter_or_bi_parting", "interlocks": "gate_before_travel"},
        "procurement": {"typical_unit_cost_gbp": {"2m_1t": 8000, "5m_2t": 15000}, "lead_time_days": 42,
                        "common_suppliers": ["Safetech", "Transdek", "PFlow", "Merrit"]},
    },

    "crossbelt_sorter_cell": {
        "mass": {"material": "aluminium_carriage_PU_belt", "typical_mass_kg_per_cell": 12},
        "electrical": {"voltage_v": 24, "motor_per_cell_w": 50, "induction": "linear_motor_contactless"},
        "thermal": {"operating_temp_c": [5, 40]},
        "mechanical": {"cell_length_mm": [400, 500, 600], "max_item_kg": [30, 50],
                       "discharge_speed_m_s": 2.5, "sort_rate_hr": 15000, "accuracy_pct": 99.99},
        "interface": {"track": "oval_loop_steel_rail", "scanner": "overhead_infeed"},
        "procurement": {"typical_system_cost_gbp": 800000, "lead_time_days": 270,
                        "common_suppliers": ["Beumer", "Vanderlande", "Interroll", "Honeywell Intelligrated"]},
    },

    "pop_up_wheel_diverter": {
        "mass": {"material": "steel_frame_PU_wheels", "typical_mass_kg": 25},
        "electrical": {"voltage_v": 24, "actuator": "pneumatic_or_electric", "cycle_time_ms": [300, 500]},
        "thermal": {"operating_temp_c": [0, 45]},
        "mechanical": {"divert_angle_deg": [30, 45, 90], "max_item_kg": 50, "rate_items_min": [30, 60]},
        "interface": {"conveyor": "between_existing_rollers", "control": "PLC_photo_eye"},
        "procurement": {"typical_unit_cost_gbp": 1500, "lead_time_days": 14,
                        "common_suppliers": ["Hytrol", "Interroll", "Itoh Denki"]},
    },

    "pick_to_light_module": {
        "mass": {"material": "ABS_housing_LED", "typical_mass_g": 120},
        "electrical": {"voltage_v": 24, "power_w": 1, "comms": "RS485_CAN_or_wireless",
                       "LED_colours": ["green", "red", "blue", "amber"]},
        "thermal": {"operating_temp_c": [0, 45]},
        "mechanical": {"display": "3_digit_7seg_or_OLED", "button": "capacitive_or_mechanical"},
        "interface": {"WMS": "pick_list_via_controller", "mounting": "rail_clip_or_adhesive"},
        "procurement": {"typical_unit_cost_gbp": 40, "lead_time_days": 14,
                        "common_suppliers": ["Lightning Pick", "Bastian", "SSI Schaefer"]},
    },

    "packing_bench": {
        "mass": {"material": "steel_frame_MDF_or_ESD_top",
                 "typical_mass_kg": {"1500mm": 50, "1800mm": 65, "2100mm": 80}},
        "electrical": {"voltage_v": 240, "sockets": 4, "USB": True, "scale_w": 10},
        "thermal": {"operating_temp_c": [5, 40], "ESD_option": True},
        "mechanical": {"load_kg": 300, "height_adj_mm": [700, 1000],
                       "accessories": ["tape_dispenser", "label_printer_shelf", "scale", "monitor_arm", "bin_rail"]},
        "interface": {"WMS": "screen_pick_confirm", "printer": "Zebra_thermal"},
        "procurement": {"typical_unit_cost_gbp": 600, "lead_time_days": 14,
                        "common_suppliers": ["Spaceguard", "Stormax", "Lista", "Treston"]},
    },

    "stretch_wrapper": {
        "mass": {"material": "steel_turntable_and_mast",
                 "typical_mass_kg": {"turntable": 450, "rotary_arm": 600}},
        "electrical": {"voltage_v": 415, "motor_kw": {"turntable": 0.75, "carriage": 0.37}, "connection": "hardwired_32A"},
        "thermal": {"operating_temp_c": [0, 40]},
        "mechanical": {"turntable_d_mm": [1500, 1650, 1800], "max_load_kg": [1500, 2000, 2500],
                       "max_pallet_h_mm": [2200, 2500], "cycle_time_s": [90, 120, 180],
                       "film_type": "LLDPE_20_23_micron_machine_stretch"},
        "interface": {"conveyor": "inline_or_standalone", "control": "PLC_pre_set_programs"},
        "procurement": {"typical_unit_cost_gbp": {"turntable": 4000, "rotary_arm": 8000}, "lead_time_days": 21,
                        "common_suppliers": ["Robopac", "Lantech", "Aetna Group", "Wulftec"]},
    },

    "pallet_rack_upright": {
        "mass": {"material": "cold_rolled_galvanised_steel_2_2.5mm", "density_kg_m3": 7850,
                 "mass_per_m_kg": {"90mm_post": 4.5, "100mm_post": 5.5}},
        "electrical": None,
        "thermal": {"operating_temp_c": [-25, 50]},
        "mechanical": {
            "height_mm": [3000, 4500, 6000, 8000, 10000, 12000],
            "depth_mm": [800, 900, 1100],
            "frame_load_kn": {"90mm_6m": 120, "100mm_10m": 180},
            "design_per": "BS_EN_15512_SEMA_codes",
            "seismic": "BS_EN_16681_where_required",
        },
        "interface": {"beam_connection": "boltless_hook_in_teardrop_or_keyhole", "floor_fix": "M12_expansion_anchor",
                      "back_to_back_spacer": "required_if_double_entry"},
        "procurement": {"typical_unit_cost_gbp": {"3m": 30, "6m": 55, "10m": 90}, "lead_time_days": 14,
                        "common_suppliers": ["Dexion", "Link51", "Mecalux", "SSI Schaefer", "AR Racking"]},
    },

    "pallet_rack_beam": {
        "mass": {"material": "cold_rolled_steel_1.5_2.0mm_powder_coated", "density_kg_m3": 7850,
                 "mass_per_beam_kg": {"2700x100": 12, "2700x125": 15, "3600x150": 22}},
        "electrical": None,
        "thermal": {"operating_temp_c": [-25, 50]},
        "mechanical": {
            "UDL_per_pair_kg": {"2700x100": 2000, "2700x125": 3000, "3600x150": 3500},
            "beam_height_mm": [85, 100, 125, 150],
            "deflection_limit": "span_over_200_BS_EN_15512",
            "safety_pin": "required",
        },
        "interface": {"connector": "3_hook_teardrop_or_4_hook_keyhole"},
        "procurement": {"typical_unit_cost_gbp_per_pair": {"2700": 20, "3600": 28}, "lead_time_days": 14,
                        "common_suppliers": ["Dexion", "Link51", "Mecalux", "SSI Schaefer"]},
    },

    "eur_pallet": {
        "mass": {"material": "softwood_timber_heat_treated_ISPM15", "density_kg_m3": 500,
                 "typical_mass_kg": {"EUR_1200x800": 25, "UK_1200x1000": 30}},
        "electrical": None,
        "thermal": {"operating_temp_c": [-30, 60]},
        "mechanical": {
            "static_load_kg": {"EUR": 4000, "UK": 4000},
            "dynamic_load_kg": {"EUR": 1500, "UK": 1500},
            "racking_load_kg": {"EUR": 1000, "UK": 1000},
            "standard": {"EUR": "BS_EN_13698_1_EPAL", "UK": "1200x1000_CHEP_blue"},
            "entry": "4_way",
        },
        "interface": {"fork_entry_height_mm": 100, "fork_width_mm": [150, 180]},
        "procurement": {"typical_unit_cost_gbp": {"EUR_new": 12, "UK_CHEP_rental": 1.50}, "lead_time_days": 3,
                        "common_suppliers": ["CHEP", "EPAL", "LPR", "IPP Logipal"]},
    },

    "picking_tote": {
        "mass": {"material": "polypropylene_PP_or_HDPE", "density_kg_m3": 950,
                 "typical_mass_kg": {"400x300x220": 0.8, "600x400x280": 1.5, "600x400x340": 1.8}},
        "electrical": None,
        "thermal": {"operating_temp_c": [-20, 60]},
        "mechanical": {"stack_load_kg": 25, "nesting_ratio_pct": 70,
                       "standard_sizes_mm": ["300x200x120", "400x300x170", "400x300x220", "600x400x280", "600x400x340"],
                       "lid": "hinged_or_separate", "dividers": "optional_removable"},
        "interface": {"label_holder": "front_snap_on", "barcode": "moulded_recess_for_label",
                      "RFID": "tag_pocket_option"},
        "procurement": {"typical_unit_cost_gbp": {"400x300": 4, "600x400": 7}, "lead_time_days": 7,
                        "common_suppliers": ["SSI Schaefer", "Bito", "Linpac Allibert", "utz"]},
    },

    "dock_leveller": {
        "mass": {"material": "steel_platform_12mm_diamond_plate_hydraulic", "density_kg_m3": 7850,
                 "typical_mass_kg": {"6t_2x3m": 700, "9t_2x3.5m": 900}},
        "electrical": {"voltage_v": 415, "motor_kw": [2.2, 3], "control": "push_button_inside_building"},
        "thermal": {"operating_temp_c": [-20, 50]},
        "mechanical": {
            "capacity_kg": [6000, 9000, 12000],
            "platform_size_mm": {"standard": "2000x3000", "wide": "2200x3500"},
            "range_mm": {"above_dock": 300, "below_dock": 300},
            "lip_length_mm": [350, 400],
            "type": ["hydraulic", "mechanical_spring", "air_bag"],
        },
        "interface": {"pit": "builder_work_pit_required", "bumpers": "paired_with_dock_bumpers",
                      "door_interlock": "optional_linked_to_roller_shutter"},
        "procurement": {"typical_unit_cost_gbp": {"6t_hydraulic": 3000, "9t_hydraulic": 4500}, "lead_time_days": 28,
                        "common_suppliers": ["Hormann", "Assa Abloy", "Stertil", "Thorworld"]},
    },

    "dock_bumper": {
        "mass": {"material": "moulded_rubber_EPDM_or_recycled", "density_kg_m3": 1100,
                 "typical_mass_kg": {"450x250x100": 12, "500x300x100": 16}},
        "electrical": None,
        "thermal": {"operating_temp_c": [-30, 70]},
        "mechanical": {"energy_absorption_kj": {"standard": 5, "heavy_duty": 15},
                       "type": ["moulded_rubber", "laminated_rubber_steel", "dock_shelter_mounted"]},
        "interface": {"fix": "through_bolt_M16_to_dock_wall", "spacing": "paired_at_1200mm_centres"},
        "procurement": {"typical_unit_cost_gbp": 60, "lead_time_days": 5,
                        "common_suppliers": ["Hormann", "Stertil", "Thorworld", "Dura"]},
    },

    "barcode_scanner_fixed": {
        "mass": {"material": "aluminium_die_cast_housing_IP65", "typical_mass_g": {"compact": 150, "industrial": 350}},
        "electrical": {"voltage_v": 24, "power_w": [5, 10], "interface": ["Ethernet_IP", "PROFINET", "RS232", "USB"]},
        "thermal": {"operating_temp_c": [0, 50]},
        "mechanical": {
            "type": ["1D_laser", "2D_imager", "DPM_reader"],
            "read_range_mm": {"1D": [50, 800], "2D": [40, 400]},
            "scan_rate_per_s": {"1D": 1000, "2D": 60},
            "resolution_mil": [5, 7.5, 10, 15, 20],
            "ip_rating": "IP65_or_IP67",
        },
        "interface": {"mounting": "DIN_rail_or_bracket", "trigger": "external_sensor_or_continuous",
                      "feedback": "good_read_LED_and_beeper"},
        "procurement": {"typical_unit_cost_gbp": {"1D": 200, "2D": 500}, "lead_time_days": 5,
                        "common_suppliers": ["Cognex", "Sick", "Keyence", "Datalogic", "Zebra"]},
    },

    "light_curtain": {
        "mass": {"material": "aluminium_extrusion_IP65", "typical_mass_g_per_100mm": 50},
        "electrical": {"voltage_v": 24, "power_w": [3, 8], "output": "OSSD_dual_channel_SIL3_PLe",
                       "interface": ["relay", "safety_PLC", "IO_Link_Safety"]},
        "thermal": {"operating_temp_c": [0, 55]},
        "mechanical": {
            "resolution_mm": [14, 20, 30, 40, 50, 90],
            "range_m": [0.3, 6, 12, 20],
            "response_time_ms": [5, 10, 15, 25],
            "height_mm": [150, 300, 600, 900, 1200, 1500, 1800],
            "safety_standard": "BS_EN_IEC_61496_1_Type_4_SIL3",
        },
        "interface": {"mounting": "swivel_bracket", "alignment": "built_in_laser_alignment_aid",
                      "cascade": "up_to_3_pairs"},
        "procurement": {"typical_unit_cost_gbp_per_pair": {"300mm": 250, "900mm": 500, "1500mm": 750},
                        "lead_time_days": 7,
                        "common_suppliers": ["Sick", "Keyence", "Banner", "Leuze", "Omron"]},
    },

    "estop_button": {
        "mass": {"material": "plastic_housing_PA66_or_metal_die_cast", "typical_mass_g": 100},
        "electrical": {"voltage_v": [24, 240], "contacts": "1NC_1NC_or_2NC", "current_a": 10,
                       "standard": "BS_EN_ISO_13850_BS_EN_60947_5_5"},
        "thermal": {"operating_temp_c": [-25, 70]},
        "mechanical": {"head_d_mm": [40, 60], "actuator": "mushroom_head_push_lock_turn_release",
                       "colour": "red_head_yellow_surround", "ip_rating": "IP65_IP67"},
        "interface": {"mounting": "22mm_panel_cutout", "wiring": "screw_or_spring_cage"},
        "procurement": {"typical_unit_cost_gbp": 8, "lead_time_days": 1,
                        "common_suppliers": ["Schneider", "Siemens", "ABB", "Eaton", "Pilz"]},
    },
}
