/**
 * @file fea-generator.ts — AI-powered load case generation + FEA orchestration
 *
 * @description Two-stage pipeline for structural analysis:
 * 1. AI infers realistic load cases from module spec (product-agnostic)
 * 2. Sends STEP geometry + loads to Modal FEA worker for meshing + solving
 *
 * The key insight: the AI generates load cases based on what the module IS,
 * not based on hard-coded product knowledge. A "motor mount" gets thrust loads,
 * a "pressure vessel" gets internal pressure, etc. — inferred from the spec.
 *
 * @security
 * - OPENAI_API_KEY for load case generation
 * - MODAL_FEA_ENDPOINT_URL for FEA execution
 *
 * @related
 * - CAD generator: ./cad-generator.ts (generates the geometry)
 * - FEA worker: /modal_fea_worker.py (runs the solver)
 * - Schema: ./xray-schema.ts (StructuralAnalysis type)
 * - Convergence: ./convergence-controller.ts (iterative design loop)
 */

import OpenAI from "openai"

import { createAdminClient } from "@/lib/supabase/admin"

import type { ModuleSpec, StructuralAnalysis, StressHotspot } from "./xray-schema"

// ─── Constants ───────────────────────────────────────────────────────

const STORAGE_BUCKET = "xray-images"
const FEA_TIMEOUT_MS = 300_000  // 5 minutes for FEA

// ─── Types ───────────────────────────────────────────────────────────

/** A load case generated by AI */
export interface LoadCase {
  type: "gravity" | "pressure" | "force" | "moment" | "acceleration"
  description: string
  magnitude_N?: number
  magnitude_MPa?: number
  magnitude_g?: number
  direction?: [number, number, number]
  application_region?: string
  rationale: string
}

/** AI-generated load case set for a module */
export interface LoadCaseSet {
  loadCases: LoadCase[]
  materialKey: string
  boundaryConditionDescription: string
  assumptions: string[]
}

/** Result from the FEA worker */
interface FeaWorkerResult {
  error: string | null
  max_von_mises_MPa: number
  yield_strength_MPa: number
  safety_factor: number
  max_deformation_mm: number
  mesh_element_count: number
  mesh_node_count?: number
  hotspots: Array<{
    location: [number, number, number]
    vonMisesStress_MPa: number
    description: string
  }>
  contour_image: string | null
  material: string
  load_case_description: string
}

// ─── AI Load Case Generation ─────────────────────────────────────────

const LOAD_CASE_SYSTEM_PROMPT = `You are a structural engineering expert. Given a module specification, generate realistic load cases for Finite Element Analysis (FEA).

You must infer the loading conditions from what the module IS and DOES — not from any specific product type. This is product-agnostic.

## Rules
1. Output valid JSON matching the schema below.
2. Generate 1-4 load cases covering the primary operating conditions.
3. Include at least one gravity/self-weight load case.
4. Choose the most appropriate material from the library based on the module description.
5. Be conservative with load magnitudes — overestimate rather than underestimate.
6. Specify boundary conditions (what's fixed/constrained).

## Material Library Keys
- "pla" — PLA plastic (3D printed prototypes)
- "abs" — ABS plastic (functional 3D prints)
- "petg" — PETG (durable 3D prints)
- "nylon" — Nylon PA6 (engineering plastic)
- "aluminum" — 6061-T6 aluminum (machined parts)
- "steel" — A36 steel (structural)
- "titanium" — Ti-6Al-4V (aerospace)

## Output Schema
{
  "loadCases": [
    {
      "type": "gravity" | "pressure" | "force" | "acceleration",
      "description": "Human-readable description",
      "magnitude_N": 10.0,  // for force type
      "magnitude_MPa": 0.5, // for pressure type
      "magnitude_g": 1.0,   // for acceleration type (multiples of g)
      "direction": [0, 0, -1],
      "rationale": "Why this load applies to this module"
    }
  ],
  "materialKey": "pla",
  "boundaryConditionDescription": "Fixed at mounting holes on bottom face",
  "assumptions": ["Uniform load distribution", "Room temperature operation"]
}

Return ONLY valid JSON. No markdown fences.`

/**
 * Generates realistic load cases for a module using AI.
 *
 * @description Uses the module's purpose, key parts, and operating principles
 * to infer what forces/pressures/constraints the part would experience in use.
 *
 * @param module - The module spec to analyze
 * @returns AI-generated load cases, material selection, and boundary conditions
 *
 * @throws Error if AI call fails
 */
export async function generateLoadCases(module: ModuleSpec): Promise<LoadCaseSet> {
  const apiKey = process.env.OPENAI_API_KEY?.trim()
  if (!apiKey) {
    throw new Error("[XRayFEA] OPENAI_API_KEY is not configured")
  }

  const openai = new OpenAI({ apiKey })

  const userPrompt = `Generate load cases for FEA analysis of this module:

**Module:** ${module.name}
**Purpose:** ${module.purpose}
**What it is:** ${module.detail.whatItIs}
**Why it matters:** ${module.detail.whyItMatters}

**Key Physical Components:**
${module.keyParts.map((p) => `- ${p}`).join("\n")}

**Inputs:** ${module.io.in.join(", ")}
**Outputs:** ${module.io.out.join(", ")}

${module.detail.operatingPrinciples ? `**Operating Principles:** ${module.detail.operatingPrinciples}` : ""}
${module.detail.materialJustification ? `**Materials:** ${module.detail.materialJustification}` : ""}
${module.detail.tolerancesAndSpecs ? `**Tolerances:** ${module.detail.tolerancesAndSpecs}` : ""}

**Common Failure Modes:**
${module.detail.commonFailureModes.map((f) => `- ${f}`).join("\n")}

What realistic loads and boundary conditions should be applied for structural analysis?`

  console.info("[XRayFEA] Generating load cases for module:", {
    moduleId: module.id,
    moduleName: module.name,
  })

  const completion = await openai.chat.completions.create({
    model: "gpt-5.3-instant",
    messages: [
      { role: "system", content: LOAD_CASE_SYSTEM_PROMPT },
      { role: "user", content: userPrompt },
    ],
    temperature: 0.2,
    max_tokens: 1500,
  })

  const rawContent = completion.choices[0]?.message?.content
  if (!rawContent) {
    throw new Error("[XRayFEA] AI returned empty response for load cases")
  }

  // Parse JSON, stripping markdown fences if present
  const cleaned = rawContent
    .replace(/^```(?:json)?\n?/gm, "")
    .replace(/\n?```$/gm, "")
    .trim()

  try {
    const parsed = JSON.parse(cleaned) as LoadCaseSet
    // Validate loadCases is an array before iterating
    if (!Array.isArray(parsed.loadCases)) {
      console.warn("[XRayFEA] AI returned non-array loadCases, using gravity fallback")
      parsed.loadCases = [{ type: "gravity", description: "Self-weight under gravity", rationale: "Fallback: loadCases was not an array" }]
    }
    if (parsed.loadCases.length > 6) {
      console.warn(`[XRayFEA] AI returned ${parsed.loadCases.length} loadCases, truncating to 6`)
      parsed.loadCases = parsed.loadCases.slice(0, 6)
    }
    // Sanity-check AI-inferred magnitudes to prevent physically implausible values
    for (const lc of parsed.loadCases) {
      if (typeof lc.magnitude_N === 'number' && isFinite(lc.magnitude_N)) {
        // SECURITY: Floor at 0.1 for force/pressure to avoid wasting solver resources on zero-magnitude loads
        const clamped = Math.max(0.1, Math.min(lc.magnitude_N, 100_000))
        if (clamped !== lc.magnitude_N) {
          console.warn(`[XRayFEA] Clamped force magnitude from ${lc.magnitude_N} to ${clamped} N`)
        }
        lc.magnitude_N = clamped
      } else if (lc.magnitude_N != null) {
        console.warn(`[XRayFEA] Invalid force magnitude ${lc.magnitude_N}, clearing`)
        lc.magnitude_N = undefined
      }
      if (typeof lc.magnitude_MPa === 'number' && isFinite(lc.magnitude_MPa)) {
        const clamped = Math.max(0.1, Math.min(lc.magnitude_MPa, 1_000))
        if (clamped !== lc.magnitude_MPa) {
          console.warn(`[XRayFEA] Clamped pressure magnitude from ${lc.magnitude_MPa} to ${clamped} MPa`)
        }
        lc.magnitude_MPa = clamped
      } else if (lc.magnitude_MPa != null) {
        console.warn(`[XRayFEA] Invalid pressure magnitude ${lc.magnitude_MPa}, clearing`)
        lc.magnitude_MPa = undefined
      }
      if (typeof lc.magnitude_g === 'number' && isFinite(lc.magnitude_g)) {
        const clamped = Math.max(0, Math.min(lc.magnitude_g, 50))
        if (clamped !== lc.magnitude_g) {
          console.warn(`[XRayFEA] Clamped acceleration magnitude from ${lc.magnitude_g} to ${clamped} g`)
        }
        lc.magnitude_g = clamped
      } else if (lc.magnitude_g != null) {
        console.warn(`[XRayFEA] Invalid acceleration magnitude ${lc.magnitude_g}, clearing`)
        lc.magnitude_g = undefined
      }
      // Normalize direction vector
      if (lc.direction) {
        const [dx, dy, dz] = lc.direction
        if (typeof dx === 'number' && typeof dy === 'number' && typeof dz === 'number'
            && isFinite(dx) && isFinite(dy) && isFinite(dz)) {
          const mag = Math.sqrt(dx * dx + dy * dy + dz * dz)
          if (isFinite(mag) && mag > 0) {
            lc.direction = [dx / mag, dy / mag, dz / mag]
          } else {
            console.warn("[XRayFEA] Zero-length direction vector, defaulting to [0,0,1]")
            lc.direction = [0, 0, 1]
          }
        } else {
          console.warn(`[XRayFEA] Invalid direction vector [${dx},${dy},${dz}], defaulting to [0,0,1]`)
          lc.direction = [0, 0, 1]
        }
      }
    }
    return parsed
  } catch (parseError) {
    console.error("[XRayFEA] Failed to parse AI load cases:", cleaned.slice(0, 200))
    // Fallback: gravity-only load case
    return {
      loadCases: [{ type: "gravity", description: "Self-weight under gravity", rationale: "Fallback: AI parsing failed" }],
      materialKey: "pla",
      boundaryConditionDescription: "Fixed at bottom face",
      assumptions: ["Gravity load only (AI load case generation failed)"],
    }
  }
}

// ─── FEA Worker Orchestration ────────────────────────────────────────

/**
 * Runs full structural FEA on a module's CAD model.
 *
 * Pipeline: AI generates load cases → Send STEP + loads to FEA worker → Upload results.
 *
 * @param scanId - The scan ID for storage namespacing
 * @param module - The module with a complete CAD model
 * @returns StructuralAnalysis results
 *
 * @throws Error if the module has no STEP file or FEA worker is not configured
 */
export async function runStructuralAnalysis(
  scanId: string,
  module: ModuleSpec,
): Promise<StructuralAnalysis> {
  // VALIDATION: Ensure module has CAD data
  if (!module.cadModel?.stepUrl) {
    return {
      status: "failed",
      computedAt: new Date().toISOString(),
    }
  }

  const feaEndpoint = process.env.MODAL_FEA_ENDPOINT_URL
  if (!feaEndpoint) {
    throw new Error("[XRayFEA] MODAL_FEA_ENDPOINT_URL is not configured")
  }

  // Stage 1: AI generates load cases
  const loadCaseSet = await generateLoadCases(module)

  // Stage 2: Download STEP file from storage and encode as base64
  const stepB64 = await downloadAsBase64(module.cadModel.stepUrl)

  // Stage 3: Send to FEA worker
  console.info("[XRayFEA] Sending to FEA worker:", {
    moduleId: module.id,
    material: loadCaseSet.materialKey,
    loadCaseCount: loadCaseSet.loadCases.length,
  })

  const controller = new AbortController()
  const timeoutId = setTimeout(() => controller.abort(), FEA_TIMEOUT_MS)

  let feaResult: FeaWorkerResult
  try {
    const response = await fetch(feaEndpoint, {
      method: "POST",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify({
        step_data_b64: stepB64,
        module_id: module.id,
        material_key: loadCaseSet.materialKey,
        load_cases: loadCaseSet.loadCases,
        mesh_size: 5.0,
      }),
      signal: controller.signal,
    })

    clearTimeout(timeoutId)

    if (!response.ok) {
      const errText = await response.text()
      throw new Error(`FEA API error (${response.status}): ${errText.slice(0, 300)}`)
    }

    feaResult = await response.json() as FeaWorkerResult
  } catch (error) {
    clearTimeout(timeoutId)
    if (error instanceof DOMException && error.name === "AbortError") {
      throw new Error(`FEA execution timed out after ${FEA_TIMEOUT_MS / 1000}s`)
    }
    throw error
  }

  if (feaResult.error) {
    return {
      status: "failed",
      loadCaseDescription: loadCaseSet.loadCases.map((lc) => lc.description).join("; "),
      computedAt: new Date().toISOString(),
    }
  }

  // Stage 4: Upload contour image if available
  let contourImageUrl: string | undefined
  if (feaResult.contour_image) {
    try {
      contourImageUrl = await uploadAnalysisFile(
        scanId,
        `module-${module.id}/fea-contour.png`,
        feaResult.contour_image,
        "image/png",
      )
    } catch (error) {
      console.warn("[XRayFEA] Failed to upload contour image:", {
        error: error instanceof Error ? error.message : "Unknown",
      })
    }
  }

  // Convert hotspots
  const criticalLocations: StressHotspot[] = (feaResult.hotspots || []).map((h) => ({
    location: h.location,
    vonMisesStress_MPa: h.vonMisesStress_MPa,
    description: h.description,
  }))

  console.info("[XRayFEA] Structural analysis complete:", {
    moduleId: module.id,
    maxStress_MPa: feaResult.max_von_mises_MPa,
    safetyFactor: feaResult.safety_factor,
    maxDeformation_mm: feaResult.max_deformation_mm,
  })

  return {
    status: "complete",
    maxVonMisesStress_MPa: feaResult.max_von_mises_MPa,
    yieldStrength_MPa: feaResult.yield_strength_MPa,
    safetyFactor: feaResult.safety_factor,
    maxDeformation_mm: feaResult.max_deformation_mm,
    criticalLocations,
    meshElementCount: feaResult.mesh_element_count,
    loadCaseDescription: feaResult.load_case_description,
    contourImageUrl,
    computedAt: new Date().toISOString(),
  }
}

// ─── Storage Helpers ─────────────────────────────────────────────────

/**
 * Downloads a file from a URL and returns it as a base64 string.
 *
 * @param url - Public URL to download from
 * @returns Base64-encoded file content
 */
async function downloadAsBase64(url: string): Promise<string> {
  const response = await fetch(url)
  if (!response.ok) {
    throw new Error(`[XRayFEA] Failed to download file: ${response.status}`)
  }
  const buffer = await response.arrayBuffer()
  return Buffer.from(buffer).toString("base64")
}

/**
 * Uploads a base64-encoded analysis file to Supabase Storage.
 *
 * @param scanId - Scan ID for path namespacing
 * @param filename - Relative file path
 * @param base64Data - Base64-encoded file content
 * @param mimeType - MIME type of the file
 * @returns Public URL of the uploaded file
 */
async function uploadAnalysisFile(
  scanId: string,
  filename: string,
  base64Data: string,
  mimeType: string,
): Promise<string> {
  const supabase = createAdminClient()
  const buffer = Buffer.from(base64Data, "base64")
  const path = `${scanId}/analysis/${filename}`

  const { error } = await supabase.storage
    .from(STORAGE_BUCKET)
    .upload(path, buffer, {
      contentType: mimeType,
      upsert: true,
    })

  if (error) {
    throw new Error(`[XRayFEA] Upload failed for ${filename}: ${error.message}`)
  }

  const { data: urlData } = supabase.storage
    .from(STORAGE_BUCKET)
    .getPublicUrl(path)

  return urlData.publicUrl
}
