/**
 * @file structural-brief.ts — Opus-powered structural description orchestrator
 *
 * @description Generates a unified "structural brief" from a module spec using
 * Claude Opus 4.6. This brief is the single source of truth for both:
 * 1. Gemini image generation (technical illustrations)
 * 2. CadQuery 3D model generation (STEP/STL/SVG exports)
 *
 * By having one AI (Opus) describe the physical structure in detail, and then
 * passing that description to both the image and CAD generators, we ensure
 * the illustration and 3D model show the same components in the same arrangement.
 *
 * @security Requires ANTHROPIC_API_KEY environment variable
 *
 * @related
 * - Image generator: ./image-generator.ts (consumes the brief for illustrations)
 * - CAD generator: ./cad-generator.ts (consumes the brief for CadQuery code)
 * - Schema: ./xray-schema.ts (ModuleSpec input type)
 */

import type { ModuleSpec, XRaySpec } from "./xray-schema"

// ─── Types ───────────────────────────────────────────────────────────

/**
 * A unified structural description of a module's physical form.
 *
 * @description Generated by Opus, consumed by both the image generator
 * (Gemini) and the CAD code generator (Opus/Gemini). Contains enough
 * detail to produce consistent visual and 3D representations.
 */
export interface StructuralBrief {
  /** The module this brief describes */
  moduleId: string
  moduleName: string
  /** Overall dimensions in mm (L x W x H) */
  overallDimensions: string
  /** Detailed narrative describing the physical structure, component arrangement,
   *  spatial relationships, and visual appearance of the module */
  physicalDescription: string
  /** Specific prompt instructions for Gemini image generation */
  imagePrompt: string
  /** Specific instructions for CadQuery code generation, including geometry
   *  strategy (what primitives to use, how to arrange components) */
  cadInstructions: string
}

/**
 * System-level structural brief for the overall product.
 */
export interface SystemStructuralBrief {
  /** Overall product dimensions in mm */
  overallDimensions: string
  /** Narrative describing the assembled product form factor */
  physicalDescription: string
  /** Instructions for the system-level CadQuery model */
  cadInstructions: string
  /** Instructions for the system-level process diagram */
  imagePrompt: string
}

// ─── System Prompt ───────────────────────────────────────────────────

const STRUCTURAL_BRIEF_PROMPT = `You are an expert mechanical/process engineer and industrial designer. Your job is to create a detailed structural description of an engineering module that will be used to generate BOTH a technical illustration AND a 3D CAD model.

## Your Output Format

Respond with EXACTLY four labeled sections, using these exact headers:

### DIMENSIONS
Provide realistic overall dimensions in mm (Length x Width x Height). Base these on the module's purpose and components — a brine pre-treatment tank might be 2000x1500x1200mm, a small pump assembly might be 400x300x250mm.

### PHYSICAL DESCRIPTION
Write a detailed narrative (150-300 words) describing:
- The main body/housing shape and material
- How key components are arranged spatially (what's on top, what's inside, what's to the sides)
- Connection points (pipe stubs, flanges, electrical connections)
- Flow path through the module (where inputs enter, where outputs exit)
- Mounting/support structure
- Any visible indicators, gauges, or access panels

Be SPECIFIC about shapes: "a horizontal cylindrical pressure vessel" not "a container". "Three vertical tube bundles arranged in parallel" not "heat exchange elements". Describe relative positions: "mounted on the left side of the base frame" not "attached to the module".

### IMAGE PROMPT
Write a prompt (80-150 words) for Gemini image generation. This should produce a clean, professional isometric technical illustration. Include:
- Specific visual style: "clean isometric technical illustration, white background, thin precise lines, subtle gray grid, engineering specification style"
- All key components that should be labeled with callout lines
- Input/output flow direction (left-to-right)
- Cutaway or transparency if needed to show internal components

### CAD INSTRUCTIONS
Write specific instructions (100-200 words) for generating CadQuery Python code. Include:
- What CadQuery primitives to use for each component (e.g., "Main tank: cq.Workplane('XY').cylinder(height=800, radius=300)")
- Assembly strategy: build base first, then union major components, then add smaller features
- Specific dimensions for the 3-5 most important components
- Which components to represent as simplified forms (e.g., "represent the heat exchanger as a rectangular block with tube stubs on each end")
- DO NOT write actual CadQuery code — just describe what the code should build

## Rules
- Be physically realistic — dimensions should make engineering sense
- Components must be consistent across all four sections
- The same components appear in both the image and CAD descriptions
- Use specific engineering terminology (flanges, bosses, manifolds, baffles, etc.)
- Think about how the module would actually look if manufactured`

// ─── System-Level Prompt ─────────────────────────────────────────────

const SYSTEM_BRIEF_PROMPT = `You are an expert mechanical/process engineer. Create a structural description of an ENTIRE assembled product/system. This will drive both the system diagram illustration and a 3D CAD model.

## Your Output Format

Respond with EXACTLY four labeled sections:

### DIMENSIONS
Overall product dimensions in mm (L x W x H). Consider the combined footprint of all modules.

### PHYSICAL DESCRIPTION
Describe the assembled product (150-250 words):
- Overall form factor (frame-mounted skid? benchtop unit? freestanding cabinet?)
- How modules connect physically (piping runs, cable trays, shared frame)
- Key external features visible from outside (control panels, inlets, outlets, access doors)
- General material and finish

### IMAGE PROMPT
Write a prompt (80-120 words) for a process flow diagram showing all modules as connected blocks with flow arrows. Clean, modern style.

### CAD INSTRUCTIONS
Instructions (100-200 words) for a CadQuery model of the assembled product:
- Overall frame/body dimensions
- Where each major module sits within the frame
- Use simplified blocks/cylinders for modules (don't model internal details)
- Key external features (pipe stubs, panels, mounting points)
- Build strategy: frame first, then union module blocks, then add external features`

// ─── Opus API Call ───────────────────────────────────────────────────

/**
 * Calls Claude Opus 4.6 for non-streaming text completion.
 *
 * @param systemPrompt - The system prompt
 * @param userPrompt - The user prompt
 * @param maxTokens - Maximum tokens to generate (default 2048)
 * @returns The response text
 *
 * @throws Error if ANTHROPIC_API_KEY is missing or API call fails
 */
async function callOpus(
  systemPrompt: string,
  userPrompt: string,
  maxTokens: number = 4096,
): Promise<string> {
  const apiKey = process.env.ANTHROPIC_API_KEY
  if (!apiKey) {
    throw new Error("[StructuralBrief] ANTHROPIC_API_KEY is not configured")
  }

  const Anthropic = (await import("@anthropic-ai/sdk")).default
  const client = new Anthropic({ apiKey })

  const response = await client.messages.create({
    model: "claude-opus-4-6",
    max_tokens: maxTokens,
    system: systemPrompt,
    messages: [{ role: "user", content: userPrompt }],
  })

  // Log response metadata for debugging
  const blockTypes = response.content.map((b) => b.type)
  console.info("[StructuralBrief] Opus response:", {
    stopReason: response.stop_reason,
    blockTypes,
    blockCount: response.content.length,
    inputTokens: response.usage?.input_tokens,
    outputTokens: response.usage?.output_tokens,
  })

  // Extract text from response content blocks
  const texts: string[] = []
  for (const block of response.content) {
    if (block.type === "text") {
      texts.push(block.text)
    }
  }

  // Fallback: if no text blocks but thinking blocks exist, extract from thinking
  if (texts.length === 0) {
    for (const block of response.content) {
      if ("thinking" in block && typeof (block as Record<string, unknown>).thinking === "string") {
        texts.push((block as Record<string, unknown>).thinking as string)
      }
    }
    if (texts.length > 0) {
      console.warn("[StructuralBrief] No text blocks found — extracted content from thinking blocks")
    }
  }

  if (texts.length === 0) {
    console.error("[StructuralBrief] Opus returned no usable content:", {
      stopReason: response.stop_reason,
      blockTypes,
      rawContent: JSON.stringify(response.content).slice(0, 500),
    })
    throw new Error(
      `[StructuralBrief] Opus returned no text content (stop_reason: ${response.stop_reason}, blocks: [${blockTypes.join(", ")}])`,
    )
  }

  return texts.join("\n")
}

// ─── Parsing ─────────────────────────────────────────────────────────

/**
 * Parses Opus's structured response into a StructuralBrief.
 *
 * @param raw - The raw text response from Opus
 * @param moduleId - Module identifier
 * @param moduleName - Module display name
 * @returns Parsed StructuralBrief
 */
function parseModuleBrief(
  raw: string,
  moduleId: string,
  moduleName: string,
): StructuralBrief {
  const sections = parseSections(raw)

  return {
    moduleId,
    moduleName,
    overallDimensions: sections.dimensions || "Unknown",
    physicalDescription: sections.physical_description || sections.physicalDescription || "",
    imagePrompt: sections.image_prompt || sections.imagePrompt || "",
    cadInstructions: sections.cad_instructions || sections.cadInstructions || "",
  }
}

/**
 * Parses Opus's structured response into a SystemStructuralBrief.
 *
 * @param raw - The raw text response from Opus
 * @returns Parsed SystemStructuralBrief
 */
function parseSystemBrief(raw: string): SystemStructuralBrief {
  const sections = parseSections(raw)

  return {
    overallDimensions: sections.dimensions || "Unknown",
    physicalDescription: sections.physical_description || sections.physicalDescription || "",
    cadInstructions: sections.cad_instructions || sections.cadInstructions || "",
    imagePrompt: sections.image_prompt || sections.imagePrompt || "",
  }
}

/**
 * Splits a markdown response into named sections by ### headers.
 *
 * @param raw - The raw response text
 * @returns Map of lowercase section name -> content
 */
function parseSections(raw: string): Record<string, string> {
  const sections: Record<string, string> = {}
  const lines = raw.split("\n")
  let currentKey = ""
  const contentLines: string[] = []

  for (const line of lines) {
    const headerMatch = line.match(/^###\s+(.+)$/i)
    if (headerMatch) {
      // Save previous section
      if (currentKey) {
        sections[currentKey] = contentLines.join("\n").trim()
        contentLines.length = 0
      }
      // Normalize header: "PHYSICAL DESCRIPTION" -> "physical_description"
      currentKey = headerMatch[1].trim().toLowerCase().replace(/\s+/g, "_")
    } else if (currentKey) {
      contentLines.push(line)
    }
  }

  // Save last section
  if (currentKey) {
    sections[currentKey] = contentLines.join("\n").trim()
  }

  return sections
}

// ─── Public API ──────────────────────────────────────────────────────

/**
 * Generates a structural brief for a single module using Claude Opus 4.6.
 *
 * @description Analyzes the module spec and produces a unified structural
 * description that drives both the technical illustration and the 3D CAD model.
 * This ensures visual consistency between the two representations.
 *
 * @param module - The module spec to analyze
 * @returns A StructuralBrief with dimensions, physical description, image prompt, and CAD instructions
 *
 * @throws Error if Opus API call fails
 */
export async function generateModuleStructuralBrief(
  module: ModuleSpec,
): Promise<StructuralBrief> {
  const userPrompt = buildModuleUserPrompt(module)

  console.info("[StructuralBrief] Generating brief for module:", {
    moduleId: module.id,
    moduleName: module.name,
  })

  const raw = await callOpus(STRUCTURAL_BRIEF_PROMPT, userPrompt)
  const brief = parseModuleBrief(raw, module.id, module.name)

  console.info("[StructuralBrief] Brief generated:", {
    moduleId: module.id,
    dimensionsLength: brief.overallDimensions.length,
    descriptionLength: brief.physicalDescription.length,
    imagePromptLength: brief.imagePrompt.length,
    cadInstructionsLength: brief.cadInstructions.length,
  })

  return brief
}

/**
 * Generates a system-level structural brief for the overall product.
 *
 * @param spec - The full XRay spec with all modules
 * @returns A SystemStructuralBrief for the assembled product
 *
 * @throws Error if Opus API call fails
 */
export async function generateSystemStructuralBrief(
  spec: XRaySpec,
): Promise<SystemStructuralBrief> {
  const userPrompt = buildSystemUserPrompt(spec)

  console.info("[StructuralBrief] Generating system-level brief")

  const raw = await callOpus(SYSTEM_BRIEF_PROMPT, userPrompt)
  const brief = parseSystemBrief(raw)

  console.info("[StructuralBrief] System brief generated:", {
    dimensionsLength: brief.overallDimensions.length,
    descriptionLength: brief.physicalDescription.length,
  })

  return brief
}

// ─── Prompt Builders ─────────────────────────────────────────────────

/**
 * Builds the user prompt for module-level structural brief generation.
 *
 * @param module - The module spec
 * @returns Formatted prompt string
 */
function buildModuleUserPrompt(module: ModuleSpec): string {
  return `Analyze this engineering module and create a detailed structural description:

**Module:** ${module.name}
**Purpose:** ${module.purpose}
**What it is:** ${module.detail.whatItIs}

**Key Physical Components:**
${module.keyParts.map((p) => `- ${p}`).join("\n")}

**Inputs:** ${module.io.in.join(", ")}
**Outputs:** ${module.io.out.join(", ")}

${module.detail.operatingPrinciples ? `**Operating Principles:** ${module.detail.operatingPrinciples}` : ""}
${module.detail.materialJustification ? `**Materials:** ${module.detail.materialJustification}` : ""}
${module.detail.tolerancesAndSpecs ? `**Tolerances:** ${module.detail.tolerancesAndSpecs}` : ""}
${module.systemInterconnections ? `**System Connections:** ${module.systemInterconnections.join("; ")}` : ""}

Create the four-section structural brief for this module. Be specific about physical shapes, dimensions, and spatial arrangement.`
}

/**
 * Builds the user prompt for system-level structural brief generation.
 *
 * @param spec - The full XRay spec
 * @returns Formatted prompt string
 */
function buildSystemUserPrompt(spec: XRaySpec): string {
  const moduleSummaries = spec.modules
    .map((m) => `- **${m.name}:** ${m.purpose} (key parts: ${m.keyParts.slice(0, 4).join(", ")})`)
    .join("\n")

  const ioChain = spec.modules
    .map((m) => `${m.io.in.join("/")} → [${m.name}] → ${m.io.out.join("/")}`)
    .join("\n")

  return `Analyze this complete product/system and create a structural description:

**Product Function:** ${spec.function}

**Modules (subsystems):**
${moduleSummaries}

**Material/Signal Flow:**
${ioChain}

**Key Materials:** ${spec.materials.slice(0, 6).join(", ")}

Create the four-section structural brief for the assembled product. Think about how these modules would be physically arranged on a shared frame or skid.`
}
