/**
 * @file structural-brief.ts — Opus-powered structural description orchestrator
 *
 * @description Generates a unified "structural brief" from a module spec using
 * Claude Opus 4.6. This brief is the single source of truth for both:
 * 1. Gemini image generation (technical illustrations)
 * 2. CadQuery 3D model generation (STEP/STL/SVG exports)
 *
 * By having one AI (Opus) describe the physical structure in detail, and then
 * passing that description to both the image and CAD generators, we ensure
 * the illustration and 3D model show the same components in the same arrangement.
 *
 * @security Requires ANTHROPIC_API_KEY environment variable
 *
 * @related
 * - Image generator: ./image-generator.ts (consumes the brief for illustrations)
 * - CAD generator: ./cad-generator.ts (consumes the brief for CadQuery code)
 * - Schema: ./xray-schema.ts (ModuleSpec input type)
 */

import type { ModuleSpec, XRaySpec } from "./xray-schema"

// ─── Types ───────────────────────────────────────────────────────────

/**
 * A unified structural description of a module's physical form.
 *
 * @description Generated by Opus, consumed by both the image generator
 * (Gemini) and the CAD code generator (Opus/Gemini). Contains enough
 * detail to produce consistent visual and 3D representations.
 */
export interface StructuralBrief {
  /** The module this brief describes */
  moduleId: string
  moduleName: string
  /** Overall dimensions in mm (L x W x H) */
  overallDimensions: string
  /** Detailed narrative describing the physical structure, component arrangement,
   *  spatial relationships, and visual appearance of the module */
  physicalDescription: string
  /** Specific prompt instructions for Gemini image generation */
  imagePrompt: string
  /** Specific instructions for CadQuery code generation, including geometry
   *  strategy (what primitives to use, how to arrange components) */
  cadInstructions: string
}

/**
 * System-level structural brief for the overall product.
 */
export interface SystemStructuralBrief {
  /** Overall product dimensions in mm */
  overallDimensions: string
  /** Narrative describing the assembled product form factor */
  physicalDescription: string
  /** Instructions for the system-level CadQuery model */
  cadInstructions: string
  /** Instructions for the system-level process diagram */
  imagePrompt: string
}

// ─── System Prompt ───────────────────────────────────────────────────

const STRUCTURAL_BRIEF_PROMPT = `You are an expert mechanical/process engineer and industrial designer. Your job is to create a detailed structural description of an engineering module that will be used to generate BOTH a technical illustration AND a 3D CAD model.

## Your Output Format

Respond with EXACTLY four labeled sections, using these exact headers:

### DIMENSIONS
Provide realistic overall dimensions in mm (Length x Width x Height). Base these on the module's purpose and components — a brine pre-treatment tank might be 2000x1500x1200mm, a small pump assembly might be 400x300x250mm.

### PHYSICAL DESCRIPTION
Write a detailed narrative (150-300 words) describing:
- The main body/housing shape and material
- How key components are arranged spatially (what's on top, what's inside, what's to the sides)
- Connection points (pipe stubs, flanges, electrical connections)
- Flow path through the module (where inputs enter, where outputs exit)
- Mounting/support structure
- Any visible indicators, gauges, or access panels

Be SPECIFIC about shapes: "a horizontal cylindrical pressure vessel" not "a container". "Three vertical tube bundles arranged in parallel" not "heat exchange elements". Describe relative positions: "mounted on the left side of the base frame" not "attached to the module".

### IMAGE PROMPT
Write a prompt (80-150 words) for image generation. CRITICAL CONSTRAINT: The prompt must NOT mention any specific component names, labels, dimensions, or text that could appear in the image. Describe components ONLY by their visual appearance (shape, color, position, relative size), never by name or label. Image models will hallucinate garbled text if the prompt contains technical terms or names — keep it purely visual.
Include:
- Specific visual style: "clean isometric technical illustration, white background, thin precise lines, subtle gray grid, engineering specification style"
- All key components visually differentiated by color, position, and shape — described by appearance only
- Input/output flow direction (left-to-right)
- Cutaway or transparency if needed to show internal components
- End the prompt with: "The image must contain absolutely no text, letters, words, numbers, labels, or annotations of any kind."

### CAD INSTRUCTIONS
Write detailed instructions (200-400 words) for generating CadQuery Python code. This drives a 200-600 line CadQuery model, so be thorough. Include:
- What CadQuery primitives to use for each component (e.g., "Main body: box with .cut() for shell wall thickness 2mm")
- Assembly strategy: build main body shell first, then internal structure, then major sub-components, then detail features, then cutouts
- Specific dimensions for ALL major components (not just 3-5)
- How to make each component RECOGNIZABLE — not just a box placeholder. Describe the actual geometry: "motor mount is a cylinder with center bore and 4-bolt pattern on 16mm circle"
- Shell body construction: specify wall thicknesses, which bodies should be hollow
- Internal features: ribs, standoffs, mounting bosses
- Surface features: where to add ventilation grilles, port cutouts, sensor recesses
- DO NOT write actual CadQuery code — describe what the code should build in enough detail that a CAD engineer could write 300+ lines from your description

## Rules
- Be physically realistic — dimensions should make engineering sense
- Components must be consistent across all four sections
- The same components appear in both the image and CAD descriptions
- Use specific engineering terminology (flanges, bosses, manifolds, baffles, etc.)
- Think about how the module would actually look if manufactured`

// ─── System-Level Prompt ─────────────────────────────────────────────

const SYSTEM_BRIEF_PROMPT = `You are an expert mechanical/process engineer. Create a structural description of an ENTIRE assembled product/system. This will drive both the system diagram illustration and a 3D CAD model.

## Your Output Format

Respond with EXACTLY four labeled sections:

### DIMENSIONS
Overall product dimensions in mm (L x W x H). Consider the combined footprint of all modules.

### PHYSICAL DESCRIPTION
Describe the assembled product (150-250 words):
- Overall form factor (frame-mounted skid? benchtop unit? freestanding cabinet?)
- How modules connect physically (piping runs, cable trays, shared frame)
- Key external features visible from outside (control panels, inlets, outlets, access doors)
- General material and finish

### IMAGE PROMPT
Write a prompt (80-120 words) for a process flow diagram showing all modules as connected, color-coded blocks with flow arrows. Clean, modern style. CRITICAL CONSTRAINT: The prompt must NOT mention any module names, labels, dimensions, or text that could appear in the image. Describe blocks ONLY by their visual appearance (color, shape, relative size). Image models hallucinate garbled text when prompts contain names — keep it purely visual. End with: "The image must contain absolutely no text, letters, words, numbers, labels, or annotations of any kind."

### CAD INSTRUCTIONS
Detailed instructions (200-400 words) for a CadQuery model of the assembled product. This is the HERO model — the main visualization. Be thorough:
- Overall frame/body dimensions and shell wall thickness
- Where each major module sits within the frame (specific coordinates/offsets)
- Each module should be a RECOGNIZABLE shape with key geometric features — NOT a plain box
- For each module, describe its external geometry: shape, ports, mounting, distinguishing features
- Structural connections: mounting brackets, pipe runs, cable routing between modules
- Surface features: ventilation, access panels, indicator locations, sensor recesses
- Build strategy: main body shell first (outer.cut(inner) for wall thickness), then internal ribs/structure, then each module sub-assembly, then external features and cutouts
- DO NOT write actual code — describe what to build in enough detail for 300-800 lines of CadQuery`

// ─── Opus API Call ───────────────────────────────────────────────────

/**
 * Calls Claude Opus 4.6 for non-streaming text completion.
 *
 * @param systemPrompt - The system prompt
 * @param userPrompt - The user prompt
 * @param maxTokens - Maximum tokens to generate (default 2048)
 * @returns The response text
 *
 * @throws Error if ANTHROPIC_API_KEY is missing or API call fails
 */
/**
 * Calls Anthropic models (Opus → Sonnet) then falls back to Gemini if
 * both refuse. Drone, industrial, and agricultural modules can trigger
 * Anthropic's safety filters, so Gemini acts as a reliable fallback.
 *
 * @param systemPrompt - System prompt for the model
 * @param userPrompt - User prompt with module details
 * @param maxTokens - Max tokens for Anthropic models (default 6144)
 * @returns The model's text response
 *
 * @throws Error if ALL models fail (Opus, Sonnet, and Gemini)
 */
async function callOpus(
  systemPrompt: string,
  userPrompt: string,
  maxTokens: number = 6144,
): Promise<string> {
  // ── Stage 1: Try Anthropic models (Opus → Sonnet) ──
  const anthropicKey = process.env.ANTHROPIC_API_KEY?.trim()
  if (anthropicKey) {
    const Anthropic = (await import("@anthropic-ai/sdk")).default
    const client = new Anthropic({ apiKey: anthropicKey })

    const ANTHROPIC_MODELS = ["claude-sonnet-4-6", "claude-opus-4-6", "claude-sonnet-4-6"] as const

    for (const model of ANTHROPIC_MODELS) {
      try {
        const response = await client.messages.create({
          model,
          max_tokens: maxTokens,
          system: systemPrompt,
          messages: [{ role: "user", content: userPrompt }],
        })

        const blockTypes = response.content.map((b) => b.type)
        console.info(`[StructuralBrief] ${model} response:`, {
          stopReason: response.stop_reason,
          blockTypes,
          blockCount: response.content.length,
          inputTokens: response.usage?.input_tokens,
          outputTokens: response.usage?.output_tokens,
        })

        // Handle refusal — try next model
        if (response.stop_reason === "refusal" || response.content.length === 0) {
          console.warn(`[StructuralBrief] ${model} refused — trying fallback`)
          continue
        }

        const texts: string[] = []
        for (const block of response.content) {
          if (block.type === "text") {
            texts.push(block.text)
          }
        }

        if (texts.length > 0) {
          return texts.join("\n")
        }

        console.warn(`[StructuralBrief] ${model} returned no text blocks — trying fallback`)
      } catch (error) {
        console.warn(`[StructuralBrief] ${model} error:`, error instanceof Error ? error.message : error)
        continue
      }
    }
  }

  // ── Stage 2: Gemini fallback (different safety characteristics) ──
  const geminiKey = process.env.GOOGLE_AI_API_KEY?.trim()
  if (!geminiKey) {
    throw new Error("[StructuralBrief] Both ANTHROPIC_API_KEY and GOOGLE_AI_API_KEY are missing")
  }

  console.info("[StructuralBrief] All Anthropic models refused — falling back to Gemini")

  // SECURITY: Use x-goog-api-key header instead of URL query param (F6)
  const geminiModel = "gemini-3.1-pro-preview"
  const url = `https://generativelanguage.googleapis.com/v1beta/models/${geminiModel}:generateContent`

  const response = await fetch(url, {
    method: "POST",
    headers: { "Content-Type": "application/json", "x-goog-api-key": geminiKey },
    body: JSON.stringify({
      systemInstruction: { parts: [{ text: systemPrompt }] },
      contents: [{ parts: [{ text: userPrompt }] }],
      generationConfig: { maxOutputTokens: maxTokens },
    }),
  })

  if (!response.ok) {
    const errText = await response.text()
    throw new Error(`[StructuralBrief] Gemini error (${response.status}): ${errText.slice(0, 300)}`)
  }

  const data = await response.json()
  const text = data.candidates?.[0]?.content?.parts
    ?.filter((p: { text?: string }) => p.text)
    ?.map((p: { text: string }) => p.text)
    ?.join("\n")

  if (!text) {
    console.error("[StructuralBrief] Gemini returned no text:", JSON.stringify(data).slice(0, 500))
    throw new Error("[StructuralBrief] All models failed to generate content")
  }

  console.info("[StructuralBrief] Gemini fallback succeeded:", { textLength: text.length })
  return text
}

// ─── Parsing ─────────────────────────────────────────────────────────

/**
 * Parses Opus's structured response into a StructuralBrief.
 *
 * @param raw - The raw text response from Opus
 * @param moduleId - Module identifier
 * @param moduleName - Module display name
 * @returns Parsed StructuralBrief
 */
function parseModuleBrief(
  raw: string,
  moduleId: string,
  moduleName: string,
): StructuralBrief {
  const sections = parseSections(raw)

  return {
    moduleId,
    moduleName,
    overallDimensions: sections.dimensions || "Unknown",
    physicalDescription: sections.physical_description || sections.physicalDescription || "",
    imagePrompt: sections.image_prompt || sections.imagePrompt || "",
    cadInstructions: sections.cad_instructions || sections.cadInstructions || "",
  }
}

/**
 * Parses Opus's structured response into a SystemStructuralBrief.
 *
 * @param raw - The raw text response from Opus
 * @returns Parsed SystemStructuralBrief
 */
function parseSystemBrief(raw: string): SystemStructuralBrief {
  const sections = parseSections(raw)

  return {
    overallDimensions: sections.dimensions || "Unknown",
    physicalDescription: sections.physical_description || sections.physicalDescription || "",
    cadInstructions: sections.cad_instructions || sections.cadInstructions || "",
    imagePrompt: sections.image_prompt || sections.imagePrompt || "",
  }
}

/**
 * Splits a markdown response into named sections by ### headers.
 *
 * @param raw - The raw response text
 * @returns Map of lowercase section name -> content
 */
function parseSections(raw: string): Record<string, string> {
  const sections: Record<string, string> = {}
  const lines = raw.split("\n")
  let currentKey = ""
  const contentLines: string[] = []

  for (const line of lines) {
    const headerMatch = line.match(/^###\s+(.+)$/i)
    if (headerMatch) {
      // Save previous section
      if (currentKey) {
        sections[currentKey] = contentLines.join("\n").trim()
        contentLines.length = 0
      }
      // Normalize header: "PHYSICAL DESCRIPTION" -> "physical_description"
      currentKey = headerMatch[1].trim().toLowerCase().replace(/\s+/g, "_")
    } else if (currentKey) {
      contentLines.push(line)
    }
  }

  // Save last section
  if (currentKey) {
    sections[currentKey] = contentLines.join("\n").trim()
  }

  return sections
}

// ─── Public API ──────────────────────────────────────────────────────

/**
 * Generates a structural brief for a single module using Claude Opus 4.6.
 *
 * @description Analyzes the module spec and produces a unified structural
 * description that drives both the technical illustration and the 3D CAD model.
 * This ensures visual consistency between the two representations.
 *
 * @param module - The module spec to analyze
 * @returns A StructuralBrief with dimensions, physical description, image prompt, and CAD instructions
 *
 * @throws Error if Opus API call fails
 */
export async function generateModuleStructuralBrief(
  module: ModuleSpec,
): Promise<StructuralBrief> {
  const userPrompt = buildModuleUserPrompt(module)

  console.info("[StructuralBrief] Generating brief for module:", {
    moduleId: module.id,
    moduleName: module.name,
  })

  const raw = await callOpus(STRUCTURAL_BRIEF_PROMPT, userPrompt)
  const brief = parseModuleBrief(raw, module.id, module.name)

  console.info("[StructuralBrief] Brief generated:", {
    moduleId: module.id,
    dimensionsLength: brief.overallDimensions.length,
    descriptionLength: brief.physicalDescription.length,
    imagePromptLength: brief.imagePrompt.length,
    cadInstructionsLength: brief.cadInstructions.length,
  })

  return brief
}

/**
 * Generates a system-level structural brief for the overall product.
 *
 * @param spec - The full XRay spec with all modules
 * @returns A SystemStructuralBrief for the assembled product
 *
 * @throws Error if Opus API call fails
 */
export async function generateSystemStructuralBrief(
  spec: XRaySpec,
): Promise<SystemStructuralBrief> {
  const userPrompt = buildSystemUserPrompt(spec)

  console.info("[StructuralBrief] Generating system-level brief")

  const raw = await callOpus(SYSTEM_BRIEF_PROMPT, userPrompt)
  const brief = parseSystemBrief(raw)

  console.info("[StructuralBrief] System brief generated:", {
    dimensionsLength: brief.overallDimensions.length,
    descriptionLength: brief.physicalDescription.length,
  })

  return brief
}

// ─── Prompt Builders ─────────────────────────────────────────────────

/**
 * Builds the user prompt for module-level structural brief generation.
 *
 * @param module - The module spec
 * @returns Formatted prompt string
 */
function buildModuleUserPrompt(module: ModuleSpec): string {
  return `Analyze this engineering module and create a detailed structural description:

**Module:** ${module.name}
**Purpose:** ${module.purpose}
**What it is:** ${module.detail.whatItIs}

**Key Physical Components:**
${module.keyParts.map((p) => `- ${p}`).join("\n")}

**Inputs:** ${module.io.in.join(", ")}
**Outputs:** ${module.io.out.join(", ")}

${module.detail.operatingPrinciples ? `**Operating Principles:** ${module.detail.operatingPrinciples}` : ""}
${module.detail.materialJustification ? `**Materials:** ${module.detail.materialJustification}` : ""}
${module.detail.tolerancesAndSpecs ? `**Tolerances:** ${module.detail.tolerancesAndSpecs}` : ""}
${module.systemInterconnections ? `**System Connections:** ${module.systemInterconnections.join("; ")}` : ""}

Create the four-section structural brief for this module. Be specific about physical shapes, dimensions, and spatial arrangement.`
}

/**
 * Builds the user prompt for system-level structural brief generation.
 *
 * @param spec - The full XRay spec
 * @returns Formatted prompt string
 */
function buildSystemUserPrompt(spec: XRaySpec): string {
  const moduleSummaries = spec.modules
    .map((m) => `- **${m.name}:** ${m.purpose} (key parts: ${m.keyParts.slice(0, 4).join(", ")})`)
    .join("\n")

  const ioChain = spec.modules
    .map((m) => `${m.io.in.join("/")} → [${m.name}] → ${m.io.out.join("/")}`)
    .join("\n")

  return `Analyze this complete product/system and create a structural description:

**Product Function:** ${spec.function}

**Modules (subsystems):**
${moduleSummaries}

**Material/Signal Flow:**
${ioChain}

**Key Materials:** ${spec.materials.slice(0, 6).join(", ")}

Create the four-section structural brief for the assembled product. Think about how these modules would be physically arranged on a shared frame or skid.`
}
