/**
 * Types for Advisory - Expert Q&A for Founders
 * Allows founders to ask questions and get AI-assisted answers with verification
 */

// Verification status for AI-generated answers
export type VerificationStatus = 
    | 'unverified'          // AI generated, not yet reviewed
    | 'verified'            // Reviewed and confirmed accurate
    | 'needs_review'        // Flagged for expert review
    | 'expert_verified'     // Verified by a human expert
    | 'partially_accurate'  // Some parts accurate, some need clarification
    | 'outdated'            // Was accurate but may be stale

// Confidence level of AI-generated answers
export type ConfidenceLevel = 'high' | 'medium' | 'low'

// Categories of advisory questions
export type AdvisoryCategory = 
    | 'Legal'
    | 'Finance'
    | 'HR'
    | 'Operations'
    | 'Strategy'
    | 'Fundraising'
    | 'Product'
    | 'Marketing'
    | 'Sales'
    | 'Technical'
    | 'General'

// Priority/urgency of the question
export type QuestionPriority = 'urgent' | 'normal' | 'low'

// Source of an answer
export type AnswerSource = 
    | 'ai_generated'        // Generated by AI
    | 'expert'              // Written by human expert
    | 'community'           // From community/other founders
    | 'knowledge_base'      // From internal knowledge base

// An advisory question asked by a founder
export interface AdvisoryQuestion {
    id: string
    foundry_id: string
    asked_by: string        // user_id
    title: string
    body: string
    category: AdvisoryCategory
    tags?: string[]
    priority: QuestionPriority
    // Related business function (links to Org Blueprint)
    related_function_id?: string
    // Current status
    status: 'open' | 'answered' | 'closed'
    // Number of answers
    answer_count: number
    // Best answer ID (if selected)
    accepted_answer_id?: string
    // View count
    view_count: number
    created_at: string
    updated_at: string
}

// An answer to an advisory question
export interface AdvisoryAnswer {
    id: string
    question_id: string
    foundry_id: string
    answered_by: string | null  // null for AI answers
    source: AnswerSource
    content: string
    // AI confidence level
    confidence: ConfidenceLevel
    // Verification status
    verification_status: VerificationStatus
    verified_by?: string
    verified_at?: string
    // Was this marked as helpful?
    helpful_count: number
    not_helpful_count: number
    // Is this the accepted answer?
    is_accepted: boolean
    // Any follow-up or clarification needed
    needs_clarification?: string
    // Related resources/links
    resources?: {
        title: string
        url: string
        type: 'article' | 'document' | 'video' | 'tool'
    }[]
    // Suggested marketplace providers (if relevant)
    suggested_providers?: string[]
    created_at: string
    updated_at: string
}

// Input for generating an AI advisory answer
export interface GenerateAnswerInput {
    question_title: string
    question_body: string
    category?: AdvisoryCategory
    // Additional context about the foundry
    foundry_context?: {
        industry?: string
        stage?: string
        team_size?: number
        location?: string
    }
    // Previous conversation context
    previous_answers?: string[]
}

// Result from AI answer generation
export interface GenerateAnswerResult {
    answer: string
    confidence: ConfidenceLevel
    reasoning: string
    // Warnings or caveats
    caveats?: string[]
    // Suggested follow-up questions
    follow_up_questions?: string[]
    // Suggested category if not provided
    suggested_category?: AdvisoryCategory
    // Tags extracted from the question
    extracted_tags?: string[]
    // Whether this question should be escalated to a human expert
    needs_expert_review: boolean
    expert_review_reason?: string
    // Related marketplace categories for finding help
    marketplace_suggestions?: {
        category: string
        subcategory?: string
        search_term: string
    }[]
}

// Structured answer with sections
export interface StructuredAnswer {
    summary: string         // TL;DR
    detailed_answer: string // Full explanation
    action_items?: string[] // Specific steps to take
    considerations?: string[] // Things to keep in mind
    resources?: {
        title: string
        url?: string
        description: string
    }[]
    disclaimer?: string     // Legal/professional disclaimer
}

// FAQ item (commonly asked questions)
export interface FAQItem {
    id: string
    question: string
    answer: string
    category: AdvisoryCategory
    tags: string[]
    view_count: number
    helpful_count: number
    created_at: string
    updated_at: string
}

// Expert profile (for human experts who can verify/answer)
export interface AdvisoryExpert {
    id: string
    user_id: string
    name: string
    expertise_areas: AdvisoryCategory[]
    bio?: string
    credentials?: string[]
    verified_answers_count: number
    average_rating: number
    is_available: boolean
}

// Summary for dashboard/widget
export interface AdvisorySummary {
    total_questions: number
    open_questions: number
    answered_questions: number
    questions_needing_review: number
    recent_questions: {
        id: string
        title: string
        category: AdvisoryCategory
        status: string
        created_at: string
    }[]
    popular_categories: {
        category: AdvisoryCategory
        count: number
    }[]
}
