/**
 * Plan section types · Phase 3 Plan redesign · Chunk A.5
 *
 * Hand-written types for the 10 new Plan tables + their enum unions.
 * The canonical DB shape lives in `src/types/database.types.ts` (auto-
 * generated by `supabase gen types --linked`). That file is regenerated
 * by the Money terminal during parallel build — we do NOT touch it here.
 *
 * These hand-written types shadow the generated types for the Plan tables
 * so that Plan code can be written before the regeneration lands. Once
 * Money regenerates database.types.ts, the generated `Database['public']
 * ['Tables']['strategic_goals']['Row']` etc. become the source of truth
 * and these types can be re-exported from Database types, or kept as
 * narrower variants for server-action payloads / CTA tokens.
 *
 * Reference: PLAN-SCHEMA.md §§1–13 (tables), §14.6 (canonical CTA tokens),
 *            §16.1 (permissions matrix / PlanAction union).
 */

/* ──────────────────────────────────────────────────────────────────────────
 * 1 · Enum unions — mirror public.* enum types from 20260422000000_plan_enums
 * ────────────────────────────────────────────────────────────────────────── */

export type GoalState =
  | 'draft'
  | 'active'
  | 'at_risk'
  | 'off_track'
  | 'on_track'
  | 'killed'
  | 'pivoted'
  | 'completed';

export type AssumptionState =
  | 'holding'
  | 'slipping'
  | 'broken'
  | 'unknown';

export type FractionalSpecialisation =
  | 'fundraising'
  | 'legal'
  | 'cto'
  | 'people'
  | 'cfo'
  | 'marketing'
  | 'product'
  | 'sales'
  | 'operations'
  | 'advisory'
  | 'other';

export type EngagementStatus =
  | 'pending_accept'
  | 'active'
  | 'ended'
  | 'on_hold';

export type WorkingStyle = 'proactive' | 'responsive' | 'blended';

export type AssigneeType = 'user' | 'fractional' | 'specialist' | 'observer';

export type HistoryEntryType =
  | 'decision'
  | 'pressure_test'
  | 'update_sent'
  | 'goal_pinned'
  | 'goal_state_changed'
  | 'specialist_rec_accepted'
  | 'specialist_rec_rejected'
  | 'gutcheck_outcome'
  | 'manual';

export type ActorType = 'founder' | 'fractional' | 'specialist' | 'system';

export type OutcomeState = 'positive' | 'negative' | 'pending' | 'neutral';

export type PressureSubjectType =
  | 'goal'
  | 'objective'
  | 'report_draft'
  | 'custom';

export type PressureVerdict =
  | 'proceed'
  | 'proceed_with_mitigations'
  | 'pivot'
  | 'kill'
  | 'inconclusive';

export type GutcheckDecision =
  | 'kill'
  | 'pivot'
  | 'double_down'
  | 'dismissed'
  | 'expired';

export type ReportTarget =
  | 'weekly_team'
  | 'monthly_investor'
  | 'quarterly_board'
  | 'custom';

export type ReportDraftBy = 'cal' | 'founder';

export type RecContextType =
  | 'goal'
  | 'objective'
  | 'task'
  | 'gutcheck'
  | 'pressure_test'
  | 'report';

export type RecConfidence = 'low' | 'medium' | 'high' | 'very_high';

export type RecStatus =
  | 'pending'
  | 'accepted'
  | 'edited_accepted'
  | 'rejected'
  | 'ignored'
  | 'expired';

/* ──────────────────────────────────────────────────────────────────────────
 * 2 · Supporting utility types
 * ────────────────────────────────────────────────────────────────────────── */

type UUID = string;
type ISODate = string; // YYYY-MM-DD (Postgres `date`)
type ISODateTime = string; // Postgres timestamptz
type JsonValue =
  | string
  | number
  | boolean
  | null
  | JsonValue[]
  | { [key: string]: JsonValue };

type GoalTeamRoleOnGoal = 'lead' | 'supporting' | 'reviewer' | 'observer';
type DisproveRefreshedBy = 'auto_specialist' | 'founder' | 'gutcheck';
type GutcheckTriggeredBy = 'cron_week6' | 'manual' | 'calendar';
type TaskHorizon = 'this_week' | 'this_month' | 'later' | 'done';
type ReportSentVia = 'email' | 'slack' | 'link';

/* ──────────────────────────────────────────────────────────────────────────
 * 3 · Row types — 10 new Plan tables (PLAN-SCHEMA §§1–13)
 * ────────────────────────────────────────────────────────────────────────── */

/** §1 · strategic_goals */
export interface StrategicGoalRow {
  id: UUID;
  foundry_id: string;
  title: string;
  description: string | null;
  state: GoalState;
  is_pinned: boolean;
  pin_order: number | null;
  quarter: string;
  milestone_date: ISODate;
  started_at: ISODate | null;
  lead_user_id: UUID | null;
  lead_fractional_id: UUID | null;
  lead_specialist_slug: string | null;
  purpose_connection: string | null;
  state_overridden_until: ISODateTime | null;
  source_objective_id: UUID | null;
  created_by: UUID;
  created_at: ISODateTime;
  updated_at: ISODateTime;
  deleted_at: ISODateTime | null;
}

export type StrategicGoalInsert = Omit<
  StrategicGoalRow,
  'id' | 'created_at' | 'updated_at' | 'deleted_at'
> & {
  id?: UUID;
  created_at?: ISODateTime;
  updated_at?: ISODateTime;
  deleted_at?: ISODateTime | null;
};

export type StrategicGoalUpdate = Partial<
  Omit<StrategicGoalRow, 'id' | 'foundry_id' | 'created_at' | 'created_by'>
>;

/** §2 · disprove_assumptions */
export interface DisproveAssumptionRow {
  id: UUID;
  foundry_id: string;
  goal_id: UUID;
  order_index: number;
  assumption: string;
  current_state: AssumptionState;
  last_refreshed_at: ISODateTime | null;
  refreshed_by: DisproveRefreshedBy | null;
  fresh_data_json: JsonValue | null;
  created_at: ISODateTime;
  updated_at: ISODateTime;
}

export type DisproveAssumptionInsert = Omit<
  DisproveAssumptionRow,
  'id' | 'created_at' | 'updated_at'
> & { id?: UUID };

export type DisproveAssumptionUpdate = Partial<
  Omit<DisproveAssumptionRow, 'id' | 'foundry_id' | 'goal_id' | 'created_at'>
>;

/** §6 · fractional_executives */
export interface FractionalExecutiveRow {
  id: UUID;
  user_id: UUID | null;
  display_name: string;
  email: string;
  specialisation: FractionalSpecialisation;
  bio_short: string | null;
  bio_long: string | null;
  avatar_gradient: string | null;
  network_listed: boolean;
  default_retainer_monthly: number | null;
  default_hours_weekly: number | null;
  response_time_avg_hours: number | null;
  reply_rate: number | null;
  created_at: ISODateTime;
  updated_at: ISODateTime;
}

export type FractionalExecutiveInsert = Omit<
  FractionalExecutiveRow,
  'id' | 'created_at' | 'updated_at'
> & { id?: UUID };

export type FractionalExecutiveUpdate = Partial<
  Omit<FractionalExecutiveRow, 'id' | 'email' | 'created_at'>
>;

/** §7 · fractional_engagements */
export interface FractionalEngagementRow {
  id: UUID;
  foundry_id: string;
  fractional_id: UUID;
  role_in_foundry: string;
  hours_per_week: number;
  hours_used_this_week: number;
  retainer_monthly: number;
  started_on: ISODate;
  ended_on: ISODate | null;
  status: EngagementStatus;
  working_style: WorkingStyle;
  notice_period_days: number;
  created_at: ISODateTime;
  updated_at: ISODateTime;
}

export type FractionalEngagementInsert = Omit<
  FractionalEngagementRow,
  'id' | 'created_at' | 'updated_at'
> & { id?: UUID };

export type FractionalEngagementUpdate = Partial<
  Omit<FractionalEngagementRow, 'id' | 'foundry_id' | 'fractional_id' | 'created_at'>
>;

/** §8 · goal_team_assignments */
export interface GoalTeamAssignmentRow {
  id: UUID;
  foundry_id: string;
  goal_id: UUID;
  assignee_type: AssigneeType;
  user_id: UUID | null;
  fractional_id: UUID | null;
  specialist_slug: string | null;
  role_on_goal: GoalTeamRoleOnGoal;
  added_at: ISODateTime;
  added_by: UUID;
  created_at: ISODateTime;
  updated_at: ISODateTime;
}

export type GoalTeamAssignmentInsert = Omit<
  GoalTeamAssignmentRow,
  'id' | 'added_at' | 'created_at' | 'updated_at'
> & { id?: UUID; added_at?: ISODateTime };

export type GoalTeamAssignmentUpdate = Partial<
  Omit<GoalTeamAssignmentRow, 'id' | 'foundry_id' | 'goal_id' | 'created_at'>
>;

/** §9 · history_entries — edit_log_json append-only (§17.5) */
export interface HistoryEntryEditLogItem {
  at: ISODateTime;
  by: UUID | null;
  from: string | null;
  to: string | null;
  field: 'body' | 'outcome' | 'outcome_note' | string;
}

export interface HistoryEntryRow {
  id: UUID;
  foundry_id: string;
  entry_type: HistoryEntryType;
  title: string;
  body: string | null;
  actor_type: ActorType;
  actor_id: string | null;
  goal_id: UUID | null;
  related_ids_json: {
    objective_ids?: UUID[];
    task_ids?: UUID[];
    pressure_test_id?: UUID;
    rec_id?: UUID;
    gutcheck_id?: UUID;
    [key: string]: JsonValue | undefined;
  } | null;
  outcome: OutcomeState | null;
  outcome_note: string | null;
  outcome_revisit_at: ISODateTime | null;
  alternatives_json: Array<{ name: string; why_rejected: string }> | null;
  grounding_text: string | null;
  edit_log_json: HistoryEntryEditLogItem[];
  created_at: ISODateTime;
  updated_at: ISODateTime;
}

export type HistoryEntryInsert = Omit<
  HistoryEntryRow,
  'id' | 'edit_log_json' | 'created_at' | 'updated_at'
> & { id?: UUID; edit_log_json?: HistoryEntryEditLogItem[] };

export type HistoryEntryUpdate = Partial<
  Omit<HistoryEntryRow, 'id' | 'foundry_id' | 'created_at'>
>;

/** §10 · pressure_test_sessions */
export interface PressureTranscriptMessage {
  persona: string;
  round: number;
  content: string;
  at: ISODateTime;
}

export interface PressureTestSessionRow {
  id: UUID;
  foundry_id: string;
  goal_id: UUID | null;
  subject_type: PressureSubjectType;
  subject_ref: UUID | null;
  subject_snapshot: JsonValue;
  personas_used: string[];
  human_reviewers_json: Array<{ user_id: UUID; display_name: string }> | null;
  rounds: number;
  transcript_json: PressureTranscriptMessage[];
  tensions_json: JsonValue | null;
  verdict: PressureVerdict | null;
  verdict_body: string | null;
  recommended_actions_json: Array<{ title: string; owner_hint?: string }> | null;
  legacy_report_snapshot_id: UUID | null;
  created_at: ISODateTime;
  updated_at: ISODateTime;
}

export type PressureTestSessionInsert = Omit<
  PressureTestSessionRow,
  'id' | 'created_at' | 'updated_at'
> & { id?: UUID };

export type PressureTestSessionUpdate = Partial<
  Omit<PressureTestSessionRow, 'id' | 'foundry_id' | 'created_at'>
>;

/** §11 · gutcheck_sessions */
export interface GutcheckAssumptionStateSnapshot {
  assumption_id: UUID;
  assumption: string;
  state_at_fire: AssumptionState;
}

export interface GutcheckSessionRow {
  id: UUID;
  foundry_id: string;
  goal_id: UUID;
  fired_at: ISODateTime;
  triggered_by: GutcheckTriggeredBy;
  assumption_states_json: GutcheckAssumptionStateSnapshot[];
  cal_narrative: string | null;
  human_narrative: string | null;
  decision: GutcheckDecision | null;
  decision_note: string | null;
  decided_at: ISODateTime | null;
  created_at: ISODateTime;
  updated_at: ISODateTime;
}

export type GutcheckSessionInsert = Omit<
  GutcheckSessionRow,
  'id' | 'created_at' | 'updated_at'
> & { id?: UUID };

export type GutcheckSessionUpdate = Partial<
  Omit<GutcheckSessionRow, 'id' | 'foundry_id' | 'goal_id' | 'created_at'>
>;

/** §12 · reports_sent */
export interface ReportRecipient {
  email: string;
  name?: string;
  to_cc_bcc: 'to' | 'cc' | 'bcc';
}

export interface ReportPulledFrom {
  goal_ids?: UUID[];
  task_ids?: UUID[];
  history_entry_ids?: UUID[];
}

export interface ReportsSentRow {
  id: UUID;
  foundry_id: string;
  target_type: ReportTarget;
  subject_line: string;
  body_html: string | null;
  body_markdown: string | null;
  pulled_from_json: ReportPulledFrom;
  recipients_json: ReportRecipient[];
  sent_via: ReportSentVia[];
  sent_at: ISODateTime;
  pressure_tested_before_send: boolean;
  pressure_test_session_id: UUID | null;
  draft_by: ReportDraftBy;
  edits_count: number;
  external_share_url: string | null;
  link_expires_at: ISODateTime | null;
  open_count: number;
  reply_count: number;
  legacy_report_snapshot_id: UUID | null;
  created_at: ISODateTime;
  updated_at: ISODateTime;
}

export type ReportsSentInsert = Omit<
  ReportsSentRow,
  'id' | 'created_at' | 'updated_at' | 'open_count' | 'reply_count' | 'edits_count'
> & {
  id?: UUID;
  open_count?: number;
  reply_count?: number;
  edits_count?: number;
};

export type ReportsSentUpdate = Partial<
  Omit<ReportsSentRow, 'id' | 'foundry_id' | 'created_at'>
>;

/** §13 · specialist_recommendations */
export interface SpecialistRecommendationRow {
  id: UUID;
  foundry_id: string;
  specialist_slug: string;
  context_type: RecContextType;
  context_ref: UUID | null;
  summary: string;
  body: string;
  grounding_text: string;
  confidence: RecConfidence;
  status: RecStatus;
  expires_at: ISODateTime | null;
  durable: boolean;
  responded_at: ISODateTime | null;
  responded_note: string | null;
  created_at: ISODateTime;
  updated_at: ISODateTime;
}

export type SpecialistRecommendationInsert = Omit<
  SpecialistRecommendationRow,
  'id' | 'created_at' | 'updated_at'
> & { id?: UUID };

export type SpecialistRecommendationUpdate = Partial<
  Omit<SpecialistRecommendationRow, 'id' | 'foundry_id' | 'created_at'>
>;

/* ──────────────────────────────────────────────────────────────────────────
 * 4 · Additive columns on legacy tables (PLAN-SCHEMA §3, §4, §A.5)
 *     — typed here so Plan code reads them without waiting on the generated
 *       database.types.ts regeneration.
 * ────────────────────────────────────────────────────────────────────────── */

export interface ObjectivesPlanColumns {
  strategic_goal_id: UUID | null;
}

export interface TasksPlanColumns {
  strategic_goal_id: UUID | null;
  is_draft: boolean;
  is_pinned: boolean;
  horizon: TaskHorizon | null;
  origin: string | null;
  origin_ref: string | null;
}

export interface TaskAssigneesPlanColumns {
  fractional_id: UUID | null;
}

export type { TaskHorizon };

/* ──────────────────────────────────────────────────────────────────────────
 * 5 · Canonical CTA tokens (PLAN-SCHEMA §14.6)
 *     Never write raw `/plan/...` hrefs into event_log.cta_href — store
 *     a `plan:<entity>:<id>[?key=value]` token and resolve client-side
 *     per the user's new_plan_experience flag state.
 * ────────────────────────────────────────────────────────────────────────── */

/** Plan CTA entity type — the second segment of the canonical token. */
export type PlanCtaEntity =
  | 'goal'
  | 'task'
  | 'objective'
  | 'rec'
  | 'report'
  | 'history'
  | 'team'
  | 'gutcheck'
  | 'pressure_test';

/**
 * Broad template literal type for any plan CTA token. Narrower helpers
 * below model the common cases.
 *
 * Format: `plan:<entity>:<id>[?key=value[&key=value]*]`
 * Examples:
 *   `plan:goal:abc-123`
 *   `plan:goal:abc-123?modal=pressure-test`
 *   `plan:goal:abc-123?gutcheck=jkl-012`
 *   `plan:task:def-456`
 *   `plan:rec:ghi-789`
 *   `plan:team:frac-999`
 *   `plan:history:xyz-000`
 *   `plan:report:rep-111`
 */
export type PlanCtaToken = `plan:${string}:${string}`;

/** Narrower entity-scoped tokens — useful for switch/case on event readers. */
export type PlanGoalCtaToken = `plan:goal:${string}`;
export type PlanTaskCtaToken = `plan:task:${string}`;
export type PlanObjectiveCtaToken = `plan:objective:${string}`;
export type PlanRecCtaToken = `plan:rec:${string}`;
export type PlanReportCtaToken = `plan:report:${string}`;
export type PlanHistoryCtaToken = `plan:history:${string}`;
export type PlanTeamCtaToken = `plan:team:${string}`;
export type PlanGutcheckCtaToken = `plan:goal:${string}?gutcheck=${string}`;
export type PlanPressureTestCtaToken = `plan:goal:${string}?modal=pressure-test`;

/** Parsed form of a CTA token — what the route resolver emits. */
export interface ParsedPlanCta {
  raw: PlanCtaToken;
  section: 'plan';
  entity: PlanCtaEntity;
  id: string;
  params: Record<string, string>;
}

/* ──────────────────────────────────────────────────────────────────────────
 * 6 · PlanAction — the permissions-matrix action union (§16.1)
 *     Mirrors plan_can()'s `p_action` parameter values exactly.
 * ────────────────────────────────────────────────────────────────────────── */

export type PlanAction =
  // Plan workspace
  | 'view_plan_workspace'
  // Strategic Goals
  | 'create_strategic_goal'
  | 'edit_strategic_goal'
  | 'pin_strategic_goal'
  | 'kill_strategic_goal'
  | 'pivot_strategic_goal'
  | 'set_goal_state_manual'
  | 'edit_disprove_assumption'
  // Objectives / Tasks
  | 'create_objective'
  | 'edit_objective'
  | 'create_task'
  | 'assign_task_self'
  | 'assign_task_others'
  | 'close_own_task'
  | 'delete_task'
  // Fractional team
  | 'invite_fractional'
  | 'end_engagement'
  | 'set_capacity_retainer'
  // Gutcheck / Pressure-test
  | 'decide_gutcheck'
  | 'start_pressure_test'
  | 'close_pressure_test'
  // Report
  | 'draft_report'
  | 'edit_report_draft'
  | 'send_report'
  | 'view_sent_reports'
  // History
  | 'view_history'
  | 'add_manual_history'
  | 'mark_history_outcome'
  // Settings
  | 'change_nudge_frequency'
  | 'change_specialist_behaviour'
  | 'manage_permissions';

/* ──────────────────────────────────────────────────────────────────────────
 * 7 · Discriminated union shortcuts — useful for server-action returns
 * ────────────────────────────────────────────────────────────────────────── */

export type PlanTable =
  | 'strategic_goals'
  | 'disprove_assumptions'
  | 'fractional_executives'
  | 'fractional_engagements'
  | 'goal_team_assignments'
  | 'history_entries'
  | 'pressure_test_sessions'
  | 'gutcheck_sessions'
  | 'reports_sent'
  | 'specialist_recommendations';
