/**
 * @file cad-lab-review-package.tsx — Engineering review summary document.
 *
 * @description Generates a read-only engineering review document from all
 * project data: modules, analysis metrics, timeline, risks, and diagnostics.
 * Designed for sharing with stakeholders or printing as a PDF-ready summary.
 *
 * @component
 *
 * @example
 * <CadLabReviewPackage
 *   modules={modules}
 *   projectName={subject}
 *   researchReport={editableReport}
 *   diagnosticAnswers={diagnosticAnswers}
 * />
 */

"use client"

import { useMemo, useRef } from "react"
import {
  FileText,
  Printer,
  Box,
  Scale,
  Ruler,
  Clock,
  AlertTriangle,
  HelpCircle,
  CheckCircle2,
  ShieldAlert,
  Copy,
} from "lucide-react"

import { Button } from "@/components/ui/button"
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card"
import { cn } from "@/lib/utils"
import { toast } from "sonner"
import type { CadLabModule } from "@/lib/cad-lab-types"
import type { DiagnosticAnswers } from "./cad-lab-diagnostics"

// ─── Types ──────────────────────────────────────────────────────────

interface CadLabReviewPackageProps {
  /** Array of decomposed modules */
  modules: CadLabModule[]
  /** Project subject/name */
  projectName: string
  /** Research report text (from Step 1) */
  researchReport?: string
  /** Diagnostic answers per module */
  diagnosticAnswers?: DiagnosticAnswers
}

// ─── Helpers ────────────────────────────────────────────────────────

/**
 * Generates a plain-text review summary for clipboard/print.
 *
 * @param modules - Project modules
 * @param projectName - Project name
 * @param diagnosticAnswers - Diagnostic answers
 * @returns Formatted plain text
 */
function generatePlainText(
  modules: CadLabModule[],
  projectName: string,
  diagnosticAnswers?: DiagnosticAnswers
): string {
  const lines: string[] = []
  const now = new Date().toLocaleDateString("en-GB", {
    day: "numeric",
    month: "long",
    year: "numeric",
  })

  lines.push(`ENGINEERING REVIEW PACKAGE`)
  lines.push(`${"=".repeat(50)}`)
  lines.push(`Project: ${projectName}`)
  lines.push(`Date: ${now}`)
  lines.push(`Modules: ${modules.length}`)
  lines.push("")

  // System metrics
  let totalMassG = 0
  let generated = 0
  let totalRisks = 0
  let totalUnknowns = 0

  for (const mod of modules) {
    totalRisks += mod.failureModes.length
    totalUnknowns += mod.unknowns.length
    if (mod.result?.massGrams) totalMassG += mod.result.massGrams
    if (mod.status === "generated") generated++
  }

  lines.push(`SUMMARY`)
  lines.push(`${"-".repeat(30)}`)
  lines.push(`Generated: ${generated}/${modules.length} modules`)
  lines.push(`Total mass: ${totalMassG > 0 ? `${(totalMassG / 1000).toFixed(2)} kg` : "TBD"}`)
  lines.push(`Failure modes: ${totalRisks}`)
  lines.push(`Unknowns: ${totalUnknowns}`)
  lines.push("")

  // Per module
  for (const mod of modules) {
    lines.push(`MODULE: ${mod.name.toUpperCase()}`)
    lines.push(`${"-".repeat(30)}`)
    lines.push(`Purpose: ${mod.purpose}`)
    lines.push(`Status: ${mod.status}`)
    lines.push(`Lead time: ${mod.leadWeeks} weeks`)
    lines.push(`Key parts: ${mod.keyParts.join(", ")}`)

    if (mod.result?.bbox) {
      lines.push(
        `Dimensions: ${mod.result.bbox.xLen.toFixed(0)}×${mod.result.bbox.yLen.toFixed(0)}×${mod.result.bbox.zLen.toFixed(0)} mm`
      )
    }
    if (mod.result?.massGrams) {
      lines.push(`Mass: ${mod.result.massGrams.toFixed(1)} g`)
    }
    if (mod.result?.dfm) {
      lines.push(`Printable: ${mod.result.dfm.printable ? "Yes" : "No"}`)
      if (mod.result.dfm.issues.length > 0) {
        lines.push(`DFM Issues:`)
        for (const issue of mod.result.dfm.issues) {
          lines.push(`  - [${issue.severity}] ${issue.message}`)
        }
      }
    }

    if (mod.failureModes.length > 0) {
      lines.push(`Failure Modes:`)
      for (const fm of mod.failureModes) lines.push(`  - ${fm}`)
    }
    if (mod.unknowns.length > 0) {
      lines.push(`Unknowns:`)
      for (const u of mod.unknowns) lines.push(`  ? ${u}`)
    }

    // Diagnostics
    const modDiag = diagnosticAnswers?.[mod.id]
    if (modDiag && Object.keys(modDiag).length > 0) {
      lines.push(`Diagnostics:`)
      for (const [key, val] of Object.entries(modDiag)) {
        lines.push(`  ${key}: ${val}`)
      }
    }

    lines.push("")
  }

  lines.push(`${"=".repeat(50)}`)
  lines.push(`Generated by The Forge — ForgeOS`)

  return lines.join("\n")
}

// ─── Component ──────────────────────────────────────────────────────

/**
 * CadLabReviewPackage — engineering review summary document.
 *
 * @description Renders a printable review package with system-level
 * metrics, per-module summaries, risk overview, and diagnostic status.
 * Includes copy-to-clipboard and print actions.
 */
export function CadLabReviewPackage({
  modules,
  projectName,
  researchReport,
  diagnosticAnswers,
}: CadLabReviewPackageProps): React.ReactNode {
  const reviewRef = useRef<HTMLDivElement>(null)

  // Aggregate metrics
  const metrics = useMemo(() => {
    let totalMassG = 0
    let totalVolumeMm3 = 0
    let generated = 0
    let printable = 0
    let totalRisks = 0
    let totalUnknowns = 0
    let maxLeadWeeks = 0

    for (const mod of modules) {
      maxLeadWeeks = Math.max(maxLeadWeeks, mod.leadWeeks)
      totalRisks += mod.failureModes.length
      totalUnknowns += mod.unknowns.length

      if (mod.status === "generated" && mod.result) {
        generated++
        if (mod.result.massGrams) totalMassG += mod.result.massGrams
        if (mod.result.volumeMm3) totalVolumeMm3 += mod.result.volumeMm3
        if (mod.result.dfm?.printable) printable++
      }
    }

    return {
      totalMassG,
      totalVolumeMm3,
      generated,
      printable,
      totalRisks,
      totalUnknowns,
      maxLeadWeeks,
    }
  }, [modules])

  const handleCopy = async (): Promise<void> => {
    const text = generatePlainText(modules, projectName, diagnosticAnswers)
    await navigator.clipboard.writeText(text)
    toast.success("Review package copied to clipboard")
  }

  const handlePrint = (): void => {
    window.print()
  }

  const dateStr = new Date().toLocaleDateString("en-GB", {
    day: "numeric",
    month: "long",
    year: "numeric",
  })

  return (
    <Card>
      <CardHeader>
        <div className="flex items-center justify-between">
          <CardTitle className="text-base flex items-center gap-2">
            <FileText className="h-4 w-4" />
            Review Package
            <span className="text-xs font-normal text-muted-foreground">
              {dateStr}
            </span>
          </CardTitle>
          <div className="flex items-center gap-2">
            <Button variant="outline" size="sm" onClick={handleCopy}>
              <Copy className="h-3.5 w-3.5 mr-1.5" />
              Copy
            </Button>
            <Button variant="outline" size="sm" onClick={handlePrint}>
              <Printer className="h-3.5 w-3.5 mr-1.5" />
              Print
            </Button>
          </div>
        </div>
      </CardHeader>
      <CardContent className="space-y-6" ref={reviewRef}>
        {/* Project header */}
        <div className="border-b pb-4">
          <h2 className="text-lg font-semibold text-foreground">
            {projectName}
          </h2>
          <p className="text-sm text-muted-foreground">
            Engineering Review — {modules.length} modules,{" "}
            {metrics.generated} with CAD generated
          </p>
        </div>

        {/* System metrics grid */}
        <div className="grid grid-cols-2 md:grid-cols-4 gap-4">
          <ReviewMetric
            icon={<Scale className="h-3.5 w-3.5" />}
            label="System Mass"
            value={
              metrics.totalMassG > 0
                ? `${(metrics.totalMassG / 1000).toFixed(2)} kg`
                : "TBD"
            }
          />
          <ReviewMetric
            icon={<Box className="h-3.5 w-3.5" />}
            label="Modules"
            value={`${metrics.generated}/${modules.length} generated`}
          />
          <ReviewMetric
            icon={<Clock className="h-3.5 w-3.5" />}
            label="Critical Path"
            value={`${metrics.maxLeadWeeks} weeks`}
          />
          <ReviewMetric
            icon={<ShieldAlert className="h-3.5 w-3.5" />}
            label="Open Risks"
            value={`${metrics.totalRisks + metrics.totalUnknowns}`}
            highlight={metrics.totalRisks > 0}
          />
        </div>

        {/* Per-module summaries */}
        <div className="space-y-4">
          <h3 className="text-sm font-semibold text-foreground uppercase tracking-wider">
            Module Summaries
          </h3>
          {modules.map((mod) => {
            const modDiag = diagnosticAnswers?.[mod.id]
            const diagComplete =
              modDiag && Object.keys(modDiag).length >= 6

            return (
              <div
                key={mod.id}
                className="border rounded-lg p-4 space-y-3"
              >
                {/* Module header */}
                <div className="flex items-center justify-between">
                  <div className="flex items-center gap-2">
                    <div
                      className={cn(
                        "h-2 w-2 rounded-full",
                        mod.status === "generated"
                          ? "bg-status-success"
                          : mod.status === "interface_ready"
                            ? "bg-status-info"
                            : "bg-muted-foreground"
                      )}
                    />
                    <h4 className="text-sm font-semibold text-foreground">
                      {mod.name}
                    </h4>
                  </div>
                  <div className="flex items-center gap-2 text-[10px] text-muted-foreground">
                    <span>{mod.leadWeeks}w lead</span>
                    <span>{mod.keyParts.length} parts</span>
                    <span
                      className={cn(
                        "px-1.5 py-0.5 rounded-full",
                        mod.status === "generated"
                          ? "bg-status-success-light text-status-success"
                          : "bg-muted text-muted-foreground"
                      )}
                    >
                      {mod.status}
                    </span>
                  </div>
                </div>

                {/* SVG thumbnail for generated modules */}
                {mod.status === "generated" && mod.result?.svgIso && (
                  <div className="w-full h-20 rounded-md bg-muted/30 border border-muted overflow-hidden">
                    {/* eslint-disable-next-line @next/next/no-img-element */}
                    <img
                      src={mod.result.svgIso}
                      alt={`${mod.name} isometric view`}
                      className="w-full h-full object-contain"
                    />
                  </div>
                )}

                {/* Purpose and description */}
                <p className="text-xs text-muted-foreground">
                  {mod.purpose}
                </p>

                {/* Metrics row (if generated) */}
                {mod.result && (
                  <div className="flex flex-wrap items-center gap-4 text-xs">
                    {mod.result.bbox && (
                      <span className="flex items-center gap-1 text-foreground">
                        <Ruler className="h-3 w-3 text-muted-foreground" />
                        {mod.result.bbox.xLen.toFixed(0)}×
                        {mod.result.bbox.yLen.toFixed(0)}×
                        {mod.result.bbox.zLen.toFixed(0)} mm
                      </span>
                    )}
                    {mod.result.massGrams && (
                      <span className="flex items-center gap-1 text-foreground">
                        <Scale className="h-3 w-3 text-muted-foreground" />
                        {mod.result.massGrams.toFixed(1)} g
                      </span>
                    )}
                    {mod.result.dfm && (
                      <span
                        className={cn(
                          "flex items-center gap-1",
                          mod.result.dfm.printable
                            ? "text-status-success"
                            : "text-status-warning"
                        )}
                      >
                        {mod.result.dfm.printable ? (
                          <CheckCircle2 className="h-3 w-3" />
                        ) : (
                          <AlertTriangle className="h-3 w-3" />
                        )}
                        {mod.result.dfm.printable
                          ? "Printable"
                          : `${mod.result.dfm.issues.length} DFM issues`}
                      </span>
                    )}
                  </div>
                )}

                {/* Risks and unknowns summary */}
                {(mod.failureModes.length > 0 ||
                  mod.unknowns.length > 0) && (
                  <div className="flex items-center gap-3 text-[10px]">
                    {mod.failureModes.length > 0 && (
                      <span className="flex items-center gap-1 text-status-warning">
                        <AlertTriangle className="h-3 w-3" />
                        {mod.failureModes.length} failure mode
                        {mod.failureModes.length !== 1 ? "s" : ""}
                      </span>
                    )}
                    {mod.unknowns.length > 0 && (
                      <span className="flex items-center gap-1 text-status-info">
                        <HelpCircle className="h-3 w-3" />
                        {mod.unknowns.length} unknown
                        {mod.unknowns.length !== 1 ? "s" : ""}
                      </span>
                    )}
                    {diagComplete && (
                      <span className="flex items-center gap-1 text-status-success">
                        <CheckCircle2 className="h-3 w-3" />
                        Diagnosed
                      </span>
                    )}
                  </div>
                )}

                {/* Diagnostic answers (if any) */}
                {modDiag && Object.keys(modDiag).length > 0 && (
                  <div className="flex flex-wrap gap-1.5">
                    {Object.entries(modDiag).map(([key, val]) => (
                      <span
                        key={key}
                        className="text-[10px] bg-muted px-2 py-0.5 rounded font-mono"
                      >
                        {val}
                      </span>
                    ))}
                  </div>
                )}
              </div>
            )
          })}
        </div>

        {/* Footer */}
        <div className="border-t pt-4 text-[10px] text-muted-foreground text-center">
          Generated by The Forge — ForgeOS — {dateStr}
        </div>
      </CardContent>
    </Card>
  )
}

// ─── Sub-components ─────────────────────────────────────────────────

/**
 * ReviewMetric — compact metric card for the review summary.
 */
function ReviewMetric({
  icon,
  label,
  value,
  highlight,
}: {
  icon: React.ReactNode
  label: string
  value: string
  highlight?: boolean
}): React.ReactNode {
  return (
    <div className="p-3 rounded-lg bg-muted/50 space-y-1">
      <p className="text-[10px] text-muted-foreground flex items-center gap-1.5 uppercase tracking-wider">
        {icon}
        {label}
      </p>
      <p
        className={cn(
          "text-sm font-semibold font-mono",
          highlight ? "text-status-warning" : "text-foreground"
        )}
      >
        {value}
      </p>
    </div>
  )
}
