/**
 * @file forge/demos/page.tsx — /forge/demos index.
 *
 * @description Public listing of the five Forge demo project packs. Each card
 * shows the cover render, the spelled-out project name, a brief description,
 * the cost envelope, and a link to the per-demo detail page at
 * /forge/demos/<slug>. No login required.
 *
 * This page is the discoverable landing for founders who want to see what a
 * finished Forge project pack looks like before they start their own. The
 * "Start your own project" call-to-action below the grid routes to
 * /signup?from=forge-demos&plan=starter_v2.
 *
 * @security Public — no auth check. All data is static.
 */

import type { Metadata } from "next"
import Link from "next/link"
import Image from "next/image"
import { ArrowRight } from "lucide-react"

import { FORGE_DEMOS, type ForgeDemo } from "@/lib/forge/demo-projects"
import { Card, CardContent } from "@/components/ui/card"
import { Button } from "@/components/ui/button"
import { cn } from "@/lib/utils"

export const metadata: Metadata = {
  title: "Forge Demo Projects",
  description:
    "Five real Forge project packs — battery energy storage system, high-altitude pseudo-satellite, modular vertical farm, containerised seawater desalination, and garden bird feeder. Read the full sixty-page plans before you start your own.",
  openGraph: {
    title: "Forge Demo Projects",
    description:
      "Five real hardware project packs generated by the Forge pipeline. Bill of materials, cost envelope, suppliers, failure modes — everything.",
    type: "website",
  },
}

export default function ForgeDemosIndexPage(): React.ReactNode {
  return (
    <div className="space-y-12">
      {/* ── Header ──────────────────────────────────────────────────────── */}
      <header className="space-y-4 pb-6 border-b border-border">
        <div className="flex items-center gap-3">
          <div className="h-8 w-1 rounded-full bg-international-orange" aria-hidden="true" />
          <h1 className="font-playfair text-3xl sm:text-4xl font-black text-foreground">
            Forge demo projects
          </h1>
        </div>
        <p className="text-base sm:text-lg text-muted-foreground max-w-3xl leading-relaxed">
          Five real project packs generated against the live Forge pipeline on
          25 April 2026. Each one covers brief, modules, bill of materials,
          supplier shortlist, failure modes, standards, cost envelope, and
          open questions. Two of the five came back over the declared cost
          ceiling. The system tells you — you decide.
        </p>
        <p className="text-sm text-muted-foreground">
          Generated with the same pipeline a £20 Starter account gets. No
          hand-crafted data, no cherry-picked results.
        </p>
      </header>

      {/* ── Demo grid ───────────────────────────────────────────────────── */}
      <section aria-labelledby="demo-grid-heading">
        <h2 id="demo-grid-heading" className="sr-only">
          Demo project packs
        </h2>
        <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6">
          {FORGE_DEMOS.map((demo) => (
            <DemoCard key={demo.slug} demo={demo} />
          ))}
        </div>
      </section>

      {/* ── CTA ─────────────────────────────────────────────────────────── */}
      <section
        aria-labelledby="demos-cta-heading"
        className="rounded-xl border border-border bg-muted/30 px-6 py-8 sm:px-8 sm:py-10 text-center space-y-4"
      >
        <h2
          id="demos-cta-heading"
          className="font-playfair text-xl sm:text-2xl font-black text-foreground"
        >
          Start your own project
        </h2>
        <p className="text-muted-foreground max-w-xl mx-auto leading-relaxed">
          Describe a paragraph — what you want to build, your target cost, how
          it ships. The Forge produces a first-pass plan like these in twenty
          minutes, then adds detail over the hours after.
        </p>
        <div className="flex flex-col sm:flex-row items-center justify-center gap-3">
          <Button
            asChild
            size="lg"
            className="gap-2 bg-international-orange hover:bg-international-orange/90 text-white min-w-[220px]"
          >
            <Link
              href="/signup?from=forge-demos&plan=starter_v2"
            >
              Start your own project
              <ArrowRight className="h-4 w-4" aria-hidden="true" />
            </Link>
          </Button>
          <Button asChild variant="ghost" size="lg">
            <Link href="/login">Already have an account</Link>
          </Button>
        </div>
      </section>
    </div>
  )
}

// ---------------------------------------------------------------------------
// DemoCard — compact card for the grid listing
// ---------------------------------------------------------------------------

function DemoCard({ demo }: { demo: ForgeDemo }): React.JSX.Element {
  const isOverBudget = demo.cost.headroomGbp < 0
  const pillToneClass = isOverBudget
    ? "bg-warning/10 text-warning border-warning/20"
    : "bg-success/10 text-success border-success/20"

  return (
    <Link
      href={`/forge/demos/${demo.slug}`}
      className="group block h-full"
      aria-label={`Read the ${demo.heading} project pack`}
    >
      <Card className="h-full overflow-hidden transition-all duration-200 hover:-translate-y-0.5 hover:shadow-md group-active:scale-[0.99]">
        {/* Cover render */}
        <div className="relative aspect-[3/4] w-full bg-muted overflow-hidden">
          <Image
            src={demo.coverPath}
            alt={`Cover render of the ${demo.heading} project pack`}
            fill
            sizes="(max-width: 768px) 100vw, (max-width: 1024px) 50vw, 33vw"
            className="object-cover object-top"
          />
        </div>

        <CardContent className="p-5 sm:p-6 flex flex-col gap-3">
          {/* Title + budget pill */}
          <div>
            <div className="flex items-start justify-between gap-2 flex-wrap mb-1.5">
              <h3 className="font-playfair text-lg font-black text-foreground leading-tight">
                {demo.heading}
                {demo.acronym ? (
                  <span className="font-sans font-normal text-sm text-muted-foreground">
                    {" "}
                    ({demo.acronym})
                  </span>
                ) : null}
              </h3>
              <span
                className={cn(
                  "inline-flex shrink-0 items-center px-2 py-0.5 rounded-full border text-[10px] font-mono uppercase tracking-widest",
                  pillToneClass,
                )}
              >
                {demo.cost.headroomLabel}
              </span>
            </div>
            <p className="text-xs sm:text-sm text-muted-foreground font-medium">
              {demo.subHeading}
            </p>
          </div>

          {/* Summary */}
          <p className="text-sm text-foreground leading-relaxed line-clamp-4">
            {demo.summary}
          </p>

          {/* Quick stats */}
          <dl className="grid grid-cols-3 gap-x-3 gap-y-2 pt-2 border-t border-border">
            <Stat label="Pages" value={demo.stats.pages} />
            <Stat label="Modules" value={demo.stats.modules} />
            <Stat label="Suppliers" value={demo.stats.suppliers} />
          </dl>

          {/* Read link */}
          <span className="inline-flex items-center gap-1.5 text-sm text-international-orange group-hover:text-international-orange/80 font-semibold transition-colors mt-1">
            Read the full pack
            <ArrowRight
              className="h-3.5 w-3.5 transition-transform duration-200 group-hover:translate-x-0.5"
              aria-hidden="true"
            />
          </span>
        </CardContent>
      </Card>
    </Link>
  )
}

// ---------------------------------------------------------------------------
// Stat — a single label + value cell in the stats grid
// ---------------------------------------------------------------------------

function Stat({
  label,
  value,
}: {
  label: string
  value: number | string
}): React.JSX.Element {
  return (
    <div className="flex flex-col">
      <dt className="text-[10px] uppercase tracking-widest font-mono text-muted-foreground">
        {label}
      </dt>
      <dd className="text-sm font-bold text-foreground">{value}</dd>
    </div>
  )
}
