/**
 * @file export-design-report-pptx.ts
 *
 * @description Exports a Design Report as a branded .pptx PowerPoint
 * presentation. Slides: cover, executive summary, research highlights,
 * module overview table, per-module detail slides, specs, and costs.
 *
 * @related
 * - src/lib/cad-lab/design-report-types.ts — DesignReportData shape
 * - src/lib/reports/export-pptx.ts — Pattern reference (brand constants, slide builders)
 */

import PptxGenJS from 'pptxgenjs'

import type { DesignReportData } from '@/lib/cad-lab/design-report-types'

// ─── Brand Constants ────────────────────────────────────────────────

const ORANGE = 'FF4500'
const DARK_TEXT = '1E293B'
const MID_TEXT = '64748B'
const LIGHT_BG = 'F8FAFC'
const WHITE = 'FFFFFF'

// ─── Helpers ────────────────────────────────────────────────────────

function addSectionTitle(slide: PptxGenJS.Slide, title: string): void {
  slide.addText(title, {
    x: 0.6,
    y: 0.35,
    w: 10,
    h: 0.5,
    fontSize: 24,
    fontFace: 'Helvetica Neue',
    bold: true,
    color: DARK_TEXT,
  })
  slide.addShape('rect', {
    x: 0.6,
    y: 0.85,
    w: 1.2,
    h: 0.04,
    fill: { color: ORANGE },
  })
}

async function fetchImageAsBase64(url: string): Promise<string | null> {
  try {
    const controller = new AbortController()
    const timeout = setTimeout(() => controller.abort(), 10_000)
    const response = await fetch(url, { signal: controller.signal })
    clearTimeout(timeout)
    if (!response.ok) return null
    const blob = await response.blob()
    return await new Promise<string>((resolve) => {
      const reader = new FileReader()
      reader.onloadend = () => resolve(reader.result as string)
      reader.readAsDataURL(blob)
    })
  } catch {
    return null
  }
}

// ─── Diagnostic key labels ──────────────────────────────────────────

const DIAG_KEYS = ['mfg_process', 'material', 'tolerance', 'finish', 'batch_size'] as const
const DIAG_LABELS: Record<string, string> = {
  mfg_process: 'Process',
  material: 'Material',
  tolerance: 'Tolerance',
  finish: 'Finish',
  batch_size: 'Batch',
}

// ─── Public API ─────────────────────────────────────────────────────

/**
 * @description Generate a branded PowerPoint presentation from design report
 * data and trigger a browser download.
 */
export async function exportDesignReportAsPPTX(data: DesignReportData): Promise<void> {
  const pres = new PptxGenJS()
  pres.layout = 'LAYOUT_16x9'
  pres.author = 'ForgeOS'
  pres.subject = data.projectName
  pres.title = `${data.projectName} — Design Report`

  // Pre-fetch images in parallel
  const heroBase64Promise = data.heroImageUrl ? fetchImageAsBase64(data.heroImageUrl) : Promise.resolve(null)
  const moduleImagePromises = data.modules.map((m) =>
    m.imageUrl ? fetchImageAsBase64(m.imageUrl) : Promise.resolve(null),
  )
  const [heroBase64, ...moduleImages] = await Promise.all([heroBase64Promise, ...moduleImagePromises])

  // ── 1. Cover Slide ──
  const coverSlide = pres.addSlide()
  coverSlide.addShape('rect', {
    x: 0, y: 0, w: '100%', h: 0.04,
    fill: { color: ORANGE },
  })

  if (heroBase64) {
    coverSlide.addImage({
      data: heroBase64,
      x: 5.5, y: 1.5, w: 6.5, h: 4.5,
      rounding: true,
    })
  }

  coverSlide.addText('FRACTIONAL FORGE', {
    x: 0.6, y: 0.6, w: 10, h: 0.4,
    fontSize: 14,
    fontFace: 'Helvetica Neue',
    color: MID_TEXT,
    charSpacing: 3,
  })

  coverSlide.addText(data.projectName, {
    x: 0.6, y: 1.3, w: 5, h: 1.0,
    fontSize: 36,
    fontFace: 'Helvetica Neue',
    bold: true,
    color: DARK_TEXT,
  })

  coverSlide.addText('Engineering Design Report', {
    x: 0.6, y: 2.4, w: 5, h: 0.4,
    fontSize: 16,
    fontFace: 'Helvetica Neue',
    color: MID_TEXT,
  })

  const dateFormatted = new Date(data.generatedAt).toLocaleDateString('en-GB', {
    day: 'numeric',
    month: 'long',
    year: 'numeric',
  })
  coverSlide.addText(dateFormatted, {
    x: 0.6, y: 2.95, w: 5, h: 0.4,
    fontSize: 14,
    fontFace: 'Helvetica Neue',
    color: MID_TEXT,
  })

  coverSlide.addText('Generated by ForgeOS', {
    x: 0.6, y: 6.6, w: 10, h: 0.3,
    fontSize: 10,
    fontFace: 'Helvetica Neue',
    color: MID_TEXT,
  })

  // ── 2. Executive Summary ──
  if (data.productOverview) {
    const summarySlide = pres.addSlide()
    addSectionTitle(summarySlide, 'Executive Summary')

    summarySlide.addText(data.productOverview, {
      x: 0.6, y: 1.2, w: 11.5, h: 3.0,
      fontSize: 14,
      fontFace: 'Helvetica Neue',
      color: DARK_TEXT,
      lineSpacingMultiple: 1.5,
      valign: 'top',
    })

    // Design brief bullets
    if (data.designBrief) {
      const bullets: { text: string; options: object }[] = []
      if (data.designBrief.useCase) bullets.push({ text: `Use Case: ${data.designBrief.useCase}`, options: { fontSize: 11, fontFace: 'Helvetica Neue', color: DARK_TEXT, bullet: { type: 'bullet' as const }, paraSpaceBefore: 4 } })
      if (data.designBrief.targetProcess) bullets.push({ text: `Process: ${data.designBrief.targetProcess}`, options: { fontSize: 11, fontFace: 'Helvetica Neue', color: DARK_TEXT, bullet: { type: 'bullet' as const }, paraSpaceBefore: 4 } })
      if (data.designBrief.targetMaterial) bullets.push({ text: `Material: ${data.designBrief.targetMaterial}`, options: { fontSize: 11, fontFace: 'Helvetica Neue', color: DARK_TEXT, bullet: { type: 'bullet' as const }, paraSpaceBefore: 4 } })
      if (data.designBrief.toleranceTarget) bullets.push({ text: `Tolerance: ${data.designBrief.toleranceTarget}`, options: { fontSize: 11, fontFace: 'Helvetica Neue', color: DARK_TEXT, bullet: { type: 'bullet' as const }, paraSpaceBefore: 4 } })

      if (bullets.length > 0) {
        summarySlide.addText(bullets, {
          x: 0.6, y: 4.4, w: 11.5, h: 2.5,
          valign: 'top',
        })
      }
    }
  }

  // ── 3. Research Highlights ──
  if (data.researchReport) {
    const researchSlide = pres.addSlide()
    addSectionTitle(researchSlide, 'Research Highlights')

    const preview = data.researchReport.slice(0, 500).replace(/[#*_]/g, '').trim()
    const truncated = preview.length < data.researchReport.length ? `${preview}...` : preview

    researchSlide.addText(truncated, {
      x: 0.6, y: 1.2, w: 11.5, h: 4.5,
      fontSize: 12,
      fontFace: 'Helvetica Neue',
      color: DARK_TEXT,
      lineSpacingMultiple: 1.4,
      valign: 'top',
    })

    if (data.researchReport.length > 500) {
      researchSlide.addText('Full research report available in the Word (.docx) export.', {
        x: 0.6, y: 6.2, w: 11.5, h: 0.3,
        fontSize: 10,
        fontFace: 'Helvetica Neue',
        color: MID_TEXT,
        italic: true,
      })
    }
  }

  // ── 4. Module Overview Table ──
  if (data.modules.length > 0) {
    const overviewSlide = pres.addSlide()
    addSectionTitle(overviewSlide, 'Module Overview')

    const headerRow: PptxGenJS.TableRow = [
      { text: 'Module', options: { bold: true, fontSize: 10, color: MID_TEXT, fill: { color: LIGHT_BG } } },
      { text: 'Purpose', options: { bold: true, fontSize: 10, color: MID_TEXT, fill: { color: LIGHT_BG } } },
      { text: 'Lead Time', options: { bold: true, fontSize: 10, color: MID_TEXT, fill: { color: LIGHT_BG }, align: 'center' } },
      { text: 'Mass', options: { bold: true, fontSize: 10, color: MID_TEXT, fill: { color: LIGHT_BG }, align: 'center' } },
    ]

    const dataRows: PptxGenJS.TableRow[] = data.modules.slice(0, 12).map((m) => [
      { text: m.name, options: { fontSize: 10, color: DARK_TEXT } },
      { text: m.purpose.slice(0, 60) + (m.purpose.length > 60 ? '...' : ''), options: { fontSize: 10, color: DARK_TEXT } },
      { text: m.leadWeeks != null ? `${m.leadWeeks}w` : '—', options: { fontSize: 10, color: DARK_TEXT, align: 'center' as const } },
      { text: m.estimatedMassKg != null ? `${m.estimatedMassKg} kg` : '—', options: { fontSize: 10, color: DARK_TEXT, align: 'center' as const } },
    ])

    overviewSlide.addTable([headerRow, ...dataRows], {
      x: 0.6, y: 1.2, w: 11.5,
      colW: [3, 5.5, 1.5, 1.5],
      border: { type: 'solid', pt: 0.5, color: 'E2E8F0' },
      rowH: 0.4,
      fontFace: 'Helvetica Neue',
    })
  }

  // ── 5. Per-module slides (max 10) ──
  const modulesToShow = data.modules.slice(0, 10)
  for (let idx = 0; idx < modulesToShow.length; idx++) {
    const mod = modulesToShow[idx]
    const moduleSlide = pres.addSlide()

    moduleSlide.addText(`${idx + 1}. ${mod.name}`, {
      x: 0.6, y: 0.35, w: 11.5, h: 0.5,
      fontSize: 22,
      fontFace: 'Helvetica Neue',
      bold: true,
      color: DARK_TEXT,
    })
    moduleSlide.addShape('rect', {
      x: 0.6, y: 0.85, w: 1.2, h: 0.04,
      fill: { color: ORANGE },
    })

    // Blueprint image (left side)
    const imgBase64 = moduleImages[idx] ?? null
    if (imgBase64) {
      moduleSlide.addImage({
        data: imgBase64,
        x: 0.6, y: 1.2, w: 5, h: 3.5,
        rounding: true,
      })
    }

    // Text content (right side, or full width if no image)
    const textX = imgBase64 ? 6.0 : 0.6
    const textW = imgBase64 ? 6.5 : 11.5

    moduleSlide.addText(mod.purpose, {
      x: textX, y: 1.2, w: textW, h: 1.2,
      fontSize: 12,
      fontFace: 'Helvetica Neue',
      color: DARK_TEXT,
      lineSpacingMultiple: 1.4,
      valign: 'top',
    })

    // Key parts as bullets
    if (mod.keyParts && mod.keyParts.length > 0) {
      const partBullets = mod.keyParts.slice(0, 6).map((p) => ({
        text: p,
        options: {
          fontSize: 10,
          fontFace: 'Helvetica Neue',
          color: DARK_TEXT,
          bullet: { type: 'bullet' as const },
          paraSpaceBefore: 3,
        },
      }))
      moduleSlide.addText(partBullets, {
        x: textX, y: 2.6, w: textW, h: 2.5,
        valign: 'top',
      })
    }

    // Quick specs at bottom
    const specParts: string[] = []
    if (mod.leadWeeks != null) specParts.push(`Lead: ${mod.leadWeeks}w`)
    if (mod.estimatedMassKg != null) specParts.push(`Mass: ${mod.estimatedMassKg} kg`)
    if (specParts.length > 0) {
      moduleSlide.addText(specParts.join('  |  '), {
        x: 0.6, y: 6.6, w: 11.5, h: 0.3,
        fontSize: 10,
        fontFace: 'Helvetica Neue',
        color: MID_TEXT,
      })
    }
  }

  // ── 6. Specs slide ──
  const diagModuleIds = Object.keys(data.diagnosticAnswers)
  if (diagModuleIds.length > 0) {
    const specsSlide = pres.addSlide()
    addSectionTitle(specsSlide, 'Specifications')

    const specHeader: PptxGenJS.TableRow = [
      { text: 'Module', options: { bold: true, fontSize: 9, color: MID_TEXT, fill: { color: LIGHT_BG } } },
      ...DIAG_KEYS.map((k) => ({
        text: DIAG_LABELS[k],
        options: { bold: true, fontSize: 9, color: MID_TEXT, fill: { color: LIGHT_BG }, align: 'center' as const },
      })),
    ]

    const specDataRows: PptxGenJS.TableRow[] = diagModuleIds.slice(0, 12).map((moduleId) => {
      const mod = data.modules.find((m) => m.id === moduleId)
      const answers = data.diagnosticAnswers[moduleId]
      return [
        { text: mod?.name ?? moduleId, options: { fontSize: 9, color: DARK_TEXT } },
        ...DIAG_KEYS.map((k) => ({
          text: answers?.[k] ?? '—',
          options: { fontSize: 9, color: DARK_TEXT, align: 'center' as const },
        })),
      ]
    })

    specsSlide.addTable([specHeader, ...specDataRows], {
      x: 0.6, y: 1.2, w: 11.5,
      colW: [3, 1.7, 1.7, 1.7, 1.7, 1.7],
      border: { type: 'solid', pt: 0.5, color: 'E2E8F0' },
      rowH: 0.35,
      fontFace: 'Helvetica Neue',
    })
  }

  // ── 7. Costs slide ──
  const costModuleIds = Object.keys(data.aiCostEstimates)
  if (costModuleIds.length > 0) {
    const costsSlide = pres.addSlide()
    addSectionTitle(costsSlide, 'Cost Estimates')

    const costHeader: PptxGenJS.TableRow = [
      { text: 'Module', options: { bold: true, fontSize: 10, color: MID_TEXT, fill: { color: LIGHT_BG } } },
      { text: 'Total / Unit', options: { bold: true, fontSize: 10, color: MID_TEXT, fill: { color: LIGHT_BG }, align: 'center' } },
      { text: 'Confidence', options: { bold: true, fontSize: 10, color: MID_TEXT, fill: { color: LIGHT_BG }, align: 'center' } },
    ]

    const costDataRows: PptxGenJS.TableRow[] = costModuleIds.slice(0, 12).map((moduleId) => {
      const mod = data.modules.find((m) => m.id === moduleId)
      const est = data.aiCostEstimates[moduleId]
      return [
        { text: mod?.name ?? moduleId, options: { fontSize: 10, color: DARK_TEXT } },
        { text: est ? `£${est.totalPerUnit.toFixed(2)}` : '—', options: { fontSize: 10, color: DARK_TEXT, align: 'center' as const } },
        { text: est?.confidence ?? '—', options: { fontSize: 10, color: DARK_TEXT, align: 'center' as const } },
      ]
    })

    costsSlide.addTable([costHeader, ...costDataRows], {
      x: 0.6, y: 1.2, w: 11.5,
      colW: [5.5, 3, 3],
      border: { type: 'solid', pt: 0.5, color: 'E2E8F0' },
      rowH: 0.4,
      fontFace: 'Helvetica Neue',
    })
  }

  // ── Download ──
  const safeName = data.projectName.replace(/[^a-zA-Z0-9]/g, '-')
  const dateStr = new Date(data.generatedAt).toISOString().split('T')[0]

  await pres.writeFile({ fileName: `${safeName}-Design-Report-${dateStr}.pptx` })
}
