/**
 * @file specialist-insight-card.tsx
 *
 * @description Displays a pre-computed specialist insight as a compact card.
 * Used across the app to surface proactive specialist intelligence on
 * every major page. Insights are generated by background sweeps and
 * stored in agent_insights.
 *
 * @example
 * <SpecialistInsightCard
 *   insight={insight}
 *   onDismiss={handleDismiss}
 *   onDiscuss={handleDiscuss}
 * />
 */

'use client'

import { useState } from 'react'

import { Card } from '@/components/ui/card'
import { Button } from '@/components/ui/button'
import { UserAvatar } from '@/components/ui/user-avatar'
import { MessageCircle, X, Lightbulb, AlertTriangle, TrendingUp, Sparkles, Check, Scale } from 'lucide-react'
import { updateDecisionOutcome } from '@/actions/decision-outcomes'
import type { OutcomeStatus } from '@/lib/agents/decision-journal'
import { cn } from '@/lib/utils'
import { getSpecialistById } from '@/app/(platform)/agents/specialists-data'
import type { AgentInsight } from '@/actions/agent-insights'

// ─── Props ──────────────────────────────────────────────────────────

interface SpecialistInsightCardProps {
    /** The insight data to display */
    insight: AgentInsight
    /** Called when user dismisses the insight */
    onDismiss?: (insightId: string) => void
    /** Called when user wants to discuss with the specialist */
    onDiscuss?: (specialistId: string, insightContext: string) => void
    /** Additional CSS classes */
    className?: string
    /** Compact mode truncates the body text */
    compact?: boolean
}

// ─── Urgency Visual Config ──────────────────────────────────────────

const URGENCY_CONFIG = {
    critical: {
        icon: AlertTriangle,
        accentColor: 'border-l-destructive',
        bgColor: 'bg-status-error-light/30',
        label: 'Needs attention',
    },
    important: {
        icon: Lightbulb,
        accentColor: 'border-l-status-warning',
        bgColor: 'bg-status-warning-light/30',
        label: 'Recommendation',
    },
    informational: {
        icon: TrendingUp,
        accentColor: 'border-l-status-info',
        bgColor: 'bg-status-info-light/30',
        label: 'Insight',
    },
} as const satisfies Record<AgentInsight['urgency'], {
    icon: typeof AlertTriangle
    accentColor: string
    bgColor: string
    label: string
}>

// ─── Component ──────────────────────────────────────────────────────

/**
 * Renders a single specialist insight as a compact, visually-coded card.
 *
 * @description Shows the specialist's avatar, name, insight body, and
 * optional actions (dismiss, discuss). Urgency level controls the left
 * border accent and background tint.
 *
 * @param props - Component props
 * @returns The insight card, or null if dismissed
 */
export function SpecialistInsightCard({
    insight,
    onDismiss,
    onDiscuss,
    className,
    compact = false,
}: SpecialistInsightCardProps): React.ReactElement | null {
    const [isDismissed, setIsDismissed] = useState(false)
    const [outcomeRecorded, setOutcomeRecorded] = useState(false)
    const specialist = getSpecialistById(insight.specialist_id)
    const config = URGENCY_CONFIG[insight.urgency]
    const Icon = config.icon
    const domainData = insight.domain_data as Record<string, unknown> | null

    if (isDismissed) return null

    function handleDismiss(): void {
        setIsDismissed(true)
        onDismiss?.(insight.id)
    }

    function handleDiscuss(): void {
        onDiscuss?.(insight.specialist_id, insight.body)
    }

    async function handleRecordOutcome(status: OutcomeStatus): Promise<void> {
        const decisionId = domainData?.decision_id as string | undefined
        if (!decisionId) return
        const { error } = await updateDecisionOutcome(decisionId, status)
        if (!error) {
            setOutcomeRecorded(true)
        }
    }

    return (
        <Card
            className={cn(
                'border-l-4 p-4 transition-all duration-200',
                config.accentColor,
                config.bgColor,
                'hover:shadow-md',
                className,
            )}
        >
            <div className="flex items-start gap-3">
                {/* Specialist avatar */}
                <div className="flex-shrink-0">
                    <UserAvatar
                        name={specialist?.name ?? 'AI'}
                        role="AI_Agent"
                        size="sm"
                    />
                </div>

                {/* Content */}
                <div className="min-w-0 flex-1">
                    <div className="mb-1 flex items-center gap-2">
                        <span className="text-sm font-semibold text-foreground">
                            {specialist?.name ?? 'Specialist'}
                        </span>
                        {specialist?.title && (
                            <span className="text-xs text-muted-foreground">
                                {specialist.title}
                            </span>
                        )}
                        <Icon className="h-3.5 w-3.5 text-muted-foreground" />
                    </div>

                    <p className="text-sm font-medium text-foreground mb-0.5">
                        {insight.title}
                    </p>

                    <p
                        className={cn(
                            'text-sm text-muted-foreground leading-relaxed',
                            compact && 'line-clamp-2',
                        )}
                    >
                        {insight.body}
                    </p>

                    {/* AI-generated indicator */}
                    <p className="mt-1 flex items-center gap-1 text-[10px] text-muted-foreground">
                        <Sparkles className="h-2.5 w-2.5" />
                        {insight.specialist_id === 'legal-counsel'
                            ? 'AI-generated \u2014 not legal advice. Verify before acting.'
                            : 'AI-generated \u2014 verify before acting.'}
                    </p>

                    {/* Decision outcome recording (for record_outcome action type) */}
                    {!compact && domainData?.action_type === 'record_outcome' && !!domainData?.decision_id && !outcomeRecorded && (
                        <div className="mt-2 flex items-center gap-1.5">
                            <Button
                                variant="ghost"
                                size="sm"
                                onClick={() => handleRecordOutcome('positive')}
                                className="h-6 px-2 text-[10px] text-success hover:text-success hover:bg-success/10"
                            >
                                <Check className="h-2.5 w-2.5 mr-1" />
                                Worked
                            </Button>
                            <Button
                                variant="ghost"
                                size="sm"
                                onClick={() => handleRecordOutcome('negative')}
                                className="h-6 px-2 text-[10px] text-destructive hover:text-destructive hover:bg-destructive/10"
                            >
                                <X className="h-2.5 w-2.5 mr-1" />
                                Didn&apos;t work
                            </Button>
                            <Button
                                variant="ghost"
                                size="sm"
                                onClick={() => handleRecordOutcome('mixed')}
                                className="h-6 px-2 text-[10px] text-warning hover:text-warning hover:bg-warning/10"
                            >
                                <Scale className="h-2.5 w-2.5 mr-1" />
                                Mixed
                            </Button>
                        </div>
                    )}
                    {outcomeRecorded && (
                        <p className="mt-2 text-[10px] text-success font-medium">Outcome recorded</p>
                    )}

                    {/* Actions */}
                    {!compact && onDiscuss && !domainData?.action_type && (
                        <div className="mt-3 flex items-center gap-2">
                            <Button
                                variant="ghost"
                                size="sm"
                                onClick={handleDiscuss}
                                className="h-7 px-2 text-xs"
                            >
                                <MessageCircle className="mr-1 h-3 w-3" />
                                Discuss with {specialist?.name ?? 'Specialist'}
                            </Button>
                        </div>
                    )}
                </div>

                {/* Dismiss */}
                {onDismiss && (
                    <Button
                        variant="ghost"
                        size="icon"
                        onClick={handleDismiss}
                        className="h-6 w-6 flex-shrink-0 text-muted-foreground hover:text-foreground"
                        aria-label="Dismiss insight"
                    >
                        <X className="h-3.5 w-3.5" />
                    </Button>
                )}
            </div>
        </Card>
    )
}
