/**
 * @file materials.ts — Engineering material properties database.
 *
 * @description Curated database of ~40 common engineering materials with
 * real mechanical, thermal, and manufacturing properties. Values sourced
 * from MatWeb, ASM International, and manufacturer datasheets.
 *
 * @related
 * - Process constraints: src/lib/engineering-data/processes.ts
 * - Standard parts: src/lib/engineering-data/standard-parts.ts
 * - Tool handlers: src/lib/agents/tools/handlers/engineering-compute.ts
 */

export interface MaterialProperty {
    /** Unique key for lookup (e.g., "al-6061-t6") */
    id: string
    /** Human-readable name (e.g., "Aluminum 6061-T6") */
    name: string
    /** Material category */
    category: "metal" | "polymer" | "composite" | "ceramic" | "elastomer"
    /** Density in kg/m3 */
    density_kg_m3: number
    /** Yield strength in MPa (null for brittle materials) */
    yield_strength_mpa: number | null
    /** Ultimate tensile strength in MPa */
    ultimate_strength_mpa: number
    /** Elastic (Young's) modulus in GPa */
    elastic_modulus_gpa: number
    /** Thermal conductivity in W/(m*K) */
    thermal_conductivity_w_mk: number
    /** Specific heat capacity in J/(kg*K) */
    specific_heat_j_kgk: number
    /** Melting point in C (null for polymers that degrade) */
    melting_point_c: number | null
    /** Glass transition temperature in C (polymers only) */
    glass_transition_c: number | null
    /** Heat deflection temperature in C at 0.45 MPa */
    hdt_c: number | null
    /** Coefficient of thermal expansion in um/(m*K) */
    cte_um_mk: number
    /** Poisson's ratio */
    poisson_ratio: number
    /** Machinability rating 0-100 (relative to free-machining steel = 100) */
    machinability_rating: number
    /** Compatibility with additive processes */
    printability: {
        fdm: boolean
        sla: boolean
        sls: boolean
        dmls: boolean
    }
    /** Cost range per kg in USD */
    cost_per_kg_usd: { low: number; high: number }
    /** Common grades/alloys */
    common_grades: string[]
    /** Engineering notes */
    notes: string
}

// ---------------------------------------------------------------------------
// Material definitions
// ---------------------------------------------------------------------------

export const MATERIALS: MaterialProperty[] = [
    // ======================================================================
    // METALS (15)
    // ======================================================================
    {
        id: "al-6061-t6",
        name: "Aluminum 6061-T6",
        category: "metal",
        density_kg_m3: 2700,
        yield_strength_mpa: 276,
        ultimate_strength_mpa: 310,
        elastic_modulus_gpa: 68.9,
        thermal_conductivity_w_mk: 167,
        specific_heat_j_kgk: 896,
        melting_point_c: 582,
        glass_transition_c: null,
        hdt_c: null,
        cte_um_mk: 23.6,
        poisson_ratio: 0.33,
        machinability_rating: 90,
        printability: { fdm: false, sla: false, sls: false, dmls: true },
        cost_per_kg_usd: { low: 3, high: 8 },
        common_grades: ["6061-T6", "6061-T651", "6061-O"],
        notes: "Most widely used aluminum alloy for structural applications. Excellent corrosion resistance, good weldability. T6 temper provides peak strength via solution heat treatment and artificial aging.",
    },
    {
        id: "al-7075-t6",
        name: "Aluminum 7075-T6",
        category: "metal",
        density_kg_m3: 2810,
        yield_strength_mpa: 503,
        ultimate_strength_mpa: 572,
        elastic_modulus_gpa: 71.7,
        thermal_conductivity_w_mk: 130,
        specific_heat_j_kgk: 960,
        melting_point_c: 477,
        glass_transition_c: null,
        hdt_c: null,
        cte_um_mk: 23.4,
        poisson_ratio: 0.33,
        machinability_rating: 70,
        printability: { fdm: false, sla: false, sls: false, dmls: true },
        cost_per_kg_usd: { low: 6, high: 15 },
        common_grades: ["7075-T6", "7075-T651", "7075-T73"],
        notes: "High-strength aerospace aluminum. Zinc as primary alloying element. Poor weldability and corrosion resistance compared to 6061. Often anodized or clad (Alclad) for corrosion protection.",
    },
    {
        id: "al-5052-h32",
        name: "Aluminum 5052-H32",
        category: "metal",
        density_kg_m3: 2680,
        yield_strength_mpa: 193,
        ultimate_strength_mpa: 228,
        elastic_modulus_gpa: 70.3,
        thermal_conductivity_w_mk: 138,
        specific_heat_j_kgk: 880,
        melting_point_c: 607,
        glass_transition_c: null,
        hdt_c: null,
        cte_um_mk: 23.8,
        poisson_ratio: 0.33,
        machinability_rating: 50,
        printability: { fdm: false, sla: false, sls: false, dmls: false },
        cost_per_kg_usd: { low: 4, high: 10 },
        common_grades: ["5052-H32", "5052-H34", "5052-O"],
        notes: "Best general-purpose sheet metal aluminum. Excellent saltwater corrosion resistance (marine grade). Good formability and weldability. Not heat-treatable; strengthened by cold working.",
    },
    {
        id: "steel-1018",
        name: "Steel 1018 (Low Carbon)",
        category: "metal",
        density_kg_m3: 7870,
        yield_strength_mpa: 370,
        ultimate_strength_mpa: 440,
        elastic_modulus_gpa: 205,
        thermal_conductivity_w_mk: 51.9,
        specific_heat_j_kgk: 486,
        melting_point_c: 1510,
        glass_transition_c: null,
        hdt_c: null,
        cte_um_mk: 11.5,
        poisson_ratio: 0.29,
        machinability_rating: 78,
        printability: { fdm: false, sla: false, sls: false, dmls: true },
        cost_per_kg_usd: { low: 1, high: 3 },
        common_grades: ["1018 CF", "1018 HR", "1020"],
        notes: "Standard low-carbon mild steel. Excellent weldability and case-hardenability. Cold-drawn (CF) stock is common for shafts and pins. Yield value above is for cold-drawn condition; hot-rolled is ~220 MPa.",
    },
    {
        id: "steel-4140",
        name: "Steel 4140 (Alloy)",
        category: "metal",
        density_kg_m3: 7850,
        yield_strength_mpa: 655,
        ultimate_strength_mpa: 1020,
        elastic_modulus_gpa: 205,
        thermal_conductivity_w_mk: 42.6,
        specific_heat_j_kgk: 473,
        melting_point_c: 1416,
        glass_transition_c: null,
        hdt_c: null,
        cte_um_mk: 12.3,
        poisson_ratio: 0.29,
        machinability_rating: 66,
        printability: { fdm: false, sla: false, sls: false, dmls: true },
        cost_per_kg_usd: { low: 2, high: 6 },
        common_grades: ["4140", "4140 PH", "4142"],
        notes: "Chromium-molybdenum alloy steel. Values given for quenched and tempered condition. Outstanding strength-to-cost ratio. Widely used for gears, shafts, and tooling. Must be stress-relieved after welding.",
    },
    {
        id: "ss-304",
        name: "Stainless Steel 304",
        category: "metal",
        density_kg_m3: 8000,
        yield_strength_mpa: 215,
        ultimate_strength_mpa: 505,
        elastic_modulus_gpa: 193,
        thermal_conductivity_w_mk: 16.2,
        specific_heat_j_kgk: 500,
        melting_point_c: 1400,
        glass_transition_c: null,
        hdt_c: null,
        cte_um_mk: 17.3,
        poisson_ratio: 0.29,
        machinability_rating: 45,
        printability: { fdm: false, sla: false, sls: false, dmls: true },
        cost_per_kg_usd: { low: 3, high: 8 },
        common_grades: ["304", "304L", "304H"],
        notes: "Most common austenitic stainless steel (18/8 Cr/Ni). Excellent corrosion resistance and formability. Work-hardens significantly. 304L variant has lower carbon for improved weld corrosion resistance.",
    },
    {
        id: "ss-316",
        name: "Stainless Steel 316",
        category: "metal",
        density_kg_m3: 8000,
        yield_strength_mpa: 205,
        ultimate_strength_mpa: 515,
        elastic_modulus_gpa: 193,
        thermal_conductivity_w_mk: 16.3,
        specific_heat_j_kgk: 500,
        melting_point_c: 1375,
        glass_transition_c: null,
        hdt_c: null,
        cte_um_mk: 15.9,
        poisson_ratio: 0.30,
        machinability_rating: 40,
        printability: { fdm: false, sla: false, sls: false, dmls: true },
        cost_per_kg_usd: { low: 4, high: 10 },
        common_grades: ["316", "316L", "316Ti"],
        notes: "Molybdenum-bearing austenitic stainless. Superior chloride/pitting corrosion resistance vs 304. Standard for marine, chemical, and medical implant applications. 316L preferred for welded assemblies.",
    },
    {
        id: "ti-6al-4v",
        name: "Titanium Ti-6Al-4V",
        category: "metal",
        density_kg_m3: 4430,
        yield_strength_mpa: 880,
        ultimate_strength_mpa: 950,
        elastic_modulus_gpa: 113.8,
        thermal_conductivity_w_mk: 6.7,
        specific_heat_j_kgk: 526,
        melting_point_c: 1604,
        glass_transition_c: null,
        hdt_c: null,
        cte_um_mk: 8.6,
        poisson_ratio: 0.34,
        machinability_rating: 22,
        printability: { fdm: false, sla: false, sls: false, dmls: true },
        cost_per_kg_usd: { low: 25, high: 80 },
        common_grades: ["Grade 5", "Grade 23 (ELI)", "Grade 5 Anneal"],
        notes: "Most widely used titanium alloy (~50% of all Ti production). Alpha-beta alloy with excellent strength-to-weight ratio. Biocompatible (Grade 23 ELI for implants). Difficult to machine — use low speed, high feed, rigid setups.",
    },
    {
        id: "cu-c110",
        name: "Copper C110 (ETP)",
        category: "metal",
        density_kg_m3: 8940,
        yield_strength_mpa: 69,
        ultimate_strength_mpa: 221,
        elastic_modulus_gpa: 117,
        thermal_conductivity_w_mk: 388,
        specific_heat_j_kgk: 385,
        melting_point_c: 1083,
        glass_transition_c: null,
        hdt_c: null,
        cte_um_mk: 16.9,
        poisson_ratio: 0.34,
        machinability_rating: 20,
        printability: { fdm: false, sla: false, sls: false, dmls: true },
        cost_per_kg_usd: { low: 8, high: 18 },
        common_grades: ["C110 (ETP)", "C101 (OFE)", "C102 (OFHC)"],
        notes: "99.9% pure electrolytic tough-pitch copper. Highest electrical and thermal conductivity of common engineering metals. Yield value for annealed condition; half-hard is ~250 MPa. Gummy to machine — use sharp tools.",
    },
    {
        id: "brass-c360",
        name: "Brass C360 (Free-Cutting)",
        category: "metal",
        density_kg_m3: 8500,
        yield_strength_mpa: 310,
        ultimate_strength_mpa: 385,
        elastic_modulus_gpa: 97,
        thermal_conductivity_w_mk: 115,
        specific_heat_j_kgk: 380,
        melting_point_c: 885,
        glass_transition_c: null,
        hdt_c: null,
        cte_um_mk: 20.5,
        poisson_ratio: 0.34,
        machinability_rating: 100,
        printability: { fdm: false, sla: false, sls: false, dmls: false },
        cost_per_kg_usd: { low: 6, high: 14 },
        common_grades: ["C360", "C353", "C385"],
        notes: "The benchmark free-machining material (machinability index = 100). Lead content (3%) enables excellent chip-breaking. RoHS-restricted for some applications — use C3604 or bismuth brass C69300 where lead-free is required.",
    },
    {
        id: "inconel-625",
        name: "Inconel 625",
        category: "metal",
        density_kg_m3: 8440,
        yield_strength_mpa: 490,
        ultimate_strength_mpa: 900,
        elastic_modulus_gpa: 205.8,
        thermal_conductivity_w_mk: 9.8,
        specific_heat_j_kgk: 410,
        melting_point_c: 1350,
        glass_transition_c: null,
        hdt_c: null,
        cte_um_mk: 12.8,
        poisson_ratio: 0.31,
        machinability_rating: 12,
        printability: { fdm: false, sla: false, sls: false, dmls: true },
        cost_per_kg_usd: { low: 40, high: 120 },
        common_grades: ["625", "625 LCF", "UNS N06625"],
        notes: "Nickel-chromium-molybdenum superalloy. Exceptional high-temperature strength (retains properties to ~800 C) and corrosion resistance. Used in turbine blades, chemical processing, and marine exhaust. Very difficult to machine.",
    },
    {
        id: "becu-c17200",
        name: "Beryllium Copper C17200",
        category: "metal",
        density_kg_m3: 8250,
        yield_strength_mpa: 1035,
        ultimate_strength_mpa: 1310,
        elastic_modulus_gpa: 131,
        thermal_conductivity_w_mk: 115,
        specific_heat_j_kgk: 420,
        melting_point_c: 870,
        glass_transition_c: null,
        hdt_c: null,
        cte_um_mk: 17.8,
        poisson_ratio: 0.30,
        machinability_rating: 50,
        printability: { fdm: false, sla: false, sls: false, dmls: false },
        cost_per_kg_usd: { low: 50, high: 150 },
        common_grades: ["C17200", "C17300", "C17500"],
        notes: "Highest-strength copper alloy. Values given for aged (AT) condition. Non-sparking and non-magnetic. Used for injection mold inserts, springs, and electrical connectors. CAUTION: beryllium dust is extremely toxic — do not machine without proper extraction.",
    },
    {
        id: "mg-az31b",
        name: "Magnesium AZ31B",
        category: "metal",
        density_kg_m3: 1770,
        yield_strength_mpa: 200,
        ultimate_strength_mpa: 260,
        elastic_modulus_gpa: 45,
        thermal_conductivity_w_mk: 96,
        specific_heat_j_kgk: 1024,
        melting_point_c: 605,
        glass_transition_c: null,
        hdt_c: null,
        cte_um_mk: 26.0,
        poisson_ratio: 0.35,
        machinability_rating: 80,
        printability: { fdm: false, sla: false, sls: false, dmls: true },
        cost_per_kg_usd: { low: 8, high: 20 },
        common_grades: ["AZ31B-H24", "AZ31B-O", "AZ80A"],
        notes: "Lightest structural metal (~35% lighter than aluminum). H24 temper values shown. Excellent machinability. Flammable chip hazard — use mineral oil coolant, never water. Limited forming at room temp; warm-form at 200-300 C.",
    },
    {
        id: "zamak-3",
        name: "Zinc Alloy Zamak 3",
        category: "metal",
        density_kg_m3: 6600,
        yield_strength_mpa: 228,
        ultimate_strength_mpa: 283,
        elastic_modulus_gpa: 85.5,
        thermal_conductivity_w_mk: 113,
        specific_heat_j_kgk: 419,
        melting_point_c: 387,
        glass_transition_c: null,
        hdt_c: null,
        cte_um_mk: 27.4,
        poisson_ratio: 0.30,
        machinability_rating: 65,
        printability: { fdm: false, sla: false, sls: false, dmls: false },
        cost_per_kg_usd: { low: 3, high: 7 },
        common_grades: ["Zamak 3", "Zamak 5", "Zamak 7"],
        notes: "Most widely used zinc die-casting alloy. Low melting point enables high-volume, tight-tolerance die casting. Excellent surface finish as-cast. Creep-prone above 70 C. Commonly electroplated (chrome, nickel).",
    },
    {
        id: "tool-steel-d2",
        name: "Tool Steel D2",
        category: "metal",
        density_kg_m3: 7700,
        yield_strength_mpa: 1570,
        ultimate_strength_mpa: 1860,
        elastic_modulus_gpa: 210,
        thermal_conductivity_w_mk: 20.0,
        specific_heat_j_kgk: 460,
        melting_point_c: 1421,
        glass_transition_c: null,
        hdt_c: null,
        cte_um_mk: 10.4,
        poisson_ratio: 0.28,
        machinability_rating: 27,
        printability: { fdm: false, sla: false, sls: false, dmls: true },
        cost_per_kg_usd: { low: 8, high: 25 },
        common_grades: ["D2", "A2", "O1", "S7"],
        notes: "High-carbon high-chromium cold-work tool steel. Values for hardened (58-62 HRC) condition. Air-hardening with minimal distortion. Excellent wear resistance for dies, punches, and cutting tools. Machine in annealed state, then harden.",
    },

    // ======================================================================
    // POLYMERS (15)
    // ======================================================================
    {
        id: "pla",
        name: "PLA (Polylactic Acid)",
        category: "polymer",
        density_kg_m3: 1240,
        yield_strength_mpa: 60,
        ultimate_strength_mpa: 65,
        elastic_modulus_gpa: 3.5,
        thermal_conductivity_w_mk: 0.13,
        specific_heat_j_kgk: 1800,
        melting_point_c: 160,
        glass_transition_c: 60,
        hdt_c: 55,
        cte_um_mk: 68,
        poisson_ratio: 0.36,
        machinability_rating: 40,
        printability: { fdm: true, sla: true, sls: false, dmls: false },
        cost_per_kg_usd: { low: 15, high: 40 },
        common_grades: ["PLA", "PLA+", "Tough PLA"],
        notes: "Most common FDM filament. Biodegradable, low-warp, easy to print. Low heat resistance is the main limitation — parts soften above 55 C. Not suitable for functional mechanical parts under sustained load. UV-degrades outdoors.",
    },
    {
        id: "petg",
        name: "PETG (Polyethylene Terephthalate Glycol)",
        category: "polymer",
        density_kg_m3: 1270,
        yield_strength_mpa: 50,
        ultimate_strength_mpa: 53,
        elastic_modulus_gpa: 2.2,
        thermal_conductivity_w_mk: 0.18,
        specific_heat_j_kgk: 1200,
        melting_point_c: 230,
        glass_transition_c: 80,
        hdt_c: 70,
        cte_um_mk: 60,
        poisson_ratio: 0.38,
        machinability_rating: 35,
        printability: { fdm: true, sla: false, sls: false, dmls: false },
        cost_per_kg_usd: { low: 18, high: 45 },
        common_grades: ["PETG", "PCTG", "Eastman Tritan"],
        notes: "Good balance of printability, strength, and chemical resistance. FDA-compliant grades available. Better heat resistance and layer adhesion than PLA. Prone to stringing during FDM printing. Impact-resistant.",
    },
    {
        id: "abs",
        name: "ABS (Acrylonitrile Butadiene Styrene)",
        category: "polymer",
        density_kg_m3: 1040,
        yield_strength_mpa: 43,
        ultimate_strength_mpa: 44,
        elastic_modulus_gpa: 2.3,
        thermal_conductivity_w_mk: 0.17,
        specific_heat_j_kgk: 1400,
        melting_point_c: null,
        glass_transition_c: 105,
        hdt_c: 98,
        cte_um_mk: 90,
        poisson_ratio: 0.35,
        machinability_rating: 55,
        printability: { fdm: true, sla: false, sls: false, dmls: false },
        cost_per_kg_usd: { low: 15, high: 35 },
        common_grades: ["ABS", "ABS-ESD", "ABS-M30"],
        notes: "Classic engineering thermoplastic. Acetone-smoothable for post-processing. Requires enclosed heated chamber for reliable FDM printing (warps badly). Good impact resistance. UV-degrades outdoors without protective coating.",
    },
    {
        id: "nylon-pa6",
        name: "Nylon PA6",
        category: "polymer",
        density_kg_m3: 1130,
        yield_strength_mpa: 70,
        ultimate_strength_mpa: 85,
        elastic_modulus_gpa: 2.7,
        thermal_conductivity_w_mk: 0.25,
        specific_heat_j_kgk: 1700,
        melting_point_c: 220,
        glass_transition_c: 47,
        hdt_c: 75,
        cte_um_mk: 80,
        poisson_ratio: 0.39,
        machinability_rating: 60,
        printability: { fdm: true, sla: false, sls: true, dmls: false },
        cost_per_kg_usd: { low: 20, high: 60 },
        common_grades: ["PA6", "PA66", "PA6 GF30"],
        notes: "Workhorse engineering polymer. Excellent wear resistance and self-lubricating. Absorbs moisture (2-3% by weight) which reduces stiffness ~20% and increases toughness. Dry-as-molded values shown; condition parts before measuring.",
    },
    {
        id: "nylon-pa12",
        name: "Nylon PA12",
        category: "polymer",
        density_kg_m3: 1010,
        yield_strength_mpa: 45,
        ultimate_strength_mpa: 50,
        elastic_modulus_gpa: 1.6,
        thermal_conductivity_w_mk: 0.23,
        specific_heat_j_kgk: 1640,
        melting_point_c: 178,
        glass_transition_c: 37,
        hdt_c: 95,
        cte_um_mk: 100,
        poisson_ratio: 0.40,
        machinability_rating: 55,
        printability: { fdm: true, sla: false, sls: true, dmls: false },
        cost_per_kg_usd: { low: 50, high: 120 },
        common_grades: ["PA12", "PA2200 (EOS)", "Duraform PA (3D Systems)"],
        notes: "The dominant SLS (powder bed fusion) material. Lower moisture absorption than PA6 (~0.7%). Excellent chemical resistance. HDT above is for SLS parts which have higher crystallinity. Slightly lower strength but better dimensional stability than PA6.",
    },
    {
        id: "polycarbonate",
        name: "Polycarbonate (PC)",
        category: "polymer",
        density_kg_m3: 1200,
        yield_strength_mpa: 62,
        ultimate_strength_mpa: 66,
        elastic_modulus_gpa: 2.3,
        thermal_conductivity_w_mk: 0.20,
        specific_heat_j_kgk: 1200,
        melting_point_c: null,
        glass_transition_c: 147,
        hdt_c: 132,
        cte_um_mk: 65,
        poisson_ratio: 0.37,
        machinability_rating: 60,
        printability: { fdm: true, sla: false, sls: false, dmls: false },
        cost_per_kg_usd: { low: 25, high: 65 },
        common_grades: ["PC (Lexan/Makrolon)", "PC-ABS", "PC-GF"],
        notes: "Outstanding impact resistance (virtually unbreakable at room temp). Optically clear. High Tg makes it suitable for under-hood automotive. Sensitive to stress cracking from solvents. Requires high FDM temps (260-310 C) and enclosed chamber.",
    },
    {
        id: "peek",
        name: "PEEK (Polyether Ether Ketone)",
        category: "polymer",
        density_kg_m3: 1310,
        yield_strength_mpa: 100,
        ultimate_strength_mpa: 100,
        elastic_modulus_gpa: 4.1,
        thermal_conductivity_w_mk: 0.25,
        specific_heat_j_kgk: 1340,
        melting_point_c: 343,
        glass_transition_c: 143,
        hdt_c: 152,
        cte_um_mk: 47,
        poisson_ratio: 0.38,
        machinability_rating: 50,
        printability: { fdm: true, sla: false, sls: true, dmls: false },
        cost_per_kg_usd: { low: 400, high: 700 },
        common_grades: ["PEEK 450G", "PEEK GF30", "PEEK CF30"],
        notes: "Premium semi-crystalline polymer. Continuous service to 250 C. Excellent chemical resistance (survives most solvents). Biocompatible for implants. Very expensive. FDM requires 400 C+ hotend and 160 C+ chamber. Often used as a metal replacement.",
    },
    {
        id: "pom-delrin",
        name: "Delrin / POM (Polyoxymethylene)",
        category: "polymer",
        density_kg_m3: 1410,
        yield_strength_mpa: 65,
        ultimate_strength_mpa: 68,
        elastic_modulus_gpa: 3.1,
        thermal_conductivity_w_mk: 0.31,
        specific_heat_j_kgk: 1500,
        melting_point_c: 175,
        glass_transition_c: -60,
        hdt_c: 110,
        cte_um_mk: 110,
        poisson_ratio: 0.35,
        machinability_rating: 85,
        printability: { fdm: false, sla: false, sls: false, dmls: false },
        cost_per_kg_usd: { low: 5, high: 15 },
        common_grades: ["Delrin 150 (homopolymer)", "Celcon (copolymer)", "Delrin AF (PTFE-filled)"],
        notes: "The go-to material for CNC-machined plastic parts. Excellent dimensional stability, low friction, high fatigue endurance. Springs back from deformation. Not printable via FDM (emits formaldehyde). Homopolymer (Delrin) is stronger; copolymer has better chemical resistance.",
    },
    {
        id: "hdpe",
        name: "HDPE (High-Density Polyethylene)",
        category: "polymer",
        density_kg_m3: 950,
        yield_strength_mpa: 26,
        ultimate_strength_mpa: 33,
        elastic_modulus_gpa: 1.1,
        thermal_conductivity_w_mk: 0.46,
        specific_heat_j_kgk: 1900,
        melting_point_c: 130,
        glass_transition_c: -120,
        hdt_c: 75,
        cte_um_mk: 120,
        poisson_ratio: 0.41,
        machinability_rating: 40,
        printability: { fdm: false, sla: false, sls: false, dmls: false },
        cost_per_kg_usd: { low: 2, high: 5 },
        common_grades: ["HDPE", "UHMWPE", "HMW-HDPE"],
        notes: "Low-cost, chemically inert, FDA-approved polymer. Very high impact resistance, especially at low temps. Extremely difficult to bond/glue. Poor dimensional stability (high CTE and creep). Machines gummy — use sharp single-flute tools.",
    },
    {
        id: "polypropylene",
        name: "Polypropylene (PP)",
        category: "polymer",
        density_kg_m3: 905,
        yield_strength_mpa: 35,
        ultimate_strength_mpa: 40,
        elastic_modulus_gpa: 1.5,
        thermal_conductivity_w_mk: 0.22,
        specific_heat_j_kgk: 1920,
        melting_point_c: 160,
        glass_transition_c: -10,
        hdt_c: 100,
        cte_um_mk: 100,
        poisson_ratio: 0.42,
        machinability_rating: 45,
        printability: { fdm: true, sla: false, sls: true, dmls: false },
        cost_per_kg_usd: { low: 2, high: 5 },
        common_grades: ["PP Homopolymer", "PP Copolymer", "PP GF30"],
        notes: "Lightest common thermoplastic. Excellent chemical resistance and living hinge capability (flexes millions of cycles). HDT given for copolymer at 0.45 MPa. Poor UV resistance. Difficult to print via FDM (extreme warp).",
    },
    {
        id: "tpu-95a",
        name: "TPU 95A (Thermoplastic Polyurethane)",
        category: "elastomer",
        density_kg_m3: 1120,
        yield_strength_mpa: null,
        ultimate_strength_mpa: 40,
        elastic_modulus_gpa: 0.012,
        thermal_conductivity_w_mk: 0.19,
        specific_heat_j_kgk: 1570,
        melting_point_c: null,
        glass_transition_c: -40,
        hdt_c: 60,
        cte_um_mk: 150,
        poisson_ratio: 0.48,
        machinability_rating: 10,
        printability: { fdm: true, sla: false, sls: true, dmls: false },
        cost_per_kg_usd: { low: 30, high: 80 },
        common_grades: ["TPU 95A", "TPU 85A", "TPU 64D"],
        notes: "Flexible elastomeric filament. 95A Shore hardness (similar to rubber band). Excellent abrasion and oil resistance. Requires direct-drive extruder for FDM (Bowden setups jam). Use slow print speeds (20-30 mm/s). Not CNC-machinable.",
    },
    {
        id: "acetal-copolymer",
        name: "Acetal Copolymer (POM-C)",
        category: "polymer",
        density_kg_m3: 1410,
        yield_strength_mpa: 60,
        ultimate_strength_mpa: 65,
        elastic_modulus_gpa: 2.8,
        thermal_conductivity_w_mk: 0.31,
        specific_heat_j_kgk: 1470,
        melting_point_c: 165,
        glass_transition_c: -60,
        hdt_c: 105,
        cte_um_mk: 110,
        poisson_ratio: 0.35,
        machinability_rating: 82,
        printability: { fdm: false, sla: false, sls: false, dmls: false },
        cost_per_kg_usd: { low: 4, high: 12 },
        common_grades: ["Celcon M90", "Hostaform C", "Ultraform"],
        notes: "Copolymer variant of POM. Slightly lower strength than Delrin homopolymer but better chemical resistance and thermal stability. Better resistance to centerline porosity in thick sections. Excellent for gears, bearings, and snap-fits.",
    },
    {
        id: "ultem-pei",
        name: "ULTEM PEI (Polyetherimide)",
        category: "polymer",
        density_kg_m3: 1270,
        yield_strength_mpa: 105,
        ultimate_strength_mpa: 115,
        elastic_modulus_gpa: 3.3,
        thermal_conductivity_w_mk: 0.22,
        specific_heat_j_kgk: 2000,
        melting_point_c: null,
        glass_transition_c: 217,
        hdt_c: 200,
        cte_um_mk: 56,
        poisson_ratio: 0.36,
        machinability_rating: 55,
        printability: { fdm: true, sla: false, sls: false, dmls: false },
        cost_per_kg_usd: { low: 100, high: 250 },
        common_grades: ["ULTEM 1000", "ULTEM 2300 (GF)", "ULTEM 9085"],
        notes: "High-performance amorphous polymer. Outstanding flame, smoke, and toxicity (FST) properties — FAA-certified for aircraft interiors (ULTEM 9085). Continuous service to 170 C. Transparent amber color. Requires 350-400 C for FDM printing.",
    },
    {
        id: "asa",
        name: "ASA (Acrylonitrile Styrene Acrylate)",
        category: "polymer",
        density_kg_m3: 1070,
        yield_strength_mpa: 42,
        ultimate_strength_mpa: 48,
        elastic_modulus_gpa: 2.2,
        thermal_conductivity_w_mk: 0.17,
        specific_heat_j_kgk: 1300,
        melting_point_c: null,
        glass_transition_c: 100,
        hdt_c: 96,
        cte_um_mk: 90,
        poisson_ratio: 0.35,
        machinability_rating: 50,
        printability: { fdm: true, sla: false, sls: false, dmls: false },
        cost_per_kg_usd: { low: 20, high: 50 },
        common_grades: ["ASA", "ASA-PC", "Luran S"],
        notes: "UV-stable alternative to ABS. Essentially ABS with the butadiene replaced by acrylate rubber. Excellent weatherability for outdoor applications. Prints similarly to ABS (needs enclosure, 240-260 C). Better color stability.",
    },
    {
        id: "polysulfone-psu",
        name: "Polysulfone (PSU)",
        category: "polymer",
        density_kg_m3: 1240,
        yield_strength_mpa: 70,
        ultimate_strength_mpa: 75,
        elastic_modulus_gpa: 2.5,
        thermal_conductivity_w_mk: 0.26,
        specific_heat_j_kgk: 1130,
        melting_point_c: null,
        glass_transition_c: 185,
        hdt_c: 174,
        cte_um_mk: 56,
        poisson_ratio: 0.37,
        machinability_rating: 50,
        printability: { fdm: false, sla: false, sls: false, dmls: false },
        cost_per_kg_usd: { low: 50, high: 130 },
        common_grades: ["PSU (Udel)", "PPSU (Radel R)", "PES (Ultrason E)"],
        notes: "Transparent, high-temperature amorphous polymer. Autoclavable (steam sterilization). FDA/NSF listed for food and water contact. Good creep resistance and dimensional stability. Sensitive to stress cracking from aromatic solvents.",
    },

    // ======================================================================
    // COMPOSITES (6)
    // ======================================================================
    {
        id: "cf-unidirectional",
        name: "Carbon Fiber Unidirectional (CFRP UD)",
        category: "composite",
        density_kg_m3: 1600,
        yield_strength_mpa: null,
        ultimate_strength_mpa: 1500,
        elastic_modulus_gpa: 135,
        thermal_conductivity_w_mk: 5.0,
        specific_heat_j_kgk: 800,
        melting_point_c: null,
        glass_transition_c: null,
        hdt_c: 150,
        cte_um_mk: 0.5,
        poisson_ratio: 0.30,
        machinability_rating: 15,
        printability: { fdm: false, sla: false, sls: false, dmls: false },
        cost_per_kg_usd: { low: 50, high: 200 },
        common_grades: ["Standard Modulus (T300/T700)", "Intermediate Modulus (T800)", "High Modulus (M55J)"],
        notes: "Values for 60% Vf epoxy matrix, 0-degree direction. Properties are HIGHLY anisotropic: 90-degree UTS is only ~50 MPa. CTE is near-zero longitudinal but ~30 transverse. UTS of 1500 MPa is fiber-direction tensile. Layup design is critical.",
    },
    {
        id: "cf-woven-3k",
        name: "Carbon Fiber Woven 3K (CFRP Fabric)",
        category: "composite",
        density_kg_m3: 1550,
        yield_strength_mpa: null,
        ultimate_strength_mpa: 600,
        elastic_modulus_gpa: 70,
        thermal_conductivity_w_mk: 3.5,
        specific_heat_j_kgk: 800,
        melting_point_c: null,
        glass_transition_c: null,
        hdt_c: 140,
        cte_um_mk: 2.5,
        poisson_ratio: 0.06,
        machinability_rating: 15,
        printability: { fdm: false, sla: false, sls: false, dmls: false },
        cost_per_kg_usd: { low: 40, high: 150 },
        common_grades: ["3K Plain Weave", "3K Twill 2x2", "12K Fabric"],
        notes: "Balanced woven carbon fiber in epoxy (plain or twill weave). More quasi-isotropic than UD but lower peak strength. 3K = 3000 filaments per tow. Values for typical ~55% Vf laminate. Excellent for cosmetic applications (visible weave pattern). Diamond tooling required for machining.",
    },
    {
        id: "fiberglass-e-glass",
        name: "Fiberglass E-Glass (GFRP)",
        category: "composite",
        density_kg_m3: 2100,
        yield_strength_mpa: null,
        ultimate_strength_mpa: 350,
        elastic_modulus_gpa: 25,
        thermal_conductivity_w_mk: 0.35,
        specific_heat_j_kgk: 810,
        melting_point_c: null,
        glass_transition_c: null,
        hdt_c: 130,
        cte_um_mk: 12,
        poisson_ratio: 0.12,
        machinability_rating: 20,
        printability: { fdm: false, sla: false, sls: false, dmls: false },
        cost_per_kg_usd: { low: 5, high: 25 },
        common_grades: ["E-Glass Cloth", "S-Glass (higher strength)", "C-Glass (chemical resistant)"],
        notes: "Most cost-effective structural composite. Values for woven E-glass/polyester at ~40% Vf. S-glass variant offers ~30% higher strength. Electrically insulating. Used in boats, wind turbines, and PCBs (FR-4). Dust is a skin/lung irritant.",
    },
    {
        id: "kevlar-49",
        name: "Kevlar 49 (Aramid Fiber Composite)",
        category: "composite",
        density_kg_m3: 1440,
        yield_strength_mpa: null,
        ultimate_strength_mpa: 525,
        elastic_modulus_gpa: 60,
        thermal_conductivity_w_mk: 0.04,
        specific_heat_j_kgk: 1400,
        melting_point_c: null,
        glass_transition_c: null,
        hdt_c: 150,
        cte_um_mk: -2.0,
        poisson_ratio: 0.34,
        machinability_rating: 10,
        printability: { fdm: false, sla: false, sls: false, dmls: false },
        cost_per_kg_usd: { low: 80, high: 300 },
        common_grades: ["Kevlar 29 (ballistic)", "Kevlar 49 (structural)", "Kevlar 149 (high modulus)"],
        notes: "Values for Kevlar 49 fabric/epoxy laminate. Outstanding impact/ballistic resistance and vibration damping. Negative longitudinal CTE. Very difficult to machine (fibers fuzz) — use specialized shears or waterjet. Degrades under UV. Weak in compression.",
    },
    {
        id: "cf-chopped-sls",
        name: "Carbon Fiber Chopped (SLS Nylon-CF)",
        category: "composite",
        density_kg_m3: 1300,
        yield_strength_mpa: 85,
        ultimate_strength_mpa: 95,
        elastic_modulus_gpa: 8.5,
        thermal_conductivity_w_mk: 0.70,
        specific_heat_j_kgk: 1300,
        melting_point_c: null,
        glass_transition_c: null,
        hdt_c: 185,
        cte_um_mk: 25,
        poisson_ratio: 0.35,
        machinability_rating: 30,
        printability: { fdm: true, sla: false, sls: true, dmls: false },
        cost_per_kg_usd: { low: 80, high: 200 },
        common_grades: ["PA12-CF (EOS)", "Nylon 12 CF (Markforged)", "CarbonMide (Windform)"],
        notes: "Short chopped carbon fiber in nylon PA12 matrix for SLS/FDM. Much higher stiffness and HDT than neat nylon. Quasi-isotropic (random fiber orientation). Also available as FDM filament. Abrasive to nozzles — requires hardened steel nozzle for FDM.",
    },
    {
        id: "glass-filled-nylon",
        name: "Glass-Filled Nylon (PA6-GF30)",
        category: "composite",
        density_kg_m3: 1350,
        yield_strength_mpa: 100,
        ultimate_strength_mpa: 130,
        elastic_modulus_gpa: 8.3,
        thermal_conductivity_w_mk: 0.52,
        specific_heat_j_kgk: 1260,
        melting_point_c: 220,
        glass_transition_c: null,
        hdt_c: 200,
        cte_um_mk: 30,
        poisson_ratio: 0.38,
        machinability_rating: 35,
        printability: { fdm: true, sla: false, sls: true, dmls: false },
        cost_per_kg_usd: { low: 8, high: 25 },
        common_grades: ["PA6-GF30", "PA66-GF30", "PA12-GF (SLS)"],
        notes: "30% glass fiber by weight in PA6 matrix. Dry-as-molded values shown. Injection molding workhorse for structural housings and brackets. Weld lines are weak points (~50% of base strength). Anisotropic in injection molding due to fiber orientation. Abrasive to tooling.",
    },

    // ======================================================================
    // CERAMICS (2)
    // ======================================================================
    {
        id: "alumina-al2o3",
        name: "Alumina (Al2O3, 99.5%)",
        category: "ceramic",
        density_kg_m3: 3950,
        yield_strength_mpa: null,
        ultimate_strength_mpa: 300,
        elastic_modulus_gpa: 370,
        thermal_conductivity_w_mk: 30,
        specific_heat_j_kgk: 880,
        melting_point_c: 2072,
        glass_transition_c: null,
        hdt_c: null,
        cte_um_mk: 8.1,
        poisson_ratio: 0.22,
        machinability_rating: 5,
        printability: { fdm: false, sla: true, sls: false, dmls: false },
        cost_per_kg_usd: { low: 20, high: 100 },
        common_grades: ["99.5% Al2O3", "96% Al2O3", "99.8% Al2O3"],
        notes: "UTS value is flexural (MOR) strength — ceramics fail in compression at ~2000 MPa. Extremely hard (9 on Mohs). Diamond grinding only. Excellent electrical insulation and wear resistance. Brittle — no plastic deformation. SLA-printable via ceramic-loaded resins with sintering.",
    },
    {
        id: "zirconia-zro2",
        name: "Zirconia (ZrO2, Y-TZP)",
        category: "ceramic",
        density_kg_m3: 6050,
        yield_strength_mpa: null,
        ultimate_strength_mpa: 400,
        elastic_modulus_gpa: 210,
        thermal_conductivity_w_mk: 2.5,
        specific_heat_j_kgk: 450,
        melting_point_c: 2715,
        glass_transition_c: null,
        hdt_c: null,
        cte_um_mk: 10.5,
        poisson_ratio: 0.31,
        machinability_rating: 5,
        printability: { fdm: false, sla: true, sls: false, dmls: false },
        cost_per_kg_usd: { low: 50, high: 200 },
        common_grades: ["Y-TZP (3 mol%)", "Mg-PSZ", "Ce-TZP"],
        notes: "UTS value is flexural (MOR) strength. Transformation-toughened — toughest engineering ceramic (KIc ~10 MPa*m^0.5). Yttria-stabilized tetragonal zirconia polycrystal (Y-TZP) is the most common grade. Used for dental crowns, bearings, and cutting tools. Low thermal conductivity makes it a thermal barrier.",
    },
]

// ---------------------------------------------------------------------------
// Lookup / search functions
// ---------------------------------------------------------------------------

/** Find a material by exact ID or fuzzy name match */
export function findMaterial(query: string): MaterialProperty | undefined {
    const normalized = query.toLowerCase().trim()

    // 1. Exact ID match
    const byId = MATERIALS.find((m) => m.id === normalized)
    if (byId) return byId

    // 2. Exact name match (case-insensitive)
    const byName = MATERIALS.find((m) => m.name.toLowerCase() === normalized)
    if (byName) return byName

    // 3. Fuzzy: check if query is a substring of name or any common grade
    const bySubstring = MATERIALS.find(
        (m) =>
            m.name.toLowerCase().includes(normalized) ||
            m.common_grades.some((g) => g.toLowerCase().includes(normalized))
    )
    if (bySubstring) return bySubstring

    // 4. Fuzzy: check if all words in query appear in name
    const words = normalized.split(/\s+/)
    const byWords = MATERIALS.find((m) => {
        const nameLower = m.name.toLowerCase()
        return words.every((w) => nameLower.includes(w))
    })
    if (byWords) return byWords

    return undefined
}

/** List all material IDs and names */
export function listMaterials(): string {
    return MATERIALS.map((m) => `${m.id}: ${m.name}`).join("\n")
}

/** Get materials filtered by category */
export function getMaterialsByCategory(
    category: MaterialProperty["category"]
): MaterialProperty[] {
    return MATERIALS.filter((m) => m.category === category)
}

/** Search materials by name (case-insensitive substring) */
export function searchMaterials(query: string): MaterialProperty[] {
    const normalized = query.toLowerCase().trim()
    return MATERIALS.filter(
        (m) =>
            m.name.toLowerCase().includes(normalized) ||
            m.id.includes(normalized) ||
            m.common_grades.some((g) => g.toLowerCase().includes(normalized)) ||
            m.category.includes(normalized)
    )
}
