#!/usr/bin/env bash
# install-forcing-hooks.sh — make the discipline STRUCTURAL, not remembered.
#
# INTENT (Tristan 2026-08-01): "how do you force yourself to use the available
# tools and the other LLMs? Figure it out and then do it."
#
# THE HONEST DIAGNOSIS. Every softer mechanism has already failed in this repo:
#   - CLAUDE.md says use the stack.                    Lost to a live bug.
#   - MEMORY.md records the tool audit.                Lost to a live bug.
#   - fpk_solver_coverage.py reports coverage.         Exit 0, so nothing changed.
#   - I built a claim-provenance gate...               ...and then stated numbers
#                                                        in prose without
#                                                        registering them.
# On 2026-08-01 I hand-scaled an iron-loss figure (B_tooth = B_gap/0.54, "capped
# ~1.9 T", P_fe ~ B^2) while motor_loss_point.py sat unrun in the repo. Running
# it gave 302.2 W against the twin's 135.56, and 4225 W of magnet eddy loss the
# twin records as ZERO. The tool was there; nothing made me call it.
#
# A hook is the only layer that does not depend on me remembering, because it
# runs whether or not I am mid-debug.
#
# WHAT IT ENFORCES, in order of cost (cheapest first, so failures are fast):
#   1. Every universal --selftest passes.
#   2. The gate registry proves every gate still catches.
#   3. The claim-provenance gate: no registered claim ships stale or unbacked.
#   4. Geometry coherence: all artefacts describe ONE machine.
# The council review is NOT run here — it costs money and takes minutes, so it
# stays an explicit call. The hook prints the command so it is never forgotten.
#
# Install:  bash scripts/lib/install-forcing-hooks.sh
# Bypass:   git commit --no-verify   (visible in the reflog; use deliberately)

set -euo pipefail
REPO="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
cd "$REPO"

# ⭐⭐ TWO GOTCHAS, the second of which I broke before I understood it.
#
# 1. This repo is a git WORKTREE, so `.git` is a FILE pointing at
#    ../<main>/.git/worktrees/<name>, not a directory. Assuming
#    "$REPO/.git/hooks" fails outright.
#
# 2. `git rev-parse --git-path hooks` then resolves to `.husky/_` because
#    core.hooksPath is set — and `.husky/_/pre-commit` is HUSKY'S INTERNAL
#    DISPATCHER (`. "$(dirname "$0")/h"`), not a user hook. Writing there
#    CLOBBERS husky and silently disables the repo's lint hook. I did exactly
#    that and had to restore the dispatcher from its sibling.
#
# The correct target when husky is in use is the USER hook `.husky/pre-commit`,
# which husky's dispatcher invokes. Append to it; never replace it.
HOOKS_PATH="$(git config --get core.hooksPath || true)"
if [ -n "$HOOKS_PATH" ] && [ -d "$(dirname "$HOOKS_PATH")" ] \
   && [ -f "$(dirname "$HOOKS_PATH")/pre-commit" ]; then
  HUSKY_DIR="$(dirname "$HOOKS_PATH")"
  HOOK="$HUSKY_DIR/pre-commit"
  MODE=append
  echo "husky detected — appending to the USER hook $HOOK (never .husky/_)"
else
  HOOKDIR="$(git rev-parse --git-path hooks 2>/dev/null)" || {
    echo "not a git repository: $REPO" >&2; exit 1; }
  mkdir -p "$HOOKDIR"
  HOOK="$HOOKDIR/pre-commit"
  MODE=create
fi

MARKER="# >>> forge structural checks >>>"
if [ "$MODE" = append ] && grep -qF "$MARKER" "$HOOK" 2>/dev/null; then
  echo "already installed in $HOOK — nothing to do"; exit 0
fi
[ "$MODE" = append ] && printf '\n%s\n' "$MARKER" >> "$HOOK"
cat >> "$HOOK" <<'HOOKEOF'
# AUTO-GENERATED by scripts/lib/install-forcing-hooks.sh — do not hand-edit.
set -uo pipefail
REPO="$(git rev-parse --show-toplevel)"
cd "$REPO"
PY="${PY:-python3}"
fail=0

say() { printf '  %-52s %s\n' "$1" "$2"; }

echo "── pre-commit: the checks that do not depend on remembering ──"

for m in machine_excitation_tracking machine_magnet_flux_focusing model_routing \
         claim_provenance_gate council_precommit_review fpk_geometry_coherence; do
  if [ -f "scripts/lib/$m.py" ]; then
    if $PY "scripts/lib/$m.py" --selftest >/dev/null 2>&1; then
      say "$m --selftest" "ok"
    else
      say "$m --selftest" "FAIL"; fail=1
    fi
  fi
done

if [ -f scripts/lib/gate-registry.ts ] && command -v npx >/dev/null 2>&1; then
  if npx --no-install tsx scripts/lib/gate-registry.ts --selftest >/dev/null 2>&1; then
    say "gate-registry (every gate proves its catch)" "ok"
  else
    say "gate-registry (every gate proves its catch)" "FAIL"; fail=1
  fi
fi

# Claim provenance across every registry in the tree. A stale or unbacked
# number is the failure mode this whole layer exists for.
shopt -s nullglob
for reg in out/*/_claims/*.json; do
  if $PY scripts/lib/claim_provenance_gate.py --claims "$reg" >/dev/null 2>&1; then
    say "claims backed: $(basename "$(dirname "$(dirname "$reg")")")" "ok"
  else
    say "claims backed: $(basename "$(dirname "$(dirname "$reg")")")" "STALE/UNBACKED"
    $PY scripts/lib/claim_provenance_gate.py --claims "$reg" 2>&1 | sed 's/^/      /'
    fail=1
  fi
done

if [ "$fail" -ne 0 ]; then
  cat <<'MSG'

COMMIT BLOCKED. Fix the above, or `git commit --no-verify` deliberately.

Not run here (costs money and minutes) — run it yourself before landing
anything with a load-bearing claim:

  .venv/bin/python scripts/lib/council_precommit_review.py --staged \
      --claim "<what this change asserts>"

MSG
  exit 1
fi
echo "── all structural checks pass ──"
exit 0
HOOKEOF

chmod +x "$HOOK"
echo "installed: $HOOK"
echo "verify with: git commit --allow-empty -m 'hook check'"
