#!/usr/bin/env bash
# install-forcing-hooks.sh — make the discipline STRUCTURAL, not remembered.
#
# INTENT (Tristan 2026-08-01): "how do you force yourself to use the available
# tools and the other LLMs? Figure it out and then do it."
#
# THE HONEST DIAGNOSIS. Every softer mechanism has already failed in this repo:
#   - CLAUDE.md says use the stack.                    Lost to a live bug.
#   - MEMORY.md records the tool audit.                Lost to a live bug.
#   - fpk_solver_coverage.py reports coverage.         Exit 0, so nothing changed.
#   - I built a claim-provenance gate...               ...and then stated numbers
#                                                        in prose without
#                                                        registering them.
# On 2026-08-01 I hand-scaled an iron-loss figure (B_tooth = B_gap/0.54, "capped
# ~1.9 T", P_fe ~ B^2) while motor_loss_point.py sat unrun in the repo. Running
# it gave 302.2 W against the twin's 135.56, and 4225 W of magnet eddy loss the
# twin records as ZERO. The tool was there; nothing made me call it.
#
# A hook is the only layer that does not depend on me remembering, because it
# runs whether or not I am mid-debug.
#
# WHAT IT ENFORCES, in order of cost (cheapest first, so failures are fast):
#   1. Every universal --selftest passes.
#   2. The gate registry proves every gate still catches.
#   3. The claim-provenance gate: no registered claim ships stale or unbacked.
#   4. Geometry coherence: all artefacts describe ONE machine.
# The council review is NOT run here — it costs money and takes minutes, so it
# stays an explicit call. The hook prints the command so it is never forgotten.
#
# Install:  bash scripts/lib/install-forcing-hooks.sh
# Bypass:   git commit --no-verify   (visible in the reflog; use deliberately)

set -euo pipefail
REPO="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
cd "$REPO"

# ⭐⭐ TWO GOTCHAS, the second of which I broke before I understood it.
#
# 1. This repo is a git WORKTREE, so `.git` is a FILE pointing at
#    ../<main>/.git/worktrees/<name>, not a directory. Assuming
#    "$REPO/.git/hooks" fails outright.
#
# 2. `git rev-parse --git-path hooks` then resolves to `.husky/_` because
#    core.hooksPath is set — and `.husky/_/pre-commit` is HUSKY'S INTERNAL
#    DISPATCHER (`. "$(dirname "$0")/h"`), not a user hook. Writing there
#    CLOBBERS husky and silently disables the repo's lint hook. I did exactly
#    that and had to restore the dispatcher from its sibling.
#
# The correct target when husky is in use is the USER hook `.husky/pre-commit`,
# which husky's dispatcher invokes. Append to it; never replace it.
HOOKS_PATH="$(git config --get core.hooksPath || true)"
# ⭐⭐ A hooksPath OUTSIDE THIS REPO installs the discipline into a checkout this
# repo does not control (2026-08-02). It was set to a SIBLING checkout's
# `.husky/_`, so `install-forcing-hooks.sh` dutifully appended the structural
# block to THAT repo's `.husky/pre-commit`. The checks then ran — husky's
# dispatcher cd's to `git rev-parse --show-toplevel`, so they audited the right
# twin — and this repo's own `.husky/pre-commit` stayed 22 lines of lint+drift.
# Both "the hook is installed" and "the hook is not installed" were true at
# once, which is exactly the shape of a discipline nobody can verify. If this
# repo has its own husky dispatcher, point at it and install HERE.
if [ -n "$HOOKS_PATH" ]; then
  case "$HOOKS_PATH" in
    "$REPO"/*) : ;;
    *)
      echo "core.hooksPath points OUTSIDE this repo:"
      echo "    $HOOKS_PATH"
      if [ -f "$REPO/.husky/_/pre-commit" ] && [ -f "$REPO/.husky/_/h" ]; then
        git config core.hooksPath "$REPO/.husky/_"
        HOOKS_PATH="$REPO/.husky/_"
        echo "  -> repointed at this repo's own dispatcher $HOOKS_PATH"
      else
        echo "  -> this repo has no .husky/_ dispatcher; refusing to install" >&2
        echo "     into a foreign checkout. Run 'npx husky init' here first." >&2
        exit 1
      fi
      ;;
  esac
fi
if [ -n "$HOOKS_PATH" ] && [ -d "$(dirname "$HOOKS_PATH")" ] \
   && [ -f "$(dirname "$HOOKS_PATH")/pre-commit" ]; then
  HUSKY_DIR="$(dirname "$HOOKS_PATH")"
  HOOK="$HUSKY_DIR/pre-commit"
  MODE=append
  echo "husky detected — appending to the USER hook $HOOK (never .husky/_)"
else
  HOOKDIR="$(git rev-parse --git-path hooks 2>/dev/null)" || {
    echo "not a git repository: $REPO" >&2; exit 1; }
  mkdir -p "$HOOKDIR"
  HOOK="$HOOKDIR/pre-commit"
  MODE=create
fi

MARKER="# >>> forge structural checks >>>"
if [ "$MODE" = append ] && grep -qF "$MARKER" "$HOOK" 2>/dev/null; then
  echo "already installed in $HOOK — nothing to do"; exit 0
fi
[ "$MODE" = append ] && printf '\n%s\n' "$MARKER" >> "$HOOK"
cat >> "$HOOK" <<'HOOKEOF'
# AUTO-GENERATED by scripts/lib/install-forcing-hooks.sh — do not hand-edit.
# ⭐⭐ POSIX sh ONLY (Sol, finish council 2026-08-02). This block used
# `set -uo pipefail` and `shopt -s nullglob`, both BASH-ONLY, while the comment
# below already acknowledged husky may invoke the hook under `sh`. On any host
# where /bin/sh is dash the hook dies at `pipefail` BEFORE a single structural
# gate runs — a hook that reports nothing and blocks nothing, which is the exact
# failure this whole layer exists to prevent. macOS /bin/sh is bash, so it
# worked here and would have silently stopped working on Linux/CI.
set -u
REPO="$(git rev-parse --show-toplevel)"
cd "$REPO"
PY="${PY:-python3}"
fail=0

say() { printf '  %-52s %s\n' "$1" "$2"; }

echo "── pre-commit: the checks that do not depend on remembering ──"

for m in machine_excitation_tracking machine_magnet_flux_focusing machine_loss_bounds \
         model_routing claim_provenance_gate council_precommit_review \
         machine_geometry_coherence capability_lookup_stage \
         stage_boundary_check calculation_guard machine_lamination \
         p_stage_discipline; do
  if [ -f "scripts/lib/$m.py" ]; then
    if $PY "scripts/lib/$m.py" --selftest >/dev/null 2>&1; then
      say "$m --selftest" "ok"
    else
      say "$m --selftest" "FAIL"; fail=1
    fi
  fi
done

# ⭐⭐ "COULD NOT RUN" IS NOT "FAILED", AND A GATE MUST NOT DEPEND ON A CACHE
# (2026-08-02). This ran `npx --no-install tsx`, and `tsx` is NOT a dependency
# of this repo — it was resolving from ~/.npm/_npx, which expired mid-session.
# The hook then reported the gate registry as FAIL, indistinguishable from "a
# gate stopped catching", on a day spent fixing exactly that confusion. Resolve
# a runner in order of reliability, and report UNAVAILABLE separately from FAIL
# so nobody debugs a phantom regression.
if [ -f scripts/lib/gate-registry.ts ]; then
  TSRUN=""
  if [ -x node_modules/.bin/tsx ]; then
    TSRUN="node_modules/.bin/tsx"
  else
    for c in "$HOME"/.npm/_npx/*/node_modules/.bin/tsx; do
      [ -x "$c" ] && TSRUN="$c" && break
    done
    if [ -z "$TSRUN" ] && [ -x node_modules/.bin/ts-node ]; then
      TSRUN="node_modules/.bin/ts-node"
    fi
  fi
  if [ -z "$TSRUN" ]; then
    say "gate-registry (every gate proves its catch)" "UNAVAILABLE — no tsx/ts-node"
    echo "      Install one (npm i -D tsx) so this check cannot silently lapse."
    echo "      NOT counted as a failure: the gates are unproven here, not broken."
  elif "$TSRUN" scripts/lib/gate-registry.ts --selftest >/dev/null 2>&1; then
    say "gate-registry (every gate proves its catch)" "ok"
  else
    say "gate-registry (every gate proves its catch)" "FAIL"; fail=1
  fi
fi

# Claim provenance across every registry in the tree. A stale or unbacked
# number is the failure mode this whole layer exists for.
# nullglob is a bashism; an unmatched glob must be skipped explicitly instead.
for reg in out/*/_claims/*.json; do
  [ -e "$reg" ] || continue
  if $PY scripts/lib/claim_provenance_gate.py --claims "$reg" >/dev/null 2>&1; then
    say "claims backed: $(basename "$(dirname "$(dirname "$reg")")")" "ok"
  else
    say "claims backed: $(basename "$(dirname "$(dirname "$reg")")")" "STALE/UNBACKED"
    $PY scripts/lib/claim_provenance_gate.py --claims "$reg" 2>&1 | sed 's/^/      /'
    fail=1
  fi
done

# CAPABILITY LOOKUP: design must not proceed without knowing what already
# exists. SCOPED TO ACTIVE TWINS ONLY — this repo holds 1594 out/ directories,
# and a hook that blocks on all of them is a hook that gets disabled within a
# day. A gate everyone bypasses is worse than no gate. "Active" = state.json
# touched in the last 2 days, which is the work anyone is actually doing.
# GOTCHA: husky invokes this under `sh` on some hosts; process substitution
# `< <(find …)` is a bashism and syntax-errors the whole hook. Prefer a
# plain find|while (fail stamp so the pipe subshell can still trip fail).
rm -f /tmp/forge-precommit-cap-fail.$$
find out -maxdepth 2 -name state.json -mtime -2 2>/dev/null | while IFS= read -r tw; do
  [ -n "$tw" ] || continue
  d="$(dirname "$tw")"
  if [ -f "$d/_capability/capability_dossier.json" ]; then
    say "capability dossier: $(basename "$d")" "present"
  else
    say "capability dossier: $(basename "$d")" "MISSING — run capability_lookup_stage"
    echo 1 > /tmp/forge-precommit-cap-fail.$$
  fi
done
if [ -f /tmp/forge-precommit-cap-fail.$$ ]; then
  fail=1
  rm -f /tmp/forge-precommit-cap-fail.$$
fi

# FINISH-COUNCIL ARTEFACT for load-bearing work. Running the models costs money
# and minutes, so the hook does NOT call them — it checks that SOMEBODY did,
# for an ACTIVE twin, within the last day. Existence is free; the council stays
# explicit via `p_stage_discipline.py finish`. This is the check that would
# have fired after the path-current fix and after the baseline measurement,
# neither of which was ever reviewed by a finish council.
if git diff --cached --name-only 2>/dev/null | grep -qE '^scripts/(motor-stack|lib)/.*\.(py|ts)$'; then
  # ⭐ BIND THE COUNCIL TO THIS CHANGE (Sol, finish council 2026-08-02). The
  # first version accepted any finish council under a day old, from any twin —
  # so an unrelated twin's council authorised every staged engine edit, coupling
  # the gate to mtimes rather than to the code under review. The panel must now
  # be NEWER THAN THE NEWEST STAGED ENGINE FILE, i.e. it must have seen this
  # diff. Still not proof it reviewed these lines; it is the cheapest binding
  # that an existence check can honestly make.
  # PATHNAME-SAFE (Sol, finish council 2026-08-02): `for f in $(...)` splits on
  # whitespace, and this repo contains a directory literally named
  # "Tier 1 and 2 parts for cad /". Read line by line instead. The `newest`
  # stamp is carried through a temp file because the while-loop runs in a
  # subshell on a pipe.
  newest_staged=""
  stampfile="${TMPDIR:-/tmp}/forge-newest-staged.$$"
  : > "$stampfile"
  git diff --cached --name-only 2>/dev/null \
    | grep -E '^scripts/(motor-stack|lib)/.*\.(py|ts)$' \
    | while IFS= read -r f; do
        [ -f "$f" ] || continue
        prev="$(cat "$stampfile")"
        if [ -z "$prev" ] || [ "$f" -nt "$prev" ]; then printf '%s' "$f" > "$stampfile"; fi
      done
  newest_staged="$(cat "$stampfile")"
  rm -f "$stampfile"
  # A fresh mtime is not a review (Sol #1): verify-panel additionally requires
  # two responding seats and EVERY finding answered, so a panel where all three
  # seats blocked cannot authorise anything. GOTCHA: the while-loop below runs
  # in a subshell on a pipe, so the verdict travels through a stamp file — the
  # same trap the capability check above already documents.
  councilstamp="${TMPDIR:-/tmp}/forge-council-ok.$$"
  rm -f "$councilstamp"
  find out -maxdepth 2 -name state.json -mtime -2 2>/dev/null | while IFS= read -r sj; do
    twin="$(dirname "$sj")"
    for panel in "$twin"/_discipline/*-finish-council.json; do
      [ -e "$panel" ] || continue
      if [ -z "$newest_staged" ] || [ "$panel" -nt "$newest_staged" ]; then
        if $PY scripts/lib/p_stage_discipline.py verify-panel --panel "$panel" --against-staged --refuse-truncated --twin "$twin" >/dev/null 2>&1; then
          echo 1 > "$councilstamp"
          say "finish council: $(basename "$panel")" "reviewed THIS diff + fully answered"
        else
          say "finish council: $(basename "$panel")" "NOT fully answered"
          $PY scripts/lib/p_stage_discipline.py verify-panel --panel "$panel" --against-staged --refuse-truncated --twin "$twin" 2>&1 | sed 's/^/      /'
        fi
      fi
    done
  done
  found_recent_council=0
  if [ -f "$councilstamp" ]; then found_recent_council=1; rm -f "$councilstamp"; fi
  if [ "$found_recent_council" -eq 0 ] && [ -n "$newest_staged" ]; then
    echo "      newest staged engine file: $newest_staged"
    echo "      (a panel older than that did not see this change)"
  fi
  if [ "$found_recent_council" -eq 0 ]; then
    say "finish council for staged engine work" "MISSING"
    echo "      No <twin>/_discipline/*-finish-council.json from the last day."
    echo "      Run:  .venv/bin/python scripts/lib/p_stage_discipline.py finish \\"
    echo "              --stage-id <id> --twin <twin> --claim \"<numbers>\" \\"
    echo "              --produced <artefacts...> --next \"<next>\""
    fail=1
  fi
fi

if [ "$fail" -ne 0 ]; then
  cat <<'MSG'

COMMIT BLOCKED. Fix the above, or `git commit --no-verify` deliberately.

The council is NOT run here (it costs money and minutes) — but it is not
optional either. `p_stage_discipline.py finish` runs council_precommit_review
on the staged diff and stamps the panel with that diff's sha256, and the check
above refuses a panel that reviewed DIFFERENT code. So the order is:

  1. stage your change
  2. .venv/bin/python scripts/lib/p_stage_discipline.py finish \
         --stage-id <id> --twin <twin> --claim "<the numbers>" \
         --produced <artefacts...> --next "<next>"
  3. answer every finding, then commit

Running `finish` must be the LAST action before committing: answering a council
means editing code, which changes the diff and correctly invalidates the panel
that demanded the edit.

MSG
  exit 1
fi
echo "── all structural checks pass ──"
exit 0
HOOKEOF

chmod +x "$HOOK"
echo "installed: $HOOK"
echo "verify with: git commit --allow-empty -m 'hook check'"
