/**
 * @file radical/demo/render-bom.ts
 *
 * Markdown BOM renderer for the BESS Radical demo.
 *
 * Outputs:
 *   1. Cover page summary block (totals + grammar verdict + budget flag)
 *   2. BOM table (one row per resolved leaf)
 *   3. Grammar verdicts paragraph
 *   4. Cost waterfall section
 */

import type { ResolvedLeaf } from './resolution.js'
import type { GrammarPassResult } from './grammar-pass.js'
import type { CostRollup } from './cost-rollup.js'
import type { EngineResult } from '../grammar.js'

// ---------------------------------------------------------------------------
// Helpers
// ---------------------------------------------------------------------------

function gbp(n: number | null, decimals = 0): string {
  if (n === null) return '—'
  return '£' + n.toLocaleString('en-GB', { minimumFractionDigits: decimals, maximumFractionDigits: decimals })
}

function statusIcon(grade: string): string {
  switch (grade) {
    case 'verified': return '✓ VERIFIED'
    case 'grade_c': return '◐ GRADE-C'
    case 'estimated': return '~ EST'
    case 'grade_d': return '⚠ GRADE-D'
    case 'stub': return '○ STUB'
    default: return '? UNKNOWN'
  }
}

function vendorLabel(leaf: ResolvedLeaf): string {
  if (leaf.distributor === 'vendor_catalog' && leaf.manufacturer) return leaf.manufacturer
  if (leaf.distributor === 'mouser') return 'Mouser'
  if (leaf.distributor === 'digikey') return 'Digi-Key'
  if (leaf.distributor === 'farnell') return 'Farnell'
  if (leaf.distributor === 'lcsc') return 'LCSC'
  if (leaf.manufacturer) return leaf.manufacturer
  return '—'
}

function leadLabel(leaf: ResolvedLeaf): string {
  if (leaf.lead_weeks !== null) return `${leaf.lead_weeks}w`
  // OEM subsystems — use catalog hints
  if (leaf.distributor === 'vendor_catalog') return 'see catalog'
  if (leaf.distributor === 'mouser' || leaf.distributor === 'digikey' || leaf.distributor === 'farnell') {
    return '2–4 days'  // Standard stocked distributor lead time
  }
  return '—'
}

function verdictBadge(verdict: string): string {
  switch (verdict) {
    case 'PASS': return '✓ PASS'
    case 'PASS_WITH_RELAXATION': return '~ PASS (relaxed)'
    case 'BLOCK': return '✗ BLOCK'
    default: return verdict
  }
}

// ---------------------------------------------------------------------------
// Main render function
// ---------------------------------------------------------------------------

export function renderBom(
  resolvedLeaves: ResolvedLeaf[],
  grammarPass: GrammarPassResult,
  costRollup: CostRollup,
): string {
  const lines: string[] = []
  const systemTotal = costRollup.sentence.total_gbp
  const budgetTarget = 1_500_000  // £1.5M typical BESS container benchmark
  const overBudget = systemTotal > budgetTarget

  const verifiedCount = resolvedLeaves.filter(l => l.verification_grade === 'verified').length
  const gradeCCount = resolvedLeaves.filter(l => l.verification_grade === 'grade_c').length
  const estimatedCount = resolvedLeaves.filter(l => l.verification_grade === 'estimated').length
  const gradeDCount = resolvedLeaves.filter(l => l.verification_grade === 'grade_d').length
  const stubCount = resolvedLeaves.filter(l => l.verification_grade === 'stub').length
  const withMpn = resolvedLeaves.filter(l => l.mpn !== null).length

  // ── Cover page summary ─────────────────────────────────────────────────────
  lines.push(`# BESS 3.5 MWh / 1 MW — Radical Architecture BOM`)
  lines.push(``)
  lines.push(`> Generated by Fractional ForgeOS — Radical Architecture demo`)
  lines.push(`> Date: ${new Date().toISOString().slice(0, 10)}`)
  lines.push(``)
  lines.push(`## System Summary`)
  lines.push(``)
  lines.push(`| Field | Value |`)
  lines.push(`|---|---|`)
  lines.push(`| **System** | BESS Container 3.5 MWh / 1 MW, 40-ft ISO, LFP prismatic |`)
  lines.push(`| **BOM lines** | ${resolvedLeaves.length} |`)
  lines.push(`| **Lines with real MPN** | ${withMpn} / ${resolvedLeaves.length} (${Math.round(withMpn / resolvedLeaves.length * 100)}%) |`)
  lines.push(`| **Verified by distributor** | ${verifiedCount} lines |`)
  lines.push(`| **From vendor catalog** | ${estimatedCount} lines |`)
  lines.push(`| **Catalog-Priced (Grade C)** | ${gradeCCount} lines |`)
  lines.push(`| **Grade-D (no price data)** | ${gradeDCount} lines |`)
  lines.push(`| **Structural stub** | ${stubCount} lines |`)
  lines.push(`| **System total (incl. integration markup)** | **${gbp(systemTotal)}** |`)
  lines.push(`| **Budget target** | ${gbp(budgetTarget)} |`)
  lines.push(`| **Budget status** | ${overBudget ? '⚠ OVER BUDGET' : '✓ WITHIN BUDGET'} |`)
  lines.push(`| **Grammar verdict** | ${verdictBadge(grammarPass.engineResult.overallVerdict)} |`)
  lines.push(``)

  // ── BOM table ──────────────────────────────────────────────────────────────
  lines.push(`## Bill of Materials`)
  lines.push(``)
  lines.push(`| Status | Part Name | Type | Qty | MPN | Unit £ | Total £ | Vendor | Lead |`)
  lines.push(`|---|---|---|---|---|---|---|---|---|`)

  for (const leaf of resolvedLeaves) {
    const status = statusIcon(leaf.verification_grade)
    const typeLabel = leaf.part_class.replace(/_/g, ' ')
    const mpnDisplay = leaf.mpn ?? '—'
    const unitPrice = leaf.unit_price_gbp !== null ? gbp(leaf.unit_price_gbp, 2) : '—'
    const lineTotal = leaf.unit_price_gbp !== null ? gbp(leaf.unit_price_gbp * leaf.qty, 0) : '—'
    const vendor = vendorLabel(leaf)
    const lead = leadLabel(leaf)
    const name = leaf.name.length > 45 ? leaf.name.slice(0, 42) + '...' : leaf.name

    lines.push(`| ${status} | ${name} | ${typeLabel} | ${leaf.qty} | ${mpnDisplay} | ${unitPrice} | ${lineTotal} | ${vendor} | ${lead} |`)
  }

  lines.push(``)

  // ── Cost waterfall ─────────────────────────────────────────────────────────
  lines.push(`## Cost Waterfall`)
  lines.push(``)
  lines.push(`| Module (Word) | Parts £ | Markup (15%+20%) | Total £ |`)
  lines.push(`|---|---|---|---|`)

  for (const word of costRollup.words) {
    lines.push(`| ${word.module_label} | ${gbp(word.subtotal_parts_gbp)} | +${word.markup_pct.toFixed(0)}% (${gbp(word.markup_gbp)}) | ${gbp(word.total_gbp)} |`)
  }

  lines.push(`| **Subtotal (words)** | | | **${gbp(costRollup.sentence.word_subtotal_gbp)}** |`)
  lines.push(`| System integration (+25%) | | +${gbp(costRollup.sentence.sentence_markup_gbp)} | |`)
  lines.push(`| **SYSTEM TOTAL** | | | **${gbp(costRollup.sentence.total_gbp)}** |`)
  lines.push(``)

  // Top cost drivers
  lines.push(`### Top Cost Drivers`)
  lines.push(``)
  for (const driver of costRollup.sentence.top_cost_drivers) {
    lines.push(`1. **${driver.name}** — ${gbp(driver.total_gbp)} (${driver.pct_of_system.toFixed(1)}% of system cost)`)
  }
  lines.push(``)

  // ── Grammar verdicts ───────────────────────────────────────────────────────
  lines.push(`## Grammar Verdicts`)
  lines.push(``)
  lines.push(`Overall: **${verdictBadge(grammarPass.engineResult.overallVerdict)}**`)
  lines.push(``)
  lines.push(`| Rule | Weight | Verdict | Reason |`)
  lines.push(`|---|---|---|---|`)

  for (const r of grammarPass.engineResult.ruleResults) {
    const verdictCell = r.relaxed ? `${r.verdict} [RELAXED]` : r.verdict
    const reason = r.reason.length > 80 ? r.reason.slice(0, 77) + '...' : r.reason
    const weight = r.weight === Infinity ? '∞ (hard)' : `${r.weight}`
    lines.push(`| \`${r.ruleId}\` | ${weight} | ${verdictCell} | ${reason} |`)
  }

  if (grammarPass.engineResult.relaxationSummary.length > 0) {
    lines.push(``)
    lines.push(`### Relaxations Applied`)
    lines.push(``)
    for (const relax of grammarPass.engineResult.relaxationSummary) {
      lines.push(`- ${relax}`)
    }
  }

  lines.push(``)
  lines.push(`---`)
  lines.push(``)
  lines.push(`*ForgeOS Radical Architecture — BESS Demo — ${new Date().toISOString()}*`)

  return lines.join('\n')
}
