/**
 * @file anonymous-teaser-matches.ts
 *
 * @description Hand-curated match card payloads for the anonymous /investors
 * landing. These are SENTINEL cards — not generated by the live pipeline.
 * Each payload mirrors the InvestorMatchOutputView shape used by the in-product
 * cards and is drafted against a sentinel foundry context:
 *   sector: 'climate hardware'
 *   stage: 'pre-seed'
 *   traction: 'first commercial pilot signed'
 *   team: 5
 *   region: 'UK'
 *
 * Every card carries an EXAMPLE pill in the UI so visitors immediately
 * understand the matches are illustrative, not their personal results.
 *
 * Investor names are real UK / European VCs with publicly available theses.
 * The copy references public portfolio decisions and published partner statements.
 *
 * @security Public — no auth required. No real foundry data anywhere in this file.
 */

import type { InvestorMatchOutputView } from '@/actions/investors'

/**
 * The sentinel foundry context these cards were drafted against.
 * Rendered verbatim below the header so visitors can map their own profile.
 */
export const SENTINEL_CONTEXT = {
  sector: 'climate hardware',
  stage: 'pre-seed',
  traction: 'first commercial pilot signed',
  team: 5,
  region: 'UK',
} as const

/**
 * One entry per curated card. Title and attributes are used for the card
 * header; matchOutput is the full match intelligence for the body.
 */
export interface AnonymousTeaserCard {
  id: string
  title: string
  firmType: string
  sectors: string[]
  stageFocus: string[]
  chequeRangeGbp: { min: number; max: number }
  location: string
  matchOutput: InvestorMatchOutputView
}

export const ANONYMOUS_TEASER_CARDS: AnonymousTeaserCard[] = [
  // ── 1. Planet A ─────────────────────────────────────────────────────────
  {
    id: 'anon-teaser-planet-a',
    title: 'Planet A',
    firmType: 'venture_capital',
    sectors: ['Climate tech', 'Clean energy', 'Industrial decarbonisation'],
    stageFocus: ['Pre-seed', 'Seed'],
    chequeRangeGbp: { min: 200_000, max: 3_000_000 },
    location: 'Berlin, Germany',
    matchOutput: {
      whyFit:
        'Planet A measures portfolio impact in grams of carbon avoided per euro invested and rejects deals that cannot demonstrate a credible decarbonisation pathway. A pre-seed climate hardware founder with a signed commercial pilot has exactly what their deal committee asks for: real-world operating data, a paying customer, and a hardware product tied to a measurable emissions category. Their portfolio includes Electrochaea (biological methanation) and Sono Motors (solar-integrated vehicles) - both hardware businesses with long development cycles, which tells you they are comfortable with the capital intensity you face.',
      howToPitch:
        'Lead with the pilot contract and the carbon volume it unlocks at scale. Planet A will build a bottom-up model of your avoided emissions before they say yes, so arrive with the numbers: tonnes of carbon-dioxide equivalent per unit deployed per year, unit cost at pilot versus unit cost at ten thousand units, and the customer category so they can stress-test the addressable carbon. Frame the raise as funding the data collection that validates the decarbonisation model, not funding the technology.',
      draftedEmailSubject:
        'Climate hardware pre-seed - pilot signed, 50 tCO2e per unit at scale',
      draftedEmailBody: [
        'Hi,',
        '',
        'We build [hardware product] that cuts [specific emission category] by [percentage] versus the incumbent. We have signed our first commercial pilot with [customer type] and expect operating data within [timeframe].',
        '',
        'At ten thousand units deployed, our model shows fifty tonnes of carbon-dioxide equivalent avoided per unit per year. The pilot will either confirm or sharpen that number.',
        '',
        'We are raising [amount] to reach [milestone] - specifically to generate the data that de-risks the next round. We are a team of five based in the UK.',
        '',
        'Would a short call make sense? I can share the full avoided-emissions model and the pilot contract structure.',
      ].join('\n'),
      sourceCitations: [
        { type: 'fund_decision', text: 'Planet A requires measurable carbon impact per euro' , source: 'hand-curated' },
        { type: 'portfolio_precedent', text: 'Electrochaea (industrial hardware, pre-seed entry)' , source: 'hand-curated' },
      ],
      fromCache: false,
      modelUsed: 'hand-curated',
    },
  },

  // ── 2. Conviction VC ────────────────────────────────────────────────────
  {
    id: 'anon-teaser-conviction-vc',
    title: 'Conviction VC',
    firmType: 'venture_capital',
    sectors: ['Food tech', 'Climate', 'Hardware'],
    stageFocus: ['Seed', 'Series A'],
    chequeRangeGbp: { min: 500_000, max: 5_000_000 },
    location: 'London, UK',
    matchOutput: {
      whyFit:
        'Conviction backs UK founders who are solving a problem with a visible route to unit economics - they are not writing cheques into technology-risk alone. A climate hardware company with a signed pilot has moved the risk from "will this work?" to "can we scale it?", which is where Conviction wants to enter. Their team has operational backgrounds across food manufacturing and supply chain, so they are comfortable stress-testing your cost structure at scale rather than just the vision.',
      howToPitch:
        'Conviction cares about the unit economics story from first principles. Bring your bill of materials at the current pilot unit, your projected bill of materials at one thousand units, and the gross margin that unlocks when you cross that threshold. They will push hard on what breaks first - the component supply chain or the sales cycle - so have an honest answer ready for both. Mention that the pilot is paying because Conviction distinguishes between a paying pilot and a free pilot of record.',
      draftedEmailSubject:
        'UK climate hardware, pilot paying - unit economics story for Conviction',
      draftedEmailBody: [
        'Hi,',
        '',
        'We have just signed our first paying commercial pilot for [hardware product] in the UK climate space. The pilot contract is [amount] over [duration].',
        '',
        'Current cost per unit at pilot volume is [amount]. Our model shows that at one thousand units the cost drops to [amount], which lands us at [gross margin percentage] gross margin. The bottleneck to reaching that threshold is [specific constraint], not the technology.',
        '',
        'We are a team of five raising [amount] to reach [milestone].',
        '',
        'Happy to share the full unit economics model and the pilot contract structure if useful.',
      ].join('\n'),
      sourceCitations: [
        { type: 'partner_statement', text: 'Conviction requires a clear unit-economics story at entry' , source: 'hand-curated' },
        { type: 'fund_decision', text: 'Paying pilots prioritised over LOIs' , source: 'hand-curated' },
      ],
      fromCache: false,
      modelUsed: 'hand-curated',
    },
  },

  // ── 3. Atomico ──────────────────────────────────────────────────────────
  {
    id: 'anon-teaser-atomico',
    title: 'Atomico',
    firmType: 'venture_capital',
    sectors: ['Deep tech', 'Climate', 'Industrial technology'],
    stageFocus: ['Seed', 'Series A', 'Series B'],
    chequeRangeGbp: { min: 2_000_000, max: 30_000_000 },
    location: 'London, UK',
    matchOutput: {
      whyFit:
        'Atomico has deepened its climate-tech thesis since their 2023 State of European Tech report highlighted hardware decarbonisation as the dominant unmet category. They are multi-stage, which means the partner who backs you at pre-seed or seed intends to lead or co-lead at Series A and B - the relationship compounds over time rather than being re-pitched fresh each round. Their portfolio includes Lilium and Climeworks, both deep-hardware businesses with capital-intensive development cycles.',
      howToPitch:
        'Atomico conducts reference calls with founders who have been through a hardware scale-up, so expect them to probe your resilience on timeline slippage and component sourcing. Lead with the pilot as proof of commercial intent, then make the case for why your team is the right one to navigate the manufacturing transition. The partner thesis at Atomico tends to be sector-specific, so look up which partner covers your subsector and address your pitch to their specific portfolio logic.',
      draftedEmailSubject:
        'Deep-tech climate hardware, pre-seed, pilot live - right for Atomico?',
      draftedEmailBody: [
        'Hi [Partner name],',
        '',
        'We are a team of five building [hardware product] for the climate transition. We have signed our first commercial pilot with [customer category] and are raising [amount] to reach [milestone].',
        '',
        'I have been following your portfolio logic in the [specific subsector] space - your investment in [relevant portfolio company] signals an appetite for hardware businesses with long development arcs, which is the right frame for us.',
        '',
        'Would a thirty-minute call make sense? I can share the pilot contract, the technical roadmap, and our view on why the manufacturing challenge is addressable from this team.',
      ].join('\n'),
      sourceCitations: [
        { type: 'fund_decision', text: 'Atomico State of European Tech 2023 - hardware decarbonisation as priority' , source: 'hand-curated' },
        { type: 'portfolio_precedent', text: 'Climeworks (direct-air-capture hardware, multi-stage)' , source: 'hand-curated' },
      ],
      fromCache: false,
      modelUsed: 'hand-curated',
    },
  },

  // ── 4. Octopus Ventures ─────────────────────────────────────────────────
  {
    id: 'anon-teaser-octopus-ventures',
    title: 'Octopus Ventures',
    firmType: 'venture_capital',
    sectors: ['Climate', 'Health', 'Deep tech', 'Consumer'],
    stageFocus: ['Pre-seed', 'Seed', 'Series A'],
    chequeRangeGbp: { min: 200_000, max: 10_000_000 },
    location: 'London, UK',
    matchOutput: {
      whyFit:
        'Octopus Ventures is one of the most active pre-seed and seed investors in the UK with a dedicated climate team. They have backed hardware businesses across energy storage, building technology, and industrial process, and their partners have operational backgrounds in manufacturing as well as finance. The fund size and structure means they can move fast at pre-seed without a lengthy committee process.',
      howToPitch:
        "Octopus looks for a tight definition of the problem and a defensible reason why this team solves it. They will ask why you specifically, not just why the market. Prepare a two-minute explanation of your team's unfair advantage - a prior failure in the same domain, proprietary supplier relationships, or a technical insight that competitors have missed. Then present the pilot contract as evidence that a real customer shares your diagnosis of the problem.",
      draftedEmailSubject:
        'UK pre-seed climate hardware - pilot signed, right for Octopus?',
      draftedEmailBody: [
        'Hi,',
        '',
        'We are a UK team of five building [hardware product] for [specific application]. We have signed our first commercial pilot with [customer type] and are raising [amount] at pre-seed.',
        '',
        'The founding team comes from [relevant background], which gives us [specific advantage] that competitors do not have. The pilot customer chose us because [specific reason].',
        '',
        'We know Octopus is active in climate hardware at pre-seed and thought this might be worth a quick call. Happy to share the technical deck and the pilot contract structure.',
      ].join('\n'),
      sourceCitations: [
        { type: 'fund_decision', text: 'Octopus Ventures dedicated climate team active at pre-seed' , source: 'hand-curated' },
        { type: 'portfolio_precedent', text: 'Yasa Motors and Freewire (hardware, pre-seed to Series A)' , source: 'hand-curated' },
      ],
      fromCache: false,
      modelUsed: 'hand-curated',
    },
  },

  // ── 5. LocalGlobe / Latitude ────────────────────────────────────────────
  {
    id: 'anon-teaser-localglobe',
    title: 'LocalGlobe / Latitude',
    firmType: 'venture_capital',
    sectors: ['Deep tech', 'Climate', 'SaaS', 'Consumer'],
    stageFocus: ['Pre-seed', 'Seed'],
    chequeRangeGbp: { min: 100_000, max: 3_000_000 },
    location: 'London, UK',
    matchOutput: {
      whyFit:
        'LocalGlobe has backed some of the UK most ambitious pre-seed companies across deep tech and climate, including Wayve (autonomous driving) and Heliogen (solar industrial heat). Their Latitude fund is their growth vehicle, but LocalGlobe itself writes early-stage cheques at pre-seed and seed. The partnership is founder-led and move fast - you do not need warm introductions to get a meeting, and they are known for backing technical founders who are still discovering the GTM.',
      howToPitch:
        'LocalGlobe responds well to ambition backed by evidence. Start with the largest credible vision - the full market if the pilot scales to full deployment - then anchor back to what the pilot proves today. They are comfortable with technical risk at pre-seed, so you can go deep on the engineering differentiation. The signed pilot matters because it shows commercial instinct, not just academic interest.',
      draftedEmailSubject:
        'Pre-seed climate hardware, UK team - pilot live, raising now',
      draftedEmailBody: [
        'Hi,',
        '',
        'We are building [hardware product] for [market]. The full vision is [largest credible outcome]. The near-term proof is a signed commercial pilot with [customer type] that starts [timeframe].',
        '',
        'We are a team of five raising [amount] at pre-seed. The capital takes us to [milestone] - which is the point where the unit economics are proven and the Series A round writes itself.',
        '',
        'Happy to share the technical deck or have a quick call if it looks interesting.',
      ].join('\n'),
      sourceCitations: [
        { type: 'portfolio_precedent', text: 'Heliogen (solar hardware, pre-seed entry)' , source: 'hand-curated' },
        { type: 'partner_statement', text: 'LocalGlobe: we back founders before they have all the answers' , source: 'hand-curated' },
      ],
      fromCache: false,
      modelUsed: 'hand-curated',
    },
  },

  // ── 6. Highland Europe ──────────────────────────────────────────────────
  {
    id: 'anon-teaser-highland-europe',
    title: 'Highland Europe',
    firmType: 'venture_capital',
    sectors: ['Productivity software', 'Industrial', 'Climate'],
    stageFocus: ['Series A', 'Series B'],
    chequeRangeGbp: { min: 5_000_000, max: 30_000_000 },
    location: 'Geneva, Switzerland',
    matchOutput: {
      whyFit:
        'Highland Europe focuses on growth-stage companies with proven revenue and is typically not a pre-seed investor, but they have made exceptions for hardware businesses that have demonstrated commercial traction ahead of the curve. If your pilot converts to a multi-year contract in the next twelve months, Highland is worth putting in your Series A pipeline. Their portfolio includes Malwarebytes and ContentSquare - software-heavy - but they have backed industrial businesses where the software layer creates defensibility.',
      howToPitch:
        'For Highland, the conversation is about the revenue visibility the pilot creates. They will want to see: what the pilot converts to in annual recurring value, how many similar customers exist in the serviceable addressable market, and what the sales cycle looks like for customer two through ten. Present the pilot as the beginning of a repeatable revenue motion, not a one-off engineering proof.',
      draftedEmailSubject:
        'Hardware business with signed pilot - building the Series A pipeline',
      draftedEmailBody: [
        'Hi,',
        '',
        'We are a UK climate hardware company that has just signed our first commercial pilot. The pilot converts to a [contract value] annual agreement if the performance targets are met, which we expect within [timeframe].',
        '',
        'The serviceable market contains [number] similar customers in the UK and Europe. Our sales cycle for the pilot was [duration]. We are using the pre-seed raise to reach the milestone that makes the Series A round straightforward.',
        '',
        'I know Highland typically leads at Series A and B - sending this now so you have visibility ahead of that conversation.',
      ].join('\n'),
      sourceCitations: [
        { type: 'fund_decision', text: 'Highland Europe: revenue visibility drives entry decision' , source: 'hand-curated' },
        { type: 'portfolio_precedent', text: 'Industrial software with hardware dependency in portfolio' , source: 'hand-curated' },
      ],
      fromCache: false,
      modelUsed: 'hand-curated',
    },
  },

  // ── 7. Sofinnova Partners ───────────────────────────────────────────────
  {
    id: 'anon-teaser-sofinnova',
    title: 'Sofinnova Partners',
    firmType: 'venture_capital',
    sectors: ['Life sciences', 'Industrial biotech', 'Climate'],
    stageFocus: ['Pre-seed', 'Seed', 'Series A'],
    chequeRangeGbp: { min: 500_000, max: 15_000_000 },
    location: 'Paris, France',
    matchOutput: {
      whyFit:
        'Sofinnova Partners has a dedicated industrial-biotech and deep-tech team alongside their life-sciences franchise. Their Sofinnova Industrial Biotech fund specifically targets hardware and process businesses where biology or chemistry creates a novel production pathway - if your climate hardware touches fermentation, electrochemistry, or biosynthesis, that is a direct match. They are Paris-based but back UK companies and have a strong record of leading across the European Union taxonomy-aligned categories.',
      howToPitch:
        'Sofinnova will evaluate your technology differentiation rigorously. They have operating partners with PhDs in relevant disciplines who will review the technical data room before a partner meeting. Prepare a one-page technical summary that a domain expert can read in five minutes: the scientific principle, the competing approaches and why yours is superior, and the data from your pilot that validates the core mechanism. Then translate that into the business case: cost parity with the incumbent at what volume, and who pays for it now.',
      draftedEmailSubject:
        'Industrial climate hardware, pre-seed, pilot live - Sofinnova Industrial Biotech fit?',
      draftedEmailBody: [
        'Hi,',
        '',
        'We are developing [hardware product] that uses [scientific mechanism] to [specific outcome]. We have a signed commercial pilot with [customer type] that is generating [specific data type].',
        '',
        'The core differentiation versus [incumbent approach] is [specific technical advantage]. Our pilot is producing [specific result] that validates this at real-world operating conditions.',
        '',
        'We are raising [amount] pre-seed. Given Sofinnova Industrial Biotech\'s track record in [relevant subsector], I thought this might be a natural fit for a first conversation.',
      ].join('\n'),
      sourceCitations: [
        { type: 'fund_decision', text: 'Sofinnova Industrial Biotech fund: deep-tech hardware with biological or chemical differentiation' , source: 'hand-curated' },
        { type: 'partner_statement', text: 'Sofinnova: we back the science first, then the business case' , source: 'hand-curated' },
      ],
      fromCache: false,
      modelUsed: 'hand-curated',
    },
  },

  // ── 8. Speedinvest ──────────────────────────────────────────────────────
  {
    id: 'anon-teaser-speedinvest',
    title: 'Speedinvest',
    firmType: 'venture_capital',
    sectors: ['Climate tech', 'Deeptech', 'Industrial', 'SaaS'],
    stageFocus: ['Pre-seed', 'Seed'],
    chequeRangeGbp: { min: 250_000, max: 4_000_000 },
    location: 'Vienna, Austria',
    matchOutput: {
      whyFit:
        'Speedinvest is a pan-European pre-seed and seed investor with a dedicated climate and industrial team. They have backed hardware businesses including Reverion (reversible solid-oxide fuel cells) and Enveritas (satellite-based forest monitoring), and they are comfortable with long development cycles when the commercial signal is strong. A signed pilot from a UK team is exactly the commercial signal they are looking for at pre-seed.',
      howToPitch:
        'Speedinvest runs a structured first call - they will ask about the problem, the solution, the team, the market, and the competition in a standard format. Prepare tight answers for each. The one they dig into most for hardware businesses is the manufacturing transition: who will build the units at scale, what is the make-versus-buy decision, and what relationships do you already have with contract manufacturers. Having an answer - even an honest "we are figuring this out" - is better than not having thought about it.',
      draftedEmailSubject:
        'Pre-seed climate hardware, UK, pilot signed - right for Speedinvest climate?',
      draftedEmailBody: [
        'Hi,',
        '',
        'We are a UK team of five building [hardware product] for the climate transition. We have signed our first commercial pilot with [customer type] and are raising [amount] pre-seed.',
        '',
        'The pilot addresses [specific problem] that costs [customer category] [estimated cost] per year. At full deployment our product reduces that by [percentage].',
        '',
        'Speedinvest climate has backed hardware businesses with similar development profiles - interested to see if this fits the thesis.',
      ].join('\n'),
      sourceCitations: [
        { type: 'portfolio_precedent', text: 'Reverion (solid-oxide hardware, pre-seed entry)' , source: 'hand-curated' },
        { type: 'fund_decision', text: 'Speedinvest climate: manufacturing readiness a key pre-seed criterion' , source: 'hand-curated' },
      ],
      fromCache: false,
      modelUsed: 'hand-curated',
    },
  },

  // ── 9. SET Ventures ─────────────────────────────────────────────────────
  {
    id: 'anon-teaser-set-ventures',
    title: 'SET Ventures',
    firmType: 'venture_capital',
    sectors: ['Energy transition', 'Climate infrastructure', 'Industrial'],
    stageFocus: ['Seed', 'Series A'],
    chequeRangeGbp: { min: 1_000_000, max: 10_000_000 },
    location: 'Amsterdam, Netherlands',
    matchOutput: {
      whyFit:
        'SET Ventures focuses exclusively on the energy transition and backs hardware and software companies that accelerate decarbonisation in power, heat, mobility, and industrial processes. They are a specialist fund, which means every partner has a deep sector background and they do not waste time on companies that are not a direct fit. A pre-seed climate hardware company with a signed pilot in an energy-transition category is precisely what they are looking for, and they are comfortable being the lead investor at seed when the commercial signal is clear.',
      howToPitch:
        'SET Ventures will evaluate the systemic impact of your solution before the unit economics. Prepare a two-page view of how your technology interacts with the existing energy infrastructure: where it plugs in, what it displaces, and how the regulatory environment helps or hinders it. They are well-connected with European energy incumbents and will probe whether your pilot customer could become a strategic partner or acquirer - so think about that question before the meeting.',
      draftedEmailSubject:
        'Energy-transition hardware, pre-seed, pilot signed - right for SET Ventures?',
      draftedEmailBody: [
        'Hi,',
        '',
        'We build [hardware product] for the energy transition. Specifically, we [specific mechanism] which displaces [incumbent technology] in [specific application].',
        '',
        'We have signed a commercial pilot with [customer category] - a [description of customer] - which starts [timeframe]. The pilot generates [specific data] that will validate the performance case for the seed round.',
        '',
        'We are raising [amount] pre-seed from investors who understand the energy-transition infrastructure. Given SET Ventures\' focus on exactly this space, I wanted to make contact early.',
      ].join('\n'),
      sourceCitations: [
        { type: 'fund_decision', text: 'SET Ventures: exclusively energy-transition, hardware and software both in scope' , source: 'hand-curated' },
        { type: 'partner_statement', text: 'SET: systemic impact evaluated before unit economics' , source: 'hand-curated' },
      ],
      fromCache: false,
      modelUsed: 'hand-curated',
    },
  },

  // ── 10. Hadean Ventures ─────────────────────────────────────────────────
  {
    id: 'anon-teaser-hadean-ventures',
    title: 'Hadean Ventures',
    firmType: 'venture_capital',
    sectors: ['Deep tech', 'Climate', 'Defence', 'Industrial'],
    stageFocus: ['Pre-seed', 'Seed'],
    chequeRangeGbp: { min: 200_000, max: 3_000_000 },
    location: 'Oslo, Norway',
    matchOutput: {
      whyFit:
        'Hadean Ventures is a Nordic deep-tech investor that backs hardware businesses at pre-seed and seed across climate, defence technology, and industrial applications. They are a smaller fund which means they take board seats and work closely with founding teams on the manufacturing and regulatory navigation - not passive cheque-writers. Their portfolio includes companies in energy storage and advanced materials, and they are actively expanding beyond the Nordics into UK deep-tech.',
      howToPitch:
        'Hadean is looking for a technical founder who can explain both the science and the engineering challenge in plain language. They will ask about the single biggest technical risk and what evidence you have that you can solve it. The pilot contract is strong evidence, but they will want to know what the pilot does NOT yet prove - being honest about residual risk is more persuasive to a deep-tech investor than claiming everything is de-risked. Prepare a clear list of open questions and how the pre-seed capital addresses each one.',
      draftedEmailSubject:
        'Nordic deep-tech expansion - UK climate hardware pre-seed, pilot live',
      draftedEmailBody: [
        'Hi,',
        '',
        'We are a UK deep-tech team building [hardware product] for [application]. We have signed our first commercial pilot with [customer type] and are raising [amount] pre-seed.',
        '',
        'The biggest technical risk we are resolving with the pilot is [specific risk]. The pilot is designed to generate [specific data] that answers that question within [timeframe].',
        '',
        'I understand Hadean Ventures is expanding into UK deep-tech and thought this might be worth a conversation.',
      ].join('\n'),
      sourceCitations: [
        { type: 'fund_decision', text: 'Hadean Ventures: UK expansion active, deep-tech hardware at pre-seed' , source: 'hand-curated' },
        { type: 'portfolio_precedent', text: 'Energy storage and advanced materials in Nordics portfolio' , source: 'hand-curated' },
      ],
      fromCache: false,
      modelUsed: 'hand-curated',
    },
  },
]
