/**
 * Morning Briefing System
 *
 * Cal (Chief of Staff) generates daily morning briefings:
 * - What the AI team accomplished overnight
 * - Key insights and findings
 * - Blockers and issues needing attention
 * - Suggested agenda for the day
 *
 * @module agents/morning-brief
 */

import { supabase } from '@/lib/supabase/server'
import { sendAgentMessage, startCollaboration, addContribution, completeCollaboration } from './collaboration-hub'

// ============================================================================
// TYPES
// ============================================================================

export interface BriefingData {
  foundryId: string
  founderId: string
  date: string // YYYY-MM-DD
}

export interface BriefingSection {
  title: string
  content: string
  priority?: 'critical' | 'important' | 'info'
  actionItems?: string[]
}

export interface MorningBriefing {
  date: string
  sections: BriefingSection[]
  generatedAt: string
}

// ============================================================================
// DATA GATHERING
// ============================================================================

/**
 * Get tasks completed by AI agents since yesterday
 */
async function getOvernightTaskCompletions(foundryId: string, since: Date): Promise<any[]> {
  const { data, error } = await supabase
    .from('tasks')
    .select('*, objectives(title)')
    .eq('foundry_id', foundryId)
    .eq('status', 'Completed')
    .eq('agent_approved', true) // Completed by agents
    .gte('updated_at', since.toISOString())
    .order('updated_at', { ascending: false })

  if (error) {
    console.error('[MorningBrief] Error getting task completions:', error)
    return []
  }

  return data || []
}

/**
 * Get objectives completed by AI agents
 */
async function getOvernightObjectiveCompletions(foundryId: string, since: Date): Promise<any[]> {
  const { data, error } = await supabase
    .from('objectives')
    .select('*')
    .eq('foundry_id', foundryId)
    .eq('status', 'Completed')
    .eq('agent_approved', true)
    .gte('updated_at', since.toISOString())
    .order('updated_at', { ascending: false })

  if (error) {
    console.error('[MorningBrief] Error getting objective completions:', error)
    return []
  }

  return data || []
}

/**
 * Get insights generated by agents
 */
async function getOvernightInsights(foundryId: string, since: Date): Promise<any[]> {
  const { data, error } = await supabase
    .from('agent_insights')
    .select('*')
    .eq('foundry_id', foundryId)
    .gte('created_at', since.toISOString())
    .order('created_at', { ascending: false })
    .limit(20)

  if (error) {
    console.error('[MorningBrief] Error getting insights:', error)
    return []
  }

  return data || []
}

/**
 * Get agent-created objectives pending approval
 */
async function getPendingApprovals(foundryId: string): Promise<{ objectives: any[]; tasks: any[] }> {
  const [objectivesRes, tasksRes] = await Promise.all([
    supabase
      .from('objectives')
      .select('*')
      .eq('foundry_id', foundryId)
      .eq('agent_approved', false)
      .eq('created_by_agent_id', 'not', null)
      .order('created_at', { ascending: false }),
    supabase
      .from('tasks')
      .select('*')
      .eq('foundry_id', foundryId)
      .eq('agent_approved', false)
      .eq('created_by_agent_id', 'not', null)
      .order('created_at', { ascending: false })
  ])

  return {
    objectives: objectivesRes.data || [],
    tasks: tasksRes.data || []
  }
}

/**
 * Get blockers (overdue tasks assigned to agents)
 */
async function getAgentBlockers(foundryId: string): Promise<any[]> {
  const { data, error } = await supabase
    .from('tasks')
    .select('*, objectives(title)')
    .eq('foundry_id', foundryId)
    .eq('agent_approved', true)
    .eq('status', 'Blocked')
    .order('due_date', { ascending: true })

  if (error) {
    console.error('[MorningBrief] Error getting blockers:', error)
    return []
  }

  return data || []
}

/**
 * Get agent action log summary
 */
async function getAgentActivitySummary(foundryId: string, since: Date): Promise<{
  total: number
  byTier: Record<string, number>
  byAgent: Record<string, number>
}> {
  const { data, error } = await supabase
    .from('agent_action_log')
    .select('tier, agent_name, status')
    .eq('foundry_id', foundryId)
    .gte('created_at', since.toISOString())

  if (error) {
    console.error('[MorningBrief] Error getting activity:', error)
    return { total: 0, byTier: {}, byAgent: {} }
  }

  const byTier: Record<string, number> = {}
  const byAgent: Record<string, number> = {}

  for (const entry of data || []) {
    byTier[entry.tier] = (byTier[entry.tier] || 0) + 1
    byAgent[entry.agent_name || 'unknown'] = (byAgent[entry.agent_name || 'unknown'] || 0) + 1
  }

  return { total: data?.length || 0, byTier, byAgent }
}

/**
 * Get recent collaboration sessions
 */
async function getRecentCollaborations(foundryId: string, since: Date): Promise<any[]> {
  const { data, error } = await supabase
    .from('agent_collaboration_sessions')
    .select('*, agent_collaboration_contributions(*)')
    .eq('foundry_id', foundryId)
    .gte('created_at', since.toISOString())
    .in('status', ['completed', 'synthesizing'])
    .order('completed_at', { ascending: false })

  if (error) {
    console.error('[MorningBrief] Error getting collaborations:', error)
    return []
  }

  return data || []
}

// ============================================================================
// BRIEFING GENERATION
// ============================================================================

/**
 * Generate the morning briefing content
 */
export async function generateMorningBriefing(
  foundryId: string,
  founderId: string
): Promise<MorningBriefing> {
  const now = new Date()
  const since = new Date(now.getTime() - 24 * 60 * 60 * 1000) // 24 hours ago

  // Gather all data in parallel
  const [
    completedTasks,
    completedObjectives,
    insights,
    pendingApprovals,
    blockers,
    activity,
    collaborations
  ] = await Promise.all([
    getOvernightTaskCompletions(foundryId, since),
    getOvernightObjectiveCompletions(foundryId, since),
    getOvernightInsights(foundryId, since),
    getPendingApprovals(foundryId),
    getAgentBlockers(foundryId),
    getAgentActivitySummary(foundryId, since),
    getRecentCollaborations(foundryId, since)
  ])

  const sections: BriefingSection[] = []

  // Section 1: Executive Summary
  const totalCompleted = completedTasks.length + completedObjectives.length
  const summaryContent = `Your AI team completed **${totalCompleted} items** in the last 24 hours, including ${completedObjectives.length} objectives and ${completedTasks.length} tasks.`

  sections.push({
    title: 'Executive Summary',
    content: summaryContent,
    priority: 'info'
  })

  // Section 2: Completed Objectives
  if (completedObjectives.length > 0) {
    const objList = completedObjectives
      .slice(0, 5)
      .map(o => `- ${o.title}`)
      .join('\n')

    sections.push({
      title: 'Completed Objectives',
      content: `${completedObjectives.length} objective${completedObjectives.length > 1 ? 's' : ''} completed:\n\n${objList}`,
      priority: 'important'
    })
  }

  // Section 3: Completed Tasks
  if (completedTasks.length > 0) {
    const taskList = completedTasks
      .slice(0, 10)
      .map(t => `- ${t.title} (${t.objectives?.title || 'No objective'})`)
      .join('\n')

    sections.push({
      title: 'Completed Tasks',
      content: `${completedTasks.length} task${completedTasks.length > 1 ? 's' : ''} completed:\n\n${taskList}`,
      priority: 'info'
    })
  }

  // Section 4: Key Insights
  if (insights.length > 0) {
    const criticalInsights = insights.filter((i: any) => i.urgency === 'critical')
    const importantInsights = insights.filter((i: any) => i.urgency === 'important')

    let insightContent = ''

    if (criticalInsights.length > 0) {
      insightContent += `**Critical (${criticalInsights.length}):**\n`
      insightContent += criticalInsights
        .slice(0, 3)
        .map((i: any) => `- ${i.title}: ${i.content?.substring(0, 100)}...`)
        .join('\n')
      insightContent += '\n\n'
    }

    if (importantInsights.length > 0) {
      insightContent += `**Important (${importantInsights.length}):**\n`
      insightContent += importantInsights
        .slice(0, 5)
        .map((i: any) => `- ${i.title}`)
        .join('\n')
    }

    sections.push({
      title: 'Key Insights',
      content: insightContent || `${insights.length} insights generated`,
      priority: criticalInsights.length > 0 ? 'critical' : 'important'
    })
  }

  // Section 5: Action Required (Pending Approvals)
  const { objectives: pendingObjectives, tasks: pendingTasks } = pendingApprovals
  const totalPending = pendingObjectives.length + pendingTasks.length

  if (totalPending > 0) {
    const actionItems: string[] = []

    if (pendingObjectives.length > 0) {
      actionItems.push(`${pendingObjectives.length} objective${pendingObjectives.length > 1 ? 's' : ''} need approval`)
    }
    if (pendingTasks.length > 0) {
      actionItems.push(`${pendingTasks.length} task${pendingTasks.length > 1 ? 's' : ''} need approval`)
    }

    sections.push({
      title: 'Action Required',
      content: `Your approval is needed:\n\n${actionItems.map(a => `- ${a}`).join('\n')}`,
      priority: 'important',
      actionItems
    })
  }

  // Section 6: Blockers
  if (blockers.length > 0) {
    const blockerList = blockers
      .slice(0, 5)
      .map(b => `- ${b.title}: ${b.description || 'No details'}`)
      .join('\n')

    sections.push({
      title: 'Blockers',
      content: `${blockers.length} task${blockers.length > 1 ? 's' : ''} blocked:\n\n${blockerList}`,
      priority: 'critical'
    })
  }

  // Section 7: Agent Activity Summary
  if (activity.total > 0) {
    const agentSummary = Object.entries(activity.byAgent)
      .map(([agent, count]) => `- ${agent}: ${count} actions`)
      .join('\n')

    sections.push({
      title: 'Team Activity',
      content: `**${activity.total} total actions** by your AI team:\n\n${agentSummary}`,
      priority: 'info'
    })
  }

  // Section 8: Today's Suggested Agenda
  const agendaItems: string[] = []

  if (totalPending > 0) {
    agendaItems.push('Review and approve pending AI-generated objectives and tasks')
  }
  if (blockers.length > 0) {
    agendaItems.push('Address blockers preventing AI team progress')
  }
  if (insights.length > 0) {
    agendaItems.push(`Review ${insights.length} new insights from overnight analysis`)
  }

  if (agendaItems.length > 0) {
    sections.push({
      title: "Today's Suggested Agenda",
      content: agendaItems.map(a => `- ${a}`).join('\n'),
      priority: 'important'
    })
  }

  return {
    date: now.toISOString().split('T')[0],
    sections,
    generatedAt: now.toISOString()
  }
}

// ============================================================================
// STORAGE AND RETRIEVAL
// ============================================================================

/**
 * Save briefing as artifact
 */
export async function saveBriefingAsArtifact(
  foundryId: string,
  briefing: MorningBriefing,
  authorAgentId: string
): Promise<string | null> {
  const content = briefing.sections
    .map(s => `## ${s.title}\n\n${s.content}`)
    .join('\n\n---\n\n')

  const { data, error } = await supabase
    .from('agent_artifacts')
    .insert({
      foundry_id: foundryId,
      created_by: authorAgentId,
      title: `Morning Briefing - ${briefing.date}`,
      content_type: 'report',
      content,
      metadata: {
        briefing_date: briefing.date,
        generated_at: briefing.generatedAt,
        type: 'morning_briefing'
      }
    })
    .select()
    .single()

  if (error) {
    console.error('[MorningBrief] Error saving artifact:', error)
    return null
  }

  return data?.id
}

// ============================================================================
// RUN BRIEFING
// ============================================================================

/**
 * Run morning briefing for a foundry
 */
export async function runMorningBriefing(
  foundryId: string,
  founderId: string
): Promise<{
  success: boolean
  briefing?: MorningBriefing
  artifactId?: string
  error?: string
}> {
  try {
    // Generate the briefing
    const briefing = await generateMorningBriefing(foundryId, founderId)

    // Save as artifact
    const artifactId = await saveBriefingAsArtifact(foundryId, briefing, 'chief-of-staff' as any)

    // TODO: Send notification to founder (Telegram/Slack/Email)

    return {
      success: true,
      briefing,
      artifactId: artifactId || undefined
    }
  } catch (error) {
    console.error('[MorningBrief] Error running briefing:', error)
    return {
      success: false,
      error: error instanceof Error ? error.message : 'Unknown error'
    }
  }
}

/**
 * Get today's briefing for a foundry (cached)
 */
export async function getTodaysBriefing(
  foundryId: string
): Promise<MorningBriefing | null> {
  const today = new Date().toISOString().split('T')[0]

  const { data, error } = await supabase
    .from('agent_artifacts')
    .select('content, metadata')
    .eq('foundry_id', foundryId)
    .eq('content_type', 'report')
    .contains('metadata', { type: 'morning_briefing', briefing_date: today })
    .order('created_at', { ascending: false })
    .limit(1)
    .single()

  if (error || !data) {
    return null
  }

  // Parse sections from content
  const sections: BriefingSection[] = []
  const contentParts = data.content.split('\n\n---\n\n')

  for (const part of contentParts) {
    const match = part.match(/^## (.+)\n\n(.+)$/s)
    if (match) {
      sections.push({
        title: match[1],
        content: match[2]
      })
    }
  }

  return {
    date: data.metadata?.briefing_date,
    sections,
    generatedAt: data.metadata?.generated_at
  }
}
