/**
 * @file class-hazards.ts — Per-product-class FMEA / hazard registry.
 *
 * Universal Principle (Tristan directive 2026-05-15): risk and FMEA content
 * is class-universal, not BoM-derived. The hazards a BESS or CGM or HAPS
 * faces exist at the CLASS level (chemistry, environment, operating mode)
 * regardless of how dense the BoM emission was for any particular brief.
 *
 * Sibling of class-floors.ts + class-standards.ts. The standalone §Risk page
 * reads from this registry and overlays brief-specific operating environment
 * to produce a hazard table with severity × likelihood × detectability RPN
 * scores per entry, plus typical mitigations linked back to class-standards.
 *
 * Each entry is a CLASS-LEVEL hazard — the failure mode every product in
 * this class needs to think about. Design-specific FMEA (specific to chosen
 * cell chemistry / refrigerant / sensor architecture) is layered on top at
 * design time.
 *
 * Scoring conventions (1-5 scale at class level — coarser than ISO 14971's
 * 1-10 because class-level data lacks the resolution for finer grading):
 *   severity:   1 = negligible · 2 = minor · 3 = serious · 4 = critical · 5 = catastrophic
 *   likelihood: 1 = remote     · 2 = rare  · 3 = occasional · 4 = frequent · 5 = continuous
 *   RPN = severity × likelihood × detectability_difficulty (1-5 where 5 = hard to detect)
 */

export type HazardCategory =
  | 'thermal'
  | 'electrical'
  | 'mechanical'
  | 'chemical'
  | 'biological'
  | 'software'
  | 'cybersecurity'
  | 'data_protection'
  | 'environmental'
  | 'operational'
  | 'human_factors'
  | 'radiation'

export interface ClassHazard {
  /** Stable short code for cross-referencing (e.g. "THR-01" for energy_storage thermal-runaway-1). */
  code: string
  title: string
  category: HazardCategory
  /** Pre-mitigation severity rating, 1-5. */
  severity_pre: 1 | 2 | 3 | 4 | 5
  /** Pre-mitigation likelihood rating, 1-5. */
  likelihood_pre: 1 | 2 | 3 | 4 | 5
  /** Detectability difficulty, 1-5. Higher = harder to detect before harm. */
  detectability: 1 | 2 | 3 | 4 | 5
  /** One-sentence description of the hazard mechanism. */
  mechanism: string
  /** Design / process mitigations typical in this class (ordered most-to-least common). */
  common_mitigations: string[]
  /** Runtime / production detection methods (sensors, surveillance, sampling). */
  detection_methods: string[]
  /** class-standards codes that govern or test this hazard. */
  regulatory_drivers: string[]
  /** How the hazard is typically verified in qualification testing. */
  typical_test_method: string
}

export interface ClassHazards {
  product_class: string
  display_name: string
  hazards: ClassHazard[]
  /** One-sentence summary of the class's hazard landscape, used in §Risk page intro. */
  hazard_summary: string
}

// ─── Per-class hazard data ─────────────────────────────────────────────────

const ENERGY_STORAGE: ClassHazards = {
  product_class: 'energy_storage',
  display_name: 'Battery Energy Storage System (BESS)',
  hazard_summary: 'BESS hazards are dominated by lithium-cell internal energy density and the thermal-electrical-chemical coupling between cells. Single-cell failures (internal short, mechanical abuse) can propagate to module-level thermal runaway within minutes if propagation barriers, off-gas venting, and suppression are inadequate.',
  hazards: [
    { code: 'THR-01', title: 'Single-cell thermal runaway',                category: 'thermal',     severity_pre: 5, likelihood_pre: 2, detectability: 3, mechanism: 'Internal short circuit (separator failure, dendrite, contamination) releases stored energy as heat, decomposes electrolyte, and emits flammable off-gas; cell temperature climbs >150 °C in seconds.', common_mitigations: ['UL 9540A-tested propagation barriers between cells and modules', 'cell-level fusing on high-energy lines', 'busbar fusing at module exit', 'inter-cell thermal mass / cooling plates', 'off-gas detection + ventilation path'], detection_methods: ['per-module temperature sensing', 'cell voltage divergence monitoring', 'off-gas (CO / H₂ / VOC) sensors', 'pressure-rise switches in sealed enclosures'], regulatory_drivers: ['IEC 62619', 'UL 9540A', 'NFPA 855'], typical_test_method: 'UL 9540A nail-penetration + propagation test at cell, module, unit, and installation levels.' },
    { code: 'THR-02', title: 'Module-to-module thermal propagation',       category: 'thermal',     severity_pre: 5, likelihood_pre: 2, detectability: 3, mechanism: 'Heat from a failed module conducts/radiates to neighbours; insufficient barriers allow cascading failure across the pack.', common_mitigations: ['mineral-wool or ceramic propagation barriers between modules', 'water-mist / aerosol suppression at unit level', 'compartmentalised rack design', 'reduced module proximity'], detection_methods: ['inter-module temperature gradients', 'rack-level smoke detectors', 'aspirating smoke detection (VESDA)'], regulatory_drivers: ['UL 9540A', 'NFPA 855'], typical_test_method: 'UL 9540A unit-level propagation test — ignite one module, observe heat-release rate and propagation to adjacent modules.' },
    { code: 'ELE-01', title: 'DC arc fault (internal busbar)',              category: 'electrical',  severity_pre: 4, likelihood_pre: 2, detectability: 4, mechanism: 'Loose connection or insulation breakdown on DC busbars sustains a low-current arc invisible to conventional overcurrent protection; ignites surrounding combustibles.', common_mitigations: ['DC arc-fault detector (AFCI) on string-level', 'crimped vs bolted busbar joints with torque verification', 'insulation-resistance monitoring at commissioning + periodic'], detection_methods: ['AFCI in BMS / PCS', 'periodic megger test', 'thermal imaging on energised busbars'], regulatory_drivers: ['BS EN 61439', 'UL 1973'], typical_test_method: 'Insulation-resistance test at 1000 V DC; arc-fault injection on a busbar coupon.' },
    { code: 'ELE-02', title: 'Cell overcharge / over-discharge',            category: 'electrical',  severity_pre: 4, likelihood_pre: 2, detectability: 2, mechanism: 'BMS voltage limit miscalibration or sensor failure allows cell to exceed upper/lower SOC limits; precipitates lithium plating on negative electrode or copper dissolution on positive.', common_mitigations: ['redundant cell-voltage sensing per BMS group', 'hard-stop contactor on out-of-range alarm', 'state-of-charge windowing 10-90 %', 'periodic cell balancing'], detection_methods: ['per-cell voltage monitoring', 'cumulative coulomb counting', 'capacity-fade trend analysis'], regulatory_drivers: ['IEC 62619', 'UL 1973'], typical_test_method: 'Overcharge test per IEC 62619 §7.3.3: charge at C/3 to 1.1 × V_max for 7 hours; observe no fire / explosion.' },
    { code: 'CHE-01', title: 'Off-gas flammable atmosphere',                category: 'chemical',    severity_pre: 5, likelihood_pre: 2, detectability: 2, mechanism: 'Thermal runaway emits H₂, CO, CH₄, electrolyte vapour; accumulates in enclosure headspace above lower-explosive-limit, ignites on subsequent spark or arc.', common_mitigations: ['off-gas detection > 25 % LEL → forced ventilation + isolation', 'inert (N₂ / argon) gas purge option', 'explosion vents on enclosure roof', 'no internal ignition sources (sealed contactors, intrinsically safe sensors)'], detection_methods: ['LEL sensors near cells', 'H₂ sensors specific (LEL is non-selective)', 'gas-chromatograph sampling in incident response'], regulatory_drivers: ['UL 9540A', 'NFPA 855'], typical_test_method: 'Off-gas composition measurement during thermal-runaway initiation (UL 9540A method).' },
    { code: 'MEC-01', title: 'Mechanical abuse (transit / installation)',   category: 'mechanical',  severity_pre: 4, likelihood_pre: 2, detectability: 4, mechanism: 'Drop, vibration, or container racking during transit or installation damages cell casings, internal welds, or separator integrity; failure appears at first charge or weeks later.', common_mitigations: ['vibration-isolated rack mounting', 'transit-rated packaging with shock/tilt indicators', 'commissioning-time visual + electrical inspection', 'pre-energisation insulation resistance test'], detection_methods: ['shock-recorder labels on shipment', 'commissioning insulation test', 'baseline EIS (electrochemical impedance spectroscopy)'], regulatory_drivers: ['UN 38.3', 'IEC 62619'], typical_test_method: 'UN 38.3 T.3 vibration + T.4 shock + T.5 external short circuit.' },
    { code: 'OPE-01', title: 'Grid-fault back-feed during fault clearing',  category: 'operational', severity_pre: 4, likelihood_pre: 3, detectability: 3, mechanism: 'PCS continues to feed an internal grid section during fault clearing; energises a section the utility expected to be dead.', common_mitigations: ['G99/EN 50549 anti-islanding loss-of-mains detection', 'redundant utility-grade interface protection relays', 'physical lock-out tag-out at maintenance disconnect'], detection_methods: ['ROCOF / vector-shift loss-of-mains', 'real-time DNO communications channel', 'maintenance-mode interlocks'], regulatory_drivers: ['G99 Issue 6', 'EN 50549', 'IEC 62933'], typical_test_method: 'Loss-of-mains witness testing per ENA Engineering Recommendation G99 type-test schedule.' },
  ],
}

const HEATPUMP: ClassHazards = {
  product_class: 'thermal_system',
  display_name: 'Heat Pump',
  hazard_summary: 'Heat pump hazards centre on refrigerant containment (especially A3-class refrigerants like R290 propane), refrigerant-circuit pressure containment, and rotating-machinery safety. Residential R290 systems balance flammability risk against the F-gas regulatory pressure to phase out high-GWP HFCs.',
  hazards: [
    { code: 'CHE-01', title: 'Flammable refrigerant leak (R290 / A3 class)', category: 'chemical',   severity_pre: 5, likelihood_pre: 2, detectability: 3, mechanism: 'Pinhole leak at brazed joint, capillary fatigue, or service-valve seat degradation releases propane; mixes with air to flammable concentration in confined spaces; ignites at ~510 °C or by spark.', common_mitigations: ['minimise refrigerant charge per BS EN 378 charge-limit tables for room volume', 'sealed-system brazed joints (no flare fittings in occupied spaces)', 'EX-rated electrical components within refrigerant circuit envelope', 'forced ventilation interlock on detection'], detection_methods: ['catalytic-bead or IR refrigerant leak sensors at 25 % LEL', 'pressure-drop trending in service intervals', 'odorant addition (some installations)'], regulatory_drivers: ['BS EN 378', 'EU 517/2014', 'PED 2014/68/EU'], typical_test_method: 'Leak-tightness test per BS EN 378-2 §6.2: vacuum decay + helium tracer + pressure-hold.' },
    { code: 'MEC-01', title: 'High-side pressure excursion',                 category: 'mechanical',  severity_pre: 4, likelihood_pre: 2, detectability: 2, mechanism: 'Fouled condenser, blocked airflow, or oversized expansion device causes high-side pressure to exceed design — relief valve must vent before vessel burst.', common_mitigations: ['PED-rated pressure-relief valve sized to compressor displacement', 'high-pressure cutout switch on suction line', 'fan-failure detection on condenser', 'over-temperature cutout on compressor discharge'], detection_methods: ['high-side pressure transducer', 'discharge-temperature thermistor', 'fan-current monitoring'], regulatory_drivers: ['PED 2014/68/EU', 'BS EN 378'], typical_test_method: 'PED §7.2 pressure-strength test at 1.43 × maximum-allowable pressure for 30 minutes.' },
    { code: 'MEC-02', title: 'Compressor lockup (oil starvation / liquid slug)', category: 'mechanical', severity_pre: 3, likelihood_pre: 2, detectability: 3, mechanism: 'Oil migration into evaporator at low load, or liquid refrigerant returning to compressor on rapid load change, hydraulically locks the compressor scroll/piston.', common_mitigations: ['suction accumulator', 'crankcase heater + minimum-off-time delay', 'electronic-expansion-valve modulation', 'oil-level sight glass for service'], detection_methods: ['compressor current spike detection', 'oil-pressure sensor (semi-hermetic models)', 'discharge superheat trending'], regulatory_drivers: ['MD 2006/42/EC'], typical_test_method: 'Liquid-slug test per BS EN 12102 — inject controlled liquid pulse during compressor operation.' },
    { code: 'ELE-01', title: 'Inverter DC-link capacitor failure',           category: 'electrical',  severity_pre: 3, likelihood_pre: 2, detectability: 3, mechanism: 'Electrolytic capacitor ESR rises with age and ripple-current heating; eventual rupture releases electrolyte aerosol and disables compressor drive.', common_mitigations: ['design with ≥ 105 °C low-ESR capacitors derated 20 % on ripple current', 'capacitance health-check on power-up self-test', 'fuse the DC link rail'], detection_methods: ['power-on capacitance test', 'DC-link ripple voltage trending', 'thermal imaging at commissioning'], regulatory_drivers: ['EMC 2014/30/EU', 'LVD 2014/35/EU'], typical_test_method: 'Capacitor lifetime endurance test per IEC 60384-4 — 1000 hr at rated voltage + temperature.' },
    { code: 'OPE-01', title: 'Defrost-cycle ice damage',                     category: 'operational', severity_pre: 2, likelihood_pre: 3, detectability: 2, mechanism: 'Outdoor unit accumulates ice on coil; defrost cycle initiation logic fails or reversing-valve sticks; ice impacts fan blades or restricts airflow.', common_mitigations: ['demand-defrost (humidity + coil-temperature) logic vs time-based', 'reversing-valve cycling self-test on commissioning', 'fan-blade vibration detection'], detection_methods: ['coil-temperature differential trend', 'fan-current vs RPM mismatch', 'condensate pan over-level switch'], regulatory_drivers: ['BS EN 14511'], typical_test_method: 'BS EN 14511-4 frosted-coil performance test.' },
    { code: 'CHE-02', title: 'Refrigerant venting on service / decommission', category: 'chemical',   severity_pre: 3, likelihood_pre: 4, detectability: 1, mechanism: 'Unrecovered refrigerant during service or end-of-life decommission released to atmosphere — climate impact (high GWP HFCs) plus immediate flammability (R290).', common_mitigations: ['F-gas-certified installer requirement (UK MCS or EU 303/2008 cert)', 'mandatory recovery to recovery cylinder before service', 'pump-down to receiver before disconnection'], detection_methods: ['service logbook + invoice recovery audit', 'F-gas register tracking', 'leak-detection survey on annual basis'], regulatory_drivers: ['EU 517/2014', 'MCS'], typical_test_method: 'F-gas leak-check certification per EU 517/2014 Article 4 (annual for ≥ 5 t CO₂e).' },
  ],
}

const VERTICAL_FARM: ClassHazards = {
  product_class: 'vertical_farm',
  display_name: 'Vertical Farm',
  hazard_summary: 'Vertical-farm hazards span food safety (pathogen contamination through irrigation water / handling / packaging), environmental control failures (HVAC, nutrient solution, CO₂ enrichment), and electrical / mechanical risks from LED arrays + automation. Food-safety hazards dominate severity because contamination is invisible until consumer harm.',
  hazards: [
    { code: 'BIO-01', title: 'Pathogen contamination (E. coli, Listeria, Salmonella)', category: 'biological', severity_pre: 5, likelihood_pre: 2, detectability: 5, mechanism: 'Contaminated irrigation water, biofilm on hydroponic surfaces, post-harvest handling, or packaging introduces enteric pathogens; recirculating systems can amplify contamination across an entire batch.', common_mitigations: ['UV-C treatment of recirculating water (≥ 40 mJ/cm² dose)', 'ozone or peracetic-acid CIP cycles on growing surfaces', 'one-way pre-rinse / post-rinse zoning, no employee crossover', 'pre-harvest swab + ATP testing'], detection_methods: ['ATP bioluminescence swabs on contact surfaces', 'water-sample microbiology (TVC, coliform, E. coli, Listeria) at least weekly', 'pre-shipment hold-and-test on finished produce'], regulatory_drivers: ['HACCP', 'BRCGS Food Safety', 'EU 1169/2011'], typical_test_method: 'Microbiological challenge testing — inoculate growing surface with known pathogen load, sample at intervals to validate CIP regime.' },
    { code: 'CHE-01', title: 'Nutrient solution pH / EC crash',              category: 'chemical',    severity_pre: 3, likelihood_pre: 3, detectability: 2, mechanism: 'Doser pump failure, sensor drift, or stock-tank depletion causes pH or electrical-conductivity excursion; plants suffer root burn or nutrient lockout within hours.', common_mitigations: ['redundant pH + EC sensors with disagreement-trigger alarm', 'doser pumps with flow-verification (pulse output)', 'reservoir-level interlock on stock tanks', 'pH-stat buffer-tank intermediate'], detection_methods: ['continuous pH + EC + temperature trending', 'doser-pump revolution counter vs commanded volume', 'visual canopy inspection daily'], regulatory_drivers: ['HACCP'], typical_test_method: 'Sensor accuracy verification quarterly against NIST-traceable buffer solutions.' },
    { code: 'OPE-01', title: 'HVAC failure (heat / RH excursion)',           category: 'operational', severity_pre: 4, likelihood_pre: 3, detectability: 2, mechanism: 'Chiller, dehumidifier, or air-handler failure pushes grow-room temperature above 28 °C or relative humidity above 80 %; promotes pathogen growth + transpiration shutdown.', common_mitigations: ['N+1 redundant HVAC modules', 'free-cooling fallback (outdoor air with HEPA filter)', 'emergency power transfer to HVAC priority circuit', 'temperature + RH alarm to on-call operator'], detection_methods: ['per-zone temperature + RH sensors at canopy + reservoir levels', 'chiller-status communications heartbeat', 'condensate-tray overflow switch'], regulatory_drivers: ['HACCP', 'MD 2006/42/EC'], typical_test_method: 'HVAC failover drill — simulate primary chiller fault, verify secondary takes load within SLA.' },
    { code: 'ELE-01', title: 'LED driver thermal runaway',                   category: 'thermal',     severity_pre: 3, likelihood_pre: 2, detectability: 3, mechanism: 'Aluminium-electrolytic capacitor failure or driver-board solder-joint failure causes one driver to consume excessive current; ignites surrounding combustibles or damages fixture.', common_mitigations: ['fixture-level over-temperature cutout at 85 °C heatsink', 'series-fused driver inputs', '100 % LED reflector / housing FR-rated materials', 'design with ≥ 105 °C-rated capacitors derated 20 %'], detection_methods: ['per-rack current monitoring', 'IR thermal imaging at commissioning + annually', 'fixture-level smoke detection in enclosed grow rooms'], regulatory_drivers: ['LVD 2014/35/EU', 'EMC 2014/30/EU'], typical_test_method: 'LED-driver lifetime endurance test per IEC 62384 with thermal cycling.' },
    { code: 'CHE-02', title: 'CO₂ enrichment asphyxiation hazard',           category: 'chemical',    severity_pre: 5, likelihood_pre: 1, detectability: 3, mechanism: 'CO₂ injection system runs away or solenoid sticks open; concentration rises above 1.5 % into workspace; humans experience headache → unconsciousness → death.', common_mitigations: ['fixed CO₂ ppm sensor with 1500 ppm alarm + 3000 ppm cutoff', 'manual disconnect valve on CO₂ supply outside grow room', 'occupancy-interlock disabling injection during entry', 'CO₂ scrubber on HVAC return as fallback'], detection_methods: ['fixed CO₂ sensor (NDIR or photoacoustic)', 'portable CO₂ meter for entry checks', 'occupancy beam-break interlock'], regulatory_drivers: ['MD 2006/42/EC'], typical_test_method: 'Injection-valve close-on-fail test — simulate sensor fault, verify valve fails closed within 5 seconds.' },
    { code: 'MEC-01', title: 'Conveyor / harvester pinch / entanglement',    category: 'mechanical',  severity_pre: 3, likelihood_pre: 3, detectability: 3, mechanism: 'Operator hand or clothing caught in conveyor pinch point, robotic harvester gripper, or vertical lift system during operation.', common_mitigations: ['light-curtain guarding at conveyor approach', 'two-hand control on harvester manual mode', 'emergency-stop ring on every operator station', 'lock-out tag-out procedure for maintenance'], detection_methods: ['safety-PLC monitoring of E-stop + light-curtain status', 'pre-shift visual inspection log', 'near-miss reporting'], regulatory_drivers: ['MD 2006/42/EC'], typical_test_method: 'Machinery Directive risk assessment per BS EN ISO 12100; emergency-stop response-time test.' },
  ],
}

const EV_CHARGER: ClassHazards = {
  product_class: 'ev_charger',
  display_name: 'Electric Vehicle Charger',
  hazard_summary: 'EV-charger hazards centre on high-current connector interfaces, residual-current detection on charging mode 3/4, V2G grid-back-feed during faults, and outdoor environmental ingress. Public-pay installations add metering-accuracy enforcement and tamper detection.',
  hazards: [
    { code: 'ELE-01', title: 'Residual current to vehicle chassis or person', category: 'electrical', severity_pre: 5, likelihood_pre: 2, detectability: 2, mechanism: 'Insulation failure inside vehicle or charger creates leakage path through chassis or charging cable; ground-fault current shocks operator or fault-current heats cable to ignition.', common_mitigations: ['IEC 61851-1 RCD Type B (DC-sensitive) on every charging point', 'PE bonding integrity check on every charge session start', 'control-pilot continuity verification', 'pre-charge dielectric test on DC chargers'], detection_methods: ['RCD-B trip detection', 'PE-bond resistance < 0.1 Ω at start', 'control-pilot diode-detection per IEC 61851'], regulatory_drivers: ['IEC 61851-1', 'IEC 62196'], typical_test_method: 'IEC 61851-1 §6.3 protection-against-electric-shock — inject simulated leakage and verify trip.' },
    { code: 'ELE-02', title: 'Connector overheat',                           category: 'thermal',     severity_pre: 4, likelihood_pre: 3, detectability: 3, mechanism: 'Loose connector pin, corrosion, or partial-contact insertion creates high-resistance joint at 100+ A; pin temperature climbs to plastic melting + fire.', common_mitigations: ['connector-housing temperature sensor with derating ≥ 75 °C', 'mechanical retention force spec per IEC 62196', 'consumer-facing visual indicator for misalignment', 'periodic pin inspection at service interval'], detection_methods: ['embedded connector-pin thermistors (one per phase)', 'current-imbalance monitoring across phases', 'consumer feedback (slow-charge complaint trigger)'], regulatory_drivers: ['IEC 62196', 'IEC 61851-1'], typical_test_method: 'IEC 62196-2 §6.6 temperature-rise test at rated current for 30 minutes.' },
    { code: 'ELE-03', title: 'Contactor / relay welding',                    category: 'electrical',  severity_pre: 4, likelihood_pre: 2, detectability: 3, mechanism: 'High-current contactor inrush or fault clearing welds main contacts closed; charger cannot de-energise vehicle connector after session end.', common_mitigations: ['redundant series-contactor architecture', 'contact-weld verification by feedback voltage measurement', 'pre-charge resistor on DC chargers to limit inrush'], detection_methods: ['contactor auxiliary feedback (closed/open) per session', 'voltage-presence check after commanded open'], regulatory_drivers: ['IEC 61851-1'], typical_test_method: 'IEC 61851-1 §6.4 — endurance test 10,000 operations at rated current.' },
    { code: 'OPE-01', title: 'V2G islanding during grid fault',              category: 'operational', severity_pre: 4, likelihood_pre: 2, detectability: 3, mechanism: 'Bidirectional charger continues to export to local circuit during utility outage; energises mains the utility expected to be dead, endangering linesmen.', common_mitigations: ['EN 50549 anti-islanding loss-of-mains protection', 'redundant utility-grade interface protection', 'physical disconnect interlock at maintenance panel'], detection_methods: ['ROCOF / vector-shift LOM detection', 'utility communications heartbeat (smart-grid networks)', 'manual lock-out tag-out procedure'], regulatory_drivers: ['EN 50549', 'G99 Issue 6'], typical_test_method: 'EN 50549-1 §4.7 loss-of-mains test — open utility breaker, verify export ceases within 1 second.' },
    { code: 'ENV-01', title: 'Water ingress + condensation',                 category: 'environmental', severity_pre: 3, likelihood_pre: 4, detectability: 2, mechanism: 'Driving rain, hose-down cleaning, or thermal-cycle condensation enters enclosure; tracks across PCB, shorts low-voltage / control circuits.', common_mitigations: ['IP54 minimum (IP65 for kerbside) per IEC 60529', 'conformal coating on PCBs', 'pressure-balancing breather valve', 'drainage path at enclosure low point'], detection_methods: ['humidity sensor in enclosure', 'leakage current trending', 'visual inspection at service interval'], regulatory_drivers: ['IEC 60529 (IP rating)'], typical_test_method: 'IEC 60529 IPX5/X6 water-jet test for kerbside chargers.' },
    { code: 'CYB-01', title: 'OCPP command injection / unauthorised access', category: 'cybersecurity', severity_pre: 3, likelihood_pre: 3, detectability: 4, mechanism: 'Attacker on the OCPP back-office network injects spoofed commands (free-vend, denial-of-service, firmware downgrade); affects billing integrity and operational availability.', common_mitigations: ['OCPP 2.0.1 with TLS 1.3 + mutual certificate authentication', 'firmware-signing with hardware-root-of-trust', 'rate-limiting + anomaly detection on charger-to-CSMS commands', 'separate physical network for OT (charger) vs IT (back-office reporting)'], detection_methods: ['OCPP transaction anomaly detection (free-vend, unusual remote-stop)', 'TLS handshake failure monitoring', 'firmware-version drift detection across fleet'], regulatory_drivers: ['OCPP 2.0.1'], typical_test_method: 'Penetration testing per OWASP ASVS Level 2; OCPP fuzz testing with malformed message frames.' },
  ],
}

const CGM: ClassHazards = {
  product_class: 'wearable_medical',
  display_name: 'Continuous Glucose Monitor (CGM)',
  hazard_summary: 'CGM hazards combine acute clinical risk (false reading driving incorrect insulin dose), patient-contact biocompatibility (allergic reaction, infection at insertion site), and software risk (algorithm drift, BLE link failure to insulin pump). ISO 14971 risk file is the central regulatory artefact reviewed by notified bodies.',
  hazards: [
    { code: 'CLI-01', title: 'False low reading → patient over-treats',     category: 'software',     severity_pre: 5, likelihood_pre: 2, detectability: 3, mechanism: 'Sensor lag, calibration drift, or interferent (paracetamol, vitamin C) causes CGM reading below true glucose; patient consumes carbohydrates, causes rebound hyperglycaemia or DKA.', common_mitigations: ['ISO 15197 ≥ 95 % MARD within ±15 mg/dL of reference', 'sensor warm-up + calibration window before therapeutic use', 'redundant trend-and-rate-of-change algorithms', 'patient training on confirming with finger-stick before treatment'], detection_methods: ['paired finger-stick comparison points', 'rate-of-change discontinuity alarms', 'sensor-impedance drift trend'], regulatory_drivers: ['EU IVDR 2017/746', 'FDA 510(k) / PMA', 'ISO 15197'], typical_test_method: 'In-clinic CGM-vs-YSI reference glucose comparison over 14-day wear, 288 paired data points per subject, ≥ 30 subjects.' },
    { code: 'CLI-02', title: 'False high reading → patient over-doses insulin', category: 'software', severity_pre: 5, likelihood_pre: 2, detectability: 3, mechanism: 'Sensor offset or compression artefact causes CGM reading above true glucose; patient or pump delivers insulin bolus, precipitates severe hypoglycaemia → seizure or death.', common_mitigations: ['minimum-dose-lockout in companion pump integration', 'compression-low-alarm logic detects sensor sleeping pressure', 'patient training to verify before bolus when symptoms disagree', 'mandatory two-hour grace period after sensor insertion before bolus'], detection_methods: ['rate-of-change spike detection', 'paired finger-stick verification on alarm', 'pump-reported insulin-on-board cross-check'], regulatory_drivers: ['EU IVDR 2017/746', 'IEC 62366-1', 'ISO 14971'], typical_test_method: 'Closed-loop clinical study with hybrid AID system — observe overshoot incidents per patient-month.' },
    { code: 'BIO-01', title: 'Adhesive / sensor allergic reaction',         category: 'biological',   severity_pre: 3, likelihood_pre: 3, detectability: 1, mechanism: 'Acrylate adhesive or nickel-bearing sensor contact triggers ACD (allergic contact dermatitis); rash, blistering, infection at insertion site.', common_mitigations: ['hypoallergenic adhesive options (silicone gel)', 'cyclic patch rotation (different anatomical site each wear)', 'over-patch barrier film for sensitive patients'], detection_methods: ['patient self-report at sensor change', 'support-line complaint clustering', 'post-market surveillance (IVDR Annex III)'], regulatory_drivers: ['ISO 14971', 'EU IVDR 2017/746', 'ISO 10993-10 (biocompatibility — skin sensitisation)'], typical_test_method: 'ISO 10993-10 skin-sensitisation test (guinea pig maximisation or LLNA).' },
    { code: 'BIO-02', title: 'Insertion-site infection',                    category: 'biological',   severity_pre: 4, likelihood_pre: 2, detectability: 2, mechanism: 'Bacterial ingress at sensor insertion site (skin flora not removed before insertion, sterile barrier compromised); localised infection, in worst case cellulitis or sepsis.', common_mitigations: ['sterile single-use applicator', 'patient instructions for cleanse + dry before insertion', 'insertion-site rotation (no re-use of recent sites)'], detection_methods: ['patient-reported redness / pain / discharge', 'support clinical helpline triage'], regulatory_drivers: ['EU IVDR 2017/746', 'ISO 11135 (sterilisation)'], typical_test_method: 'ISO 11135 ethylene-oxide sterilisation cycle validation; SAL ≤ 10⁻⁶.' },
    { code: 'SW-01',  title: 'BLE link loss to insulin pump',               category: 'software',     severity_pre: 4, likelihood_pre: 3, detectability: 2, mechanism: 'Bluetooth Low Energy connection between CGM and partner pump drops (interference, distance, sleep-state bug); pump reverts to open-loop, patient unaware until later hypo / hyper event.', common_mitigations: ['link-loss alarm to patient within 30 minutes', 'pump fail-safe to last-known-trend insulin delivery', 'multi-vendor interoperability standards (IEEE 11073)', 'BLE re-pair flow accessible from lock screen'], detection_methods: ['BLE RSSI trend tracking', 'pump heartbeat ping every minute', 'companion-app warning'], regulatory_drivers: ['IEC 62304', 'EU IVDR 2017/746', 'IEEE 11073'], typical_test_method: 'IEC 62304 software-failure-mode injection test; BLE-interference robustness test per FCC Part 15.' },
    { code: 'DAT-01', title: 'Cloud data breach (PHI exposure)',            category: 'cybersecurity', severity_pre: 4, likelihood_pre: 2, detectability: 4, mechanism: 'CGM cloud service compromised; glucose / insulin / location history exfiltrated; reportable breach under GDPR (Article 33) and HIPAA Breach Notification Rule.', common_mitigations: ['AES-256 encryption at rest + TLS 1.3 in transit', 'role-based access with audit log', 'penetration testing quarterly', 'incident-response runbook + 72-hour breach-notification process'], detection_methods: ['anomaly detection on cloud API access patterns', 'SIEM alerting on privilege escalation', 'periodic third-party security audit'], regulatory_drivers: ['GDPR', 'HIPAA'], typical_test_method: 'Penetration testing (PTES / OWASP ASVS); cloud-config audit (CIS Benchmarks).' },
  ],
}

const DRONE: ClassHazards = {
  product_class: 'drone',
  display_name: 'Unmanned Aerial Vehicle (Drone)',
  hazard_summary: 'Drone hazards centre on uncommanded flight (control-link loss, GPS denial, software fault), in-flight power loss, prop strike on persons or property, and (for BVLOS) airspace intrusion. Class identification (C0-C6) drives mass-energy limits that directly determine kinetic-injury severity.',
  hazards: [
    { code: 'OPE-01', title: 'Control-link loss (RC or telemetry)',          category: 'software',     severity_pre: 4, likelihood_pre: 3, detectability: 2, mechanism: 'RF interference, range exceedance, or transmitter battery failure breaks the command link; without geofence + return-to-home, drone continues last commanded path until energy depleted.', common_mitigations: ['return-to-home on > 3-second link-loss', 'redundant radio (915 MHz + LTE) for BVLOS', 'geofence + altitude lockout', 'low-battery RTH trigger'], detection_methods: ['RC signal-strength + link quality indicator', 'periodic ack/nack between drone and ground', 'failsafe-test on every flight pre-arm check'], regulatory_drivers: ['EU 2019/945', 'CAP 722'], typical_test_method: 'EU 2019/945 §UAS.OPEN.060 — verify failsafe behaviour on commanded link interruption.' },
    { code: 'OPE-02', title: 'GPS / GNSS spoofing or denial',                category: 'cybersecurity', severity_pre: 4, likelihood_pre: 2, detectability: 3, mechanism: 'Adversary transmits false GPS signal or jams GNSS receiver; drone navigation drifts, fly-away or controlled landing in wrong location.', common_mitigations: ['multi-constellation GNSS (GPS + Galileo + BeiDou + GLONASS)', 'IMU dead-reckoning fallback for ≥ 60 s', 'visual odometry / optical-flow secondary nav', 'authenticated GNSS receivers (Galileo OS-NMA for civil)'], detection_methods: ['GNSS satellite-count + DOP trend', 'IMU vs GPS position residual trend', 'C/N₀ anomaly detection'], regulatory_drivers: ['EU 2019/945', 'ASTM F3411'], typical_test_method: 'GNSS jamming + spoofing range test per ASD-STAN prEN 4709 series.' },
    { code: 'MEC-01', title: 'Single motor / ESC failure → loss of control', category: 'mechanical',   severity_pre: 4, likelihood_pre: 3, detectability: 2, mechanism: 'ESC overheat, motor winding short, or prop foreign-object strike kills one rotor; quad-copters lose control immediately, hex/octo can fly home degraded.', common_mitigations: ['minimum hex-copter for BVLOS commercial', 'motor-current + temperature monitoring with derate', 'prop-strike protection guard (≤ C2)', 'parachute recovery system for ≥ C5'], detection_methods: ['per-motor RPM vs commanded mismatch', 'ESC temperature alarm', 'IMU yaw-error spike'], regulatory_drivers: ['EU 2019/945', 'MD 2006/42/EC'], typical_test_method: 'Single-motor-fail flight test — induce ESC fail in hover, verify recovery / parachute deployment within 2 seconds.' },
    { code: 'THR-01', title: 'Lithium battery thermal runaway in flight',    category: 'thermal',      severity_pre: 5, likelihood_pre: 2, detectability: 4, mechanism: 'LiPo battery internal short from puncture / crash damage / poor cell matching; cell fire in flight precipitates uncontrolled descent and ground-impact fire.', common_mitigations: ['intelligent BMS with per-cell voltage + temperature', 'flame-retardant battery enclosure (LiPo-safe bag)', 'pre-flight cell-balance verification', 'parachute auto-deploy on power loss > 50 %'], detection_methods: ['per-cell voltage divergence alarm pre-arm', 'battery-temperature sensor in pack', 'IMU-detected freefall + auto-disarm'], regulatory_drivers: ['UN 38.3', 'EU 2019/945'], typical_test_method: 'UN 38.3 cell-level test set + over-discharge / nail-penetration at pack level.' },
    { code: 'OPE-03', title: 'Airspace intrusion (controlled airspace / drone-vs-manned)', category: 'operational', severity_pre: 5, likelihood_pre: 2, detectability: 3, mechanism: 'Drone enters Class C/D airspace, NOTAM zone, or comes into conflict with manned aircraft; collision risk especially at < 500 ft below visual flight rules.', common_mitigations: ['geofence database with daily refresh from CAA / EASA', 'Remote ID broadcast (ASTM F3411)', 'ADS-B In receiver for traffic awareness ≥ C5', 'UTM integration for BVLOS'], detection_methods: ['ADS-B In live aircraft display', 'geofence boundary alarm', 'NOTAM auto-fetch'], regulatory_drivers: ['EU 2019/947', 'CAP 722', 'ASTM F3411'], typical_test_method: 'Geofence boundary-conformance test per EU 2019/945 §UAS.OPEN.040.' },
    { code: 'OPE-04', title: 'Prop strike on persons / payload separation', category: 'mechanical',   severity_pre: 4, likelihood_pre: 3, detectability: 2, mechanism: 'Operator-procedure error or unexpected entry into operating area; spinning props inflict cuts / amputations; payload-retention failure drops cargo on persons or property below.', common_mitigations: ['mandatory operator + observer separation distance', 'prop guards (≤ C2 close-quarter ops)', 'redundant payload retention (mechanical + electronic)', 'low-noise propeller selection reduces operator complacency'], detection_methods: ['operator pre-flight checklist', 'payload-retention-switch feedback', 'observer continuous visual'], regulatory_drivers: ['EU 2019/947', 'MD 2006/42/EC'], typical_test_method: 'Payload-retention proof load 2 × max-payload sustained for 15 minutes.' },
  ],
}

const EDGE_AI: ClassHazards = {
  product_class: 'edge_ai_server',
  display_name: 'Edge AI Compute Module',
  hazard_summary: 'Edge AI hazards combine compute-stack issues (thermal throttling, supply-rail transients, ECC failures) with AI-specific risks (adversarial inputs, inference drift, training/deployment data leakage). For high-risk applications under the EU AI Act, transparency + post-market monitoring obligations dominate the compliance picture.',
  hazards: [
    { code: 'SW-01',  title: 'Inference drift over deployment lifetime',     category: 'software',     severity_pre: 4, likelihood_pre: 4, detectability: 5, mechanism: 'Real-world input distribution shifts from training distribution (concept drift, covariate shift); model continues to produce confident but degraded predictions; downstream automation acts on bad outputs.', common_mitigations: ['continuous monitoring of input-feature distributions vs training baseline', 'periodic model retraining with fresh labelled data', 'confidence-threshold gating with human-review fallback', 'shadow-mode A/B between current and candidate models'], detection_methods: ['statistical drift detectors (KS test, Wasserstein distance)', 'output-distribution monitoring', 'business-metric correlation to model output'], regulatory_drivers: ['EU AI Act 2024/1689', 'IEC 61508'], typical_test_method: 'EU AI Act Annex IV post-market-monitoring plan; shadow-mode comparison for ≥ 90 days before promotion.' },
    { code: 'CYB-01', title: 'Adversarial input attack',                     category: 'cybersecurity', severity_pre: 4, likelihood_pre: 3, detectability: 4, mechanism: 'Adversary crafts perturbed input (image, sensor signal) that crosses decision boundary; misclassifies stop-sign as speed-limit, evades fraud detection.', common_mitigations: ['adversarial-training during model development', 'input preprocessing + sanity bounds (e.g. plausible-physics filters)', 'ensemble model with disagreement-trigger fallback', 'rate-limiting + anomaly detection on inference API'], detection_methods: ['input-anomaly detection vs training distribution', 'confidence-score thresholding', 'red-team adversarial testing'], regulatory_drivers: ['EU AI Act 2024/1689'], typical_test_method: 'Adversarial robustness benchmarking (FGSM, PGD, CW attacks at standard epsilon budgets).' },
    { code: 'THR-01', title: 'Sustained-load thermal throttling',            category: 'thermal',      severity_pre: 2, likelihood_pre: 4, detectability: 2, mechanism: 'Inference workload sustains > 70 % accelerator utilisation; SoC junction temperature climbs to throttle threshold; latency degrades or worse, NPU clock gates and stalls inference pipeline.', common_mitigations: ['heatsink + airflow sized for worst-case sustained workload', 'dynamic-voltage-and-frequency-scaling with hysteresis', 'workload-aware scheduling with deadline guarantees', 'thermal-emergency safe-mode'], detection_methods: ['on-die temperature sensor with telemetry export', 'inference-latency p99 trending', 'fan-RPM vs thermal feedback'], regulatory_drivers: ['LVD 2014/35/EU', 'EMC 2014/30/EU'], typical_test_method: 'Sustained-load burn-in at 45 °C ambient for 4 hours; verify clock not gated, latency p99 within spec.' },
    { code: 'ELE-01', title: 'Power supply transient → silent data corruption', category: 'electrical', severity_pre: 4, likelihood_pre: 2, detectability: 5, mechanism: 'Brown-out or supply-rail glitch below SoC voltage-detect threshold flips DRAM bits or causes mid-write storage corruption; subsequent inference uses corrupted weights or returns wrong result without error indication.', common_mitigations: ['ECC DRAM (mandatory for safety-critical)', 'brown-out detection with reset', 'redundant power supply (N+1) for SIL deployments', 'firmware integrity check on each boot'], detection_methods: ['ECC single/double-bit error counters', 'periodic memory scrub', 'firmware-hash verification on boot'], regulatory_drivers: ['IEC 61508'], typical_test_method: 'IEC 61508 §7.4.6 hardware-fault-tolerance test; voltage-transient injection at brown-out boundary.' },
    { code: 'DAT-01', title: 'Personal-data exposure (vision / audio capture)', category: 'data_protection', severity_pre: 4, likelihood_pre: 3, detectability: 4, mechanism: 'On-device vision / audio captures identifiable individuals; data uploaded to cloud, retained beyond purpose, accessed without basis.', common_mitigations: ['on-device anonymisation (face blurring, voice synthesis) before any upload', 'retention policy with automated purge', 'DPIA per GDPR Article 35 for high-risk processing', 'transparency notice + signage in deployment context'], detection_methods: ['data-flow audit (training + inference + cloud paths)', 'DPO oversight + DPIA review', 'incident-response runbook for data-subject access requests'], regulatory_drivers: ['GDPR', 'EU AI Act 2024/1689'], typical_test_method: 'DPIA per GDPR Article 35; privacy-by-design review checkpoint at module design milestones.' },
  ],
}

const BIOREACTOR: ClassHazards = {
  product_class: 'bioreactor',
  display_name: 'Bioreactor',
  hazard_summary: 'Bioreactor hazards centre on sterility breach (contamination loses entire batch), agitator / pressure mechanical hazards, runaway exotherm / pH crash, and product-quality risks from CIP / SIP failure. Single-use bioreactors trade some sterility risk for extractables / leachables risk.',
  hazards: [
    { code: 'BIO-01', title: 'Sterility breach (contamination)',             category: 'biological',  severity_pre: 5, likelihood_pre: 3, detectability: 4, mechanism: 'Pinhole in filter, faulty seal, inadequate CIP/SIP cycle, or single-use bag leak allows microbial ingress; entire batch contaminated, sometimes unobserved until late in production.', common_mitigations: ['integrity test (bubble-point) of 0.2 µm filters before and after use', 'redundant sterile barriers on all process inlets', 'SIP cycle Fo ≥ 12 minutes at 121 °C', 'single-use bag pre-use leak test (helium or air retention)'], detection_methods: ['real-time online microbial sampling (BIOCOMM / Solaris ATP)', 'pH + dissolved-O₂ + osmolality trend deviation', 'post-batch sterility test per Ph.Eur. 2.6.1'], regulatory_drivers: ['EU GMP Vol 4', 'ICH Q7', '21 CFR Part 211'], typical_test_method: 'Media fill simulation per PIC/S Annex 1 — fill bioreactor with growth medium, run normal process, observe for turbidity over 14 days.' },
    { code: 'MEC-01', title: 'Agitator-drive failure',                       category: 'mechanical',  severity_pre: 4, likelihood_pre: 2, detectability: 2, mechanism: 'Motor / coupling / impeller failure causes loss of mixing; oxygen mass-transfer crashes, anaerobic zones develop, batch yield collapses.', common_mitigations: ['redundant agitator drives (dual-drive impeller layout for high-value batches)', 'magnetic-drive impellers in single-use systems', 'vibration monitoring on shaft', 'fault-bypass aeration via spargers'], detection_methods: ['motor current + RPM telemetry', 'dissolved-oxygen trend departure', 'shaft-vibration sensor (semi-perm reactors)'], regulatory_drivers: ['MD 2006/42/EC', 'EU GMP Vol 4'], typical_test_method: 'Endurance test of agitator drive at maximum-rated viscosity for 1000 hours.' },
    { code: 'CHE-01', title: 'pH / temperature excursion',                   category: 'chemical',    severity_pre: 4, likelihood_pre: 3, detectability: 2, mechanism: 'Doser pump failure, sensor drift, jacket-cooling failure, or runaway exotherm causes pH or temperature to leave critical-process-parameter window; cell line stress or death, batch yield loss.', common_mitigations: ['redundant pH + temperature sensors with disagreement alarm', 'jacket-cooling N+1 redundancy', 'feed-pump revolution counter vs commanded volume', 'emergency-cooling fallback (chilled water bypass)'], detection_methods: ['continuous trend + rate-of-change monitoring', 'sensor-disagreement alarm', 'jacket-temperature in/out delta'], regulatory_drivers: ['EU GMP Vol 4', 'ICH Q7'], typical_test_method: 'Probe accuracy verification quarterly against NIST-traceable buffer / temperature reference.' },
    { code: 'MEC-02', title: 'Foam-out / fluid escape',                      category: 'mechanical',  severity_pre: 3, likelihood_pre: 3, detectability: 2, mechanism: 'Excessive sparging or surfactant build-up creates foam column; foam exits vessel through exhaust filter, blinds filter, eventually breaches sterile barrier.', common_mitigations: ['anti-foam dosing system with optical level sensor', 'mechanical foam breaker on agitator shaft', 'oversized exhaust filter with foam-out detection', 'sparge-rate limit + ramp logic'], detection_methods: ['optical foam-level sensor in headspace', 'exhaust-filter differential-pressure trending', 'overflow tray with conductivity sensor'], regulatory_drivers: ['EU GMP Vol 4'], typical_test_method: 'Foam-stability test per cell-line + media combination at production-scale conditions.' },
    { code: 'OPE-01', title: 'CIP cycle failure (residual cleaning agent)',  category: 'operational', severity_pre: 4, likelihood_pre: 2, detectability: 3, mechanism: 'Clean-in-Place cycle skipped, abbreviated, or with depleted detergent; residual sodium hydroxide / phosphoric acid carries into next batch, kills cell line or contaminates product.', common_mitigations: ['CIP recipe interlocks (conductivity + temperature + time)', 'final-rinse conductivity verification before SIP', 'TOC (total-organic-carbon) test post-CIP', 'CIP-skid validation per ASME BPE'], detection_methods: ['conductivity trend during final rinse', 'TOC sampling on post-CIP grab', 'CIP-recipe deviation log + e-records (Part 11)'], regulatory_drivers: ['EU GMP Vol 4', '21 CFR Part 11'], typical_test_method: 'CIP cycle validation per ASME BPE — coupon test with riboflavin tracer; final rinse conductivity ≤ 1 µS/cm.' },
    { code: 'CHE-02', title: 'Extractables / leachables (single-use bags)',  category: 'chemical',    severity_pre: 3, likelihood_pre: 3, detectability: 4, mechanism: 'Polymer additives, plasticisers, gamma-irradiation byproducts leach from single-use bag into product; contaminates final drug substance, alters cell growth.', common_mitigations: ['BPSA/BPOG E&L study per bag-bioreactor system + process fluid', 'standardised pre-conditioning rinse', 'risk-based assessment per cell-line + product modality'], detection_methods: ['post-batch HPLC-MS screening for known extractables', 'cell-growth comparison vs glass-vessel control', 'periodic supplier change-notification review'], regulatory_drivers: ['BPSA / BPOG SUS', 'EU GMP Vol 4'], typical_test_method: 'BPOG standardised extractables study — 50 °C × 70 % ethanol model solvent for 21 days; identify and quantify extracted species by LC-MS / GC-MS.' },
  ],
}

const AUV: ClassHazards = {
  product_class: 'auv',
  display_name: 'Autonomous Underwater Vehicle (AUV)',
  hazard_summary: 'AUV hazards are dominated by pressure-hull integrity (catastrophic implosion at depth), loss-of-comms (no radio underwater), battery failure (lithium fire in confined volume), and entanglement / fouling in operational environment. Recovery in event of failure is slow + expensive.',
  hazards: [
    { code: 'MEC-01', title: 'Pressure-hull implosion',                      category: 'mechanical',  severity_pre: 5, likelihood_pre: 2, detectability: 1, mechanism: 'External pressure exceeds hull collapse depth (e.g. ballast control failure causes excursion below design depth); implosion is instantaneous, releases all stored mechanical energy, destroys vehicle.', common_mitigations: ['hull collapse depth ≥ 1.5 × maximum-operating-depth', 'redundant depth sensors with disagreement alarm', 'automatic ballast drop on depth excursion', 'pressure-strength test of each hull article per PED'], detection_methods: ['depth sensor (multiple, independent)', 'hull strain gauge on critical-section bulkheads', 'acoustic communications to surface support'], regulatory_drivers: ['PED 2014/68/EU', 'DNV-RU-NAUT'], typical_test_method: 'PED §7.2 + DNV pressure-strength test at 1.5 × maximum-allowable pressure for 1 hour.' },
    { code: 'CHE-01', title: 'Lithium battery thermal event in pressure vessel', category: 'thermal',  severity_pre: 5, likelihood_pre: 2, detectability: 3, mechanism: 'Cell internal short or mechanical damage initiates thermal runaway inside sealed pressure vessel; off-gas pressurises vessel beyond design, breaches hull or vents into oil-filled pressure-balanced compartment with risk of ignition + secondary damage.', common_mitigations: ['oil-filled pressure-balanced battery compartments (no headspace)', 'per-cell fusing + propagation barriers', 'pressure-relief diaphragm vented to ocean', 'inert (silicone fluid) thermal mass'], detection_methods: ['compartment pressure transducer', 'temperature sensors on each cell module', 'voltage divergence between parallel strings'], regulatory_drivers: ['UN 38.3', 'IEC 62619', 'DNV-RU-NAUT'], typical_test_method: 'UN 38.3 cell tests + DNV battery-system FMEA + single-cell-fail injection test.' },
    { code: 'OPE-01', title: 'Loss of acoustic communications',              category: 'software',    severity_pre: 3, likelihood_pre: 4, detectability: 2, mechanism: 'Acoustic propagation distorted by thermocline / multipath / noise; surface support loses contact; recovery uncertain in time and location.', common_mitigations: ['acoustic-modem with adaptive coding + repeat', 'mission-plan return-to-rendezvous time after timeout', 'surface marker buoy auto-release on long timeout', 'redundant Iridium / VHF on surface for emergency'], detection_methods: ['ack/nack on every command + telemetry', 'acoustic-modem SNR trend', 'mission-time-elapsed checkpoint'], regulatory_drivers: ['IMO MEPC', 'DNV-RU-NAUT'], typical_test_method: 'Sea-trial under realistic acoustic conditions including thermocline traversal; verify recovery from 1-hour comms gap.' },
    { code: 'OPE-02', title: 'GPS-denied surface navigation (post-mission)', category: 'software',    severity_pre: 3, likelihood_pre: 3, detectability: 3, mechanism: 'AUV surfaces in expected location but GPS fix unavailable (electronics fault, GPS-denied environment); inertial position-error from dead-reckoning accumulates; cannot rendezvous with support vessel.', common_mitigations: ['multi-constellation GNSS receiver', 'pre-mission inertial / DVL-aided dead-reckoning calibration', 'acoustic-positioning beacon range from support vessel', 'surface-mode visual / Iridium beacon'], detection_methods: ['GNSS fix-acquisition timeout', 'inertial-vs-GNSS residual at surface', 'time-since-last-fix counter'], regulatory_drivers: ['DNV-RU-NAUT'], typical_test_method: 'Surface-rendezvous accuracy test under realistic operating conditions; CEP ≤ 100 m at 10 km range.' },
    { code: 'MEC-02', title: 'Propeller fouling / entanglement',             category: 'mechanical',  severity_pre: 4, likelihood_pre: 3, detectability: 3, mechanism: 'Fishing line, kelp, debris fouls thruster; loss of propulsion or loss of control; vehicle drifts in current, may not return.', common_mitigations: ['ducted thrusters with screen', 'cable-cutter at thruster intake', 'redundant thrusters with control-allocation fallback', 'emergency ballast-drop on stuck-thruster detection'], detection_methods: ['thruster current vs RPM mismatch (high current low RPM = fouled)', 'attitude-error-vs-commanded thrust residual', 'descent-rate / depth-rate anomaly'], regulatory_drivers: ['DNV-RU-NAUT'], typical_test_method: 'Fouling-rig sea-trial — deliberately introduce monofilament to thruster, verify cutter clears or fallback engages.' },
    { code: 'CHE-02', title: 'Hydraulic / lubricant release into water',     category: 'chemical',    severity_pre: 2, likelihood_pre: 3, detectability: 1, mechanism: 'Pressure-balanced compartment fluid leak, hydraulic-actuator seal failure releases oil into seawater; biodegradable lubricants typical but reportable in sensitive areas.', common_mitigations: ['biodegradable hydraulic fluid (e.g. canola-ester EALs)', 'compartment-level leakage monitoring', 'compartment volume tracked over mission', 'environmental-permit documentation'], detection_methods: ['compartment-fluid-volume sensor', 'periodic visual at surface', 'environmental observer onboard support vessel'], regulatory_drivers: ['IMO MEPC'], typical_test_method: 'Hydraulic fluid biodegradability test per OECD 301B — ≥ 60 % biodegradation in 28 days.' },
  ],
}

const HAPS: ClassHazards = {
  product_class: 'haps',
  display_name: 'High-Altitude Pseudo-Satellite (HAPS)',
  hazard_summary: 'HAPS hazards combine stratospheric environmental extremes (−70 °C, low pressure, UV, atomic oxygen), aviation-grade flight-safety risks (loss of control, uncommanded descent through controlled airspace), and operational risks (PV array degradation, lithium battery night-cycle failure, ice accretion during ascent / descent through tropopause).',
  hazards: [
    { code: 'OPE-01', title: 'Uncommanded descent through controlled airspace', category: 'operational', severity_pre: 5, likelihood_pre: 2, detectability: 3, mechanism: 'Loss-of-control event in stratosphere descends HAPS through Class A airspace (FL180 - FL600 in many jurisdictions); collision risk with commercial aviation; debris on ground.', common_mitigations: ['mandatory flight-termination system (independent of primary autopilot)', 'ADS-B Out transmitter at all altitudes', 'pre-coordinated descent corridor agreed with ATC', 'parachute / glide-recovery design'], detection_methods: ['IMU-based descent-rate monitor', 'altitude vs commanded-trajectory residual', 'ATC TCAS conflict alert (manned)'], regulatory_drivers: ['ICAO Annex 8', 'EASA Special Conditions / FAA Experimental', 'CAA CAP 722A'], typical_test_method: 'Flight-termination-system actuation test at high-altitude test article; controlled descent demonstration.' },
    { code: 'ENV-01', title: 'PV array degradation from atomic oxygen / UV',  category: 'environmental', severity_pre: 3, likelihood_pre: 4, detectability: 4, mechanism: 'Stratospheric atomic-oxygen flux + intense UV degrades polymer encapsulants, browns optical materials, reduces PV efficiency by 0.5-2 % per month of exposure.', common_mitigations: ['space-qualified encapsulants (ETFE / fluoropolymer)', 'inorganic-coating overlayer on optics', 'designed for ≥ 30 % EOL margin on PV array', 'in-flight PV-string current-trend monitoring'], detection_methods: ['per-string current + voltage telemetry', 'spectroradiometer aboard for solar-spectrum reference', 'periodic on-orbit calibration manoeuvre'], regulatory_drivers: ['ICAO Annex 8', 'DO-160G'], typical_test_method: 'Atomic-oxygen + UV chamber exposure test per ASTM E2089 — accelerated equivalent of 1-year stratospheric exposure.' },
    { code: 'THR-01', title: 'Battery cold-soak failure (night cycle)',      category: 'thermal',     severity_pre: 4, likelihood_pre: 3, detectability: 2, mechanism: 'During night, battery temperature drops below −20 °C in stratosphere; cell internal resistance climbs, discharge curve sags; insufficient power for control systems or PV charging at dawn.', common_mitigations: ['battery thermal-management heater + insulation', 'lithium chemistry rated for −40 °C operation (e.g. Tadiran LiSOCl₂ for low-rate)', 'battery-mass / thermal-time-constant tuned for night duration', 'minimum-power dawn-recovery mode'], detection_methods: ['per-cell temperature + voltage telemetry', 'state-of-charge tracking against night-duration model', 'discharge-current limit cuts in below voltage floor'], regulatory_drivers: ['DO-160G', 'UN 38.3'], typical_test_method: 'DO-160 §4 + §5 temperature-altitude test from +50 °C to −70 °C in altitude chamber.' },
    { code: 'ENV-02', title: 'Ice accretion during ascent / descent',         category: 'environmental', severity_pre: 4, likelihood_pre: 3, detectability: 2, mechanism: 'Traversing the tropopause through supercooled-liquid-water clouds during ascent or descent accretes ice on wings + control surfaces; weight + drag spike; stall or loss-of-control.', common_mitigations: ['ascent / descent profile avoidance of high-icing latitudes', 'electrothermal or pneumatic-boot wing leading-edge de-ice', 'ice-detection sensors triggering profile adjust', 'rapid climb through icing band'], detection_methods: ['ice-detector probes on leading edges', 'lift / pitch-attitude vs commanded mismatch', 'temperature + dew-point spread monitoring'], regulatory_drivers: ['DO-160G'], typical_test_method: 'DO-160 §22 icing test; supercooled-liquid-water-tunnel exposure at certified rates.' },
    { code: 'OPE-02', title: 'Solar-storm radiation upset (SEU)',            category: 'radiation',   severity_pre: 3, likelihood_pre: 2, detectability: 4, mechanism: 'Solar particle event raises proton flux at 25 km altitude; single-event upset flips memory bits, corrupts control state; software-recoverable but not guaranteed for unprotected code.', common_mitigations: ['rad-tolerant or rad-hardened FPGAs in critical path', 'ECC memory with periodic scrub', 'redundant compute (TMR) with majority voting on critical signals', 'space-weather forecasting for mission planning'], detection_methods: ['SEU error counter telemetry', 'memory-scrub-error rate trend', 'space-weather forecast monitoring'], regulatory_drivers: ['DO-178C', 'DO-254'], typical_test_method: 'DO-254 / MIL-STD-883 SEU test at proton accelerator; characterise upset cross-section.' },
    { code: 'OPE-03', title: 'Stratospheric wind shear (jet stream)',        category: 'environmental', severity_pre: 3, likelihood_pre: 4, detectability: 2, mechanism: 'Polar jet stream incursion into stratosphere produces wind speeds exceeding HAPS airspeed envelope; vehicle drifts off station-keeping orbit; mission disruption + fuel reserve depleted.', common_mitigations: ['flight planning vs forecast jet-stream position', 'sufficient propulsion margin (≥ 2× forecast max wind)', 'mission-replan when station-keeping margin falls below threshold', 'descent to lower altitude as fallback'], detection_methods: ['GPS-derived ground-speed vs airspeed delta', 'meteorological probe (Pitot + dynamic pressure)', 'forecast-vs-actual residual'], regulatory_drivers: ['ICAO Annex 8'], typical_test_method: 'Sustained-station-keeping demonstration in forecast worst-case winds during operational test.' },
  ],
}

// ─── Registry ───────────────────────────────────────────────────────────────

export const CLASS_HAZARDS: Record<string, ClassHazards> = {
  energy_storage: ENERGY_STORAGE,
  thermal_system:       HEATPUMP,
  vertical_farm:  VERTICAL_FARM,
  ev_charger:     EV_CHARGER,
  wearable_medical:            CGM,
  drone:          DRONE,
  edge_ai_server:        EDGE_AI,
  bioreactor:     BIOREACTOR,
  auv:            AUV,
  haps:           HAPS,
}

// Same alias-resolution pattern as class-standards.ts: maps display strings
// like "Battery Energy Storage System (BESS)" to canonical keys.
function resolveHazardKey(productClass: string): string | null {
  if (CLASS_HAZARDS[productClass]) return productClass
  const lower = productClass.toLowerCase()
  for (const k of Object.keys(CLASS_HAZARDS)) {
    if (k.toLowerCase() === lower) return k
  }
  const aliases: Array<[RegExp, string]> = [
    [/\b(bess|battery\s+energy\s+storage|energy\s+storage)\b/, 'energy_storage'],
    [/\b(heatpump|heat\s+pump|thermal\s+system|hvac)\b/, 'thermal_system'],
    [/\b(vertical\s+farm|indoor\s+farm|hydroponic)\b/, 'vertical_farm'],
    [/\b(ev[\s-]?charger|charging\s+station|charge\s+point)\b/, 'ev_charger'],
    [/\b(cgm|continuous\s+glucose|wearable\s+medical|patch\s+monitor)\b/, 'wearable_medical'],
    [/\b(drone|uav|quadcopter)\b/, 'drone'],
    [/\b(edge\s+ai|edge[-\s]?compute|inference\s+box)\b/, 'edge_ai_server'],
    [/\b(bioreactor|fermenter|cell[-\s]?culture)\b/, 'bioreactor'],
    [/\b(auv|underwater\s+vehicle|subsea)\b/, 'auv'],
    [/\b(haps|stratospheric|high[-\s]?altitude\s+platform)\b/, 'haps'],
  ]
  for (const [rx, key] of aliases) {
    if (rx.test(lower)) return key
  }
  return null
}

/** Get the hazards block for a product class. Resolves display names + aliases. Falls back to empty. */
export function getClassHazards(productClass: string): ClassHazards {
  const key = resolveHazardKey(productClass)
  if (key) return CLASS_HAZARDS[key]
  return {
    product_class: productClass,
    display_name: productClass,
    hazards: [],
    hazard_summary: `No hazards registered for product class "${productClass}". Add an entry to class-hazards.ts to render the §Risk section for this class.`,
  }
}

/**
 * Compute RPN (Risk Priority Number) for a hazard before mitigation:
 *   RPN = severity × likelihood × detectability_difficulty
 *
 * Returns 1-125. Higher = worse. Use to sort hazards in the §Risk page so
 * the highest-RPN items are at the top.
 */
export function computeHazardRPN(hazard: ClassHazard): number {
  return hazard.severity_pre * hazard.likelihood_pre * hazard.detectability
}
