#!/bin/bash
# check-ai-models.sh — Scan codebase for stale/retired AI model references.
# Runs on SessionStart hook and outputs JSON for Claude to act on.
#
# Model registry: maps retired model IDs to their replacements.
# Update this list when providers announce retirements or new GA models.

set -euo pipefail

REPO_ROOT="$(cd "$(dirname "$0")/.." && pwd)"
SRC="$REPO_ROOT/src"

STALE_COUNT=0
OUTPUT=""

check_model() {
  local pattern="$1"
  local replacement="$2"
  local reason="$3"

  local matches
  matches=$(grep -rn --include="*.ts" --include="*.tsx" "$pattern" "$SRC" 2>/dev/null \
    | grep -v node_modules \
    | grep -v __tests__ \
    | grep -v "\.test\." \
    | grep -v "\.spec\." \
    || true)

  if [ -n "$matches" ]; then
    local count
    count=$(echo "$matches" | wc -l | tr -d ' ')
    STALE_COUNT=$((STALE_COUNT + count))
    OUTPUT="${OUTPUT}
## ${pattern} → ${replacement}
**Reason:** ${reason}
**${count} reference(s):**
$(echo "$matches" | head -10 | sed 's/^/- /')
"
  fi
}

# ── Retired text models ────────────────────────────────────────────
check_model "gpt-4o" "gpt-5.3-instant" "GPT-4o retired March 11 2026"
check_model "gpt-4-turbo" "gpt-5.3-instant" "GPT-4 Turbo retired"
check_model "o1" "gpt-5.4-thinking" "o1 replaced by GPT-5.4 Thinking"

# ── Preview → GA migrations ───────────────────────────────────────
check_model "gemini-3.1-pro-preview" "gemini-3.1-pro" "GA version available"
check_model "gemini-3.1-flash-lite-preview" "gemini-3.1-flash-lite" "GA version available"
check_model "gemini-3-pro-preview" "gemini-3.1-pro" "Superseded by 3.1"
check_model "gemini-3-flash-preview" "gemini-3.1-flash-lite" "Superseded by 3.1"

# ── Retired audio/TTS models ──────────────────────────────────────
check_model "\"tts-1\"" "gpt-4o-mini-tts" "Legacy TTS, 35% higher error rate"
check_model "tts-1-hd" "gpt-4o-mini-tts" "Legacy TTS HD"
check_model "eleven_multilingual_v2" "eleven_v3" "ElevenLabs v3 available"
check_model "eleven_turbo_v2_5" "eleven_v3" "ElevenLabs v3 available"

# ── Retired image models ──────────────────────────────────────────
check_model "stable-diffusion-xl" "stable-image-ultra" "SDXL from 2023, SD 3.5 available"
check_model "stable-image-core" "stable-image-ultra" "Replaced by Ultra (SD 3.5)"
check_model "flux-1.1-pro" "flux-2-pro" "Flux 2 available with better typography"

# ── Output ─────────────────────────────────────────────────────────
if [ "$STALE_COUNT" -eq 0 ]; then
  echo '{"systemMessage": "All AI models are up to date."}'
else
  # Write detailed report for Claude to read
  REPORT_FILE="$REPO_ROOT/.ai-model-audit.md"
  cat > "$REPORT_FILE" << EOF
# AI Model Audit — $(date +%Y-%m-%d)

**${STALE_COUNT} stale model reference(s) found.**
${OUTPUT}

---
*Auto-generated by scripts/check-ai-models.sh*
EOF

  echo "{\"systemMessage\": \"Found ${STALE_COUNT} stale AI model reference(s). Run: cat .ai-model-audit.md for details.\"}"
fi
