/**
 * @file fact-check-seeded-techniques-opus.ts
 *
 * @description Phase 5B second-pass fact-check using Claude Opus 4.7 via the
 * Anthropic SDK. Cross-model review of the 80 rows in
 * `manufacturing_technique_enrichments` with source='seed_llm_deepseek' —
 * genuinely independent from the DeepSeek-seeded content (different provider,
 * different training), so the flag set is not just DeepSeek-reviewing-DeepSeek
 * sycophancy. Stronger technical reasoning than the DeepSeek reviewer pass.
 *
 * @usage npx tsx scripts/fact-check-seeded-techniques-opus.ts [--limit=N] [--slug=<slug>]
 *        Output: FORGE-TECHNIQUE-FACTCHECK-OPUS-<ISO-DATE>.md
 *
 * @requires ANTHROPIC_API_KEY, NEXT_PUBLIC_SUPABASE_URL, SUPABASE_SERVICE_ROLE_KEY
 *
 * Read-only against the DB. Safe to re-run.
 */

import Anthropic from "@anthropic-ai/sdk"
import { createClient } from "@supabase/supabase-js"
import { readFileSync, writeFileSync } from "node:fs"
import { join } from "node:path"

const MODEL_ID = "claude-opus-4-7"
const MAX_TOKENS = 2000
const DELAY_MS = 200
const CONCURRENCY = 3

function loadEnvLocal() {
  try {
    const envPath = join(process.cwd(), ".env.local")
    const raw = readFileSync(envPath, "utf-8")
    for (const line of raw.split("\n")) {
      const trimmed = line.trim()
      if (!trimmed || trimmed.startsWith("#")) continue
      const eq = trimmed.indexOf("=")
      if (eq < 0) continue
      const key = trimmed.slice(0, eq).trim()
      let value = trimmed.slice(eq + 1).trim()
      if ((value.startsWith('"') && value.endsWith('"')) || (value.startsWith("'") && value.endsWith("'"))) {
        value = value.slice(1, -1)
      }
      if (!process.env[key]) process.env[key] = value
    }
  } catch {
    /* noop */
  }
}

interface Flag {
  severity: "low" | "medium" | "high"
  category: string
  quote: string
  reason: string
  suggested_correction: string | null
}

interface ReviewResult {
  verdict: "ok" | "concerns"
  flags: Flag[]
  summary: string
}

const REVIEW_PROMPT = `You are a senior manufacturing engineer reviewing a Design-for-Manufacture reference entry for factual accuracy. The entry was generated by another LLM (DeepSeek) and may contain errors. Your review will be cross-model — you are Claude Opus 4.7, not DeepSeek.

Your job: flag DEFINITE factual errors, unrealistic tolerance claims, invented brand names, misapplied examples, or unsafe advice. Do not flag stylistic issues. Do not flag things that are merely incomplete. Only flag what is WRONG or MISLEADING.

For each flag, suggest a corrected value where possible (e.g. if best_mm is over-optimistic, suggest a realistic value).

Severity scale:
- high: advice is safety-critical wrong, or a tolerance claim is physically impossible, or an application suggestion is genuinely dangerous to follow
- medium: misleading enough to mislead a founder's design (e.g. claiming ±0.01mm for a process that realistically holds ±0.1mm; listing an inappropriate application as "common")
- low: minor technical error (e.g. wrong units, slightly optimistic best-case, edge-case material suggestion)

Return ONLY valid JSON (no markdown fences, no prose outside the JSON) with this exact schema:
{
  "verdict": "ok" | "concerns",
  "flags": [
    {
      "severity": "low" | "medium" | "high",
      "category": "tolerance" | "material" | "equipment" | "safety" | "application" | "other",
      "quote": "the specific claim from the entry",
      "reason": "why this is wrong, with the correct technical context",
      "suggested_correction": "recommended replacement value/claim, or null if edit isn't obvious"
    }
  ],
  "summary": "one-sentence overall verdict"
}

If the entry is broadly accurate, return verdict="ok" and flags=[]. Do not manufacture concerns to look thorough.`

function tryParseJson(text: string): unknown {
  const trimmed = text.trim()
  const candidate = trimmed.startsWith("{")
    ? trimmed
    : trimmed.replace(/^```json?\s*/i, "").replace(/```\s*$/i, "").trim()
  try {
    return JSON.parse(candidate)
  } catch {
    // Try to pull out the first {...} block
    const match = candidate.match(/\{[\s\S]*\}/)
    if (match) {
      try {
        return JSON.parse(match[0])
      } catch {
        return null
      }
    }
    return null
  }
}

async function reviewRow(
  client: Anthropic,
  row: Record<string, unknown>,
): Promise<ReviewResult | null> {
  const payload = JSON.stringify(
    {
      technique_slug: row.technique_slug,
      article_markdown: row.article_markdown,
      real_world_tolerances: row.real_world_tolerances,
      real_world_materials: row.real_world_materials,
      real_world_equipment: row.real_world_equipment,
      tips_and_insights: row.tips_and_insights,
      common_applications: row.common_applications,
    },
    null,
    2,
  )

  try {
    // NOTE: claude-opus-4-7 deprecated the `temperature` parameter — omit it.
    const msg = await client.messages.create({
      model: MODEL_ID,
      max_tokens: MAX_TOKENS,
      system: REVIEW_PROMPT,
      messages: [
        { role: "user", content: `Review this technique entry:\n\n${payload}` },
      ],
    })

    // Concatenate all text blocks
    const text = msg.content
      .filter((b) => b.type === "text")
      .map((b) => (b.type === "text" ? b.text : ""))
      .join("")

    const parsed = tryParseJson(text) as
      | { verdict?: string; flags?: unknown; summary?: string }
      | null
    if (!parsed) {
      console.warn(`  ✗ ${row.technique_slug} JSON parse failed. Raw: ${text.slice(0, 200)}`)
      return null
    }

    const verdict = parsed.verdict === "concerns" ? "concerns" : "ok"
    const flags: Flag[] = Array.isArray(parsed.flags)
      ? parsed.flags
          .filter((f): f is Record<string, unknown> => !!f && typeof f === "object")
          .map((f) => ({
            severity: (["low", "medium", "high"].includes(f.severity as string) ? f.severity : "low") as Flag["severity"],
            category: String(f.category ?? "other"),
            quote: String(f.quote ?? "").slice(0, 600),
            reason: String(f.reason ?? "").slice(0, 800),
            suggested_correction:
              f.suggested_correction === null || f.suggested_correction === undefined
                ? null
                : String(f.suggested_correction).slice(0, 400),
          }))
      : []

    return {
      verdict,
      flags,
      summary: String(parsed.summary ?? "").slice(0, 400),
    }
  } catch (err) {
    console.warn(`  ✗ ${row.technique_slug} Anthropic API failed: ${err instanceof Error ? err.message : err}`)
    return null
  }
}

async function main() {
  loadEnvLocal()

  const args = new Set(process.argv.slice(2))
  const limitArg = [...args].find((a) => a.startsWith("--limit="))
  const limit = limitArg ? Math.max(1, Number.parseInt(limitArg.split("=")[1], 10)) : undefined
  const slugArg = [...args].find((a) => a.startsWith("--slug="))
  const slug = slugArg ? slugArg.split("=")[1] : null

  const supabaseUrl = process.env.NEXT_PUBLIC_SUPABASE_URL
  const supabaseKey = process.env.SUPABASE_SERVICE_ROLE_KEY
  const anthropicKey = process.env.ANTHROPIC_API_KEY

  if (!supabaseUrl || !supabaseKey || !anthropicKey) {
    console.error("Missing env: NEXT_PUBLIC_SUPABASE_URL / SUPABASE_SERVICE_ROLE_KEY / ANTHROPIC_API_KEY")
    process.exit(1)
  }

  const supabase = createClient(supabaseUrl, supabaseKey)
  const client = new Anthropic({ apiKey: anthropicKey, timeout: 180_000, maxRetries: 1 })

  console.log(`Model: ${MODEL_ID}`)
  console.log("Fetching seed_llm_deepseek rows…")
  let query = supabase
    .from("manufacturing_technique_enrichments")
    .select("id, technique_slug, article_markdown, real_world_tolerances, real_world_materials, real_world_equipment, tips_and_insights, common_applications")
    .eq("source", "seed_llm_deepseek")
    .order("technique_slug")

  if (slug) query = query.eq("technique_slug", slug)
  if (limit) query = query.limit(limit)

  const { data: rows, error } = await query
  if (error || !rows) {
    console.error("Fetch failed:", error?.message)
    process.exit(1)
  }
  console.log(`Reviewing ${rows.length} rows, concurrency=${CONCURRENCY}…\n`)

  const results: Array<{ slug: string; result: ReviewResult | null }> = []
  let ok = 0
  let concerns = 0
  let errored = 0
  let highSev = 0
  let medSev = 0
  let lowSev = 0

  for (let i = 0; i < rows.length; i += CONCURRENCY) {
    const batch = rows.slice(i, i + CONCURRENCY)
    const batchResults = await Promise.all(
      batch.map(async (row) => {
        const slugLabel = row.technique_slug as string
        const result = await reviewRow(client, row as Record<string, unknown>)
        return { slug: slugLabel, result }
      }),
    )

    for (const { slug: slugLabel, result } of batchResults) {
      results.push({ slug: slugLabel, result })
      const idx = results.length
      if (!result) {
        errored++
        console.log(`  [${idx}/${rows.length}] ${slugLabel} … ERROR`)
      } else if (result.verdict === "ok") {
        ok++
        console.log(`  [${idx}/${rows.length}] ${slugLabel} … ok`)
      } else {
        concerns++
        const h = result.flags.filter((f) => f.severity === "high").length
        const m = result.flags.filter((f) => f.severity === "medium").length
        const l = result.flags.filter((f) => f.severity === "low").length
        highSev += h
        medSev += m
        lowSev += l
        console.log(`  [${idx}/${rows.length}] ${slugLabel} … concerns (H${h} M${m} L${l})`)
      }
    }

    if (i + CONCURRENCY < rows.length) {
      await new Promise((r) => setTimeout(r, DELAY_MS))
    }
  }

  // ── Report ──
  const now = new Date().toISOString().slice(0, 10)
  const reportPath = `FORGE-TECHNIQUE-FACTCHECK-OPUS-${now}.md`

  const lines: string[] = []
  lines.push(`# Forge Technique Fact-Check — Opus 4.7 — ${now}`)
  lines.push("")
  lines.push(`**Reviewer model:** ${MODEL_ID} via Anthropic SDK (cross-model: genuinely independent from DeepSeek-seeded content).`)
  lines.push(`**Rows reviewed:** ${rows.length}`)
  lines.push(`**Ok (no concerns):** ${ok}`)
  lines.push(`**Concerns:** ${concerns}`)
  lines.push(`**Errored (API call failed):** ${errored}`)
  lines.push(`**Flag totals:** High ${highSev} · Medium ${medSev} · Low ${lowSev}`)
  lines.push("")
  lines.push(`Unlike the prior DeepSeek-reviews-DeepSeek pass, Opus 4.7 and DeepSeek are different architectures + training data, so the flag set represents independent review rather than model-family confirmation bias. (Claude Opus 4.7 does not expose \`temperature\` — reasoning is deterministic-enough for a reviewer prompt.)`)
  lines.push("")

  const renderFlagsOfSeverity = (severity: "high" | "medium" | "low", includeOnlyIfOnlySev = false) => {
    const header = severity === "high" ? "High-severity" : severity === "medium" ? "Medium-severity" : "Low-severity"
    lines.push(`## ${header} flags`)
    lines.push("")
    const filtered = includeOnlyIfOnlySev
      ? results.filter(
          (r) =>
            r.result?.flags.some((f) => f.severity === severity) &&
            !r.result.flags.some((f) => f.severity === "high" || f.severity === "medium"),
        )
      : results.filter((r) => r.result?.flags.some((f) => f.severity === severity))

    if (filtered.length === 0) {
      lines.push("_None._")
      lines.push("")
      return
    }
    for (const { slug, result } of filtered) {
      lines.push(`### \`${slug}\``)
      if (result?.summary) lines.push(`_${result.summary}_`)
      lines.push("")
      for (const f of result!.flags.filter((f) => f.severity === severity)) {
        lines.push(`- **[${f.category}]** ${f.reason}`)
        lines.push(`  > ${f.quote}`)
        if (f.suggested_correction) {
          lines.push(`  - Suggested: ${f.suggested_correction}`)
        }
      }
      lines.push("")
    }
  }

  renderFlagsOfSeverity("high")
  renderFlagsOfSeverity("medium")
  renderFlagsOfSeverity("low", true)

  lines.push("## OK rows")
  lines.push("")
  const okRows = results.filter((r) => r.result?.verdict === "ok")
  for (const { slug } of okRows) {
    lines.push(`- \`${slug}\``)
  }
  if (okRows.length === 0) lines.push("_None._")
  lines.push("")

  if (errored > 0) {
    lines.push("## Errored (API call failed)")
    lines.push("")
    for (const { slug, result } of results) {
      if (!result) lines.push(`- \`${slug}\``)
    }
    lines.push("")
  }

  lines.push("---")
  lines.push("")
  lines.push("### Suggested actions")
  lines.push("")
  lines.push("1. **High-severity flags** — manually review the quoted claim. If confirmed wrong, either edit `real_world_tolerances` / `article_markdown` / `common_applications` via `/ops/techniques`, or run `rejectTechnique`. A re-embed cron pass will refresh the vector overnight.")
  lines.push("2. **Medium-severity flags** — same process, less urgent. Most are `best_mm` over-optimism — can be batch-corrected using the `suggested_correction` field from each flag. A separate script can apply these corrections systematically.")
  lines.push("3. **Low-severity flags** — batch-edit on the next enrichment pass; no urgent action.")

  writeFileSync(reportPath, lines.join("\n"))
  console.log(`\nReport written: ${reportPath}`)
  console.log(`Summary: ${ok} ok · ${concerns} concerns · ${errored} errored`)
  console.log(`Flag totals: H${highSev} M${medSev} L${lowSev}`)
}

main().catch((err) => {
  console.error(err)
  process.exit(1)
})
