/**
 * @file fact-check-seeded-techniques.ts
 *
 * @description Phase 5B second-pass fact-check over the 80 LLM-seeded rows in
 * `manufacturing_technique_enrichments` where source='seed_llm_deepseek'. For
 * each row, sends a fresh DeepSeek completion asking a skeptical reviewer
 * prompt to flag factual errors, unrealistic tolerance claims, invented
 * equipment brand names, or unsafe advice. Writes a per-run markdown report
 * listing every flagged row with severity + excerpt.
 *
 * @usage npx tsx scripts/fact-check-seeded-techniques.ts [--limit=N] [--skip-ok]
 *        Output: FORGE-TECHNIQUE-FACTCHECK-<ISO-DATE>.md
 *
 * @requires DEEPSEEK_API_KEY, NEXT_PUBLIC_SUPABASE_URL, SUPABASE_SERVICE_ROLE_KEY
 *
 * Safe to re-run; read-only against the DB (no writes).
 */

import { createClient } from "@supabase/supabase-js"
import { readFileSync, writeFileSync } from "node:fs"
import { join } from "node:path"

const DEEPSEEK_URL = "https://api.deepseek.com/chat/completions"
const DELAY_MS = 250

function loadEnvLocal() {
  try {
    const envPath = join(process.cwd(), ".env.local")
    const raw = readFileSync(envPath, "utf-8")
    for (const line of raw.split("\n")) {
      const trimmed = line.trim()
      if (!trimmed || trimmed.startsWith("#")) continue
      const eq = trimmed.indexOf("=")
      if (eq < 0) continue
      const key = trimmed.slice(0, eq).trim()
      let value = trimmed.slice(eq + 1).trim()
      if ((value.startsWith('"') && value.endsWith('"')) || (value.startsWith("'") && value.endsWith("'"))) {
        value = value.slice(1, -1)
      }
      if (!process.env[key]) process.env[key] = value
    }
  } catch {
    /* noop */
  }
}

interface Flag {
  severity: "low" | "medium" | "high"
  category: string
  quote: string
  reason: string
}

interface ReviewResult {
  verdict: "ok" | "concerns"
  flags: Flag[]
  summary: string
}

const REVIEW_PROMPT = `You are a skeptical manufacturing engineer reviewing a Design-for-Manufacture reference entry for factual accuracy. The entry was generated by another LLM and may contain errors.

Your job: flag only DEFINITE factual errors, unrealistic tolerance claims, invented brand names, or unsafe advice. Do not flag stylistic issues. Do not flag things that are merely incomplete. Only flag what is WRONG.

Severity scale:
- high: advice is safety-critical wrong (e.g. "FSW can join dissimilar thermoplastics" — it's for metals), or a tolerance claim is physically impossible
- medium: misleading enough to mislead a founder's design (e.g. claiming ±0.01mm for a process that realistically holds ±0.1mm)
- low: minor technical error (e.g. wrong units, slightly optimistic capacity)

Return ONLY valid JSON (no markdown fences) with this schema:
{
  "verdict": "ok" | "concerns",
  "flags": [
    { "severity": "low"|"medium"|"high", "category": "tolerance"|"material"|"equipment"|"safety"|"application"|"other", "quote": "the specific claim from the entry", "reason": "why this is wrong" }
  ],
  "summary": "one-sentence verdict"
}

If the entry is broadly accurate, return verdict="ok" and flags=[]. Do not manufacture concerns to look thorough.`

async function reviewRow(row: Record<string, unknown>, apiKey: string): Promise<ReviewResult | null> {
  const payload = JSON.stringify(
    {
      technique_slug: row.technique_slug,
      article_markdown: row.article_markdown,
      real_world_tolerances: row.real_world_tolerances,
      real_world_materials: row.real_world_materials,
      real_world_equipment: row.real_world_equipment,
      tips_and_insights: row.tips_and_insights,
      common_applications: row.common_applications,
    },
    null,
    2,
  )

  try {
    const res = await fetch(DEEPSEEK_URL, {
      method: "POST",
      headers: { Authorization: `Bearer ${apiKey}`, "Content-Type": "application/json" },
      body: JSON.stringify({
        model: "deepseek-chat",
        temperature: 0.1,
        max_tokens: 1500,
        messages: [
          { role: "system", content: REVIEW_PROMPT },
          { role: "user", content: `Review this technique entry:\n\n${payload}` },
        ],
      }),
    })
    if (!res.ok) {
      console.warn(`  ✗ ${row.technique_slug} HTTP ${res.status}`)
      return null
    }
    const data = await res.json()
    const text = (data.choices?.[0]?.message?.content ?? "").trim()
    if (!text) return null
    const jsonStr = text.startsWith("{") ? text : text.replace(/^```json?\s*/i, "").replace(/```$/, "").trim()
    const parsed = JSON.parse(jsonStr)
    const verdict = parsed.verdict === "concerns" ? "concerns" : "ok"
    const flags: Flag[] = Array.isArray(parsed.flags)
      ? parsed.flags
          .filter((f: unknown) => f && typeof f === "object")
          .map((f: Record<string, unknown>) => ({
            severity: (["low", "medium", "high"].includes(f.severity as string) ? f.severity : "low") as Flag["severity"],
            category: String(f.category ?? "other"),
            quote: String(f.quote ?? "").slice(0, 600),
            reason: String(f.reason ?? "").slice(0, 600),
          }))
      : []
    return {
      verdict,
      flags,
      summary: String(parsed.summary ?? "").slice(0, 400),
    }
  } catch (err) {
    console.warn(`  ✗ ${row.technique_slug} review failed: ${err instanceof Error ? err.message : err}`)
    return null
  }
}

async function main() {
  loadEnvLocal()

  const args = new Set(process.argv.slice(2))
  const limitArg = [...args].find((a) => a.startsWith("--limit="))
  const limit = limitArg ? Math.max(1, Number.parseInt(limitArg.split("=")[1], 10)) : undefined
  const skipOk = args.has("--skip-ok")

  const supabaseUrl = process.env.NEXT_PUBLIC_SUPABASE_URL
  const supabaseKey = process.env.SUPABASE_SERVICE_ROLE_KEY
  const deepseekKey = process.env.DEEPSEEK_API_KEY

  if (!supabaseUrl || !supabaseKey || !deepseekKey) {
    console.error("Missing env: NEXT_PUBLIC_SUPABASE_URL / SUPABASE_SERVICE_ROLE_KEY / DEEPSEEK_API_KEY")
    process.exit(1)
  }

  const supabase = createClient(supabaseUrl, supabaseKey)

  console.log("Fetching seed_llm_deepseek rows…")
  let query = supabase
    .from("manufacturing_technique_enrichments")
    .select("id, technique_slug, article_markdown, real_world_tolerances, real_world_materials, real_world_equipment, tips_and_insights, common_applications")
    .eq("source", "seed_llm_deepseek")
    .order("technique_slug")

  if (limit) query = query.limit(limit)

  const { data: rows, error } = await query
  if (error || !rows) {
    console.error("Fetch failed:", error?.message)
    process.exit(1)
  }
  console.log(`Reviewing ${rows.length} rows…\n`)

  const results: Array<{ slug: string; result: ReviewResult | null }> = []
  let ok = 0
  let concerns = 0
  let errored = 0

  for (const [i, row] of rows.entries()) {
    const slug = row.technique_slug as string
    process.stdout.write(`  [${i + 1}/${rows.length}] ${slug} … `)
    const result = await reviewRow(row as Record<string, unknown>, deepseekKey)
    results.push({ slug, result })
    if (!result) {
      errored++
      process.stdout.write("ERROR\n")
    } else if (result.verdict === "ok") {
      ok++
      process.stdout.write("ok\n")
    } else {
      concerns++
      const high = result.flags.filter((f) => f.severity === "high").length
      const med = result.flags.filter((f) => f.severity === "medium").length
      const low = result.flags.filter((f) => f.severity === "low").length
      process.stdout.write(`concerns (H${high} M${med} L${low})\n`)
    }
    await new Promise((r) => setTimeout(r, DELAY_MS))
  }

  // ── Report ──
  const now = new Date().toISOString().slice(0, 10)
  const reportPath = `FORGE-TECHNIQUE-FACTCHECK-${now}.md`

  const lines: string[] = []
  lines.push(`# Forge Technique Fact-Check — ${now}`)
  lines.push("")
  lines.push(`**Rows reviewed:** ${rows.length}`)
  lines.push(`**Ok (no concerns):** ${ok}`)
  lines.push(`**Concerns:** ${concerns}`)
  lines.push(`**Errored (LLM call failed):** ${errored}`)
  lines.push("")
  lines.push(`Review model: deepseek-chat, temperature 0.1, skeptical-reviewer prompt.`)
  lines.push(`Original seed model: deepseek-chat, temperature 0.3 (see scripts/seed-manufacturing-techniques.ts).`)
  lines.push(`Cross-model fact-check would require swapping the review LLM — left as follow-up.`)
  lines.push("")

  // High severity first
  lines.push("## High-severity flags")
  lines.push("")
  const highRows = results.filter((r) => r.result?.flags.some((f) => f.severity === "high"))
  if (highRows.length === 0) {
    lines.push("_None._")
  } else {
    for (const { slug, result } of highRows) {
      lines.push(`### \`${slug}\``)
      lines.push(`_${result?.summary ?? ""}_`)
      lines.push("")
      for (const f of result!.flags.filter((f) => f.severity === "high")) {
        lines.push(`- **[${f.category}]** ${f.reason}`)
        lines.push(`  > ${f.quote}`)
      }
      lines.push("")
    }
  }

  lines.push("## Medium-severity flags")
  lines.push("")
  const medRows = results.filter((r) => r.result?.flags.some((f) => f.severity === "medium"))
  if (medRows.length === 0) {
    lines.push("_None._")
  } else {
    for (const { slug, result } of medRows) {
      lines.push(`### \`${slug}\``)
      lines.push(`_${result?.summary ?? ""}_`)
      lines.push("")
      for (const f of result!.flags.filter((f) => f.severity === "medium")) {
        lines.push(`- **[${f.category}]** ${f.reason}`)
        lines.push(`  > ${f.quote}`)
      }
      lines.push("")
    }
  }

  lines.push("## Low-severity flags (summary)")
  lines.push("")
  const lowOnlyRows = results.filter(
    (r) =>
      r.result?.flags.some((f) => f.severity === "low") &&
      !r.result.flags.some((f) => f.severity === "medium" || f.severity === "high"),
  )
  for (const { slug, result } of lowOnlyRows) {
    const low = result!.flags.filter((f) => f.severity === "low")
    lines.push(`- \`${slug}\` — ${low.length} minor: ${low.map((f) => f.category).join(", ")}`)
  }
  if (lowOnlyRows.length === 0) lines.push("_None._")
  lines.push("")

  if (skipOk) {
    lines.push("## OK rows (suppressed via --skip-ok)")
  } else {
    lines.push("## OK rows")
    lines.push("")
    const okRows = results.filter((r) => r.result?.verdict === "ok")
    for (const { slug } of okRows) {
      lines.push(`- \`${slug}\``)
    }
    lines.push("")
  }

  if (errored > 0) {
    lines.push("## Errored (LLM call failed)")
    lines.push("")
    for (const { slug, result } of results) {
      if (!result) lines.push(`- \`${slug}\``)
    }
    lines.push("")
  }

  lines.push("---")
  lines.push("")
  lines.push("### Suggested actions")
  lines.push("")
  lines.push("1. **High-severity flags** — manually review the quoted claim. If confirmed wrong, either edit the row (article_markdown / tolerances / etc.) or run `rejectTechnique` via `/ops/techniques`. A re-embed cron pass will refresh the vector next night.")
  lines.push("2. **Medium-severity flags** — same process, less urgent. Consider editing before a public demo.")
  lines.push("3. **Low-severity flags** — batch-edit on the next enrichment pass; no urgent action.")

  writeFileSync(reportPath, lines.join("\n"))
  console.log(`\nReport written: ${reportPath}`)
  console.log(`Summary: ${ok} ok · ${concerns} concerns · ${errored} errored`)
}

main().catch((err) => {
  console.error(err)
  process.exit(1)
})
