/**
 * @file seed-product-dimensions.ts — Seeds product_reference_dimensions with
 * real-world dimensions for ~50 common product categories.
 *
 * Values sourced from manufacturer specs, product databases, engineering handbooks.
 * These are deterministic reference data — no AI generation needed.
 *
 * Usage: npx tsx scripts/seed-product-dimensions.ts
 */

import { config } from "dotenv"
import { resolve } from "path"
config({ path: resolve(process.cwd(), ".env.local") })

import { createClient } from "@supabase/supabase-js"

const supabase = createClient(
  process.env.NEXT_PUBLIC_SUPABASE_URL!,
  process.env.SUPABASE_SERVICE_ROLE_KEY!,
)

const PRODUCTS = [
  // ─── Consumer Electronics ─────────────────────────────────────────
  { product_category: "smartphone", display_name: "Smartphone", typical_length_mm: 150, typical_width_mm: 72, typical_height_mm: 8, length_range_min_mm: 140, length_range_max_mm: 165, width_range_min_mm: 65, width_range_max_mm: 80, height_range_min_mm: 7, height_range_max_mm: 10, typical_weight_kg: 0.19, weight_range_min_kg: 0.15, weight_range_max_kg: 0.24, component_dimensions: { screen_diagonal_mm: 165, battery_capacity_mah: 4500, camera_module_mm: 35 }, common_materials: ["aluminum", "glass", "polymer"], search_keywords: ["phone", "mobile", "smartphone", "cellphone", "handset"] },
  { product_category: "laptop", display_name: "Laptop (13-14 inch)", typical_length_mm: 310, typical_width_mm: 220, typical_height_mm: 16, length_range_min_mm: 295, length_range_max_mm: 325, width_range_min_mm: 210, width_range_max_mm: 235, height_range_min_mm: 12, height_range_max_mm: 20, typical_weight_kg: 1.4, weight_range_min_kg: 1.0, weight_range_max_kg: 1.8, component_dimensions: { screen_diagonal_mm: 355, keyboard_width_mm: 280, trackpad_width_mm: 120, battery_wh: 56 }, common_materials: ["aluminum", "magnesium", "polymer"], search_keywords: ["laptop", "notebook", "computer", "ultrabook"] },
  { product_category: "tablet", display_name: "Tablet (10-11 inch)", typical_length_mm: 250, typical_width_mm: 175, typical_height_mm: 6, length_range_min_mm: 240, length_range_max_mm: 265, width_range_min_mm: 165, width_range_max_mm: 185, height_range_min_mm: 5, height_range_max_mm: 8, typical_weight_kg: 0.48, weight_range_min_kg: 0.35, weight_range_max_kg: 0.65, component_dimensions: { screen_diagonal_mm: 275, battery_mah: 7500 }, common_materials: ["aluminum", "glass"], search_keywords: ["tablet", "ipad", "slate"] },
  { product_category: "smartwatch", display_name: "Smartwatch", typical_length_mm: 44, typical_width_mm: 38, typical_height_mm: 11, length_range_min_mm: 40, length_range_max_mm: 50, width_range_min_mm: 34, width_range_max_mm: 45, height_range_min_mm: 9, height_range_max_mm: 13, typical_weight_kg: 0.045, weight_range_min_kg: 0.03, weight_range_max_kg: 0.07, component_dimensions: { screen_diameter_mm: 40, band_width_mm: 22, battery_mah: 300 }, common_materials: ["aluminum", "stainless_steel", "glass"], search_keywords: ["watch", "smartwatch", "wearable", "fitness tracker"] },
  { product_category: "headphones", product_subcategory: "over_ear", display_name: "Over-Ear Headphones", typical_length_mm: 190, typical_width_mm: 170, typical_height_mm: 85, length_range_min_mm: 170, length_range_max_mm: 210, width_range_min_mm: 150, width_range_max_mm: 190, height_range_min_mm: 75, height_range_max_mm: 95, typical_weight_kg: 0.28, weight_range_min_kg: 0.22, weight_range_max_kg: 0.38, component_dimensions: { driver_diameter_mm: 40, ear_cup_inner_diameter_mm: 60, headband_width_mm: 30 }, common_materials: ["polymer", "aluminum", "foam"], search_keywords: ["headphones", "over-ear", "headset", "audio"] },
  { product_category: "wireless_earbuds", display_name: "Wireless Earbuds + Case", typical_length_mm: 60, typical_width_mm: 50, typical_height_mm: 30, length_range_min_mm: 50, length_range_max_mm: 70, width_range_min_mm: 40, width_range_max_mm: 60, height_range_min_mm: 25, height_range_max_mm: 35, typical_weight_kg: 0.05, weight_range_min_kg: 0.04, weight_range_max_kg: 0.07, component_dimensions: { earbud_length_mm: 30, earbud_weight_g: 5.5, driver_mm: 11, case_battery_mah: 500 }, common_materials: ["polymer", "silicone"], search_keywords: ["earbuds", "airpods", "wireless earphones", "tws"] },
  { product_category: "bluetooth_speaker", display_name: "Portable Bluetooth Speaker", typical_length_mm: 180, typical_width_mm: 70, typical_height_mm: 70, length_range_min_mm: 100, length_range_max_mm: 250, width_range_min_mm: 50, width_range_max_mm: 90, height_range_min_mm: 50, height_range_max_mm: 90, typical_weight_kg: 0.55, weight_range_min_kg: 0.3, weight_range_max_kg: 1.0, component_dimensions: { driver_diameter_mm: 45, passive_radiator_mm: 55, battery_mah: 4000 }, common_materials: ["polymer", "rubber", "aluminum"], search_keywords: ["speaker", "bluetooth speaker", "portable speaker", "wireless speaker"] },

  // ─── Kitchen Appliances ───────────────────────────────────────────
  { product_category: "coffee_machine", product_subcategory: "pod", display_name: "Pod Coffee Machine (Nespresso-style)", typical_length_mm: 330, typical_width_mm: 120, typical_height_mm: 260, length_range_min_mm: 280, length_range_max_mm: 370, width_range_min_mm: 100, width_range_max_mm: 150, height_range_min_mm: 230, height_range_max_mm: 300, typical_weight_kg: 3.0, weight_range_min_kg: 2.5, weight_range_max_kg: 4.0, component_dimensions: { water_tank_volume_ml: 700, pump_pressure_bar: 19, capsule_chamber_diameter_mm: 37, drip_tray_width_mm: 100 }, common_materials: ["polymer", "aluminum", "stainless_steel"], search_keywords: ["coffee", "nespresso", "coffee machine", "espresso", "pod", "capsule"] },
  { product_category: "coffee_machine", product_subcategory: "espresso", display_name: "Semi-Automatic Espresso Machine", typical_length_mm: 350, typical_width_mm: 280, typical_height_mm: 360, length_range_min_mm: 300, length_range_max_mm: 420, width_range_min_mm: 250, width_range_max_mm: 320, height_range_min_mm: 300, height_range_max_mm: 400, typical_weight_kg: 8.0, weight_range_min_kg: 5.0, weight_range_max_kg: 12.0, component_dimensions: { portafilter_diameter_mm: 58, water_tank_volume_ml: 1800, boiler_volume_ml: 250, group_head_diameter_mm: 58 }, common_materials: ["stainless_steel", "aluminum", "brass"], search_keywords: ["espresso", "coffee machine", "barista", "portafilter"] },
  { product_category: "toaster", display_name: "2-Slot Toaster", typical_length_mm: 260, typical_width_mm: 160, typical_height_mm: 200, length_range_min_mm: 230, length_range_max_mm: 300, width_range_min_mm: 140, width_range_max_mm: 180, height_range_min_mm: 180, height_range_max_mm: 220, typical_weight_kg: 1.5, weight_range_min_kg: 1.0, weight_range_max_kg: 2.0, component_dimensions: { slot_width_mm: 28, slot_depth_mm: 130, heating_element_watt: 800 }, common_materials: ["stainless_steel", "polymer"], search_keywords: ["toaster", "bread toaster", "toast"] },
  { product_category: "blender", display_name: "Countertop Blender", typical_length_mm: 200, typical_width_mm: 180, typical_height_mm: 400, length_range_min_mm: 170, length_range_max_mm: 230, width_range_min_mm: 150, width_range_max_mm: 210, height_range_min_mm: 350, height_range_max_mm: 450, typical_weight_kg: 3.5, weight_range_min_kg: 2.5, weight_range_max_kg: 5.0, component_dimensions: { jar_volume_ml: 1500, motor_watt: 700, blade_diameter_mm: 80 }, common_materials: ["polymer", "stainless_steel", "glass"], search_keywords: ["blender", "smoothie", "mixer", "food processor"] },
  { product_category: "kettle", display_name: "Electric Kettle", typical_length_mm: 220, typical_width_mm: 160, typical_height_mm: 250, length_range_min_mm: 190, length_range_max_mm: 250, width_range_min_mm: 140, width_range_max_mm: 180, height_range_min_mm: 220, height_range_max_mm: 280, typical_weight_kg: 1.0, weight_range_min_kg: 0.7, weight_range_max_kg: 1.5, component_dimensions: { volume_ml: 1700, heating_element_watt: 2200, base_diameter_mm: 150 }, common_materials: ["stainless_steel", "polymer", "glass"], search_keywords: ["kettle", "electric kettle", "water boiler", "hot water"] },

  // ─── Vehicles / Mobility ──────────────────────────────────────────
  { product_category: "bicycle", product_subcategory: "road", display_name: "Road Bicycle (Adult)", typical_length_mm: 1700, typical_width_mm: 450, typical_height_mm: 950, length_range_min_mm: 1600, length_range_max_mm: 1850, width_range_min_mm: 400, width_range_max_mm: 500, height_range_min_mm: 850, height_range_max_mm: 1050, typical_weight_kg: 8.5, weight_range_min_kg: 6.5, weight_range_max_kg: 11.0, component_dimensions: { wheel_diameter_mm: 700, tire_width_mm: 25, frame_top_tube_mm: 540, handlebar_width_mm: 420, crank_length_mm: 172 }, common_materials: ["aluminum", "carbon_fiber", "steel"], search_keywords: ["bicycle", "bike", "road bike", "cycling", "cycle"] },
  { product_category: "electric_scooter", display_name: "Electric Kick Scooter", typical_length_mm: 1100, typical_width_mm: 450, typical_height_mm: 1150, length_range_min_mm: 1000, length_range_max_mm: 1200, width_range_min_mm: 400, width_range_max_mm: 500, height_range_min_mm: 1050, height_range_max_mm: 1250, typical_weight_kg: 14, weight_range_min_kg: 10, weight_range_max_kg: 20, component_dimensions: { wheel_diameter_mm: 254, battery_wh: 360, motor_watt: 350, deck_width_mm: 155, folded_height_mm: 490 }, common_materials: ["aluminum", "steel", "polymer"], search_keywords: ["scooter", "electric scooter", "e-scooter", "kick scooter"] },

  // ─── Drones ───────────────────────────────────────────────────────
  { product_category: "drone", product_subcategory: "consumer_quadcopter", display_name: "Consumer Quadcopter Drone", typical_length_mm: 350, typical_width_mm: 350, typical_height_mm: 80, length_range_min_mm: 250, length_range_max_mm: 500, width_range_min_mm: 250, width_range_max_mm: 500, height_range_min_mm: 60, height_range_max_mm: 120, typical_weight_kg: 0.9, weight_range_min_kg: 0.25, weight_range_max_kg: 2.0, component_dimensions: { motor_to_motor_diagonal_mm: 350, propeller_diameter_mm: 240, battery_capacity_mah: 5000, camera_gimbal_weight_g: 120, arm_length_mm: 170 }, common_materials: ["polymer", "carbon_fiber", "aluminum"], search_keywords: ["drone", "quadcopter", "uav", "multirotor", "fpv", "aerial"] },
  { product_category: "drone", product_subcategory: "mini_drone", display_name: "Mini Drone (Sub-250g)", typical_length_mm: 180, typical_width_mm: 180, typical_height_mm: 55, length_range_min_mm: 140, length_range_max_mm: 220, width_range_min_mm: 140, width_range_max_mm: 220, height_range_min_mm: 45, height_range_max_mm: 65, typical_weight_kg: 0.245, weight_range_min_kg: 0.1, weight_range_max_kg: 0.249, component_dimensions: { motor_size_mm: 12, propeller_diameter_mm: 150, battery_capacity_mah: 2250, flight_time_min: 30 }, common_materials: ["polymer", "carbon_fiber"], search_keywords: ["mini drone", "sub-250g", "lightweight drone", "travel drone"] },

  // ─── Furniture ────────────────────────────────────────────────────
  { product_category: "office_chair", display_name: "Ergonomic Office Chair", typical_length_mm: 650, typical_width_mm: 680, typical_height_mm: 1150, length_range_min_mm: 600, length_range_max_mm: 700, width_range_min_mm: 620, width_range_max_mm: 750, height_range_min_mm: 1050, height_range_max_mm: 1300, typical_weight_kg: 15, weight_range_min_kg: 10, weight_range_max_kg: 22, component_dimensions: { seat_width_mm: 500, seat_depth_mm: 450, armrest_height_range_mm: 180, gas_cylinder_stroke_mm: 120, base_diameter_mm: 700 }, common_materials: ["steel", "aluminum", "polymer", "foam", "mesh"], search_keywords: ["chair", "office chair", "desk chair", "ergonomic chair", "task chair"] },
  { product_category: "desk", display_name: "Standing Desk", typical_length_mm: 1400, typical_width_mm: 700, typical_height_mm: 750, length_range_min_mm: 1200, length_range_max_mm: 1800, width_range_min_mm: 600, width_range_max_mm: 800, height_range_min_mm: 650, height_range_max_mm: 1280, typical_weight_kg: 35, weight_range_min_kg: 25, weight_range_max_kg: 50, component_dimensions: { top_thickness_mm: 25, leg_width_mm: 65, motor_lift_capacity_kg: 80, height_adjust_range_mm: 630 }, common_materials: ["mdf", "steel", "aluminum"], search_keywords: ["desk", "standing desk", "sit-stand", "work desk", "table"] },
  { product_category: "bookshelf", display_name: "5-Shelf Bookshelf", typical_length_mm: 800, typical_width_mm: 300, typical_height_mm: 1800, length_range_min_mm: 600, length_range_max_mm: 1000, width_range_min_mm: 250, width_range_max_mm: 350, height_range_min_mm: 1500, height_range_max_mm: 2000, typical_weight_kg: 25, weight_range_min_kg: 15, weight_range_max_kg: 40, component_dimensions: { shelf_spacing_mm: 300, shelf_thickness_mm: 18, back_panel_thickness_mm: 5, shelf_load_capacity_kg: 15 }, common_materials: ["mdf", "plywood", "steel"], search_keywords: ["bookshelf", "shelf", "shelving", "bookcase", "storage"] },

  // ─── Industrial / Manufacturing ───────────────────────────────────
  { product_category: "3d_printer", product_subcategory: "fdm_desktop", display_name: "Desktop FDM 3D Printer", typical_length_mm: 450, typical_width_mm: 440, typical_height_mm: 470, length_range_min_mm: 380, length_range_max_mm: 550, width_range_min_mm: 380, width_range_max_mm: 520, height_range_min_mm: 400, height_range_max_mm: 600, typical_weight_kg: 9, weight_range_min_kg: 6, weight_range_max_kg: 15, component_dimensions: { build_volume_x_mm: 220, build_volume_y_mm: 220, build_volume_z_mm: 250, nozzle_diameter_mm: 0.4, filament_diameter_mm: 1.75, bed_size_mm: 235, lead_screw_pitch_mm: 2, stepper_nema: 17 }, common_materials: ["aluminum", "steel", "polymer"], search_keywords: ["3d printer", "fdm", "filament printer", "additive manufacturing"] },
  { product_category: "cnc_router", product_subcategory: "desktop", display_name: "Desktop CNC Router", typical_length_mm: 600, typical_width_mm: 500, typical_height_mm: 400, length_range_min_mm: 400, length_range_max_mm: 800, width_range_min_mm: 400, width_range_max_mm: 600, height_range_min_mm: 300, height_range_max_mm: 500, typical_weight_kg: 20, weight_range_min_kg: 10, weight_range_max_kg: 35, component_dimensions: { work_area_x_mm: 300, work_area_y_mm: 300, work_area_z_mm: 50, spindle_rpm_max: 12000, spindle_collet_mm: 6.35 }, common_materials: ["aluminum", "steel"], search_keywords: ["cnc", "cnc router", "cnc mill", "milling machine", "engraver"] },
  { product_category: "laser_cutter", product_subcategory: "desktop", display_name: "Desktop Laser Cutter/Engraver", typical_length_mm: 700, typical_width_mm: 500, typical_height_mm: 200, length_range_min_mm: 500, length_range_max_mm: 900, width_range_min_mm: 400, width_range_max_mm: 600, height_range_min_mm: 150, height_range_max_mm: 300, typical_weight_kg: 12, weight_range_min_kg: 7, weight_range_max_kg: 20, component_dimensions: { work_area_x_mm: 400, work_area_y_mm: 400, laser_power_watt: 40, focal_length_mm: 50 }, common_materials: ["aluminum", "steel", "acrylic"], search_keywords: ["laser", "laser cutter", "laser engraver", "co2 laser", "diode laser"] },

  // ─── Robotics ─────────────────────────────────────────────────────
  { product_category: "robot_arm", product_subcategory: "desktop", display_name: "Desktop Robot Arm (6-DOF)", typical_length_mm: 400, typical_width_mm: 200, typical_height_mm: 500, length_range_min_mm: 300, length_range_max_mm: 550, width_range_min_mm: 150, width_range_max_mm: 250, height_range_min_mm: 400, height_range_max_mm: 600, typical_weight_kg: 5, weight_range_min_kg: 3, weight_range_max_kg: 10, component_dimensions: { reach_mm: 350, payload_g: 500, base_diameter_mm: 130, servo_torque_nm: 2.5, repeatability_mm: 0.5 }, common_materials: ["aluminum", "steel", "polymer"], search_keywords: ["robot arm", "robotic arm", "6-dof", "manipulator", "servo arm"] },

  // ─── Medical Devices ──────────────────────────────────────────────
  { product_category: "pulse_oximeter", display_name: "Finger Pulse Oximeter", typical_length_mm: 60, typical_width_mm: 35, typical_height_mm: 32, length_range_min_mm: 55, length_range_max_mm: 68, width_range_min_mm: 30, width_range_max_mm: 40, height_range_min_mm: 28, height_range_max_mm: 36, typical_weight_kg: 0.03, weight_range_min_kg: 0.02, weight_range_max_kg: 0.05, component_dimensions: { display_width_mm: 25, finger_opening_mm: 25, led_wavelength_nm: 660, battery_type: "AAA" }, common_materials: ["polymer", "silicone"], search_keywords: ["oximeter", "pulse oximeter", "spo2", "blood oxygen", "medical device"] },

  // ─── Power Tools ──────────────────────────────────────────────────
  { product_category: "drill", product_subcategory: "cordless", display_name: "Cordless Drill/Driver", typical_length_mm: 200, typical_width_mm: 75, typical_height_mm: 220, length_range_min_mm: 175, length_range_max_mm: 230, width_range_min_mm: 65, width_range_max_mm: 85, height_range_min_mm: 190, height_range_max_mm: 250, typical_weight_kg: 1.5, weight_range_min_kg: 1.0, weight_range_max_kg: 2.2, component_dimensions: { chuck_diameter_mm: 13, battery_voltage: 18, max_torque_nm: 50, max_rpm: 1800, battery_ah: 2.0 }, common_materials: ["polymer", "aluminum", "steel"], search_keywords: ["drill", "cordless drill", "driver", "power tool", "screwdriver"] },

  // ─── Enclosures ───────────────────────────────────────────────────
  { product_category: "electronics_enclosure", product_subcategory: "project_box", display_name: "Electronics Project Enclosure", typical_length_mm: 120, typical_width_mm: 80, typical_height_mm: 40, length_range_min_mm: 60, length_range_max_mm: 200, width_range_min_mm: 40, width_range_max_mm: 150, height_range_min_mm: 20, height_range_max_mm: 80, typical_weight_kg: 0.1, weight_range_min_kg: 0.03, weight_range_max_kg: 0.5, component_dimensions: { wall_thickness_mm: 2, screw_boss_diameter_mm: 6, pcb_standoff_height_mm: 5, vent_slot_width_mm: 1.5 }, common_materials: ["abs", "aluminum", "steel"], search_keywords: ["enclosure", "project box", "housing", "case", "electronics enclosure", "junction box"] },
  { product_category: "rack_mount", product_subcategory: "1u", display_name: "1U Rack Mount Enclosure", typical_length_mm: 483, typical_width_mm: 450, typical_height_mm: 44, length_range_min_mm: 483, length_range_max_mm: 483, width_range_min_mm: 300, width_range_max_mm: 600, height_range_min_mm: 44, height_range_max_mm: 44, typical_weight_kg: 3, weight_range_min_kg: 2, weight_range_max_kg: 5, component_dimensions: { rack_width_mm: 483, ear_to_ear_mm: 482.6, mounting_hole_spacing_mm: 465.1, panel_height_1u_mm: 44.45 }, common_materials: ["steel", "aluminum"], search_keywords: ["rack mount", "1u", "server", "rack enclosure", "19 inch rack"] },

  // ─── Pumps / Valves ───────────────────────────────────────────────
  { product_category: "centrifugal_pump", product_subcategory: "small", display_name: "Small Centrifugal Pump", typical_length_mm: 200, typical_width_mm: 120, typical_height_mm: 150, length_range_min_mm: 150, length_range_max_mm: 300, width_range_min_mm: 100, width_range_max_mm: 180, height_range_min_mm: 120, height_range_max_mm: 200, typical_weight_kg: 3.5, weight_range_min_kg: 2, weight_range_max_kg: 8, component_dimensions: { inlet_diameter_mm: 25, outlet_diameter_mm: 25, impeller_diameter_mm: 100, motor_watt: 370, max_flow_lpm: 40, max_head_m: 15 }, common_materials: ["cast_iron", "stainless_steel", "polymer"], search_keywords: ["pump", "centrifugal pump", "water pump", "circulation pump"] },

  // ─── Lighting ─────────────────────────────────────────────────────
  { product_category: "desk_lamp", display_name: "LED Desk Lamp", typical_length_mm: 150, typical_width_mm: 150, typical_height_mm: 450, length_range_min_mm: 120, length_range_max_mm: 200, width_range_min_mm: 120, width_range_max_mm: 200, height_range_min_mm: 350, height_range_max_mm: 550, typical_weight_kg: 1.2, weight_range_min_kg: 0.5, weight_range_max_kg: 2.0, component_dimensions: { head_width_mm: 120, arm_length_mm: 350, base_diameter_mm: 140, led_watt: 10, color_temp_k: 4000 }, common_materials: ["aluminum", "steel", "polymer"], search_keywords: ["lamp", "desk lamp", "led lamp", "table lamp", "reading light"] },

  // ─── Outdoor / Garden ─────────────────────────────────────────────
  { product_category: "birdhouse", display_name: "Garden Birdhouse", typical_length_mm: 150, typical_width_mm: 140, typical_height_mm: 230, length_range_min_mm: 120, length_range_max_mm: 200, width_range_min_mm: 110, width_range_max_mm: 180, height_range_min_mm: 180, height_range_max_mm: 300, typical_weight_kg: 0.8, weight_range_min_kg: 0.3, weight_range_max_kg: 2.0, component_dimensions: { entrance_hole_diameter_mm: 32, floor_area_mm: 120, roof_overhang_mm: 30 }, common_materials: ["wood", "plywood"], search_keywords: ["birdhouse", "bird box", "nest box", "garden"] },

  // ─── Boats ────────────────────────────────────────────────────────
  { product_category: "kayak", display_name: "Single Kayak", typical_length_mm: 3500, typical_width_mm: 650, typical_height_mm: 350, length_range_min_mm: 2700, length_range_max_mm: 5000, width_range_min_mm: 550, width_range_max_mm: 750, height_range_min_mm: 300, height_range_max_mm: 400, typical_weight_kg: 22, weight_range_min_kg: 12, weight_range_max_kg: 35, component_dimensions: { cockpit_length_mm: 850, cockpit_width_mm: 450, hull_thickness_mm: 5, load_capacity_kg: 120 }, common_materials: ["polyethylene", "fiberglass", "carbon_fiber"], search_keywords: ["kayak", "canoe", "paddle", "boat", "watercraft"] },

  // ─── Automotive ───────────────────────────────────────────────────
  { product_category: "helmet", product_subcategory: "motorcycle", display_name: "Motorcycle Helmet (Full-Face)", typical_length_mm: 340, typical_width_mm: 260, typical_height_mm: 280, length_range_min_mm: 320, length_range_max_mm: 360, width_range_min_mm: 240, width_range_max_mm: 280, height_range_min_mm: 260, height_range_max_mm: 300, typical_weight_kg: 1.5, weight_range_min_kg: 1.2, weight_range_max_kg: 1.8, component_dimensions: { shell_thickness_mm: 3, eps_liner_thickness_mm: 30, visor_thickness_mm: 2.5, chin_bar_depth_mm: 80 }, common_materials: ["polycarbonate", "fiberglass", "carbon_fiber", "eps_foam"], search_keywords: ["helmet", "motorcycle helmet", "full face", "motorbike helmet"] },
]

async function main() {
  console.log(`Seeding ${PRODUCTS.length} product reference dimensions...`)

  const { data, error } = await supabase
    .from("product_reference_dimensions")
    .upsert(
      PRODUCTS.map(p => ({ ...p, source: "engineering_reference", verified: true })),
      { onConflict: "product_category,product_subcategory", ignoreDuplicates: false },
    )
    .select("product_category")

  if (error) {
    console.error("Error:", error.message)
    process.exit(1)
  }

  console.log(`✓ Inserted ${data?.length ?? 0} product dimensions`)
}

main().catch(console.error)
