/**
 * @file supplier-description-sanitiser.ts — shared sanitiser for LLM
 * reasoning-trace leaks in supplier descriptions.
 *
 * @description A single authoritative list of leak-detection patterns for
 * supplier-facing text generated by the synthesis pipeline. The same patterns
 * are used in two places:
 *
 *   1. `forge-v2-supplier-match.ts` — validate() catches leaks at generation
 *      time, before the synthesis is passed to addToShortlist().
 *   2. `export-project-pdf.tsx` — cleanReviewText() / SCRATCH_PROMPT_INDICATORS
 *      catches anything that slipped through, before the text reaches the
 *      rendered PDF.
 *
 * Both call sites import from here so the pattern lists stay in sync.
 *
 * Background: Loop 26 critique (Nolato, Hedgerow PDF p.92) found that
 * DeepSeek V4-Flash emitted its chain-of-thought verbatim in `content` because
 * it treated the supplier-synthesis task as a reasoning problem and wrote its
 * working before its answer. A 4-model frontier council unanimously flagged
 * this as the most embarrassing customer-facing failure — the founder could
 * read "We are asked to write one sentence about Nolato as a supplier for a
 * specific bill-of-materials part. The user says no description on file..."
 * in the finished engineering report.
 *
 * @see forge-v2-supplier-match.ts synthesizeSupplierForProject
 * @see export-project-pdf.tsx SCRATCH_PROMPT_INDICATORS
 */

/**
 * Fallback text used whenever a leak is detected and no clean synthesis is
 * available. Intentionally neutral — it does not claim to be a real
 * description. The founder will see this and know to verify directly.
 */
export const SUPPLIER_DESCRIPTION_FALLBACK =
    "Supplier description pending verification."

/**
 * Patterns that indicate an LLM has emitted its internal reasoning process
 * (chain-of-thought, scratch-pad, meta-commentary) into the visible output
 * field instead of — or before — the requested answer.
 *
 * Two categories:
 *   A. Prompt-echo markers: the model is paraphrasing the instructions back
 *      rather than answering them ("Output only the sentence", "matched BOM
 *      parts:", "Supplier: "). Present since Loop 3.
 *   B. Reasoning-trace markers: the model is thinking aloud before answering
 *      ("We are asked to write...", "So we need to infer...", "Let me think").
 *      Added in Loop 26 after DeepSeek V4-Flash leaked its working into the
 *      Hedgerow PDF supplier cards.
 *
 * Applied case-insensitively. Match against the full text — any single
 * pattern match disqualifies the entire description.
 */
export const SUPPLIER_DESCRIPTION_LEAK_PATTERNS: ReadonlyArray<RegExp> = [
    // ── Category A: prompt-echo markers ─────────────────────────────────
    /\bwe need to (write|produce|generate)\b/i,
    /\bsentence must\b/i,
    /\bthe (supplier|founder) (description|brief) is\b/i,
    /\boutput only\b/i,
    /\bd50 words\b/i,
    /^supplier:\s/im,
    /^matched bom parts:/im,
    /^(prompt|instructions?|system):/im,

    // ── Category B: reasoning-trace markers (Loop 26) ───────────────────
    /\bwe are asked to (write|produce|generate)\b/i,
    /\bthe user (says|mentions|notes|states)\b/i,
    /\bso we need to infer\b/i,
    /\bno description on file\b/i,
    /\blet me (think|consider|check|look)\b/i,
    /\bi need to (write|produce|generate|find|check)\b/i,
    /\bfirst[,.]?\s+(let'?s|i'?ll|we)\b/i,
    /\bthe question (is|asks)\b/i,
    /\bbased on (this|the above|what)\b/i,
    /\blooking at (this|the|what)\b/i,
    /\bare (not|typically|known for|a)\s+their\s+(typical|usual|main|primary)\b/i,
    /\bbut\s+\w+\s+are\s+not\s+(their|a)\s+(typical|usual|primary|core)\b/i,

    // ── Category B continued: additional reasoning-trace markers ─────────
    // "as an AI" / "as an AI language model" — model breaking persona
    /\bas an ai\b/i,
    // "my instructions" — model referencing its own system prompt
    /\bmy instructions\b/i,
    // "I should", "I will", "I'll" at sentence start — model talking about
    // its own process rather than writing the answer
    /^i (should|will|'ll)\b/im,
    /\.\s+I (should|will|'ll)\b/i,
    // "let's" at sentence start — model inviting the user into its reasoning
    /^let'?s\b/im,
    /\.\s+Let'?s\b/i,
    // "here is" / "here are" at sentence start — model prefacing rather than answering
    /^here (is|are)\b/im,
    /\.\s+Here (is|are)\b/i,
]

/**
 * Tests whether a supplier description text contains an LLM reasoning-trace
 * or prompt-echo leak.
 *
 * @param text - The raw text to check.
 * @returns true if a leak pattern is detected, false otherwise.
 */
export function hasSupplierDescriptionLeak(text: string): boolean {
    return SUPPLIER_DESCRIPTION_LEAK_PATTERNS.some((re) => re.test(text))
}

/**
 * Sanitises a supplier description that may contain LLM reasoning-trace leaks.
 *
 * If a leak is detected the entire text is replaced with SUPPLIER_DESCRIPTION_FALLBACK
 * and a console.warn is emitted so the call site can be traced. The warning
 * includes the supplier identifier and the first 120 characters of the raw
 * text so the model/prompt responsible can be identified in Vercel logs.
 *
 * If no leak is detected the original text is returned unchanged.
 *
 * @param text    - Raw generated supplier description text.
 * @param context - Identifier for logging (e.g. supplier id or name).
 * @returns Sanitised text, or the fallback string if a leak was detected.
 */
export function sanitiseSupplierDescription(
    text: string,
    context: string,
): string {
    if (hasSupplierDescriptionLeak(text)) {
        console.warn(
            `[supplier-description-sanitiser] reasoning-trace leak detected` +
                ` for "${context}" — replacing with fallback.` +
                ` Raw (first 120 chars): "${text.slice(0, 120).replace(/\n/g, " ")}"`,
        )
        return SUPPLIER_DESCRIPTION_FALLBACK
    }
    return text
}
