import {
  BookOpen,
  FileOutput,
  Globe,
  Hammer,
  Package,
  Users,
  UsersRound,
} from 'lucide-react'
import type { SidebarNavItem } from './types'

/**
 * WORKSHOP section — Forge routing.
 *
 * The Forge entry is flag-aware: when `new_forge_experience` is true the
 * link routes to /the-forge-v2 (Phase 1 rebuild); otherwise to legacy
 * /the-forge. DEFAULT IS OFF to preserve the original experience — users
 * opt in per-profile when ready. CAD Lab remains at /the-forge/cad-lab
 * regardless.
 *
 * Rollback 2026-04-20: unconditional cutover to /the-forge-v2 reverted
 * because the V2 experience had unaddressed issues in production. Per-user
 * opt-in via new_forge_experience flag is the safer path.
 */

export function getWorkshopNavigation(newForgeExperience: boolean = false): SidebarNavItem[] {
  const forgeHref = newForgeExperience ? '/the-forge-v2' : '/the-forge'
  return [
    { name: 'The Forge', href: forgeHref, icon: Hammer, tooltip: 'Explore materials, manufacturing approaches, and find suppliers' },
    { name: 'Products', href: '/products', icon: Package, tooltip: 'Your hardware products — from concept to market' },
    { name: 'Team', href: '/team', icon: Users, tooltip: 'Team members, roles, and capacity' },
    { name: 'Specialists', href: '/agents', icon: UsersRound, tooltip: '13 specialists — strategy, engineering, finance, legal, hiring, and more' },
    { name: 'Outputs', href: '/agents/artifacts', icon: FileOutput, tooltip: 'Documents, decks, and analysis generated by your specialists' },
    { name: 'Browse', href: '/browse', icon: Globe, tooltip: 'Browse the web with your specialist — get real-time guidance and analysis' },
    { name: 'Inspiration', href: '/learn', icon: BookOpen, tooltip: 'Techniques, tutorials, and expert guidance to level up your skills' },
  ]
}
