import {
  BookOpen,
  FileOutput,
  Hammer,
  Users,
  UsersRound,
} from 'lucide-react'
import type { SidebarNavItem } from './types'

/**
 * WORKSHOP section — Forge cutover 2026-04-19.
 *
 * The Forge entry now routes unconditionally to /the-forge-v2 (Phase 1
 * Forge rebuild). The `new_forge_experience` flag parameter is retained
 * for signature compatibility but ignored. Legacy /the-forge route stays
 * functional for deep links + is preserved for fallback while the v2
 * surfaces continue to iterate. CAD Lab remains at /the-forge/cad-lab
 * and is deep-linked from every v2 page.
 *
 * Rollback if needed: revert this file and users fall back to legacy
 * /the-forge via the flag-off path.
 */

// Hidden during pivot focus (2026-04-24): Products, Browse.
// eslint-disable-next-line @typescript-eslint/no-unused-vars
export function getWorkshopNavigation(newForgeExperience: boolean = true): SidebarNavItem[] {
  const forgeHref = '/the-forge-v2'
  return [
    { name: 'The Forge', href: forgeHref, icon: Hammer, tooltip: 'Explore materials, manufacturing approaches, and find suppliers' },
    { name: 'Team', href: '/team', icon: Users, tooltip: 'Team members, roles, and capacity' },
    { name: 'Specialists', href: '/agents', icon: UsersRound, tooltip: '13 specialists — strategy, engineering, finance, legal, hiring, and more' },
    { name: 'Deliverables', href: '/agents/artifacts', icon: FileOutput, tooltip: 'Documents, decks, and analysis generated by your specialists' },
    { name: 'Inspiration', href: '/learn', icon: BookOpen, tooltip: 'Techniques, tutorials, and expert guidance to level up your skills' },
  ]
}
