import {
  BookOpen,
  FileOutput,
  Globe,
  Hammer,
  Package,
  Users,
  UsersRound,
} from 'lucide-react'
import type { SidebarNavItem } from './types'

/**
 * WORKSHOP section — includes the flag-aware Forge entry.
 *
 * When `new_forge_experience` flag is ON for the current user, the Forge
 * nav item routes to /the-forge-v2 (the Phase 1 redesign at its dev path
 * before the cutover rename). When OFF (default), it routes to the
 * existing /the-forge. The entry-level target is the only flag-aware
 * link in the sidebar during Phase 1.
 *
 * CAD Lab stays at /the-forge/cad-lab regardless of the flag — it's
 * preserved as the Geometry artefact drill-in. See FORGE-DATA-PRESERVATION.md.
 */

export function getWorkshopNavigation(newForgeExperience: boolean): SidebarNavItem[] {
  const forgeHref = newForgeExperience ? '/the-forge-v2' : '/the-forge'
  return [
    { name: 'The Forge', href: forgeHref, icon: Hammer, tooltip: 'Explore materials, manufacturing approaches, and find suppliers' },
    { name: 'Products', href: '/products', icon: Package, tooltip: 'Your hardware products — from concept to market' },
    { name: 'Team', href: '/team', icon: Users, tooltip: 'Team members, roles, and capacity' },
    { name: 'Specialists', href: '/agents', icon: UsersRound, tooltip: '13 specialists — strategy, engineering, finance, legal, hiring, and more' },
    { name: 'Outputs', href: '/agents/artifacts', icon: FileOutput, tooltip: 'Documents, decks, and analysis generated by your specialists' },
    { name: 'Browse', href: '/browse', icon: Globe, tooltip: 'Browse the web with your specialist — get real-time guidance and analysis' },
    { name: 'Inspiration', href: '/learn', icon: BookOpen, tooltip: 'Techniques, tutorials, and expert guidance to level up your skills' },
  ]
}
