/**
 * @file export-skill-docx.ts
 *
 * @description DOCX export for skill-generated documents. Uses the shared
 * Markdown → DOCX parser to convert content into headings, paragraphs,
 * tables, and lists with orange accent headers matching ForgeOS styling.
 *
 * @related
 * - src/lib/reports/markdown-to-docx.ts — Shared markdown parser
 * - src/lib/reports/export-docx.ts — Existing report DOCX export (pattern reference)
 * - src/lib/document-skills/types.ts — SkillDocumentResult type
 */

import {
  Document,
  Packer,
  Paragraph,
  TextRun,
  BorderStyle,
  AlignmentType,
  LevelFormat,
} from 'docx'

import type { SkillDocumentResult } from '@/lib/document-skills/types'
import { parseMarkdownToDocx, ORANGE, DARK_TEXT, MID_TEXT } from '@/lib/reports/markdown-to-docx'

// ─── Public API ─────────────────────────────────────────────────────

/**
 * Export a skill document as a .docx file and trigger browser download.
 *
 * @param result - The skill document result containing Markdown content
 */
export async function exportSkillDocumentAsDOCX(result: SkillDocumentResult): Promise<void> {
  const children = parseMarkdownToDocx(result.content)

  // Prepend title page
  const titleChildren = [
    new Paragraph({
      spacing: { after: 400 },
      children: [
        new TextRun({
          text: result.title,
          bold: true,
          size: 48,
          color: ORANGE,
          font: 'Calibri',
        }),
      ],
    }),
    new Paragraph({
      spacing: { after: 200 },
      children: [
        new TextRun({
          text: result.foundryName,
          size: 28,
          color: DARK_TEXT,
          font: 'Calibri',
        }),
      ],
    }),
    new Paragraph({
      spacing: { after: 400 },
      children: [
        new TextRun({
          text: `Generated ${new Date(result.generatedAt).toLocaleDateString('en-GB', { day: 'numeric', month: 'long', year: 'numeric' })} · ${result.wordCount.toLocaleString()} words · ${result.tone} tone`,
          size: 20,
          color: MID_TEXT,
          font: 'Calibri',
        }),
      ],
    }),
    new Paragraph({
      spacing: { after: 600 },
      border: {
        bottom: { style: BorderStyle.SINGLE, size: 6, color: ORANGE },
      },
      children: [],
    }),
  ]

  const doc = new Document({
    creator: 'ForgeOS',
    title: result.title,
    description: `${result.title} — generated by ForgeOS Document Writer`,
    numbering: {
      config: [
        {
          reference: 'default-numbering',
          levels: [
            {
              level: 0,
              format: LevelFormat.DECIMAL,
              text: '%1.',
              alignment: AlignmentType.START,
              style: { paragraph: { indent: { left: 720, hanging: 360 } } },
            },
          ],
        },
      ],
    },
    sections: [
      {
        properties: {
          page: {
            margin: { top: 1440, bottom: 1440, left: 1440, right: 1440 },
          },
        },
        children: [...titleChildren, ...children],
      },
    ],
  })

  const blob = await Packer.toBlob(doc)
  const url = URL.createObjectURL(blob)
  const link = window.document.createElement('a')
  link.href = url
  link.download = `${result.foundryName.replace(/\s+/g, '-')}-${result.title.replace(/\s+/g, '-')}.docx`
  link.click()
  URL.revokeObjectURL(url)
}
