/**
 * @file export-skill-docx.ts
 *
 * @description DOCX export for skill-generated documents. Parses the Markdown
 * content into heading/paragraph/table/list sections and maps them to docx
 * library primitives. Uses orange accent headers matching the existing report
 * DOCX styling.
 *
 * @related
 * - src/lib/reports/export-docx.ts — Existing report DOCX export (pattern reference)
 * - src/lib/document-skills/types.ts — SkillDocumentResult type
 */

import {
  Document,
  Packer,
  Paragraph,
  TextRun,
  Table,
  TableRow,
  TableCell,
  HeadingLevel,
  AlignmentType,
  WidthType,
  BorderStyle,
  LevelFormat,
} from 'docx'

import type { SkillDocumentResult } from '@/lib/document-skills/types'

// ─── Constants ──────────────────────────────────────────────────────

const ORANGE = 'FF4500'
const DARK_TEXT = '1E293B'
const MID_TEXT = '64748B'
const LIGHT_BG = 'F8FAFC'

// ─── Public API ─────────────────────────────────────────────────────

/**
 * Export a skill document as a .docx file and trigger browser download.
 *
 * @param result - The skill document result containing Markdown content
 */
export async function exportSkillDocumentAsDOCX(result: SkillDocumentResult): Promise<void> {
  const children = parseMarkdownToDocx(result.content)

  // Prepend title page
  const titleChildren = [
    new Paragraph({
      spacing: { after: 400 },
      children: [
        new TextRun({
          text: result.title,
          bold: true,
          size: 48,
          color: ORANGE,
          font: 'Calibri',
        }),
      ],
    }),
    new Paragraph({
      spacing: { after: 200 },
      children: [
        new TextRun({
          text: result.foundryName,
          size: 28,
          color: DARK_TEXT,
          font: 'Calibri',
        }),
      ],
    }),
    new Paragraph({
      spacing: { after: 400 },
      children: [
        new TextRun({
          text: `Generated ${new Date(result.generatedAt).toLocaleDateString('en-GB', { day: 'numeric', month: 'long', year: 'numeric' })} · ${result.wordCount.toLocaleString()} words · ${result.tone} tone`,
          size: 20,
          color: MID_TEXT,
          font: 'Calibri',
        }),
      ],
    }),
    new Paragraph({
      spacing: { after: 600 },
      border: {
        bottom: { style: BorderStyle.SINGLE, size: 6, color: ORANGE },
      },
      children: [],
    }),
  ]

  const doc = new Document({
    creator: 'ForgeOS',
    title: result.title,
    description: `${result.title} — generated by ForgeOS Document Writer`,
    numbering: {
      config: [
        {
          reference: 'default-numbering',
          levels: [
            {
              level: 0,
              format: LevelFormat.DECIMAL,
              text: '%1.',
              alignment: AlignmentType.START,
              style: { paragraph: { indent: { left: 720, hanging: 360 } } },
            },
          ],
        },
      ],
    },
    sections: [
      {
        properties: {
          page: {
            margin: { top: 1440, bottom: 1440, left: 1440, right: 1440 },
          },
        },
        children: [...titleChildren, ...children],
      },
    ],
  })

  const blob = await Packer.toBlob(doc)
  const url = URL.createObjectURL(blob)
  const link = window.document.createElement('a')
  link.href = url
  link.download = `${result.foundryName.replace(/\s+/g, '-')}-${result.title.replace(/\s+/g, '-')}.docx`
  link.click()
  URL.revokeObjectURL(url)
}

// ─── Markdown → DOCX parser ────────────────────────────────────────

type DocChild = Paragraph | Table

function parseMarkdownToDocx(markdown: string): DocChild[] {
  const lines = markdown.split('\n')
  const children: DocChild[] = []
  let i = 0

  while (i < lines.length) {
    const line = lines[i]

    // Empty line
    if (!line.trim()) {
      i++
      continue
    }

    // Headings
    if (line.startsWith('#### ')) {
      children.push(heading(line.slice(5).trim(), HeadingLevel.HEADING_4))
      i++
      continue
    }
    if (line.startsWith('### ')) {
      children.push(heading(line.slice(4).trim(), HeadingLevel.HEADING_3))
      i++
      continue
    }
    if (line.startsWith('## ')) {
      children.push(heading(line.slice(3).trim(), HeadingLevel.HEADING_2))
      i++
      continue
    }
    if (line.startsWith('# ')) {
      children.push(heading(line.slice(2).trim(), HeadingLevel.HEADING_1))
      i++
      continue
    }

    // Horizontal rule
    if (/^-{3,}$/.test(line.trim()) || /^\*{3,}$/.test(line.trim())) {
      children.push(
        new Paragraph({
          spacing: { before: 200, after: 200 },
          border: {
            bottom: { style: BorderStyle.SINGLE, size: 1, color: 'CCCCCC' },
          },
          children: [],
        })
      )
      i++
      continue
    }

    // Table (pipe-delimited)
    if (line.includes('|') && line.trim().startsWith('|')) {
      const tableLines: string[] = []
      while (i < lines.length && lines[i].includes('|') && lines[i].trim().startsWith('|')) {
        tableLines.push(lines[i])
        i++
      }
      const table = parseTable(tableLines)
      if (table) children.push(table)
      continue
    }

    // Bullet list
    if (/^[-*] /.test(line.trim())) {
      while (i < lines.length && /^[-*] /.test(lines[i].trim())) {
        children.push(bulletParagraph(lines[i].trim().slice(2).trim()))
        i++
      }
      continue
    }

    // Numbered list
    if (/^\d+\.\s/.test(line.trim())) {
      while (i < lines.length && /^\d+\.\s/.test(lines[i].trim())) {
        const text = lines[i].trim().replace(/^\d+\.\s/, '')
        children.push(numberedParagraph(text))
        i++
      }
      continue
    }

    // Blockquote
    if (line.trim().startsWith('>')) {
      const quoteLines: string[] = []
      while (i < lines.length && lines[i].trim().startsWith('>')) {
        quoteLines.push(lines[i].trim().slice(1).trim())
        i++
      }
      children.push(blockquote(quoteLines.join(' ')))
      continue
    }

    // Regular paragraph
    children.push(bodyParagraph(line.trim()))
    i++
  }

  return children
}

// ─── Primitives ─────────────────────────────────────────────────────

function heading(text: string, level: (typeof HeadingLevel)[keyof typeof HeadingLevel]): Paragraph {
  const isH2 = level === HeadingLevel.HEADING_2
  return new Paragraph({
    heading: level,
    spacing: { before: isH2 ? 400 : 240, after: 120 },
    children: [
      new TextRun({
        text: stripMarkdownFormatting(text),
        bold: true,
        size: isH2 ? 32 : level === HeadingLevel.HEADING_3 ? 28 : level === HeadingLevel.HEADING_1 ? 36 : 24,
        color: isH2 ? ORANGE : DARK_TEXT,
        font: 'Calibri',
      }),
    ],
  })
}

function bodyParagraph(text: string): Paragraph {
  return new Paragraph({
    spacing: { after: 120 },
    children: parseInlineFormatting(text),
  })
}

function bulletParagraph(text: string): Paragraph {
  return new Paragraph({
    spacing: { after: 60 },
    bullet: { level: 0 },
    children: parseInlineFormatting(text),
  })
}

function numberedParagraph(text: string): Paragraph {
  return new Paragraph({
    spacing: { after: 60 },
    numbering: { reference: 'default-numbering', level: 0 },
    children: parseInlineFormatting(text),
  })
}

function blockquote(text: string): Paragraph {
  return new Paragraph({
    spacing: { before: 120, after: 120 },
    indent: { left: 720 },
    border: {
      left: { style: BorderStyle.SINGLE, size: 6, color: ORANGE },
    },
    children: [
      new TextRun({
        text: stripMarkdownFormatting(text),
        italics: true,
        size: 22,
        color: MID_TEXT,
        font: 'Calibri',
      }),
    ],
  })
}

function parseTable(tableLines: string[]): Table | null {
  if (tableLines.length < 2) return null

  const parseRow = (line: string): string[] =>
    line.split('|').map(c => c.trim()).filter(Boolean)

  const headerCells = parseRow(tableLines[0])
  // Skip separator row (index 1)
  const dataRows = tableLines.slice(2).map(parseRow)

  if (headerCells.length === 0) return null

  const cellWidth = Math.floor(100 / headerCells.length)

  const headerRow = new TableRow({
    tableHeader: true,
    children: headerCells.map(
      cell =>
        new TableCell({
          width: { size: cellWidth, type: WidthType.PERCENTAGE },
          shading: { fill: LIGHT_BG },
          children: [
            new Paragraph({
              children: [
                new TextRun({
                  text: stripMarkdownFormatting(cell),
                  bold: true,
                  size: 20,
                  color: DARK_TEXT,
                  font: 'Calibri',
                }),
              ],
            }),
          ],
        })
    ),
  })

  const rows = dataRows.map(
    cells =>
      new TableRow({
        children: cells.map(
          cell =>
            new TableCell({
              width: { size: cellWidth, type: WidthType.PERCENTAGE },
              children: [
                new Paragraph({
                  children: [
                    new TextRun({
                      text: stripMarkdownFormatting(cell),
                      size: 20,
                      color: DARK_TEXT,
                      font: 'Calibri',
                    }),
                  ],
                }),
              ],
            })
        ),
      })
  )

  return new Table({
    width: { size: 100, type: WidthType.PERCENTAGE },
    rows: [headerRow, ...rows],
  })
}

// ─── Inline formatting ──────────────────────────────────────────────

function parseInlineFormatting(text: string): TextRun[] {
  const runs: TextRun[] = []
  // Simple regex to handle **bold** and *italic*
  const parts = text.split(/(\*\*[^*]+\*\*|\*[^*]+\*)/)

  for (const part of parts) {
    if (part.startsWith('**') && part.endsWith('**')) {
      runs.push(
        new TextRun({
          text: part.slice(2, -2),
          bold: true,
          size: 22,
          color: DARK_TEXT,
          font: 'Calibri',
        })
      )
    } else if (part.startsWith('*') && part.endsWith('*')) {
      runs.push(
        new TextRun({
          text: part.slice(1, -1),
          italics: true,
          size: 22,
          color: DARK_TEXT,
          font: 'Calibri',
        })
      )
    } else if (part) {
      runs.push(
        new TextRun({
          text: part,
          size: 22,
          color: DARK_TEXT,
          font: 'Calibri',
        })
      )
    }
  }

  return runs.length > 0 ? runs : [new TextRun({ text: '', size: 22, font: 'Calibri' })]
}

function stripMarkdownFormatting(text: string): string {
  return text
    .replace(/\*\*([^*]+)\*\*/g, '$1')
    .replace(/\*([^*]+)\*/g, '$1')
    .replace(/`([^`]+)`/g, '$1')
    .replace(/\[([^\]]+)\]\([^)]+\)/g, '$1')
}
