/**
 * @file export-pptx.ts
 *
 * @description Client-side module that converts a ReportDocument into a
 * downloadable .pptx file using pptxgenjs. Dynamically imported in the
 * browser when a user requests a PowerPoint export.
 *
 * @related
 * - src/lib/reports/report-document-types.ts — Section data shapes
 * - src/lib/reports/export-pdf.ts — PDF export counterpart
 * - src/components/reports/ReportDocument.tsx — On-screen renderer
 */

import PptxGenJS from 'pptxgenjs'

import type {
  ReportDocument,
  SectionData,
  CoverSectionData,
  ExecutiveSummarySectionData,
  KeyMetricsSectionData,
  KPIMetric,
  ObjectivesProgressSectionData,
  TeamActivitySectionData,
  BlockersRisksSectionData,
  CompletionTrendSectionData,
  WeekAheadSectionData,
} from '@/lib/reports/report-document-types'

// ========================
// Brand Constants
// ========================

const ORANGE = 'FF4500'
const BLUE = '3B82F6'
const DARK_TEXT = '1E293B'
const NAVY_ACCENT = '1E293B' // Dark navy for board-pack cover
const MID_TEXT = '64748B'
const LIGHT_BG = 'F8FAFC'
const WHITE = 'FFFFFF'
const GREEN = '16A34A'
const RED = 'DC2626'

// ========================
// Helpers
// ========================

// INTENT: Reusable section title with an orange underline accent, matching
// the ForgeOS brand pattern used throughout the on-screen report renderer.
function addSectionTitle(slide: PptxGenJS.Slide, title: string): void {
  slide.addText(title, {
    x: 0.6,
    y: 0.35,
    w: 10,
    h: 0.5,
    fontSize: 24,
    fontFace: 'Helvetica Neue',
    bold: true,
    color: DARK_TEXT,
  })
  slide.addShape('rect', {
    x: 0.6,
    y: 0.85,
    w: 1.2,
    h: 0.04,
    fill: { color: ORANGE },
  })
}

function formatMetricValue(value: number, format: KPIMetric['format']): string {
  switch (format) {
    case 'percentage':
      return `${Math.round(value)}%`
    case 'number':
      return value.toLocaleString('en-US', { maximumFractionDigits: 0 })
    case 'decimal':
      return value.toLocaleString('en-US', {
        minimumFractionDigits: 1,
        maximumFractionDigits: 1,
      })
    default:
      return String(value)
  }
}

function healthColor(health: string): string {
  switch (health) {
    case 'on-track':
    case 'completed':
      return GREEN
    case 'at-risk':
      return ORANGE
    case 'off-track':
      return RED
    default:
      return MID_TEXT
  }
}

function formatDate(dateStr: string): string {
  const d = new Date(dateStr + 'T00:00:00')
  return d.toLocaleDateString('en-GB', { day: 'numeric', month: 'short' })
}

// INTENT: Board-pack template adds Confidential and slide numbers to every
// slide except the cover. Footer elements go in the bottom-left and bottom-right.
function addBoardPackFooter(
  slide: PptxGenJS.Slide,
  slideNum: number
): void {
  slide.addText('Confidential', {
    x: 0.6,
    y: 7.1,
    w: 3,
    h: 0.25,
    fontSize: 9,
    fontFace: 'Helvetica Neue',
    color: MID_TEXT,
  })
  slide.addText(String(slideNum), {
    x: 11.8,
    y: 7.1,
    w: 1.2,
    h: 0.25,
    fontSize: 9,
    fontFace: 'Helvetica Neue',
    color: MID_TEXT,
    align: 'right',
  })
}

// ========================
// Slide Builders
// ========================

function buildCoverSlide(
  pres: PptxGenJS,
  data: CoverSectionData,
  templateId: string
): PptxGenJS.Slide {
  const slide = pres.addSlide()
  const accentColor = templateId === 'board-pack' ? NAVY_ACCENT : ORANGE

  slide.addShape('rect', {
    x: 0,
    y: 0,
    w: '100%',
    h: 0.04,
    fill: { color: accentColor },
  })

  slide.addText(data.companyName.toUpperCase(), {
    x: 0.6,
    y: 0.6,
    w: 10,
    h: 0.4,
    fontSize: 14,
    fontFace: 'Helvetica Neue',
    color: MID_TEXT,
    charSpacing: 3,
  })

  slide.addText(data.reportTitle, {
    x: 0.6,
    y: 1.3,
    w: 10,
    h: 1.0,
    fontSize: 36,
    fontFace: 'Helvetica Neue',
    bold: true,
    color: DARK_TEXT,
  })

  const subtitle = data.subtitle || `${formatDate(data.dateRange.start)} – ${formatDate(data.dateRange.end)}`
  slide.addText(subtitle, {
    x: 0.6,
    y: 2.4,
    w: 10,
    h: 0.4,
    fontSize: 16,
    fontFace: 'Helvetica Neue',
    color: MID_TEXT,
  })

  if (templateId === 'board-pack') {
    slide.addText('Prepared for Board of Directors', {
      x: 0.6,
      y: 2.95,
      w: 10,
      h: 0.4,
      fontSize: 14,
      fontFace: 'Helvetica Neue',
      color: MID_TEXT,
    })
  }

  slide.addText('Generated by ForgeOS', {
    x: 0.6,
    y: 6.6,
    w: 10,
    h: 0.3,
    fontSize: 10,
    fontFace: 'Helvetica Neue',
    color: MID_TEXT,
  })

  return slide
}

function buildExecutiveSummarySlide(
  pres: PptxGenJS,
  data: ExecutiveSummarySectionData
): PptxGenJS.Slide {
  const slide = pres.addSlide()
  addSectionTitle(slide, 'Executive Summary')

  slide.addText(data.narrative, {
    x: 0.6,
    y: 1.2,
    w: 11.5,
    h: 2.5,
    fontSize: 14,
    fontFace: 'Helvetica Neue',
    color: DARK_TEXT,
    lineSpacingMultiple: 1.5,
    valign: 'top',
  })

  if (data.highlights.length > 0) {
    const bulletText = data.highlights.map((h) => ({
      text: h,
      options: {
        fontSize: 12,
        fontFace: 'Helvetica Neue',
        color: DARK_TEXT,
        bullet: { type: 'bullet' as const },
        paraSpaceBefore: 4,
      },
    }))

    slide.addText(bulletText, {
      x: 0.6,
      y: 3.9,
      w: 11.5,
      h: 3.0,
      valign: 'top',
    })
  }
  return slide
}

function buildKeyMetricsSlide(
  pres: PptxGenJS,
  data: KeyMetricsSectionData
): PptxGenJS.Slide {
  const slide = pres.addSlide()
  addSectionTitle(slide, 'Key Metrics')

  // DECISION: Layout as a 2×2 grid even if fewer than 4 metrics. The grid
  // stays visually stable; empty cells are simply left blank. When more than
  // 4 metrics exist we only show the first 4 since cards need breathing room.
  const metrics = data.metrics.slice(0, 4)
  const cardW = 5.2
  const cardH = 2.4
  const startX = 0.6
  const startY = 1.2
  const gapX = 0.8
  const gapY = 0.5

  metrics.forEach((m, i) => {
    const col = i % 2
    const row = Math.floor(i / 2)
    const x = startX + col * (cardW + gapX)
    const y = startY + row * (cardH + gapY)

    slide.addShape('roundRect', {
      x,
      y,
      w: cardW,
      h: cardH,
      rectRadius: 0.1,
      fill: { color: LIGHT_BG },
    })

    slide.addText(m.label.toUpperCase(), {
      x: x + 0.3,
      y: y + 0.25,
      w: cardW - 0.6,
      h: 0.3,
      fontSize: 10,
      fontFace: 'Helvetica Neue',
      color: MID_TEXT,
      charSpacing: 1.5,
    })

    slide.addText(formatMetricValue(m.value, m.format), {
      x: x + 0.3,
      y: y + 0.6,
      w: cardW - 0.6,
      h: 0.9,
      fontSize: 40,
      fontFace: 'Helvetica Neue',
      bold: true,
      color: DARK_TEXT,
    })

    const trendArrow = m.trend === 'up' ? '▲' : m.trend === 'down' ? '▼' : '●'
    const trendColor = m.trend === 'up' ? GREEN : m.trend === 'down' ? RED : MID_TEXT
    const sign = m.changePercent >= 0 ? '+' : ''

    slide.addText(`${trendArrow} ${sign}${m.changePercent.toFixed(1)}%`, {
      x: x + 0.3,
      y: y + 1.6,
      w: cardW - 0.6,
      h: 0.4,
      fontSize: 14,
      fontFace: 'Helvetica Neue',
      color: trendColor,
    })
  })
  return slide
}

function buildObjectivesProgressSlide(
  pres: PptxGenJS,
  data: ObjectivesProgressSectionData
): PptxGenJS.Slide {
  const slide = pres.addSlide()
  addSectionTitle(slide, 'Objectives Progress')

  const headerRow: PptxGenJS.TableRow = [
    { text: 'Objective', options: { bold: true, fontSize: 10, color: MID_TEXT, fill: { color: LIGHT_BG } } },
    { text: 'Progress', options: { bold: true, fontSize: 10, color: MID_TEXT, fill: { color: LIGHT_BG }, align: 'center' } },
    { text: 'Health', options: { bold: true, fontSize: 10, color: MID_TEXT, fill: { color: LIGHT_BG }, align: 'center' } },
    { text: 'Tasks', options: { bold: true, fontSize: 10, color: MID_TEXT, fill: { color: LIGHT_BG }, align: 'center' } },
  ]

  const dataRows: PptxGenJS.TableRow[] = data.objectives.slice(0, 10).map((obj) => [
    { text: obj.title, options: { fontSize: 10, color: DARK_TEXT } },
    { text: `${Math.round(obj.progress)}%`, options: { fontSize: 10, color: DARK_TEXT, align: 'center' as const } },
    { text: obj.health.replace('-', ' '), options: { fontSize: 10, color: healthColor(obj.health), bold: true, align: 'center' as const } },
    { text: `${obj.tasksCompleted}/${obj.tasksCompleted + obj.tasksRemaining}`, options: { fontSize: 10, color: DARK_TEXT, align: 'center' as const } },
  ])

  slide.addTable([headerRow, ...dataRows], {
    x: 0.6,
    y: 1.2,
    w: 11.5,
    colW: [5.5, 2, 2, 2],
    border: { type: 'solid', pt: 0.5, color: 'E2E8F0' },
    rowH: 0.4,
    fontFace: 'Helvetica Neue',
  })
  return slide
}

function buildTeamActivitySlide(
  pres: PptxGenJS,
  data: TeamActivitySectionData
): PptxGenJS.Slide {
  const slide = pres.addSlide()
  addSectionTitle(slide, 'Team Activity')

  const sorted = [...data.members].sort((a, b) => b.tasksCompleted - a.tasksCompleted).slice(0, 10)

  const headerRow: PptxGenJS.TableRow = [
    { text: 'Name', options: { bold: true, fontSize: 10, color: MID_TEXT, fill: { color: LIGHT_BG } } },
    { text: 'Role', options: { bold: true, fontSize: 10, color: MID_TEXT, fill: { color: LIGHT_BG } } },
    { text: 'Tasks Completed', options: { bold: true, fontSize: 10, color: MID_TEXT, fill: { color: LIGHT_BG }, align: 'center' } },
  ]

  const dataRows: PptxGenJS.TableRow[] = sorted.map((m) => [
    { text: m.name, options: { fontSize: 10, color: DARK_TEXT } },
    { text: m.role ?? '—', options: { fontSize: 10, color: MID_TEXT } },
    { text: String(m.tasksCompleted), options: { fontSize: 10, color: DARK_TEXT, align: 'center' as const } },
  ])

  slide.addTable([headerRow, ...dataRows], {
    x: 0.6,
    y: 1.2,
    w: 11.5,
    colW: [5, 4, 2.5],
    border: { type: 'solid', pt: 0.5, color: 'E2E8F0' },
    rowH: 0.4,
    fontFace: 'Helvetica Neue',
  })
  return slide
}

function buildBlockersRisksSlide(
  pres: PptxGenJS,
  data: BlockersRisksSectionData
): PptxGenJS.Slide {
  const slide = pres.addSlide()
  addSectionTitle(slide, 'Blockers & Risks')

  let yPos = 1.2

  if (data.blockers.length > 0) {
    slide.addText('Blockers', {
      x: 0.6,
      y: yPos,
      w: 10,
      h: 0.35,
      fontSize: 14,
      fontFace: 'Helvetica Neue',
      bold: true,
      color: DARK_TEXT,
    })
    yPos += 0.4

    const blockerBullets = data.blockers.map((b) => ({
      text: `${b.reporterName}: ${b.description}`,
      options: {
        fontSize: 11,
        fontFace: 'Helvetica Neue',
        color: DARK_TEXT,
        bullet: { type: 'bullet' as const },
        paraSpaceBefore: 4,
      },
    }))

    slide.addText(blockerBullets, {
      x: 0.6,
      y: yPos,
      w: 11.5,
      h: 2.5,
      valign: 'top' as const,
    })
    yPos += 2.7
  }

  if (data.atRiskObjectives.length > 0) {
    slide.addText('At-Risk Objectives', {
      x: 0.6,
      y: yPos,
      w: 10,
      h: 0.35,
      fontSize: 14,
      fontFace: 'Helvetica Neue',
      bold: true,
      color: DARK_TEXT,
    })
    yPos += 0.4

    const riskBullets = data.atRiskObjectives.map((o) => ({
      text: `${o.title} — ${Math.round(o.progress)}% complete, ${o.daysRemaining} days remaining`,
      options: {
        fontSize: 11,
        fontFace: 'Helvetica Neue',
        color: ORANGE,
        bullet: { type: 'bullet' as const },
        paraSpaceBefore: 4,
      },
    }))

    slide.addText(riskBullets, {
      x: 0.6,
      y: yPos,
      w: 11.5,
      h: 2.5,
      valign: 'top' as const,
    })
  }
  return slide
}

function buildCompletionTrendSlide(
  pres: PptxGenJS,
  data: CompletionTrendSectionData
): PptxGenJS.Slide {
  const slide = pres.addSlide()
  addSectionTitle(slide, 'Completion Trend')

  // DECISION: Using pptxgenjs's built-in chart support for a real line chart
  // rather than faking it with shapes. The library handles axis scaling and
  // legends natively, which produces a cleaner result than manual drawing.
  const labels = data.dataPoints.map((dp) => formatDate(dp.date))

  const chartData = [
    {
      name: 'Completed',
      labels,
      values: data.dataPoints.map((dp) => dp.completed),
    },
    {
      name: 'Created',
      labels,
      values: data.dataPoints.map((dp) => dp.created),
    },
  ]

  slide.addChart(pres.ChartType.line, chartData, {
    x: 0.6,
    y: 1.2,
    w: 11.5,
    h: 5.5,
    showLegend: true,
    legendPos: 'b',
    legendFontSize: 10,
    chartColors: [ORANGE, BLUE],
    lineDataSymbol: 'circle',
    lineDataSymbolSize: 6,
    catAxisLabelFontSize: 9,
    catAxisLabelColor: MID_TEXT,
    valAxisLabelFontSize: 9,
    valAxisLabelColor: MID_TEXT,
    showValAxisTitle: false,
    showCatAxisTitle: false,
  })
  return slide
}

function buildWeekAheadSlide(
  pres: PptxGenJS,
  data: WeekAheadSectionData
): PptxGenJS.Slide {
  const slide = pres.addSlide()
  addSectionTitle(slide, 'Week Ahead')

  const headerRow: PptxGenJS.TableRow = [
    { text: 'Task', options: { bold: true, fontSize: 10, color: MID_TEXT, fill: { color: LIGHT_BG } } },
    { text: 'Assignee', options: { bold: true, fontSize: 10, color: MID_TEXT, fill: { color: LIGHT_BG } } },
    { text: 'Due Date', options: { bold: true, fontSize: 10, color: MID_TEXT, fill: { color: LIGHT_BG }, align: 'center' } },
    { text: 'Objective', options: { bold: true, fontSize: 10, color: MID_TEXT, fill: { color: LIGHT_BG } } },
  ]

  const dataRows: PptxGenJS.TableRow[] = data.tasks.slice(0, 15).map((t) => [
    { text: t.title, options: { fontSize: 10, color: DARK_TEXT } },
    { text: t.assigneeName ?? '—', options: { fontSize: 10, color: MID_TEXT } },
    { text: formatDate(t.dueDate), options: { fontSize: 10, color: DARK_TEXT, align: 'center' as const } },
    { text: t.objectiveTitle ?? '—', options: { fontSize: 10, color: MID_TEXT } },
  ])

  slide.addTable([headerRow, ...dataRows], {
    x: 0.6,
    y: 1.2,
    w: 11.5,
    colW: [4.5, 2.5, 1.5, 3],
    border: { type: 'solid', pt: 0.5, color: 'E2E8F0' },
    rowH: 0.35,
    fontFace: 'Helvetica Neue',
  })
  return slide
}

// ========================
// Section Dispatcher
// ========================

// INTENT: Single routing point so adding a new section type only requires
// one case here and one builder function — keeps the main export lean.
// Returns the created slide (or undefined for unknown types) so callers can
// add template-specific footer elements.
function buildSlideForSection(
  pres: PptxGenJS,
  section: SectionData,
  templateId: string
): PptxGenJS.Slide | undefined {
  switch (section.type) {
    case 'cover':
      return buildCoverSlide(pres, section.data as CoverSectionData, templateId)
    case 'executive-summary':
      return buildExecutiveSummarySlide(pres, section.data as ExecutiveSummarySectionData)
    case 'key-metrics':
      return buildKeyMetricsSlide(pres, section.data as KeyMetricsSectionData)
    case 'objectives-progress':
      return buildObjectivesProgressSlide(pres, section.data as ObjectivesProgressSectionData)
    case 'team-activity':
      return buildTeamActivitySlide(pres, section.data as TeamActivitySectionData)
    case 'blockers-risks':
      return buildBlockersRisksSlide(pres, section.data as BlockersRisksSectionData)
    case 'completion-trend':
      return buildCompletionTrendSlide(pres, section.data as CompletionTrendSectionData)
    case 'week-ahead':
      return buildWeekAheadSlide(pres, section.data as WeekAheadSectionData)
    default:
      // GOTCHA: Unknown section types are silently skipped so a newer
      // template with extra sections doesn't crash older export code.
      console.warn('[ExportPPTX] Unknown section type, skipping:', (section as SectionData).type)
      return undefined
  }
}

// ========================
// Public API
// ========================

/**
 * @description Converts a ReportDocument into a branded .pptx presentation
 * and triggers a browser download. Each document section becomes one slide
 * with consistent typography and the ForgeOS orange accent.
 *
 * @param document The fully-populated report document to export
 */
export async function exportReportAsPPTX(document: ReportDocument): Promise<void> {
  const pres = new PptxGenJS()
  const templateId = document.templateId ?? 'custom'

  pres.layout = 'LAYOUT_16x9'
  pres.author = 'ForgeOS'
  pres.subject = document.title
  pres.title = document.title

  document.sections.forEach((section, index) => {
    const slide = buildSlideForSection(pres, section, templateId)
    if (slide && templateId === 'board-pack' && section.type !== 'cover') {
      addBoardPackFooter(slide, index + 1)
    }
  })

  const safeName = document.foundryName.replace(/[^a-zA-Z0-9]/g, '-')
  const safeTitle = document.title.replace(/[^a-zA-Z0-9]/g, '-')
  const dateStr = document.dateRange.start

  await pres.writeFile({ fileName: `${safeName}-${safeTitle}-${dateStr}.pptx` })
}
