/**
 * Migration: Intelligence Reports and Sweep Log
 *
 * Purpose: Store intelligence reports generated by specialist sweeps
 * and track when each source was last analyzed.
 *
 * Security:
 * - RLS ensures users can only see reports for their foundry
 * - Service role can insert (used by sweep orchestrator)
 *
 * Rollback: DROP TABLE intelligence_reports, intelligence_sweep_log CASCADE
 */

-- Intelligence reports table
CREATE TABLE IF NOT EXISTS intelligence_reports (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    foundry_id TEXT NOT NULL REFERENCES foundries(id) ON DELETE CASCADE,
    source_id TEXT NOT NULL,
    specialist_id TEXT NOT NULL,
    title TEXT NOT NULL,
    summary TEXT NOT NULL,
    implications JSONB DEFAULT '[]'::jsonb,
    recommended_actions JSONB DEFAULT '[]'::jsonb,
    urgency TEXT NOT NULL DEFAULT 'monitor' CHECK (urgency IN ('immediate', 'this_week', 'monitor')),
    is_read BOOLEAN DEFAULT false,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- Indexes for querying
CREATE INDEX IF NOT EXISTS idx_intelligence_reports_foundry
    ON intelligence_reports(foundry_id, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_intelligence_reports_specialist
    ON intelligence_reports(foundry_id, specialist_id, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_intelligence_reports_urgency
    ON intelligence_reports(foundry_id, urgency, is_read, created_at DESC);

-- RLS
ALTER TABLE intelligence_reports ENABLE ROW LEVEL SECURITY;

-- Users can read reports for their foundry
CREATE POLICY "Users can view own foundry reports"
    ON intelligence_reports FOR SELECT
    USING (
        EXISTS (
            SELECT 1 FROM foundry_memberships fm
            WHERE fm.foundry_id = intelligence_reports.foundry_id
            AND fm.user_id = auth.uid()
        )
    );

-- Users can mark reports as read
CREATE POLICY "Users can update own foundry reports"
    ON intelligence_reports FOR UPDATE
    USING (
        EXISTS (
            SELECT 1 FROM foundry_memberships fm
            WHERE fm.foundry_id = intelligence_reports.foundry_id
            AND fm.user_id = auth.uid()
        )
    )
    WITH CHECK (
        EXISTS (
            SELECT 1 FROM foundry_memberships fm
            WHERE fm.foundry_id = intelligence_reports.foundry_id
            AND fm.user_id = auth.uid()
        )
    );

-- Service role can insert (sweep orchestrator)
CREATE POLICY "Service role can insert reports"
    ON intelligence_reports FOR INSERT
    WITH CHECK (true);


-- Sweep log table (tracks when each source was last run)
CREATE TABLE IF NOT EXISTS intelligence_sweep_log (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    source_id TEXT NOT NULL,
    foundry_id TEXT NOT NULL REFERENCES foundries(id) ON DELETE CASCADE,
    last_run_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    UNIQUE(source_id, foundry_id)
);

-- RLS
ALTER TABLE intelligence_sweep_log ENABLE ROW LEVEL SECURITY;

-- Service role only
CREATE POLICY "Service role can manage sweep log"
    ON intelligence_sweep_log FOR ALL
    WITH CHECK (true);

-- Cleanup function for old reports (keep 90 days)
CREATE OR REPLACE FUNCTION cleanup_old_intelligence_reports()
RETURNS void AS $$
BEGIN
    DELETE FROM intelligence_reports
    WHERE created_at < NOW() - INTERVAL '90 days';
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;
