-- =============================================
-- MIGRATION: Add awesome-ceo Inspired Objective Packs
-- =============================================
-- This migration adds 7 new objective packs inspired by resources from
-- the awesome-ceo curated list (github.com/kuchin/awesome-ceo):
-- - Operations: Crisis Management & Runway Extension (Sequoia "Adapting to Endure")
-- - Product: Mom Test Customer Discovery (Rob Fitzpatrick)
-- - HR: Executive Hiring Process (Keith Rabois methodology)
-- - Startup: Pitch Deck Builder (30 Legendary Pitch Decks)
-- - Growth: Network Effects & Cold Start Strategy (Andrew Chen / a16z)
-- - Growth: Series A Readiness Checklist (YC Diligence Checklist)
-- - Finance: Equity & Option Grant Planning (Index Ventures / Dan Luu)

-- 1. Insert the 7 new objective packs
INSERT INTO public.objective_packs (title, description, category, difficulty, estimated_duration, icon_name)
VALUES
('Crisis Management & Runway Extension', 'When the market turns or a key customer churns, you need a battle-tested crisis playbook—not panic. Based on Sequoia Capital''s "Adapting to Endure" framework, this pack guides you through calculating true runway in weeks (not months), modeling base/bear/worst-case scenarios, identifying the 3 cost cuts that matter most, making difficult headcount decisions within 7 days, and communicating transparently with your team and investors. Companies that act decisively in the first two weeks of a crisis survive at 3x the rate of those that delay. This is your emergency operating manual for extending runway by 6+ months while preserving team trust and customer relationships.', 'Operations', 'Hard', '1-2 Weeks', 'shield'),
('Mom Test Customer Discovery', 'Stop getting lied to by potential customers. Based on Rob Fitzpatrick''s "The Mom Test"—the gold standard methodology for customer discovery—this pack teaches you to ask questions that even your mom can''t give you a false positive on. The core rule: never ask anyone if your idea is good. Instead, ask about their existing behavior, real problems, and actual spending. This structured discovery process guides you through designing anti-bias interview questions, conducting 15+ interviews without ever pitching your product, extracting actionable pain patterns, and validating willingness to pay through commitment (not opinion). The #1 reason startups fail is building something nobody wants. This pack prevents that.', 'Product', 'Medium', '3-4 Weeks', 'users'),
('Executive Hiring Process', 'A bad executive hire costs $1-3M when you factor in salary, opportunity cost, and cultural damage. Based on Keith Rabois''s battle-tested methodology from PayPal, Square, and Khosla Ventures, this pack implements a rigorous executive hiring process: define the role by writing the press release for their first achievement, create a scorecard separating must-have from nice-to-have traits, conduct 5+ back-channel references before the first interview, design a 2-hour work trial that simulates the actual job, and build an offer using Index Ventures'' equity framework. Transforms executive hiring from gut-feel to data-driven decision-making.', 'HR', 'Hard', '4-6 Weeks', 'users'),
('Pitch Deck Builder', 'Build an investor-ready pitch deck slide by slide, informed by patterns from 30+ legendary startup decks (Airbnb, Buffer, LinkedIn, Intercom). Each task maps to one essential slide with best-practice guidance on what to include, what to cut, and what makes investors lean forward. Covers the 10 critical slides: Problem, Solution, Why Now, Market Size, Product, Traction, Business Model, Team, Financials, and The Ask. Based on David Rose''s TED talk on pitching to VCs and analysis of 200+ successful seed and Series A decks. The output is not just a deck—it''s a fundraising narrative that tells a compelling story from problem to opportunity.', 'Startup', 'Medium', '1-2 Weeks', 'file'),
('Network Effects & Cold Start Strategy', 'If your product gets more valuable as more people use it, you have a potential network effect—the most powerful competitive moat in technology. But every network effect product faces the cold start problem: it''s useless until it has users, and nobody wants to join an empty network. Based on Andrew Chen''s "The Cold Start Problem" (a16z), this pack guides you through identifying your network effect type (direct, indirect, data, or platform), defining your atomic network (the smallest viable group), designing the hard-side value proposition, building supply before demand, creating single-player mode utility, measuring network density metrics, and planning viral acquisition loops. Essential for marketplace, platform, and social product founders.', 'Growth', 'Hard', '4-6 Weeks', 'rocket'),
('Series A Readiness Checklist', 'You''ve found product-market fit and proven initial traction—now it''s time to raise a Series A. But Series A is a fundamentally different game than seed: VCs expect repeatable growth, retention data, and a clear path to market leadership. Based on YC''s Series A Diligence Checklist and analysis of 500+ Series A raises from DocSend, this pack prepares you across every dimension investors will evaluate: hit key traction milestones ($1M+ ARR or equivalent), document cohort retention curves that prove PMF, prepare a complete 20+ document data room, establish 3+ months of consistent month-over-month growth, build board composition for governance, and secure warm introductions to 5+ target Series A leads through strategic networking.', 'Growth', 'Hard', '8-12 Weeks', 'target'),
('Equity & Option Grant Planning', 'Your equity is your most powerful hiring and retention tool—but most founders get it wrong, either giving away too much too early or too little to attract top talent. Based on Index Ventures'' "Rewarding Talent" framework and Dan Luu''s "Options vs Cash" analysis, this pack guides you through setting up a properly sized option pool (10-20% of fully diluted shares), creating equity bands by role and seniority, establishing industry-standard vesting schedules (4-year with 1-year cliff), defining exercise windows and early exercise provisions, and creating equity education materials that help employees actually understand what they''re getting. The difference between a great equity strategy and a poor one can mean the difference between retaining your best people and losing them to competitors.', 'Finance', 'Medium', '2-3 Weeks', 'chart');

-- 2. Get IDs for seeding pack items
DO $$
DECLARE
    crisis_id UUID;
    momtest_id UUID;
    exec_hire_id UUID;
    pitchdeck_id UUID;
    network_id UUID;
    series_a_id UUID;
    equity_id UUID;
BEGIN
    SELECT id INTO crisis_id FROM public.objective_packs WHERE title = 'Crisis Management & Runway Extension' LIMIT 1;
    SELECT id INTO momtest_id FROM public.objective_packs WHERE title = 'Mom Test Customer Discovery' LIMIT 1;
    SELECT id INTO exec_hire_id FROM public.objective_packs WHERE title = 'Executive Hiring Process' LIMIT 1;
    SELECT id INTO pitchdeck_id FROM public.objective_packs WHERE title = 'Pitch Deck Builder' LIMIT 1;
    SELECT id INTO network_id FROM public.objective_packs WHERE title = 'Network Effects & Cold Start Strategy' LIMIT 1;
    SELECT id INTO series_a_id FROM public.objective_packs WHERE title = 'Series A Readiness Checklist' LIMIT 1;
    SELECT id INTO equity_id FROM public.objective_packs WHERE title = 'Equity & Option Grant Planning' LIMIT 1;

    -- Crisis Management & Runway Extension Items
    INSERT INTO public.pack_items (pack_id, title, description, role, order_index) VALUES
    (crisis_id, 'Calculate True Runway in Weeks', 'Analyze current burn rate, cash position, and committed revenue to calculate runway in weeks (not months). Include accounts receivable timing, upcoming large expenses, and revenue churn risk. Present honest numbers—not optimistic projections.', 'AI_Agent', 1),
    (crisis_id, 'Model Three Scenarios', 'Build base case (current trajectory), bear case (lose 20% revenue + key hire leaves), and worst case (50% revenue drop) financial models. For each scenario, calculate runway and identify the decision trigger points.', 'AI_Agent', 2),
    (crisis_id, 'Identify Top 3 Cost Reduction Levers', 'Rank all expenses by impact and reversibility. Identify the 3 cuts that extend runway the most with the least damage to core business. Consider: vendor renegotiation, hiring freeze, compensation adjustments, office costs, and non-essential tools.', 'Executive', 3),
    (crisis_id, 'Make Headcount Decisions Within 7 Days', 'If layoffs are necessary, decide within one week—delay destroys morale and burns cash. Define affected roles, severance terms, and communication plan. Treat departing team members with maximum dignity and support.', 'Executive', 4),
    (crisis_id, 'Communicate Crisis Plan to Team', 'Hold an all-hands within 24 hours of decisions. Be transparent about the situation, what you''re doing about it, and what the path forward looks like. Share the plan, not just the bad news. Teams respect honesty over false optimism.', 'Executive', 5),
    (crisis_id, 'Renegotiate Vendor Contracts', 'Contact top 5 vendors by spend. Request payment deferrals, reduced rates, or contract restructuring. Most vendors prefer renegotiation over losing a customer entirely. Document all changes and track savings.', 'Apprentice', 6),
    (crisis_id, 'Update Board and Investors', 'Send board update within 48 hours with honest assessment, action plan, revised projections, and specific asks (bridge financing, introductions, advisory time). Investors respect founders who face problems head-on.', 'Executive', 7);

    -- Mom Test Customer Discovery Items
    INSERT INTO public.pack_items (pack_id, title, description, role, order_index) VALUES
    (momtest_id, 'Design Anti-Bias Interview Questions', 'Write 10 questions that follow Mom Test rules: ask about past behavior (not hypothetical future), focus on problems (not your solution), and probe for specifics (not generalities). Example: "Walk me through the last time you dealt with [problem]" instead of "Would you use a product that does X?"', 'AI_Agent', 1),
    (momtest_id, 'Identify and Recruit 20 Target Interviewees', 'Build a list of 20 potential customers who match your hypothesis. Prioritize people currently experiencing the problem over people in your network. Reach out with a genuine learning request—not a sales pitch.', 'Apprentice', 2),
    (momtest_id, 'Conduct 15 Customer Interviews', 'Run 15 conversations (30-45 minutes each) following Mom Test methodology. Never mention your product. Ask about their workflow, pain points, current solutions, and what they''ve tried before. Listen more than you talk. Record and transcribe every interview.', 'Executive', 3),
    (momtest_id, 'Extract Pain Patterns', 'Analyze all 15 interview transcripts and identify the top 3 recurring pain patterns. For each pattern, document: how many interviewees mentioned it, how severe it is (mild annoyance vs hair-on-fire), what they currently do about it, and how much they spend on existing solutions.', 'AI_Agent', 4),
    (momtest_id, 'Validate Willingness to Pay', 'For each top pain pattern, assess evidence of willingness to pay. Look for: current spending on solutions, time invested in workarounds, emotional intensity when describing the problem, and any commitments made during interviews (sharing data, making introductions, pre-ordering).', 'Executive', 5),
    (momtest_id, 'Document Findings in Lean Canvas', 'Synthesize all findings into an updated Lean Canvas. Update Problem, Customer Segments, and Unique Value Proposition based on actual interview data—not assumptions. Flag which hypotheses were validated and which were invalidated.', 'AI_Agent', 6);

    -- Executive Hiring Process Items
    INSERT INTO public.pack_items (pack_id, title, description, role, order_index) VALUES
    (exec_hire_id, 'Write the Press Release for Their First Achievement', 'Before writing a job description, write the press release you''d publish 12 months after they start. What did they accomplish? What changed because of them? This forces clarity on what success looks like and becomes the foundation of the entire hiring process.', 'Executive', 1),
    (exec_hire_id, 'Create a Hiring Scorecard', 'Define 5-7 evaluation criteria split into must-have traits (dealbreakers) and nice-to-have traits (differentiators). For each criterion, describe what "great" looks like with specific behavioral examples. This scorecard is used by every interviewer for consistent evaluation.', 'AI_Agent', 2),
    (exec_hire_id, 'Conduct 5+ Back-Channel References', 'Before the first formal interview, conduct back-channel reference checks through your network. Find people who worked with the candidate but weren''t listed as references. Ask: "On a scale of 1-10, how likely are you to hire this person again?" Anything below 8 is a red flag.', 'Executive', 3),
    (exec_hire_id, 'Design a 2-Hour Work Trial', 'Create a real-world simulation of the actual job. For a VP Sales: have them review your pipeline and present a 90-day plan. For a CTO: have them review your architecture and identify top 3 risks. Evaluate how they think, not just what they know.', 'AI_Agent', 4),
    (exec_hire_id, 'Run Structured Interview Process', 'Conduct 4-5 interviews with different panel members, each focused on specific scorecard criteria. Use behavioral questions ("Tell me about a time when...") not hypotheticals. Debrief as a panel using the scorecard—not gut feel.', 'Apprentice', 5),
    (exec_hire_id, 'Build Offer with Equity Framework', 'Construct a competitive offer using Index Ventures'' Rewarding Talent benchmarks for equity allocation by role and stage. Include base salary, equity (with clear explanation of value), signing bonus if needed, and performance milestones for the first year.', 'Executive', 6);

    -- Pitch Deck Builder Items
    INSERT INTO public.pack_items (pack_id, title, description, role, order_index) VALUES
    (pitchdeck_id, 'Draft the Problem Slide', 'Articulate the problem in 1-2 sentences that make the audience feel the pain. Use a specific customer story or data point—not abstract market trends. Best decks make investors nod because they''ve seen this problem themselves.', 'Executive', 1),
    (pitchdeck_id, 'Draft the Solution & Product Slides', 'Show how your product solves the problem with a clear demo screenshot or visual. Keep it concrete—show the product, not a diagram of your architecture. Best decks: Airbnb showed their listing page, not a marketplace diagram.', 'Executive', 2),
    (pitchdeck_id, 'Draft the Why Now Slide', 'Explain the market timing: what changed recently (technology, regulation, behavior) that makes this possible or necessary NOW. If this could have been built 5 years ago, explain why it wasn''t.', 'AI_Agent', 3),
    (pitchdeck_id, 'Draft the Market Size Slide', 'Calculate TAM/SAM/SOM using bottom-up methodology (not top-down "if we get 1% of a $100B market"). Show your math. Investors care about SOM—the market you can actually capture in 3-5 years.', 'AI_Agent', 4),
    (pitchdeck_id, 'Draft the Traction Slide', 'Show your strongest proof of progress: revenue growth, user growth, key partnerships, pilot results, or waitlist numbers. Use a graph that goes up and to the right. If pre-revenue, show engagement metrics or LOIs.', 'Executive', 5),
    (pitchdeck_id, 'Draft the Business Model Slide', 'Explain how you make money in one simple diagram. Show unit economics if available (CAC, LTV, margins). Investors want to see a repeatable, scalable revenue model—not just "we''ll figure out monetization later."', 'AI_Agent', 6),
    (pitchdeck_id, 'Draft the Team Slide', 'Highlight 2-4 key team members with relevant achievements (not just titles). Show why THIS team is uniquely positioned to solve THIS problem. Include notable advisors or investors if relevant.', 'Executive', 7),
    (pitchdeck_id, 'Draft the Financials & Ask Slide', 'Show 3-year projections with key assumptions stated clearly. State exactly how much you''re raising, what milestones the money will fund, and what you''ll be worth at next raise. Be specific: "$2M to reach $1M ARR in 18 months."', 'AI_Agent', 8),
    (pitchdeck_id, 'Review Full Deck for Narrative Flow', 'Read the entire deck as a story: Problem -> Solution -> Why Now -> Market -> Product -> Traction -> Model -> Team -> Ask. Each slide should make the next one feel inevitable. Cut anything that breaks the narrative flow.', 'Executive', 9),
    (pitchdeck_id, 'Practice Pitch with 3-5 Friendly Investors', 'Present to advisor-level contacts for feedback before approaching target investors. Time yourself (aim for 3-4 minutes of narration). Collect objections and refine weak slides. Your first 5 pitches are practice—never waste your best investors on a first draft.', 'Executive', 10);

    -- Network Effects & Cold Start Strategy Items
    INSERT INTO public.pack_items (pack_id, title, description, role, order_index) VALUES
    (network_id, 'Identify Your Network Effect Type', 'Classify your product''s network effect: Direct (more users = more value, e.g., messaging), Indirect (more of one side = more of another, e.g., marketplace), Data (more usage = better product, e.g., recommendation engine), or Platform (developers build on top, e.g., app store). This determines your entire launch strategy.', 'AI_Agent', 1),
    (network_id, 'Define Your Atomic Network', 'Identify the smallest possible group of users that creates a self-sustaining network. For Uber it was one neighborhood. For Slack it was one team. For Airbnb it was one city. Your launch strategy is about creating density in this atomic unit—not spreading thin across many.', 'Executive', 2),
    (network_id, 'Design the Hard-Side Value Proposition', 'In every network, one side is harder to attract (supply-side for marketplaces, creators for platforms). Design a compelling value proposition for THIS side that works even without the network effect. What''s their reason to join when you have zero users on the other side?', 'Executive', 3),
    (network_id, 'Build Single-Player Mode Utility', 'Create value that works without the network. Yelp started as a useful review directory. Instagram started as a great photo editor. LinkedIn started as an online resume. What utility does your product provide to the very first user with no network?', 'AI_Agent', 4),
    (network_id, 'Plan Supply-Before-Demand Launch', 'Design your launch sequence: seed the supply side first, then bring demand. Uber recruited drivers before riders. Airbnb seeded listings before marketing to travelers. Map out exactly who you''ll recruit first, how, and what incentives you''ll use.', 'Executive', 5),
    (network_id, 'Define Network Density Metrics', 'Establish metrics that measure network health: connections per user, fill rate (marketplace), response time, match rate, and content creation ratio. Set thresholds for when the atomic network is "lit" vs still cold.', 'AI_Agent', 6),
    (network_id, 'Design Viral Acquisition Loops', 'Map the viral loops in your product: invite mechanics, sharing incentives, referral programs, and organic word-of-mouth triggers. Calculate your viral coefficient (K-factor) and design experiments to improve it. Even a K-factor of 0.5 cuts your CAC in half.', 'AI_Agent', 7);

    -- Series A Readiness Checklist Items
    INSERT INTO public.pack_items (pack_id, title, description, role, order_index) VALUES
    (series_a_id, 'Hit Key Traction Milestone', 'Reach the traction bar for your market: $1M+ ARR for B2B SaaS, 100K+ active users for consumer, or equivalent proof of demand. Series A investors want evidence of repeatable growth—not a one-time spike.', 'Executive', 1),
    (series_a_id, 'Document Cohort Retention Curves', 'Build retention analysis showing how user/revenue cohorts behave over 6+ months. Flat or improving retention curves prove product-market fit. Declining curves = your PMF isn''t real yet. This is the single most scrutinized chart in Series A diligence.', 'AI_Agent', 2),
    (series_a_id, 'Prepare Complete Data Room', 'Assemble 20+ documents: cap table, articles of incorporation, financial statements, customer contracts, IP assignments, employment agreements, board minutes, previous term sheets, and key metrics dashboards. Missing documents signal disorganization to investors.', 'Apprentice', 3),
    (series_a_id, 'Establish 3+ Months of Consistent Growth', 'Show month-over-month growth of 15-20% for 3+ consecutive months. Investors look for trajectory, not just a single impressive month. If growth is lumpy, explain the drivers and show the underlying trend.', 'Executive', 4),
    (series_a_id, 'Build Board Composition', 'If you don''t have a formal board yet, establish one with at least a lead seed investor and an independent director. Have board materials and governance in place. Series A investors expect professional governance—not just founder-only decisions.', 'Executive', 5),
    (series_a_id, 'Create Investor Target List and Secure Warm Intros', 'Build a ranked list of 20-30 Series A funds with thesis alignment. Secure warm introductions to at least 5 top targets through existing investors, advisors, or portfolio company founders. Cold outreach at Series A has single-digit response rates—warm intros are essential.', 'Executive', 6),
    (series_a_id, 'Prepare for Deep-Dive Diligence', 'Anticipate diligence questions on: unit economics evolution, customer acquisition channels, competitive differentiation, team scaling plan, and technology architecture. Prepare 1-page memos for each topic. First-time founders often fail diligence through unpreparedness, not bad metrics.', 'AI_Agent', 7);

    -- Equity & Option Grant Planning Items
    INSERT INTO public.pack_items (pack_id, title, description, role, order_index) VALUES
    (equity_id, 'Size the Option Pool', 'Determine appropriate option pool size (typically 10-20% of fully diluted shares) based on your stage, headcount plan, and next fundraise timeline. Factor in that investors will want the pool created pre-money. Research benchmarks from Index Ventures'' Rewarding Talent data.', 'AI_Agent', 1),
    (equity_id, 'Create Equity Bands by Role and Seniority', 'Define equity grant ranges for each role and level: first 5 employees, first 20, first 50. Engineering, product, and revenue roles typically get more. Use percentage of fully diluted shares for early hires, shift to dollar value for later hires. Document the framework.', 'AI_Agent', 2),
    (equity_id, 'Establish Vesting Schedule', 'Set up standard 4-year vesting with 1-year cliff. Decide on monthly vs quarterly vesting after cliff. Consider acceleration provisions (single vs double trigger) for key executives. Document terms in a standard option grant agreement template.', 'Executive', 3),
    (equity_id, 'Define Exercise Windows and Provisions', 'Set post-termination exercise window (standard is 90 days, but 7-10 year windows are founder-friendly and help retention). Decide on early exercise (83(b) election) provisions. Establish buyback policy for departed employees.', 'Executive', 4),
    (equity_id, 'Create Equity Education Materials', 'Build a clear, jargon-free guide that helps employees understand: what options are, how vesting works, the difference between options and shares, tax implications (ISO vs NSO, 83(b) elections), and realistic scenarios for what their equity could be worth. Most employees don''t understand equity—educate them.', 'AI_Agent', 5),
    (equity_id, 'Set Up Legal and Administrative Infrastructure', 'Work with counsel to create: stock option plan document, board approval for the plan, individual grant agreements, and 409A valuation process. Set up cap table management tool (Carta, Pulley, or equivalent) to track all grants and exercises.', 'Apprentice', 6);

END $$;
