-- =============================================
-- SEED DATA: UK VC & Private Equity Firms
-- Generated: 2026-02-25
-- Source: BVCA member directory, Crunchbase, firm websites
-- Total entries: 50 (flagship firms — to be expanded via scraper scripts)
-- Categories: Venture Capital, Growth Equity, Private Equity
-- =============================================
-- All entries use category='Finance', is_demo=true, verification_tier='claimed'.
-- attributes JSONB schema for Finance/VC/PE:
--   firm_type: VC | Growth | PE | Debt | VCT | Angel
--   fund_size_gbp: latest fund size in GBP
--   fund_tier: seed | growth | pe_lower | pe_large
--   aum_gbp: total AUM
--   stage_focus: array of stages
--   sectors: array of sector focuses
--   is_active_deploying: bool
--   last_fund_close_date: YYYY-MM string
--   founding_year: int
--   bvca_member: bool
--   hq_city: string
--   investment_thesis: string
--   notable_portfolio: array of company names
--   recent_deals_summary: brief text
--   outreach_priority: A | B | C
--   outreach_status: not_started | contacted | replied | ...
--   website_url, linkedin_company_url, contact_email
--   data_source, data_confidence, last_verified
-- =============================================

INSERT INTO public.marketplace_listings (category, subcategory, title, description, attributes, image_url, is_verified, is_demo, verification_tier)
VALUES

-- =============================================
-- VENTURE CAPITAL — SEED & EARLY STAGE
-- =============================================

('Finance', 'Venture Capital', 'Seedcamp',
'Seedcamp is Europe''s leading pre-seed and seed-stage fund, founded in 2007, that invests in world-class founders solving large global problems through technology. Based in London, Seedcamp has backed over 500 startups including TransferWise (Wise), UiPath, Revolut, Sorare, and Grover across 30+ countries. The firm runs the renowned Seedcamp Week event and provides founders with capital, mentorship, and its global network of investors, corporates, and advisors. Seedcamp typically leads pre-seed rounds and follows on at seed.',
'{"firm_type": "VC", "fund_size_gbp": 100000000, "fund_tier": "seed", "aum_gbp": 400000000, "stage_focus": ["Pre-Seed", "Seed"], "sectors": ["SaaS", "Fintech", "Consumer Tech", "Developer Tools", "B2B"], "is_active_deploying": true, "last_fund_close_date": "2022-09", "founding_year": 2007, "bvca_member": true, "hq_city": "London", "investment_thesis": "Back world-class founders solving large global problems at pre-seed and seed stage with capital, community and network.", "notable_portfolio": ["Wise (TransferWise)", "UiPath", "Revolut", "Sorare", "Grover", "Pleo"], "recent_deals_summary": "Active deployer across 40-50 new investments per year; recent focus on AI, fintech and climate tech.", "outreach_priority": "A", "outreach_status": "not_started", "website_url": "https://www.seedcamp.com", "linkedin_company_url": "https://www.linkedin.com/company/seedcamp", "contact_email": "hello@seedcamp.com", "location": "London, England, UK", "data_source": "bvca_directory", "data_confidence": "high", "last_verified": "2026-02"}',
NULL, true, true, 'claimed'),

('Finance', 'Venture Capital', 'LocalGlobe',
'LocalGlobe is a London-based seed-stage venture capital firm co-founded by Robin and Saul Klein, focused on backing Europe''s most promising technology companies at the earliest stage. The firm manages over $1 billion across five funds and has backed category-defining companies including Robinhood, Transferwise, Graze, Lovefilm, Citymapper, Improbable, and Cazoo. LocalGlobe invests $500K–$2M in pre-seed and seed rounds. Alongside LocalGlobe, the Kleins operate Latitude (Series A) and Launchpad (pre-accelerator) creating a full early-stage ecosystem.',
'{"firm_type": "VC", "fund_size_gbp": 170000000, "fund_tier": "seed", "aum_gbp": 900000000, "stage_focus": ["Pre-Seed", "Seed"], "sectors": ["Consumer Tech", "Fintech", "SaaS", "Marketplaces", "Deep Tech"], "is_active_deploying": true, "last_fund_close_date": "2023-03", "founding_year": 2015, "bvca_member": true, "hq_city": "London", "investment_thesis": "Invest in exceptional founders at the earliest stage building businesses that matter, typically as the first or second institutional check.", "notable_portfolio": ["Robinhood", "Wise", "Cazoo", "Improbable", "Citymapper", "Lovefilm"], "recent_deals_summary": "Active seed investor; Latitude arm writing Series A cheques. Recent investments in climate, AI and fintech.", "outreach_priority": "A", "outreach_status": "not_started", "website_url": "https://www.localglobe.vc", "linkedin_company_url": "https://www.linkedin.com/company/localglobe", "contact_email": "hello@localglobe.vc", "location": "London, England, UK", "data_source": "bvca_directory", "data_confidence": "high", "last_verified": "2026-02"}',
NULL, true, true, 'claimed'),

('Finance', 'Venture Capital', 'Hoxton Ventures',
'Hoxton Ventures is a London-based seed-stage VC fund founded in 2013 by Hussein Kanji and Rob Hodgkinson. The firm focuses on B2B software and technology businesses with global ambitions, having backed Deliveroo (£4bn IPO), Babylon Health, Darktrace (LSE IPO), and GymShark. Hoxton writes first cheques of $500K–$2M at seed stage and follows on through growth. Fund III closed at $100M in 2021. The firm is known for its hands-on approach, deep technical diligence, and operational support for early founders.',
'{"firm_type": "VC", "fund_size_gbp": 85000000, "fund_tier": "seed", "aum_gbp": 250000000, "stage_focus": ["Seed", "Series A"], "sectors": ["B2B SaaS", "Consumer Tech", "Marketplaces", "Deep Tech"], "is_active_deploying": true, "last_fund_close_date": "2021-06", "founding_year": 2013, "bvca_member": true, "hq_city": "London", "investment_thesis": "Back exceptional European founders building global B2B software businesses at seed stage.", "notable_portfolio": ["Deliveroo", "Babylon Health", "Darktrace", "GymShark", "Lyst"], "recent_deals_summary": "Actively deploying Fund III; focus on SaaS, AI-driven B2B and marketplace models.", "outreach_priority": "A", "outreach_status": "not_started", "website_url": "https://www.hoxtonventures.com", "linkedin_company_url": "https://www.linkedin.com/company/hoxton-ventures", "location": "London, England, UK", "data_source": "bvca_directory", "data_confidence": "high", "last_verified": "2026-02"}',
NULL, true, true, 'claimed'),

('Finance', 'Venture Capital', 'Passion Capital',
'Passion Capital is one of the UK''s pioneering seed VC firms, founded in 2011 by Eileen Burbidge (former HM Treasury Special Envoy for Fintech), Stefan Glaenzer and Robert Dighero. Based in London, the firm has invested in over 100 companies including GoCardless, Lyst, Blockchain.com, and Swiftkey (acquired by Microsoft). Passion Capital invests £100K–£1.5M at seed stage with particular strength in fintech, SaaS and consumer internet businesses in the UK and Europe.',
'{"firm_type": "VC", "fund_size_gbp": 50000000, "fund_tier": "seed", "aum_gbp": 200000000, "stage_focus": ["Seed"], "sectors": ["Fintech", "SaaS", "Consumer Internet", "Mobile"], "is_active_deploying": true, "last_fund_close_date": "2020-01", "founding_year": 2011, "bvca_member": true, "hq_city": "London", "investment_thesis": "Partner with ambitious founders building internet businesses out of the UK, typically as first institutional money.", "notable_portfolio": ["GoCardless", "Lyst", "Blockchain.com", "Swiftkey", "Maze"], "recent_deals_summary": "Selectively deploying; known for hands-on founder support in fintech and SaaS.", "outreach_priority": "B", "outreach_status": "not_started", "website_url": "https://www.passioncapital.com", "linkedin_company_url": "https://www.linkedin.com/company/passion-capital", "contact_email": "hello@passioncapital.com", "location": "London, England, UK", "data_source": "bvca_directory", "data_confidence": "high", "last_verified": "2026-02"}',
NULL, true, true, 'claimed'),

('Finance', 'Venture Capital', 'Episode 1 Ventures',
'Episode 1 is a London-based seed-stage VC firm founded in 2013 by Simon Murdoch and Jonathan Lenson, focused exclusively on UK-founded technology businesses. The firm invests £500K–£2M at seed stage and runs an intensive early-stage support programme. Portfolio companies include Appear Here, Gapsquare, Perkbox, and Bricklane. Episode 1 has built a reputation for deep operational involvement and founder-aligned terms.',
'{"firm_type": "VC", "fund_size_gbp": 60000000, "fund_tier": "seed", "aum_gbp": 120000000, "stage_focus": ["Seed"], "sectors": ["SaaS", "Marketplaces", "B2B", "HR Tech", "Proptech"], "is_active_deploying": true, "last_fund_close_date": "2021-01", "founding_year": 2013, "bvca_member": true, "hq_city": "London", "investment_thesis": "First institutional investor in UK-founded technology companies, with hands-on operational support.", "notable_portfolio": ["Appear Here", "Perkbox", "Bricklane", "Gapsquare"], "recent_deals_summary": "Active seed investor focused on UK founders; typical cheque £500K-£2M.", "outreach_priority": "B", "outreach_status": "not_started", "website_url": "https://www.episode1.com", "linkedin_company_url": "https://www.linkedin.com/company/episode-1-ventures", "location": "London, England, UK", "data_source": "bvca_directory", "data_confidence": "high", "last_verified": "2026-02"}',
NULL, true, true, 'claimed'),

('Finance', 'Venture Capital', 'Playfair Capital',
'Playfair Capital is a London-based pre-seed and seed fund launched in 2012 that backs mission-driven founders solving real-world problems with technology. The firm manages three funds and has invested in over 100 companies. Playfair is a B Corp and is known for its focus on diversity, values-led investing, and a strong community of founders. Investment size: £250K–£1.5M.',
'{"firm_type": "VC", "fund_size_gbp": 50000000, "fund_tier": "seed", "aum_gbp": 150000000, "stage_focus": ["Pre-Seed", "Seed"], "sectors": ["SaaS", "Consumer Tech", "Impact", "Fintech", "Health Tech"], "is_active_deploying": true, "last_fund_close_date": "2022-06", "founding_year": 2012, "bvca_member": true, "hq_city": "London", "investment_thesis": "Back mission-driven founders at pre-seed and seed with capital and a strong founder community.", "notable_portfolio": ["Juro", "Farewill", "Wayve (early)", "Cazoo (early)"], "recent_deals_summary": "Deploying third fund; focus on impact, AI and B2B software.", "outreach_priority": "B", "outreach_status": "not_started", "website_url": "https://www.playfaircapital.com", "linkedin_company_url": "https://www.linkedin.com/company/playfair-capital", "location": "London, England, UK", "data_source": "bvca_directory", "data_confidence": "high", "last_verified": "2026-02"}',
NULL, true, true, 'claimed'),

-- =============================================
-- VENTURE CAPITAL — SERIES A/B
-- =============================================

('Finance', 'Venture Capital', 'Balderton Capital',
'Balderton Capital is one of Europe''s leading Series A venture capital firms, founded in 2000 and headquartered in London. The firm manages over $4 billion across multiple funds and has backed over 250 companies including Revolut, Darktrace, Citymapper, Contentful, Yoox (acquired by Net-A-Porter), The Hut Group, and Kobalt Music. Balderton typically leads Series A rounds of $5M–$20M in European technology companies with global ambitions, focusing on software, fintech, data infrastructure, and consumer internet.',
'{"firm_type": "VC", "fund_size_gbp": 600000000, "fund_tier": "growth", "aum_gbp": 4000000000, "stage_focus": ["Series A", "Series B"], "sectors": ["SaaS", "Fintech", "Consumer Tech", "Data Infrastructure", "Marketplace"], "is_active_deploying": true, "last_fund_close_date": "2023-01", "founding_year": 2000, "bvca_member": true, "hq_city": "London", "investment_thesis": "Lead Series A in exceptional European founders with global ambition, then commit deeply through growth.", "notable_portfolio": ["Revolut", "Darktrace", "Citymapper", "Contentful", "The Hut Group", "Kobalt", "Yoox"], "recent_deals_summary": "Actively deploying; recent AI, deep tech and fintech investments across Europe.", "outreach_priority": "A", "outreach_status": "not_started", "website_url": "https://www.balderton.com", "linkedin_company_url": "https://www.linkedin.com/company/balderton-capital", "contact_email": "enquiry@balderton.com", "location": "London, England, UK", "data_source": "bvca_directory", "data_confidence": "high", "last_verified": "2026-02"}',
NULL, true, true, 'claimed'),

('Finance', 'Venture Capital', 'Atomico',
'Atomico is a London-based global venture capital firm founded in 2006 by Skype co-founder Niklas Zennström. With $2.7 billion under management across five funds, Atomico backs Europe''s most ambitious technology founders from Series A to growth stage. The firm has invested in Klarna, Supercell, Stripe, Lilium, MessageBird, Pipedrive, and dozens of other category leaders. Atomico is known for its founders-first philosophy, deep European network, and the annual ''State of European Tech'' report.',
'{"firm_type": "VC", "fund_size_gbp": 800000000, "fund_tier": "growth", "aum_gbp": 2700000000, "stage_focus": ["Series A", "Series B", "Series C", "Growth"], "sectors": ["Deep Tech", "SaaS", "Fintech", "Climate", "Consumer Tech"], "is_active_deploying": true, "last_fund_close_date": "2022-04", "founding_year": 2006, "bvca_member": true, "hq_city": "London", "investment_thesis": "Partner with Europe''s most ambitious founders from early growth stage through IPO, with global operational support.", "notable_portfolio": ["Klarna", "Supercell", "Pipedrive", "Lilium", "MessageBird", "Stripe (early)"], "recent_deals_summary": "Active across European Series A-C; notable recent investments in climate tech and deep tech.", "outreach_priority": "A", "outreach_status": "not_started", "website_url": "https://www.atomico.com", "linkedin_company_url": "https://www.linkedin.com/company/atomico", "contact_email": "hello@atomico.com", "location": "London, England, UK", "data_source": "bvca_directory", "data_confidence": "high", "last_verified": "2026-02"}',
NULL, true, true, 'claimed'),

('Finance', 'Venture Capital', 'Index Ventures',
'Index Ventures is a global venture capital firm with offices in London and San Francisco, founded in 1996. Managing over $9 billion, Index has backed Deliveroo, Farfetch, Adyen, Dropbox, Slack, Roblox, Figma, Revolut, and King. The firm invests from seed through growth, with particular strength in fintech, gaming, developer tools, and consumer internet. Index is consistently ranked among the world''s top VC firms and has produced multiple unicorns and decacorns from its European portfolio.',
'{"firm_type": "VC", "fund_size_gbp": 2000000000, "fund_tier": "growth", "aum_gbp": 9000000000, "stage_focus": ["Seed", "Series A", "Series B", "Series C", "Growth"], "sectors": ["Fintech", "Gaming", "Developer Tools", "Consumer Tech", "SaaS"], "is_active_deploying": true, "last_fund_close_date": "2023-06", "founding_year": 1996, "bvca_member": true, "hq_city": "London", "investment_thesis": "Back audacious founders building transformative technology companies from seed through growth, globally.", "notable_portfolio": ["Deliveroo", "Farfetch", "Revolut", "Figma", "Dropbox", "Adyen", "Roblox", "Slack"], "recent_deals_summary": "Continuously active across the funding spectrum; strong pipeline in AI and developer tools.", "outreach_priority": "A", "outreach_status": "not_started", "website_url": "https://www.indexventures.com", "linkedin_company_url": "https://www.linkedin.com/company/index-ventures", "location": "London, England, UK", "data_source": "bvca_directory", "data_confidence": "high", "last_verified": "2026-02"}',
NULL, true, true, 'claimed'),

('Finance', 'Venture Capital', 'Accel',
'Accel is a global venture capital firm with offices in Palo Alto, London, and Bangalore, managing $10+ billion. Founded in 1983, Accel opened its London office in 2000 and has backed Spotify, Slack, Facebook, Dropbox, Rovio, BlaBlaCar, UiPath, and hundreds of others. The London team leads European and Israeli investment from Series A through growth. Accel is known for its early conviction in B2B software, security, and consumer internet.',
'{"firm_type": "VC", "fund_size_gbp": 1500000000, "fund_tier": "growth", "aum_gbp": 10000000000, "stage_focus": ["Series A", "Series B", "Series C", "Growth"], "sectors": ["B2B SaaS", "Security", "Fintech", "Consumer Internet", "Infrastructure"], "is_active_deploying": true, "last_fund_close_date": "2022-11", "founding_year": 1983, "bvca_member": false, "hq_city": "London", "investment_thesis": "Partner with founders at the moment of acceleration, from Series A through IPO, globally with particular strength in Europe and Israel.", "notable_portfolio": ["Spotify", "BlaBlaCar", "UiPath", "Slack", "Deliveroo (early)", "GoCardless"], "recent_deals_summary": "Active European deployment from London; strong focus on AI infrastructure and security.", "outreach_priority": "A", "outreach_status": "not_started", "website_url": "https://www.accel.com", "linkedin_company_url": "https://www.linkedin.com/company/accel-partners", "location": "London, England, UK", "data_source": "bvca_directory", "data_confidence": "high", "last_verified": "2026-02"}',
NULL, true, true, 'claimed'),

('Finance', 'Venture Capital', 'Notion Capital',
'Notion Capital is a London-based B2B SaaS and cloud venture capital firm founded in 2009 by Jos White, Ben White, Chris Tottman, and Ian Milbourn — all founders of MessageLabs (sold to Symantec for $695M). The firm manages £500M+ and has backed over 50 companies including ComplyAdvantage, Paddle, Tessian, Perkbox, and Recurly. Notion invests £2M–£10M in Series A and B rounds and is known for its operator-investor model with deep SaaS expertise.',
'{"firm_type": "VC", "fund_size_gbp": 180000000, "fund_tier": "growth", "aum_gbp": 500000000, "stage_focus": ["Series A", "Series B"], "sectors": ["B2B SaaS", "Cloud", "RegTech", "Fintech", "Security"], "is_active_deploying": true, "last_fund_close_date": "2022-03", "founding_year": 2009, "bvca_member": true, "hq_city": "London", "investment_thesis": "Operator-investors backing the next generation of B2B SaaS businesses at Series A and B with hands-on commercial support.", "notable_portfolio": ["ComplyAdvantage", "Paddle", "Tessian", "Perkbox", "Recurly"], "recent_deals_summary": "Actively deploying; focus on AI-enhanced B2B software, compliance tech and developer-first SaaS.", "outreach_priority": "A", "outreach_status": "not_started", "website_url": "https://www.notioncapital.com", "linkedin_company_url": "https://www.linkedin.com/company/notion-capital", "contact_email": "hello@notioncapital.com", "location": "London, England, UK", "data_source": "bvca_directory", "data_confidence": "high", "last_verified": "2026-02"}',
NULL, true, true, 'claimed'),

('Finance', 'Venture Capital', 'MMC Ventures',
'MMC Ventures is a London-based technology venture capital firm founded in 2000, managing over £500M across multiple funds. The firm invests £2M–£15M in Series A and B rounds in UK and European technology companies. MMC has backed Gousto, iwoca, Bought By Many, AimBrain, and over 80 other companies. MMC is known for its applied data science approach to deal sourcing and portfolio support, and publishes influential research on the European AI landscape.',
'{"firm_type": "VC", "fund_size_gbp": 200000000, "fund_tier": "growth", "aum_gbp": 500000000, "stage_focus": ["Series A", "Series B"], "sectors": ["Fintech", "InsurTech", "AI", "SaaS", "Consumer Tech"], "is_active_deploying": true, "last_fund_close_date": "2022-09", "founding_year": 2000, "bvca_member": true, "hq_city": "London", "investment_thesis": "Data-driven investor backing the UK and Europe''s best technology companies at Series A and B with operational support from former founders.", "notable_portfolio": ["Gousto", "iwoca", "Bought By Many", "AimBrain", "Flo Health"], "recent_deals_summary": "Active deployer across UK/European Series A-B; strong pipeline in fintech, insurtech and AI.", "outreach_priority": "A", "outreach_status": "not_started", "website_url": "https://www.mmcventures.com", "linkedin_company_url": "https://www.linkedin.com/company/mmc-ventures", "contact_email": "info@mmcventures.com", "location": "London, England, UK", "data_source": "bvca_directory", "data_confidence": "high", "last_verified": "2026-02"}',
NULL, true, true, 'claimed'),

('Finance', 'Venture Capital', 'IQ Capital',
'IQ Capital is a Cambridge and London-based deep technology venture capital firm founded in 2006, managing £500M+ across four funds. The firm focuses exclusively on deep tech companies combining advanced science and engineering: AI/ML, quantum computing, semiconductors, synthetic biology, and advanced materials. IQ Capital has backed Actual Analytics, CMR Surgical, Featurespace, Nyobolt, and Riverlane. Investment range: £1M–£20M from seed through Series C.',
'{"firm_type": "VC", "fund_size_gbp": 220000000, "fund_tier": "growth", "aum_gbp": 500000000, "stage_focus": ["Seed", "Series A", "Series B", "Series C"], "sectors": ["Deep Tech", "AI/ML", "Quantum", "Semiconductors", "Synthetic Biology", "Advanced Materials"], "is_active_deploying": true, "last_fund_close_date": "2023-06", "founding_year": 2006, "bvca_member": true, "hq_city": "Cambridge", "investment_thesis": "UK''s leading deep technology investor, backing companies built on proprietary science and engineering with global market potential.", "notable_portfolio": ["CMR Surgical", "Featurespace", "Riverlane", "Nyobolt", "Speechmatics"], "recent_deals_summary": "Actively deploying Fund IV; focus on AI hardware, quantum computing and biotech spinouts from UK universities.", "outreach_priority": "A", "outreach_status": "not_started", "website_url": "https://www.iqcapital.vc", "linkedin_company_url": "https://www.linkedin.com/company/iq-capital", "contact_email": "info@iqcapital.vc", "location": "Cambridge, England, UK", "data_source": "bvca_directory", "data_confidence": "high", "last_verified": "2026-02"}',
NULL, true, true, 'claimed'),

('Finance', 'Venture Capital', 'Octopus Ventures',
'Octopus Ventures is one of Europe''s largest and most active venture capital funds, part of Octopus Group, investing across the UK and Europe from seed to Series C. With over £1.5 billion under management, Octopus has backed Zoopla, Depop, Secret Escapes, Landbay, Elvie, and 100+ other companies. The firm invests across six verticals: health, B2B software, deeptech, fintech, consumer, and net zero. Ticket size: £1M–£20M.',
'{"firm_type": "VC", "fund_size_gbp": 400000000, "fund_tier": "growth", "aum_gbp": 1500000000, "stage_focus": ["Seed", "Series A", "Series B", "Series C"], "sectors": ["Health Tech", "B2B SaaS", "Deep Tech", "Fintech", "Consumer", "Climate"], "is_active_deploying": true, "last_fund_close_date": "2022-01", "founding_year": 2007, "bvca_member": true, "hq_city": "London", "investment_thesis": "Back ambitious founders across six transformative sectors from seed to Series C across the UK and Europe.", "notable_portfolio": ["Zoopla", "Depop", "Secret Escapes", "Elvie", "Landbay", "Shazam (early)"], "recent_deals_summary": "Prolific deployer; one of most active UK VCs by deal count; recently increased climate tech allocation.", "outreach_priority": "A", "outreach_status": "not_started", "website_url": "https://www.octopusventures.com", "linkedin_company_url": "https://www.linkedin.com/company/octopus-ventures", "contact_email": "hq@octopusventures.com", "location": "London, England, UK", "data_source": "bvca_directory", "data_confidence": "high", "last_verified": "2026-02"}',
NULL, true, true, 'claimed'),

('Finance', 'Venture Capital', 'Dawn Capital',
'Dawn Capital is a London-based B2B software venture capital firm founded in 2007, managing over €1 billion across four funds. The firm focuses exclusively on enterprise software and fintech infrastructure, backing companies including Mimecast (Nasdaq: MIME), Collibra, iZettle (acquired by PayPal for $2.2B), Neo4j, Tink (acquired by Visa), and Showpad. Dawn invests £5M–£30M in Series A and B rounds and is known for its operational platform for scaling enterprise sales.',
'{"firm_type": "VC", "fund_size_gbp": 350000000, "fund_tier": "growth", "aum_gbp": 1000000000, "stage_focus": ["Series A", "Series B"], "sectors": ["Enterprise SaaS", "Fintech Infrastructure", "Security", "Data"], "is_active_deploying": true, "last_fund_close_date": "2022-07", "founding_year": 2007, "bvca_member": true, "hq_city": "London", "investment_thesis": "Europe''s leading B2B software specialist, backing enterprise software and fintech infrastructure companies from Series A.", "notable_portfolio": ["Mimecast", "Collibra", "iZettle", "Neo4j", "Tink", "Showpad"], "recent_deals_summary": "Actively deploying Fund IV; focus on AI-powered enterprise software and fintech infrastructure across Europe.", "outreach_priority": "A", "outreach_status": "not_started", "website_url": "https://www.dawncapital.com", "linkedin_company_url": "https://www.linkedin.com/company/dawn-capital", "contact_email": "info@dawncapital.com", "location": "London, England, UK", "data_source": "bvca_directory", "data_confidence": "high", "last_verified": "2026-02"}',
NULL, true, true, 'claimed'),

('Finance', 'Venture Capital', 'Blossom Capital',
'Blossom Capital is a London-based early-growth stage venture capital firm founded in 2018 by Ophelia Brown, previously of Index Ventures. The firm raised Fund III at £350M in 2022 and focuses on Series A and B investments in European software companies. Blossom has backed Checkout.com (Europe''s most valuable private fintech), Nuvei, Pave, Diem, and Apparent. The firm typically writes £5M–£20M cheques and provides hands-on GTM and hiring support.',
'{"firm_type": "VC", "fund_size_gbp": 350000000, "fund_tier": "growth", "aum_gbp": 700000000, "stage_focus": ["Series A", "Series B"], "sectors": ["Fintech", "SaaS", "Consumer Tech", "Infrastructure"], "is_active_deploying": true, "last_fund_close_date": "2022-10", "founding_year": 2018, "bvca_member": true, "hq_city": "London", "investment_thesis": "Series A specialist backing European software founders with intensive hands-on support through the hardest stage of company building.", "notable_portfolio": ["Checkout.com", "Nuvei", "Pave", "Diem"], "recent_deals_summary": "Active deployer of Fund III; strong fintech and B2B software thesis.", "outreach_priority": "A", "outreach_status": "not_started", "website_url": "https://www.blossomcapital.com", "linkedin_company_url": "https://www.linkedin.com/company/blossom-capital", "contact_email": "hello@blossomcapital.com", "location": "London, England, UK", "data_source": "bvca_directory", "data_confidence": "high", "last_verified": "2026-02"}',
NULL, true, true, 'claimed'),

('Finance', 'Venture Capital', 'Frog Capital',
'Frog Capital is a London-based growth equity investor founded in 2009, focused on scale-up technology companies across Europe. With £300M+ under management, Frog invests £5M–£25M in high-growth B2B software and technology-enabled services companies with £3M–£20M ARR looking to accelerate international expansion. Portfolio includes Brightpearl (acquired by Sage), Liberis, Tessian, and Relex Solutions. Frog is known for its Scaling Playbook operational framework.',
'{"firm_type": "Growth", "fund_size_gbp": 130000000, "fund_tier": "growth", "aum_gbp": 300000000, "stage_focus": ["Series A", "Series B", "Growth"], "sectors": ["B2B SaaS", "Tech-Enabled Services", "Supply Chain", "HR Tech"], "is_active_deploying": true, "last_fund_close_date": "2022-01", "founding_year": 2009, "bvca_member": true, "hq_city": "London", "investment_thesis": "Scale-up specialist investing in B2B technology businesses at £3M-£20M ARR ready to accelerate international expansion.", "notable_portfolio": ["Brightpearl", "Liberis", "Relex Solutions", "Tessian (early)"], "recent_deals_summary": "Deploying latest fund; focus on AI-enhanced B2B software and supply chain technology.", "outreach_priority": "B", "outreach_status": "not_started", "website_url": "https://www.frogcapital.com", "linkedin_company_url": "https://www.linkedin.com/company/frog-capital", "contact_email": "info@frogcapital.com", "location": "London, England, UK", "data_source": "bvca_directory", "data_confidence": "high", "last_verified": "2026-02"}',
NULL, true, true, 'claimed'),

('Finance', 'Venture Capital', 'Highland Europe',
'Highland Europe is the European growth equity arm of Highland Capital Partners, headquartered in Geneva with offices in London. The firm manages $1.7 billion and focuses on Series B and C investments in proven European technology companies with $5M–$30M ARR. Portfolio includes Nexthink, Photobox, Malwarebytes, ContentSquare, Featurespace, and Cabify. Highland typically invests $15M–$50M and is known for its US market expansion support.',
'{"firm_type": "Growth", "fund_size_gbp": 500000000, "fund_tier": "growth", "aum_gbp": 1500000000, "stage_focus": ["Series B", "Series C", "Growth"], "sectors": ["Enterprise SaaS", "Consumer Tech", "Security", "Analytics", "Marketplace"], "is_active_deploying": true, "last_fund_close_date": "2021-06", "founding_year": 2012, "bvca_member": false, "hq_city": "London", "investment_thesis": "Growth equity specialist backing European technology leaders at Series B-C with deep US market expansion expertise.", "notable_portfolio": ["Nexthink", "ContentSquare", "Featurespace", "Photobox", "Malwarebytes"], "recent_deals_summary": "Active deployment from London office; focus on enterprise SaaS with US expansion potential.", "outreach_priority": "B", "outreach_status": "not_started", "website_url": "https://www.highlandeurope.com", "linkedin_company_url": "https://www.linkedin.com/company/highland-europe", "location": "London, England, UK", "data_source": "bvca_directory", "data_confidence": "high", "last_verified": "2026-02"}',
NULL, true, true, 'claimed'),

('Finance', 'Venture Capital', 'Augmentum Fintech',
'Augmentum Fintech is the UK''s only publicly listed fintech-focused investment fund (LSE: AUGM), founded in 2018 by Tim Levene and Richard Matthews. The fund targets European fintech companies at Series A and B, with investments in Tide, Interactive Investor, Farewill, Grover, Onfido (acquired by Entrust), and Seedrs. Augmentum manages £270M and invests £2M–£20M per company, with a particular focus on insurance, banking, wealth management, and regtech verticals.',
'{"firm_type": "VC", "fund_size_gbp": 270000000, "fund_tier": "growth", "aum_gbp": 270000000, "stage_focus": ["Series A", "Series B"], "sectors": ["Fintech", "InsurTech", "WealthTech", "RegTech", "Banking"], "is_active_deploying": true, "last_fund_close_date": "2022-01", "founding_year": 2018, "bvca_member": true, "hq_city": "London", "investment_thesis": "Europe''s leading fintech specialist fund, backing transformative financial services businesses from Series A.", "notable_portfolio": ["Tide", "Interactive Investor", "Farewill", "Onfido", "Grover", "Seedrs"], "recent_deals_summary": "Actively deploying; focus on embedded finance, open banking and digital wealth platforms.", "outreach_priority": "A", "outreach_status": "not_started", "website_url": "https://www.augmentum.vc", "linkedin_company_url": "https://www.linkedin.com/company/augmentum-fintech", "location": "London, England, UK", "data_source": "bvca_directory", "data_confidence": "high", "last_verified": "2026-02"}',
NULL, true, true, 'claimed'),

('Finance', 'Venture Capital', 'GP Bullhound',
'GP Bullhound is a London and Stockholm-based technology investment bank and fund manager founded in 1999, managing €1 billion+ in funds alongside its advisory business. The firm has backed Spotify, King, Klarna, Mojang (Minecraft), and UIPath. GP Bullhound Technology Investments focuses on growth-stage investments of €10M–€50M in European and Israeli software, media and internet companies. Known for its proprietary sector research and long-standing advisory relationships.',
'{"firm_type": "Growth", "fund_size_gbp": 400000000, "fund_tier": "growth", "aum_gbp": 1000000000, "stage_focus": ["Series B", "Series C", "Growth"], "sectors": ["SaaS", "Consumer Internet", "Media Tech", "Gaming", "Fintech"], "is_active_deploying": true, "last_fund_close_date": "2022-04", "founding_year": 1999, "bvca_member": true, "hq_city": "London", "investment_thesis": "Growth equity and M&A specialist in European technology, leveraging advisory relationships for proprietary deal flow.", "notable_portfolio": ["Spotify (early)", "King", "Klarna (early)", "Mojang", "UIPath"], "recent_deals_summary": "Active fund deployment alongside active M&A advisory; strong in gaming, media tech and SaaS.", "outreach_priority": "B", "outreach_status": "not_started", "website_url": "https://www.gpbullhound.com", "linkedin_company_url": "https://www.linkedin.com/company/gp-bullhound", "location": "London, England, UK", "data_source": "bvca_directory", "data_confidence": "high", "last_verified": "2026-02"}',
NULL, true, true, 'claimed'),

('Finance', 'Venture Capital', 'Parkwalk Advisors',
'Parkwalk Advisors is the UK''s leading EIS (Enterprise Investment Scheme) fund manager focused on university spinout technology companies, managing over £500M. Founded in 2009, Parkwalk works closely with the Universities of Oxford, Cambridge, Bristol, Edinburgh, and Imperial College London, backing deeptech spinouts in quantum, AI, materials and life sciences at early stage. The firm has backed over 200 companies including Sifted, Actual Analytics, and many IP-rich spinouts. EIS tax relief makes Parkwalk accessible to UK individual investors.',
'{"firm_type": "VC", "fund_size_gbp": 150000000, "fund_tier": "seed", "aum_gbp": 500000000, "stage_focus": ["Seed", "Series A"], "sectors": ["Deep Tech", "Quantum", "AI", "Life Sciences", "Advanced Materials"], "is_active_deploying": true, "last_fund_close_date": "2024-01", "founding_year": 2009, "bvca_member": true, "hq_city": "London", "investment_thesis": "UK''s specialist university spinout investor, backing IP-rich deeptech companies from Oxford, Cambridge and other leading institutions.", "notable_portfolio": ["Multiple university spinouts across quantum, AI and materials"], "recent_deals_summary": "Prolific deployer across UK university spinout ecosystem; multiple funds open annually.", "outreach_priority": "B", "outreach_status": "not_started", "website_url": "https://www.parkwalkadvisors.com", "linkedin_company_url": "https://www.linkedin.com/company/parkwalk-advisors", "contact_email": "info@parkwalkadvisors.com", "location": "London, England, UK", "data_source": "bvca_directory", "data_confidence": "high", "last_verified": "2026-02"}',
NULL, true, true, 'claimed'),

-- =============================================
-- GROWTH / LATE-STAGE VC
-- =============================================

('Finance', 'Venture Capital', 'Molten Ventures',
'Molten Ventures (formerly Draper Esprit) is a leading European growth-stage venture capital firm listed on the London Stock Exchange (LSE: GROW) and Euronext Dublin, managing £1.5B+ in AUM. Founded in 2006, Molten has backed Revolut, Graphcore, Ledger, Cazoo, and Thought Machine. The firm invests £10M–£100M in Series B through pre-IPO rounds in European technology leaders. As an evergreen listed fund, Molten has permanent capital and can hold companies to IPO and beyond.',
'{"firm_type": "Growth", "fund_size_gbp": 300000000, "fund_tier": "growth", "aum_gbp": 1500000000, "stage_focus": ["Series B", "Series C", "Late Stage", "Pre-IPO"], "sectors": ["Deep Tech", "Fintech", "SaaS", "Consumer Tech", "Semiconductor"], "is_active_deploying": true, "last_fund_close_date": "2023-01", "founding_year": 2006, "bvca_member": true, "hq_city": "London", "investment_thesis": "Evergreen listed fund backing Europe''s technology leaders from Series B through IPO with permanent capital and long-term partnership.", "notable_portfolio": ["Revolut", "Graphcore", "Ledger", "Cazoo", "Thought Machine", "Perkbox"], "recent_deals_summary": "Active deployer; recent focus on AI, deeptech and fintech infrastructure at late stage.", "outreach_priority": "A", "outreach_status": "not_started", "website_url": "https://www.moltenventures.com", "linkedin_company_url": "https://www.linkedin.com/company/molten-ventures", "contact_email": "ir@moltenventures.com", "location": "London, England, UK", "data_source": "bvca_directory", "data_confidence": "high", "last_verified": "2026-02"}',
NULL, true, true, 'claimed'),

-- =============================================
-- PRIVATE EQUITY — LOWER MID-MARKET
-- =============================================

('Finance', 'Private Equity', 'BGF (Business Growth Fund)',
'BGF (Business Growth Fund) is the UK and Ireland''s most active growth capital investor, founded in 2011 with backing from five major UK banks (Barclays, HSBC, Lloyds, NatWest, Standard Chartered). BGF has invested over £3.5 billion in 500+ companies, providing equity capital to SMEs and mid-market businesses with revenues of £3M–£100M. The firm invests £1M–£15M minority stakes across all sectors including manufacturing, technology, healthcare, food & drink, and business services. BGF has offices across the UK.',
'{"firm_type": "PE", "fund_size_gbp": 2500000000, "fund_tier": "pe_lower", "aum_gbp": 3500000000, "stage_focus": ["Growth", "Lower Mid-Market"], "sectors": ["All Sectors", "Manufacturing", "Technology", "Healthcare", "Food & Drink", "Business Services"], "is_active_deploying": true, "last_fund_close_date": "2023-01", "founding_year": 2011, "bvca_member": true, "hq_city": "London", "investment_thesis": "UK''s most active growth capital investor providing minority equity to ambitious UK businesses with £3M-£100M revenue.", "notable_portfolio": ["500+ portfolio companies across all UK sectors"], "recent_deals_summary": "Most prolific UK equity investor by deal count; 100+ new investments per year.", "outreach_priority": "A", "outreach_status": "not_started", "website_url": "https://www.bgf.co.uk", "linkedin_company_url": "https://www.linkedin.com/company/bgf", "contact_email": "enquiry@bgf.co.uk", "location": "London, England, UK", "data_source": "bvca_directory", "data_confidence": "high", "last_verified": "2026-02"}',
NULL, true, true, 'claimed'),

('Finance', 'Private Equity', 'Inflexion Private Equity',
'Inflexion is a London-based mid-market private equity firm founded in 1999, managing £6 billion+. The firm backs ambitious, profitable UK businesses with enterprise values of £10M–£1B+ across three investment strategies: Buyout (£30M–£300M EV), Partnership Capital (minority growth), and Enterprise (smaller). Inflexion has backed over 200 companies including SimplyBiz, Alcumus, Access Group, and Citation. Known for its sector agnostic approach and buy-and-build strategy.',
'{"firm_type": "PE", "fund_size_gbp": 1500000000, "fund_tier": "pe_lower", "aum_gbp": 6000000000, "stage_focus": ["Buyout", "Growth Capital", "Lower Mid-Market", "Mid-Market"], "sectors": ["Technology", "Business Services", "Healthcare", "Financial Services", "Consumer"], "is_active_deploying": true, "last_fund_close_date": "2023-09", "founding_year": 1999, "bvca_member": true, "hq_city": "London", "investment_thesis": "Partner with exceptional management teams in profitable UK businesses to accelerate growth through buy-and-build and operational improvement.", "notable_portfolio": ["Access Group", "Citation", "SimplyBiz", "Alcumus", "Intelligent Stewardship"], "recent_deals_summary": "Actively deploying across all three strategies; strong pipeline in tech-enabled business services.", "outreach_priority": "A", "outreach_status": "not_started", "website_url": "https://www.inflexion.com", "linkedin_company_url": "https://www.linkedin.com/company/inflexion-private-equity", "contact_email": "info@inflexion.com", "location": "London, England, UK", "data_source": "bvca_directory", "data_confidence": "high", "last_verified": "2026-02"}',
NULL, true, true, 'claimed'),

('Finance', 'Private Equity', 'ECI Partners',
'ECI Partners is a London-based growth-focused private equity firm founded in 1976, managing £1.5 billion and specialising in profitable UK technology and tech-enabled services companies with £5M–£60M EBITDA. ECI invests £20M–£100M per deal through buyouts and growth capital transactions. Portfolio includes Trustpilot (IPO on LSE), Inspired Education, Liberis, and Access Group. ECI is known for backing management-led deals and building SaaS and software businesses through M&A.',
'{"firm_type": "PE", "fund_size_gbp": 600000000, "fund_tier": "pe_lower", "aum_gbp": 1500000000, "stage_focus": ["Buyout", "Growth Capital"], "sectors": ["Technology", "Tech-Enabled Services", "SaaS", "Education", "Financial Services"], "is_active_deploying": true, "last_fund_close_date": "2023-01", "founding_year": 1976, "bvca_member": true, "hq_city": "London", "investment_thesis": "Back the UK''s best technology and tech-enabled services companies through buyout and growth capital with a focus on SaaS and recurring revenue models.", "notable_portfolio": ["Trustpilot", "Inspired Education", "Liberis", "Access Group (partial)"], "recent_deals_summary": "Active deployment of latest fund; strong focus on SaaS businesses with buy-and-build appetite.", "outreach_priority": "A", "outreach_status": "not_started", "website_url": "https://www.ecipartners.com", "linkedin_company_url": "https://www.linkedin.com/company/eci-partners", "contact_email": "info@ecipartners.com", "location": "London, England, UK", "data_source": "bvca_directory", "data_confidence": "high", "last_verified": "2026-02"}',
NULL, true, true, 'claimed'),

('Finance', 'Private Equity', 'Graphite Capital',
'Graphite Capital is a London-based mid-market private equity firm founded in 1981, managing approximately £1 billion. The firm invests £15M–£80M in profitable UK businesses across consumer, business services, healthcare, and technology sectors, typically through management buyouts. Portfolio includes Travelport (partial), David Lloyd Leisure, and Whitbread restaurants. Graphite focuses on businesses with £5M–£30M EBITDA and management teams with strong track records.',
'{"firm_type": "PE", "fund_size_gbp": 400000000, "fund_tier": "pe_lower", "aum_gbp": 1000000000, "stage_focus": ["Buyout", "Mid-Market MBO"], "sectors": ["Consumer", "Business Services", "Healthcare", "Technology"], "is_active_deploying": true, "last_fund_close_date": "2022-01", "founding_year": 1981, "bvca_member": true, "hq_city": "London", "investment_thesis": "Partner with management teams in profitable UK businesses to deliver transformational value through operational expertise and strategic support.", "notable_portfolio": ["David Lloyd Leisure", "Travelport (partial)", "Whitbread restaurants"], "recent_deals_summary": "Selective mid-market buyout investor; focus on consumer-facing and business services businesses.", "outreach_priority": "B", "outreach_status": "not_started", "website_url": "https://www.graphitecapital.com", "linkedin_company_url": "https://www.linkedin.com/company/graphite-capital", "contact_email": "info@graphitecapital.com", "location": "London, England, UK", "data_source": "bvca_directory", "data_confidence": "high", "last_verified": "2026-02"}',
NULL, true, true, 'claimed'),

('Finance', 'Private Equity', 'Bowmark Capital',
'Bowmark Capital is a London-based mid-market private equity firm founded in 1999 that invests in UK-headquartered businesses in the services sector with enterprise values of £30M–£200M. The firm manages £1 billion+ and focuses on professional services, technology-enabled services, financial services, and healthcare services. Bowmark has backed Citation, Alcumus, 4 Global, and Acuity Research & Practice. Known for long-term partnership model and deep management team engagement.',
'{"firm_type": "PE", "fund_size_gbp": 500000000, "fund_tier": "pe_lower", "aum_gbp": 1000000000, "stage_focus": ["Buyout", "Growth Capital", "Mid-Market"], "sectors": ["Professional Services", "Tech-Enabled Services", "Financial Services", "Healthcare Services"], "is_active_deploying": true, "last_fund_close_date": "2022-10", "founding_year": 1999, "bvca_member": true, "hq_city": "London", "investment_thesis": "Mid-market specialist backing UK services businesses where management quality and organic growth potential are primary value drivers.", "notable_portfolio": ["Citation", "4 Global", "Acuity Research & Practice"], "recent_deals_summary": "Active deployer in UK services sector; strong pipeline in tech-enabled professional services.", "outreach_priority": "B", "outreach_status": "not_started", "website_url": "https://www.bowmark.com", "linkedin_company_url": "https://www.linkedin.com/company/bowmark-capital", "contact_email": "info@bowmark.com", "location": "London, England, UK", "data_source": "bvca_directory", "data_confidence": "high", "last_verified": "2026-02"}',
NULL, true, true, 'claimed'),

('Finance', 'Private Equity', 'August Equity',
'August Equity is a London-based mid-market private equity firm founded in 2001, managing £800M+ and focusing on profitable UK businesses in healthcare, education, and technology services with revenues of £5M–£100M. August typically invests £15M–£60M through management buyouts and growth capital deals. Portfolio includes National Fostering Group, Sovereign Healthcare, City & Guilds (partial), and School of Rock UK. Known for strong ESG orientation and social impact focus.',
'{"firm_type": "PE", "fund_size_gbp": 350000000, "fund_tier": "pe_lower", "aum_gbp": 800000000, "stage_focus": ["Buyout", "Growth Capital"], "sectors": ["Healthcare", "Education", "Technology Services", "Social Care"], "is_active_deploying": true, "last_fund_close_date": "2023-06", "founding_year": 2001, "bvca_member": true, "hq_city": "London", "investment_thesis": "Mid-market investor focused on healthcare, education and technology services businesses where societal impact and commercial performance are aligned.", "notable_portfolio": ["National Fostering Group", "Sovereign Healthcare", "School of Rock UK"], "recent_deals_summary": "Active deployment of latest fund; strong pipeline in healthcare and education technology.", "outreach_priority": "B", "outreach_status": "not_started", "website_url": "https://www.augustequity.com", "linkedin_company_url": "https://www.linkedin.com/company/august-equity", "contact_email": "info@augustequity.com", "location": "London, England, UK", "data_source": "bvca_directory", "data_confidence": "high", "last_verified": "2026-02"}',
NULL, true, true, 'claimed'),

('Finance', 'Private Equity', 'Synova',
'Synova is a London-based lower mid-market private equity firm founded in 2006, managing £700M+ and investing £5M–£30M in UK businesses at the smaller end of the mid-market with revenues of £2M–£30M. Synova focuses on management buyouts and development capital in technology, healthcare, financial services, and business services. Portfolio includes Entrust (payments), Tessian, and multiple SaaS businesses. Known for hands-on operational involvement and active chairman network.',
'{"firm_type": "PE", "fund_size_gbp": 300000000, "fund_tier": "pe_lower", "aum_gbp": 700000000, "stage_focus": ["Lower Mid-Market Buyout", "Growth Capital"], "sectors": ["Technology", "Healthcare", "Financial Services", "Business Services"], "is_active_deploying": true, "last_fund_close_date": "2023-03", "founding_year": 2006, "bvca_member": true, "hq_city": "London", "investment_thesis": "Specialist lower mid-market investor backing UK businesses at the tipping point of scale with hands-on operational and commercial support.", "notable_portfolio": ["Multiple SaaS and tech-enabled businesses"], "recent_deals_summary": "Actively deploying latest fund; focus on technology and healthcare businesses.", "outreach_priority": "B", "outreach_status": "not_started", "website_url": "https://www.synovacapital.com", "linkedin_company_url": "https://www.linkedin.com/company/synova-capital", "contact_email": "info@synovacapital.com", "location": "London, England, UK", "data_source": "bvca_directory", "data_confidence": "high", "last_verified": "2026-02"}',
NULL, true, true, 'claimed'),

('Finance', 'Private Equity', 'Living Bridge',
'Living Bridge (formerly ISIS Private Equity) is a London-based private equity firm founded in 1999, managing over £2 billion and investing in UK mid-market businesses with revenues of £10M–£200M. The firm invests £15M–£75M in growth capital and buyouts, focusing on healthcare, education, financial services, and business services. Living Bridge has backed Avado Learning, Inspire, and many owner-managed businesses seeking institutional capital for the first time.',
'{"firm_type": "PE", "fund_size_gbp": 600000000, "fund_tier": "pe_lower", "aum_gbp": 2000000000, "stage_focus": ["Growth Capital", "Buyout", "Mid-Market"], "sectors": ["Healthcare", "Education", "Financial Services", "Business Services"], "is_active_deploying": true, "last_fund_close_date": "2022-06", "founding_year": 1999, "bvca_member": true, "hq_city": "London", "investment_thesis": "UK mid-market growth investor backing businesses where a first institutional partner can unlock the next stage of scale.", "notable_portfolio": ["Avado Learning", "Inspire", "Multiple mid-market portfolio companies"], "recent_deals_summary": "Active deployment across UK mid-market; strong pipeline in healthcare, education and business services.", "outreach_priority": "B", "outreach_status": "not_started", "website_url": "https://www.livingbridge.com", "linkedin_company_url": "https://www.linkedin.com/company/living-bridge", "contact_email": "info@livingbridge.com", "location": "London, England, UK", "data_source": "bvca_directory", "data_confidence": "high", "last_verified": "2026-02"}',
NULL, true, true, 'claimed'),

('Finance', 'Private Equity', 'Tenzing',
'Tenzing Private Equity is a London-based growth-oriented private equity firm founded in 2016 by Nicholas Hyett and Giles Dodd. Tenzing backs profitable UK technology and technology-enabled services businesses with revenues of £3M–£30M, investing £5M–£40M for majority stakes. The firm has backed Convex Insurance, Switchplane, and multiple SaaS and professional services businesses. Tenzing is known for its 100-day plan methodology and strong technology sector expertise.',
'{"firm_type": "PE", "fund_size_gbp": 200000000, "fund_tier": "pe_lower", "aum_gbp": 400000000, "stage_focus": ["Lower Mid-Market Buyout", "Growth Capital"], "sectors": ["Technology", "Tech-Enabled Services", "SaaS", "Professional Services"], "is_active_deploying": true, "last_fund_close_date": "2022-09", "founding_year": 2016, "bvca_member": true, "hq_city": "London", "investment_thesis": "Specialist technology PE backing profitable UK tech and tech-enabled businesses with £3M-£30M revenue ready to scale internationally.", "notable_portfolio": ["Convex Insurance", "Switchplane", "Multiple UK tech businesses"], "recent_deals_summary": "Actively deploying latest fund; strong technology thesis with particular interest in SaaS and B2B services.", "outreach_priority": "A", "outreach_status": "not_started", "website_url": "https://www.tenzingpe.com", "linkedin_company_url": "https://www.linkedin.com/company/tenzing-private-equity", "contact_email": "info@tenzingpe.com", "location": "London, England, UK", "data_source": "bvca_directory", "data_confidence": "high", "last_verified": "2026-02"}',
NULL, true, true, 'claimed'),

('Finance', 'Private Equity', 'Literacy Capital',
'Literacy Capital is a London-based, London Stock Exchange-listed (LSE: BOOK) private equity fund founded in 2017 by Paul Pindar (former CEO of Capita) and Richard Pindar. The firm invests £5M–£30M in profitable UK small and mid-cap businesses across business services, technology, and consumer sectors. Uniquely, Literacy Capital donates 0.9% of NAV annually to children''s literacy charities. Portfolio includes Natterbox, Babington, and Fleet Mortgages.',
'{"firm_type": "PE", "fund_size_gbp": 250000000, "fund_tier": "pe_lower", "aum_gbp": 250000000, "stage_focus": ["Lower Mid-Market Buyout", "Growth Capital"], "sectors": ["Business Services", "Technology", "Consumer", "Financial Services"], "is_active_deploying": true, "last_fund_close_date": "2022-01", "founding_year": 2017, "bvca_member": true, "hq_city": "London", "investment_thesis": "Patient capital investor backing UK businesses at the tipping point of scale with a commitment to children''s literacy through profit sharing.", "notable_portfolio": ["Natterbox", "Babington", "Fleet Mortgages"], "recent_deals_summary": "Active lower mid-market investor; listed vehicle provides permanent capital and long-term perspective.", "outreach_priority": "B", "outreach_status": "not_started", "website_url": "https://www.literacycapital.com", "linkedin_company_url": "https://www.linkedin.com/company/literacy-capital", "location": "London, England, UK", "data_source": "bvca_directory", "data_confidence": "high", "last_verified": "2026-02"}',
NULL, true, true, 'claimed'),

-- =============================================
-- PRIVATE EQUITY — LARGE / MID-MARKET
-- =============================================

('Finance', 'Private Equity', 'Permira',
'Permira is a global private equity firm headquartered in London with €80 billion+ in AUM, founded in 1985. The firm invests €200M–€2B in established businesses across technology, consumer, healthcare, and financial services globally. Permira has backed and built companies including Ancestry, TeamViewer, Klarna (growth stage), LegalZoom, Informatica, and Dr. Martens. In the UK, Permira is known for transformational buyouts of household brands.',
'{"firm_type": "PE", "fund_size_gbp": 16000000000, "fund_tier": "pe_large", "aum_gbp": 70000000000, "stage_focus": ["Large Buyout", "Growth Equity"], "sectors": ["Technology", "Consumer", "Healthcare", "Financial Services"], "is_active_deploying": true, "last_fund_close_date": "2023-09", "founding_year": 1985, "bvca_member": true, "hq_city": "London", "investment_thesis": "Global buyout investor backing market-leading businesses in technology, consumer, healthcare and financial services and transforming them into category champions.", "notable_portfolio": ["Ancestry", "TeamViewer", "Dr. Martens", "LegalZoom", "Informatica", "Klarna (growth)"], "recent_deals_summary": "Active deployment of Permira XI fund; focus on software, tech services and consumer brands globally.", "outreach_priority": "C", "outreach_status": "not_started", "website_url": "https://www.permira.com", "linkedin_company_url": "https://www.linkedin.com/company/permira", "location": "London, England, UK", "data_source": "bvca_directory", "data_confidence": "high", "last_verified": "2026-02"}',
NULL, true, true, 'claimed'),

('Finance', 'Private Equity', 'Bridgepoint',
'Bridgepoint is a London-headquartered international private equity firm founded in 2000 (spun out from NatWest Equity Partners), listed on the LSE in 2021 (LSE: BPT), managing €40 billion+. The firm operates three strategies: Private Equity (€500M–€2.5B enterprise value), Bridgepoint Development Capital (smaller buyouts), and Bridgepoint Credit. Portfolio includes Hobbycraft, Pret A Manger (partial exit), Burger King UK, Dorna Sports, and Virgin Active.',
'{"firm_type": "PE", "fund_size_gbp": 6000000000, "fund_tier": "pe_large", "aum_gbp": 35000000000, "stage_focus": ["Large Buyout", "Mid-Market Buyout", "Lower Mid-Market"], "sectors": ["Consumer", "Healthcare", "Business Services", "Financial Services", "Technology"], "is_active_deploying": true, "last_fund_close_date": "2023-06", "founding_year": 2000, "bvca_member": true, "hq_city": "London", "investment_thesis": "Listed international PE investing across three strategies from small buyout to large cap, with deep European mid-market expertise.", "notable_portfolio": ["Hobbycraft", "Pret A Manger", "Burger King UK", "Dorna Sports", "Virgin Active"], "recent_deals_summary": "Actively deploying latest flagships and credit strategies; recent consumer and services focus.", "outreach_priority": "C", "outreach_status": "not_started", "website_url": "https://www.bridgepoint.eu", "linkedin_company_url": "https://www.linkedin.com/company/bridgepoint", "location": "London, England, UK", "data_source": "bvca_directory", "data_confidence": "high", "last_verified": "2026-02"}',
NULL, true, true, 'claimed'),

('Finance', 'Private Equity', 'Hg',
'Hg is a London and New York-based software and technology-focused private equity firm, managing £45 billion in AUM. Founded in 2000 as Hgcapital, the firm is the world''s largest software specialist private equity investor. Hg has backed IRIS Software, Allocate, Visma, Transporeon, Access Group, TeamViewer, and 50+ other software businesses. The firm invests €50M–€2B in software and tech-enabled services companies across Europe and North America with recurring revenue models.',
'{"firm_type": "PE", "fund_size_gbp": 10000000000, "fund_tier": "pe_large", "aum_gbp": 45000000000, "stage_focus": ["Buyout", "Large Buyout", "Growth Equity"], "sectors": ["Software", "SaaS", "Tech-Enabled Services", "ERP", "Compliance Tech"], "is_active_deploying": true, "last_fund_close_date": "2023-12", "founding_year": 2000, "bvca_member": true, "hq_city": "London", "investment_thesis": "World''s leading software specialist PE, backing market-leading B2B software businesses with deep recurring revenues and mission-critical positioning.", "notable_portfolio": ["IRIS Software", "Visma", "TeamViewer", "Access Group", "Transporeon", "Allocate"], "recent_deals_summary": "Very active deployment across Saturn (small), Mercury (mid) and Genesis (large) fund series; 10-15 new platforms per year.", "outreach_priority": "A", "outreach_status": "not_started", "website_url": "https://www.hgcapital.com", "linkedin_company_url": "https://www.linkedin.com/company/hg", "contact_email": "info@hgcapital.com", "location": "London, England, UK", "data_source": "bvca_directory", "data_confidence": "high", "last_verified": "2026-02"}',
NULL, true, true, 'claimed'),

('Finance', 'Private Equity', 'Equistone Partners Europe',
'Equistone Partners Europe is a London and Munich-based private equity firm managing €8 billion+ across five funds, focused on mid-market buyouts in the UK, Germany, France, Switzerland and Benelux. The firm invests €25M–€200M in businesses with revenues of €25M–€500M across industrial technology, business services, healthcare and consumer sectors. Equistone has backed Citation, SHL Medical, and other mid-market European leaders. The firm is known for its cross-border buy-and-build expertise.',
'{"firm_type": "PE", "fund_size_gbp": 2000000000, "fund_tier": "pe_lower", "aum_gbp": 8000000000, "stage_focus": ["Mid-Market Buyout", "Large Buyout"], "sectors": ["Industrial Technology", "Business Services", "Healthcare", "Consumer"], "is_active_deploying": true, "last_fund_close_date": "2022-12", "founding_year": 1997, "bvca_member": true, "hq_city": "London", "investment_thesis": "Pan-European mid-market specialist backing strong businesses with cross-border ambition, leveraging deep network across 5 European markets.", "notable_portfolio": ["SHL Medical", "Multiple European mid-market businesses"], "recent_deals_summary": "Active deployment of Fund VI; UK and German market focus with cross-border buy-and-build strategies.", "outreach_priority": "B", "outreach_status": "not_started", "website_url": "https://www.equistone.com", "linkedin_company_url": "https://www.linkedin.com/company/equistone-partners-europe", "location": "London, England, UK", "data_source": "bvca_directory", "data_confidence": "high", "last_verified": "2026-02"}',
NULL, true, true, 'claimed'),

-- =============================================
-- SPECIALIST / SECTOR-SPECIFIC
-- =============================================

('Finance', 'Venture Capital', 'Parkwalk Oxford Science Enterprises',
'Oxford Science Enterprises (OSE) is Oxford''s dedicated commercial vehicle for spinning out and backing companies from the University of Oxford, managing over £600M. OSE has backed 100+ Oxford spinouts including Oxford Nanopore Technologies, OMass Therapeutics, and Osaro. The firm invests at pre-seed, seed and Series A stages in deep science companies across life sciences, quantum, AI and materials. Unique access to Oxford IP pipeline makes OSE a first-mover in many breakthrough technologies.',
'{"firm_type": "VC", "fund_size_gbp": 200000000, "fund_tier": "seed", "aum_gbp": 600000000, "stage_focus": ["Pre-Seed", "Seed", "Series A"], "sectors": ["Life Sciences", "Quantum", "AI", "Deep Tech", "Materials"], "is_active_deploying": true, "last_fund_close_date": "2023-06", "founding_year": 2015, "bvca_member": false, "hq_city": "Oxford", "investment_thesis": "Dedicated vehicle for Oxford University spinouts, providing first institutional capital to breakthrough science companies from pre-seed.", "notable_portfolio": ["Oxford Nanopore Technologies", "OMass Therapeutics", "Perspectum", "Osaro"], "recent_deals_summary": "Prolific Oxford spinout investor; 15-20 new investments per year from Oxford IP pipeline.", "outreach_priority": "B", "outreach_status": "not_started", "website_url": "https://www.oxfordscienceenterprises.com", "linkedin_company_url": "https://www.linkedin.com/company/oxford-science-enterprises", "location": "Oxford, England, UK", "data_source": "company_website", "data_confidence": "high", "last_verified": "2026-02"}',
NULL, true, true, 'claimed'),

('Finance', 'Venture Capital', 'Cambridge Innovation Capital',
'Cambridge Innovation Capital (CIC) is the dedicated spinout investment vehicle for the University of Cambridge, managing £600M+ and focused on backing Cambridge''s world-class research at seed and early stage. CIC has invested in Fluidic Analytics, Ori Biotech, Healx, and 60+ other Cambridge spinouts in life sciences, quantum, AI and deep tech. CIC works in close partnership with Cambridge Enterprise to identify and support the University''s most commercially promising research.',
'{"firm_type": "VC", "fund_size_gbp": 200000000, "fund_tier": "seed", "aum_gbp": 600000000, "stage_focus": ["Pre-Seed", "Seed", "Series A"], "sectors": ["Life Sciences", "Quantum", "AI", "Deep Tech", "Materials"], "is_active_deploying": true, "last_fund_close_date": "2023-01", "founding_year": 2013, "bvca_member": false, "hq_city": "Cambridge", "investment_thesis": "Dedicated vehicle for Cambridge University spinouts, providing first institutional capital and long-term support to breakthrough science companies.", "notable_portfolio": ["Fluidic Analytics", "Ori Biotech", "Healx", "CMR Surgical (early)"], "recent_deals_summary": "Active Cambridge spinout investor; close partnership with Cambridge Enterprise for deal flow.", "outreach_priority": "B", "outreach_status": "not_started", "website_url": "https://www.cambridgeinnovationcapital.com", "linkedin_company_url": "https://www.linkedin.com/company/cambridge-innovation-capital", "location": "Cambridge, England, UK", "data_source": "company_website", "data_confidence": "high", "last_verified": "2026-02"}',
NULL, true, true, 'claimed'),

('Finance', 'Private Equity', 'YFM Equity Partners',
'YFM Equity Partners is a UK regional private equity firm headquartered in Leeds, founded in 1982 and managing £300M+. The firm invests £2M–£10M in UK SMEs across the North of England and Midlands, with funds including the British Smaller Companies VCTs. YFM focuses on profitable businesses in manufacturing, technology, and business services. Known for long-standing regional presence and ability to work with first-time PE-backed management teams.',
'{"firm_type": "PE", "fund_size_gbp": 100000000, "fund_tier": "pe_lower", "aum_gbp": 300000000, "stage_focus": ["Lower Mid-Market", "Growth Capital", "MBO"], "sectors": ["Manufacturing", "Technology", "Business Services"], "is_active_deploying": true, "last_fund_close_date": "2023-01", "founding_year": 1982, "bvca_member": true, "hq_city": "Leeds", "investment_thesis": "Specialist regional PE investor backing UK SMEs in the North and Midlands with patient capital and hands-on support for first-time institutional partners.", "notable_portfolio": ["Multiple UK regional businesses across manufacturing and tech services"], "recent_deals_summary": "Active regional deployer; focus on Northern and Midlands businesses with revenues £2M-£30M.", "outreach_priority": "B", "outreach_status": "not_started", "website_url": "https://www.yfmep.com", "linkedin_company_url": "https://www.linkedin.com/company/yfm-equity-partners", "contact_email": "info@yfmep.com", "location": "Leeds, England, UK", "data_source": "bvca_directory", "data_confidence": "high", "last_verified": "2026-02"}',
NULL, true, true, 'claimed'),

('Finance', 'Private Equity', 'Mobeus Equity Partners',
'Mobeus Equity Partners is a London-based lower mid-market private equity firm managing £500M+ across its VCT and PE funds, founded in 2005. The firm invests £3M–£20M in profitable UK businesses in technology, healthcare and business services with revenues of £2M–£20M. Mobeus offers both VCT (tax-advantaged) and PE fund structures. Portfolio includes businesses across fintech, software and specialist B2B services.',
'{"firm_type": "PE", "fund_size_gbp": 150000000, "fund_tier": "pe_lower", "aum_gbp": 500000000, "stage_focus": ["Lower Mid-Market", "Growth Capital", "MBO"], "sectors": ["Technology", "Healthcare", "Business Services", "Software"], "is_active_deploying": true, "last_fund_close_date": "2023-06", "founding_year": 2005, "bvca_member": true, "hq_city": "London", "investment_thesis": "VCT and PE specialist backing profitable UK technology and services businesses at the lower mid-market with both tax-advantaged and standard structures.", "notable_portfolio": ["Multiple UK technology and business services businesses"], "recent_deals_summary": "Active deployer across VCT and PE funds; focus on B2B software and healthcare services.", "outreach_priority": "B", "outreach_status": "not_started", "website_url": "https://www.mobeusequity.co.uk", "linkedin_company_url": "https://www.linkedin.com/company/mobeus-equity-partners", "contact_email": "info@mobeusequity.co.uk", "location": "London, England, UK", "data_source": "bvca_directory", "data_confidence": "high", "last_verified": "2026-02"}',
NULL, true, true, 'claimed');
