-- ─────────────────────────────────────────────────────────────────────────────
-- CAD upload Round A — drop DWG from V1.
--
-- Context: the preceding migration (20260420200000_cad_lab_project_files.sql)
-- accepted STEP/STL/DXF/DWG because Tristan had pinned 4 formats. There is no
-- permissively-licensed, server-side pure-JS DWG parser available, so rather
-- than ship a broken DWG path Tristan has decided to drop DWG from V1. The UI
-- now tells founders to export DWG as DXF in their CAD tool.
--
-- This migration:
--   1. Replaces the `format` check constraint so only 'step' / 'stl' / 'dxf'
--      are accepted.
--   2. Removes the DWG MIME types from the private project-cad-files bucket
--      allowlist. `application/octet-stream` stays as the safety fallback for
--      CAD exporters that don't set a specific MIME.
--
-- Safety: verified via `SELECT COUNT(*) WHERE format = 'dwg'` = 0 before
-- applying. The constraint replacement would otherwise refuse.
-- ─────────────────────────────────────────────────────────────────────────────


-- ── 1. Narrow the format check constraint ──────────────────────────────────
--
-- Postgres does not support altering a CHECK constraint in place; drop and
-- re-add under the same name. The check-constraint name generated by Postgres
-- for the original `CHECK (format IN (...))` on `cad_lab_project_files` is
-- `cad_lab_project_files_format_check` (the standard auto-generated name for
-- an anonymous column-level CHECK). Guarded with IF EXISTS so a one-off
-- rename or re-apply doesn't break the migration.

ALTER TABLE public.cad_lab_project_files
  DROP CONSTRAINT IF EXISTS cad_lab_project_files_format_check;

ALTER TABLE public.cad_lab_project_files
  ADD CONSTRAINT cad_lab_project_files_format_check
    CHECK (format IN ('step', 'stl', 'dxf'));


-- ── 2. Update storage bucket MIME allowlist ────────────────────────────────
--
-- Drop DWG MIMEs (application/acad, application/dwg, application/x-dwg,
-- image/vnd.dwg). Keep the STEP/STL/DXF entries plus application/octet-stream
-- as the fallback for CAD exporters that don't set a specific MIME.

UPDATE storage.buckets
SET allowed_mime_types = ARRAY[
  'application/step',
  'application/STEP',
  'application/x-step',
  'model/step',
  'model/stl',
  'application/sla',
  'application/vnd.ms-pki.stl',
  'application/dxf',
  'image/vnd.dxf',
  -- Fallback for CAD exporters that don't set a specific MIME
  'application/octet-stream'
]
WHERE id = 'project-cad-files';
