-- Add task_number column to tasks table
-- Use GENERATED BY DEFAULT AS IDENTITY to auto-increment
ALTER TABLE "public"."tasks" 
ADD COLUMN "task_number" bigint GENERATED BY DEFAULT AS IDENTITY;

-- Update existing tasks to have a number (optional, but good for completeness if any exist)
-- The IDENTITY column will handle new ones, but existing rows gets numbered sequentially
-- We can't easily "backfill" strict sequential numbers without a script/complex query if data exists,
-- but typically adding the column with IDENTITY handles it for new rows.
-- For existing rows, we might want to populate them if they are null (though IDENTITY usually implies NOT NULL or auto-fill).
-- Actually, adding IDENTITY to existing table:
-- If table has data, we need to handle it. 
-- "ADD COLUMN task_number bigint GENERATED BY DEFAULT AS IDENTITY" will fail if table not empty? 
-- No, it populates. Wait, Postgres 10+ IDENTITY.
-- Let's make it safe.

DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_schema = 'public' AND table_name = 'tasks' AND column_name = 'task_number') THEN
        ALTER TABLE "public"."tasks" ADD COLUMN "task_number" bigint GENERATED BY DEFAULT AS IDENTITY;
    END IF;
END $$;
