-- Adds interior_overview_url + hero_bounding_boxes columns to cad_lab_projects.
--
-- INTENT: The V2 module-render pipeline is switching from per-module gpt-image-2
-- generation to deterministic Sharp-based "ghosted context" crops of a single
-- high-detail interior-exploded hero. Geometric consistency of the individual
-- module tiles is guaranteed because their pixels come FROM the hero rather
-- than being regenerated by an image model that can drift ("container in a
-- container" was the failure mode on BESS battery-rack).
--
-- interior_overview_url — URL to a "no exterior walls" high-detail render
-- showing every sub-assembly in its spatial position. Sharp crops regions
-- of this image (with a desaturated peripheral layer) to produce each
-- module tile. Distinct from system_illustration_url (exterior-shell /
-- marketing cover) and concept_render_url (photo-realistic marketing).
--
-- hero_bounding_boxes — cached map of module-name -> {x,y,w,h} in 0-1
-- normalised coordinates produced by analyseHeroBoundingBoxes (Claude
-- Vision) against interior_overview_url. Computed once per project so
-- subsequent per-module crops reuse the map instead of paying the ~5s
-- vision call per module.
--
-- ROLLBACK:
--   ALTER TABLE public.cad_lab_projects DROP COLUMN IF EXISTS interior_overview_url;
--   ALTER TABLE public.cad_lab_projects DROP COLUMN IF EXISTS hero_bounding_boxes;

BEGIN;

ALTER TABLE public.cad_lab_projects
    ADD COLUMN IF NOT EXISTS interior_overview_url TEXT DEFAULT NULL;

ALTER TABLE public.cad_lab_projects
    ADD COLUMN IF NOT EXISTS hero_bounding_boxes JSONB DEFAULT NULL;

COMMENT ON COLUMN public.cad_lab_projects.interior_overview_url IS
    'URL to a high-detail interior-exploded hero (NO exterior walls) showing every sub-assembly in its spatial position. Used as the source image for deterministic Sharp-based ghosted-context crops that produce each module tile. When set, the V2 per-module render path uses the crop pipeline and skips gpt-image-2 generation entirely.';

COMMENT ON COLUMN public.cad_lab_projects.hero_bounding_boxes IS
    'Cached map of module-name -> {x,y,w,h} in normalised 0-1 coordinates produced by Claude Vision against interior_overview_url. Computed once per project; subsequent per-module crops reuse the map to avoid paying the vision call per module.';

COMMIT;
