-- Phase G: investor match output cache.
--
-- Each investor result on /investors that gets the why-fit + how-to-pitch +
-- drafted-email treatment is generated by a Sonnet call. To keep the £10/100
-- add-on from being loss-making, every (foundry, investor, founder-context)
-- triple is cached and reused across searches. Regenerate only when the
-- founder profile changes (driving a new context_hash).
--
-- Applied via mcp__claude_ai_Supabase__apply_migration on 2026-04-25
-- to project jyarhvinengfyrwgtskq.

create table if not exists public.investor_match_cache (
  id uuid primary key default gen_random_uuid(),
  foundry_id text not null references public.foundries(id) on delete cascade,
  investor_listing_id uuid not null references public.marketplace_listings(id) on delete cascade,
  foundry_context_hash text not null,
  why_fit text not null,
  how_to_pitch text not null,
  drafted_email_subject text not null,
  drafted_email_body text not null,
  source_citations jsonb,
  model_used text not null,
  tokens_in int not null default 0,
  tokens_out int not null default 0,
  cost_usd numeric(10,6) not null default 0,
  created_at timestamptz not null default now(),
  unique (foundry_id, investor_listing_id, foundry_context_hash)
);

create index if not exists investor_match_cache_foundry_created_idx
  on public.investor_match_cache(foundry_id, created_at desc);

create index if not exists investor_match_cache_lookup_idx
  on public.investor_match_cache(foundry_id, investor_listing_id, foundry_context_hash);

alter table public.investor_match_cache enable row level security;

drop policy if exists "users see own foundry match cache" on public.investor_match_cache;
create policy "users see own foundry match cache"
  on public.investor_match_cache
  for select
  using (
    foundry_id in (
      select foundry_id from public.foundry_memberships
      where user_id = auth.uid() and active
    )
  );

drop policy if exists "service_role inserts match cache" on public.investor_match_cache;
create policy "service_role inserts match cache"
  on public.investor_match_cache
  for insert
  with check (auth.jwt()->>'role' = 'service_role');

comment on table public.investor_match_cache is
  'Cache of generated why-fit + how-to-pitch + drafted-email outputs per (foundry, investor, founder-context). Phase G post-pivot, 2026-04-25.';
comment on column public.investor_match_cache.foundry_context_hash is
  'sha256 hex digest of the canonical foundry context string. Regenerate row when this changes.';
