/**
 * Seed reference_models with common product categories for CAD Lab instant preview.
 * stl_url/step_url are null until actual reference files are uploaded to storage.
 */

INSERT INTO public.reference_models (category, name, description, search_keywords, module_template, sort_order)
VALUES
  ('rocket', 'Rocket / Launch Vehicle', 'Reference outline for a rocket or launch vehicle with stages, nose cone, and propulsion.', ARRAY['rocket', 'launch vehicle', 'missile', 'propulsion', 'bipropellant', 'thrust structure', 'gimbal'], '[{"name": "Propulsion / Engine", "purpose": "Thrust generation and gimbal"}, {"name": "Propellant Tanks", "purpose": "Fuel and oxidizer storage"}, {"name": "Avionics / GNC", "purpose": "Guidance, navigation, control"}, {"name": "Structure / Airframe", "purpose": "Load-bearing and aerodynamic envelope"}, {"name": "Payload Fairing", "purpose": "Payload enclosure and separation"}]'::jsonb, 1),
  ('drone', 'Drone / UAV', 'Reference outline for a multi-rotor or fixed-wing drone.', ARRAY['drone', 'uav', 'quadcopter', 'octocopter', 'multirotor', 'heavy lift', 'frame', 'gimbal'], '[{"name": "Frame / Airframe", "purpose": "Structural frame and motor mounts"}, {"name": "Power / Battery", "purpose": "Energy storage and distribution"}, {"name": "Propulsion", "purpose": "Motors and propellers"}, {"name": "Payload / Gimbal", "purpose": "Payload bay and stabilization"}, {"name": "Avionics / Flight Controller", "purpose": "Sensors and flight control"}]'::jsonb, 2),
  ('ev', 'Electric Vehicle', 'Reference outline for an electric car or drivetrain.', ARRAY['electric car', 'ev', 'battery', 'drivetrain', 'battery module', 'prismatic cell', 'cooling', 'bms'], '[{"name": "Battery Module / Pack", "purpose": "Cell enclosure, BMS, cooling"}, {"name": "Drivetrain / Motor", "purpose": "Electric motor and gearbox"}, {"name": "Power Electronics", "purpose": "Inverter, DC-DC, charging"}, {"name": "Thermal Management", "purpose": "Cooling and heating"}, {"name": "Chassis / Structure", "purpose": "Vehicle structure and crash"}]'::jsonb, 3),
  ('cubesat', 'CubeSat / SmallSat', 'Reference outline for a CubeSat bus or small satellite.', ARRAY['cubesat', 'smallsat', 'satellite', 'bus', 'pc-104', 'solar panel', 'reaction wheel'], '[{"name": "Structural Bus", "purpose": "Frame, rails, deployment"}, {"name": "Avionics Stack", "purpose": "OBC, power, comms"}, {"name": "Power / Solar", "purpose": "Solar panels and batteries"}, {"name": "ADCS", "purpose": "Reaction wheels, sensors"}, {"name": "Payload", "purpose": "Instruments and interfaces"}]'::jsonb, 4),
  ('robotic-arm', 'Robotic Arm', 'Reference outline for a robotic arm or manipulator.', ARRAY['robotic arm', 'manipulator', 'wrist', 'harmonic drive', 'encoder', 'force torque'], '[{"name": "Base / Shoulder", "purpose": "Base structure and first axis"}, {"name": "Arm Links", "purpose": "Links and joints"}, {"name": "Wrist / End Effector", "purpose": "Wrist and tool interface"}, {"name": "Drives / Actuation", "purpose": "Motors and reducers"}, {"name": "Sensors / Encoders", "purpose": "Position and force sensing"}]'::jsonb, 5),
  ('reaction-wheel', 'Reaction Wheel Assembly', 'Reference outline for a satellite reaction wheel.', ARRAY['reaction wheel', 'flywheel', 'bldc', 'adcs', 'satellite'], '[{"name": "Flywheel Housing", "purpose": "Rotor enclosure and bearings"}, {"name": "Motor / Drive", "purpose": "BLDC motor and driver"}, {"name": "Encoder", "purpose": "Speed and position sensing"}, {"name": "Mounting Interface", "purpose": "Vibration isolation and attach"}]'::jsonb, 6),
  ('ev-battery', 'EV Battery Module', 'Reference outline for a prismatic cell battery module.', ARRAY['battery module', 'prismatic', 'bms', 'cooling channel', 'busbar', 'thermal runaway'], '[{"name": "Cell Enclosure", "purpose": "Mechanical enclosure and retention"}, {"name": "Thermal System", "purpose": "Cooling channels and vents"}, {"name": "BMS / Electrical", "purpose": "BMS mounting and busbars"}, {"name": "Interfaces", "purpose": "HV connectors and mounting"}]'::jsonb, 7),
  ('rocket-mount', 'Rocket Thrust Mount', 'Reference outline for an engine thrust structure.', ARRAY['thrust mount', 'engine mount', 'gimbal', 'thrust structure', '5kn', 'regenerative cooling'], '[{"name": "Thrust Structure", "purpose": "Load path to vehicle"}, {"name": "Gimbal Interface", "purpose": "Bearing and actuation"}, {"name": "Feed-through Ports", "purpose": "Propellant and cooling"}, {"name": "Mounting Flanges", "purpose": "Engine and ancillary attach"}]'::jsonb, 8),
  ('heavy-drone', 'Heavy-Lift Drone Frame', 'Reference outline for a heavy-lift multirotor frame.', ARRAY['heavy lift', 'octocopter', 'coaxial', 'carbon fiber', 'folding arm', 'payload bay'], '[{"name": "Central Hub", "purpose": "Central structure and electronics"}, {"name": "Arms / Motor Mounts", "purpose": "Arm geometry and folding"}, {"name": "Payload Bay", "purpose": "Payload and gimbal interface"}, {"name": "Landing Gear", "purpose": "Retractable or fixed gear"}]'::jsonb, 9),
  ('generic', 'Generic Product', 'Generic placeholder for products that do not match a specific category.', ARRAY['product', 'assembly', 'device', 'system'], '[{"name": "Main Assembly", "purpose": "Primary structure or enclosure"}, {"name": "Power", "purpose": "Power source and distribution"}, {"name": "Control / Logic", "purpose": "Control and sensing"}, {"name": "Interfaces", "purpose": "User or external interfaces"}]'::jsonb, 99)
ON CONFLICT (category) DO UPDATE SET
  name = EXCLUDED.name,
  description = EXCLUDED.description,
  search_keywords = EXCLUDED.search_keywords,
  module_template = EXCLUDED.module_template,
  sort_order = EXCLUDED.sort_order,
  updated_at = now();
